In [1]:
import requests

In [2]:
from bs4 import BeautifulSoup
url = "https://ajuntament.barcelona.cat/calendarifestius/es/"

response = requests.get(url) # peticion http
print(response)
print(bool(response))

<Response [200]>
True

In [3]:
soup = BeautifulSoup(response.text, "html.parser")

In [19]:
ul_list = soup.find_all("ul", attrs={"class": "dies"})
fest = ul_list[0]  # solo el primer <ul> 2025

In [20]:
len(fest)

31

In [15]:
fest.li.strong.text

'1 de enero'

In [16]:
fest.li.span.text

'(e)'

In [41]:
dia_festivo =[] # 1 de enero
tipo_festivo =[] # estatal
Name_festivo =[]
for li in fest.find_all("li"): 
    dia = li.strong # encontrar a 
    if dia: # condicio si a 
        dia_festivo.append(dia.get_text(strip=True)) # obtener y guardar
        
    tip = li.span
    if tip:
        tipo_festivo.append(tip.get_text(strip=True)) #obtener y guardar
        
    nom = li
    if nom:
        destino = "".join(nom.find_all(string=True, recursive=False)).strip() # obtener solo 
        #destino = destino.lstrip("- ").strip()    # eliminar "- " limpiar
        Name_festivo.append(destino)
        
print(dia_festivo)
print(tipo_festivo)
print(len(dia_festivo))
print(len(tipo_festivo))

print(len(Name_festivo))
print((Name_festivo))

['1 de enero', '6 de enero', '18 de abril', '21 de abril', '1 de mayo', '9 de junio', '24 de junio', '15 de agosto', '11 de septiembre', '24 de septiembre', '1 de noviembre', '6 de diciembre', '8 de diciembre', '25 de diciembre', '26 de diciembre']
['(e)', '(e)', '(e)', '(a)', '(e)', '(L)', '(a)', '(e)', '(a)', '(l)', '(e)', '(e)', '(e)', '(e)', '(a)']
15
15
15
['AÃ±o Nuevo', 'Reyes', 'Viernes Santo', 'Lunes de Pascua Florida', 'Fiesta del Trabajo', 'Lunes de Pascua Granada', 'San Juan', 'La AsunciÃ³n', 'Diada Nacional de CataluÃ±a', 'Mare de DÃ©u de la MercÃ¨', 'Todos los Santos', 'DÃ\xada de la ConstituciÃ³n', 'La Inmaculada', 'Navidad', 'San Esteban']

In [42]:
import pandas as pd
data = pd.DataFrame({'dia_festivo':dia_festivo, 'nombre_festivo':Name_festivo, 'tipo_festivo':tipo_festivo})
data

         dia_festivo               nombre_festivo tipo_festivo
0         1 de enero                   AÃ±o Nuevo          (e)
1         6 de enero                        Reyes          (e)
2        18 de abril                Viernes Santo          (e)
3        21 de abril      Lunes de Pascua Florida          (a)
4          1 de mayo           Fiesta del Trabajo          (e)
5         9 de junio      Lunes de Pascua Granada          (L)
6        24 de junio                     San Juan          (a)
7       15 de agosto                 La AsunciÃ³n          (e)
8   11 de septiembre  Diada Nacional de CataluÃ±a          (a)
9   24 de septiembre    Mare de DÃ©u de la MercÃ¨          (l)
10    1 de noviembre             Todos los Santos          (e)
11    6 de diciembre     DÃ­a de la ConstituciÃ³n          (e)
12    8 de diciembre                La Inmaculada          (e)
13   25 de diciembre                      Navidad          (e)
14   26 de diciembre                  San Esteban          (a)

In [30]:
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

In [31]:
fechas_convertidas = []

for texto in dia_festivo:       # ej. "1 de enero"
    partes = texto.split(" ")   # ["1", "de", "enero"]
    dia = int(partes[0])
    mes = meses[partes[2]]      # "enero" → 1
    fecha = pd.Timestamp(year=2025, month=mes, day=dia)
    fechas_convertidas.append(fecha)

In [33]:
fechas_convertidas

[Timestamp('2025-01-01 00:00:00'),
 Timestamp('2025-01-06 00:00:00'),
 Timestamp('2025-04-18 00:00:00'),
 Timestamp('2025-04-21 00:00:00'),
 Timestamp('2025-05-01 00:00:00'),
 Timestamp('2025-06-09 00:00:00'),
 Timestamp('2025-06-24 00:00:00'),
 Timestamp('2025-08-15 00:00:00'),
 Timestamp('2025-09-11 00:00:00'),
 Timestamp('2025-09-24 00:00:00'),
 Timestamp('2025-11-01 00:00:00'),
 Timestamp('2025-12-06 00:00:00'),
 Timestamp('2025-12-08 00:00:00'),
 Timestamp('2025-12-25 00:00:00'),
 Timestamp('2025-12-26 00:00:00')]

In [43]:
df_fest = pd.DataFrame({
    "Date_holiday": fechas_convertidas,
    "Name_holiday": Name_festivo,
    "Type_holiday": tipo_festivo
})
df_fest

   Date_holiday                 Name_holiday Type_holiday
0    2025-01-01                   AÃ±o Nuevo          (e)
1    2025-01-06                        Reyes          (e)
2    2025-04-18                Viernes Santo          (e)
3    2025-04-21      Lunes de Pascua Florida          (a)
4    2025-05-01           Fiesta del Trabajo          (e)
5    2025-06-09      Lunes de Pascua Granada          (L)
6    2025-06-24                     San Juan          (a)
7    2025-08-15                 La AsunciÃ³n          (e)
8    2025-09-11  Diada Nacional de CataluÃ±a          (a)
9    2025-09-24    Mare de DÃ©u de la MercÃ¨          (l)
10   2025-11-01             Todos los Santos          (e)
11   2025-12-06     DÃ­a de la ConstituciÃ³n          (e)
12   2025-12-08                La Inmaculada          (e)
13   2025-12-25                      Navidad          (e)
14   2025-12-26                  San Esteban          (a)

In [45]:
from datetime import datetime, timedelta
df_fest['holiday_eve'] = df_fest['Date_holiday'] - pd.Timedelta(days=1)

In [46]:
df_fest

   Date_holiday                 Name_holiday Type_holiday holiday_eve
0    2025-01-01                   AÃ±o Nuevo          (e)  2024-12-31
1    2025-01-06                        Reyes          (e)  2025-01-05
2    2025-04-18                Viernes Santo          (e)  2025-04-17
3    2025-04-21      Lunes de Pascua Florida          (a)  2025-04-20
4    2025-05-01           Fiesta del Trabajo          (e)  2025-04-30
5    2025-06-09      Lunes de Pascua Granada          (L)  2025-06-08
6    2025-06-24                     San Juan          (a)  2025-06-23
7    2025-08-15                 La AsunciÃ³n          (e)  2025-08-14
8    2025-09-11  Diada Nacional de CataluÃ±a          (a)  2025-09-10
9    2025-09-24    Mare de DÃ©u de la MercÃ¨          (l)  2025-09-23
10   2025-11-01             Todos los Santos          (e)  2025-10-31
11   2025-12-06     DÃ­a de la ConstituciÃ³n          (e)  2025-12-05
12   2025-12-08                La Inmaculada          (e)  2025-12-07
13   2025-12-25                      Navidad          (e)  2025-12-24
14   2025-12-26                  San Esteban          (a)  2025-12-25

In [47]:
df_fest.to_csv("festividades_bcn.csv")