¿Qué columnas vas a obtener?

La API devuelve normalmente:

time → fecha y hora

temp → temperatura (°C)

dwpt → punto de rocío

rhum → humedad relativa (%)

prcp → precipitación (mm)

wdir → dirección del viento

wspd → velocidad del viento

wpgt → racha máxima

pres → presión hPa

tsun → insolación

y otros si están disponibles

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
df = pd.read_csv("export.csv")
df

,time,temp,dwpt,rhum,prcp,snow,wdir,wspd,wpgt,pres,tsun,coco
0,2025-11-20 00:00:00,7.0,3.1,76,0,NaN,320,17,20.4,1013.0,0,1
1,2025-11-20 01:00:00,6.9,2.6,74,0,NaN,330,13,20.4,1013.1,0,1
2,2025-11-20 02:00:00,7.0,3.1,76,0,NaN,330,15,22.2,1013.0,0,1
3,2025-11-20 03:00:00,6.0,3.0,81,0,NaN,320,19,20.4,1012.0,0,1
4,2025-11-20 04:00:00,6.0,2.1,76,0,NaN,330,24,25.9,1012.0,0,1
5,2025-11-20 05:00:00,5.0,2.0,81,0,NaN,320,22,27.8,1012.0,0,2
6,2025-11-20 06:00:00,6.0,3.0,81,0,NaN,320,22,27.8,1012.0,0,2
7,2025-11-20 07:00:00,5.9,2.7,80,0,NaN,340,21,24.1,1013.0,0,2
8,2025-11-20 08:00:00,6.0,3.0,81,0,NaN,320,22,25.9,1013.0,0,2
9,2025-11-20 09:00:00,7.0,3.1,76,0,NaN,330,24,26.0,1013.0,20,2
10,2025-11-20 10:00:00,8.0,4.0,76,0,NaN,340,20,22.0,1014.0,23,2
11,2025-11-20 11:00:00,9.0,4.0,71,0,NaN,320,22,23.0,1014.0,21,3
12,2025-11-20 12:00:00,11.0,4.0,62,0,NaN,340,24,20.0,1013.0,22,3
13,2025-11-20 13:00:00,12.3,4.5,59,0,NaN,360,21,20.4,1013.5,25,3
14,2025-11-20 14:00:00,13.0,4.9,58,0,NaN,300,7,18.5,1013.0,31,3
15,2025-11-20 15:00:00,13.0,4.9,58,0,NaN,140,9,18.5,1012.0,36,2
16,2025-11-20 16:00:00,13.0,4.9,58,0,NaN,140,7,16.7,1013.0,31,2
17,2025-11-20 17:00:00,13.0,7.0,67,0,NaN,173,4,16.7,1013.0,28,1
18,2025-11-20 18:00:00,13.0,7.0,67,0,NaN,200,4,16.7,1013.0,13,2
19,2025-11-20 19:00:00,10.3,6.6,78,0,NaN,320,11,14.8,1013.9,0,2
20,2025-11-20 20:00:00,9.0,6.1,82,0,NaN,320,9,14.8,1014.0,0,2
21,2025-11-20 21:00:00,8.0,2.0,66,0,NaN,290,7,16.7,1014.0,0,2
22,2025-11-20 22:00:00,9.0,0.9,57,0,NaN,300,17,18.5,1014.0,0,2
23,2025-11-20 23:00:00,9.0,-0.1,53,0,NaN,10,4,16.7,1013.0,0,2

In [3]:
df.drop(columns=['dwpt','rhum', 'snow'], inplace=True)

In [4]:
df

                   time  temp  prcp  wdir  wspd  wpgt    pres  tsun  coco
0   2025-11-20 00:00:00   7.0     0   320    17  20.4  1013.0     0     1
1   2025-11-20 01:00:00   6.9     0   330    13  20.4  1013.1     0     1
2   2025-11-20 02:00:00   7.0     0   330    15  22.2  1013.0     0     1
3   2025-11-20 03:00:00   6.0     0   320    19  20.4  1012.0     0     1
4   2025-11-20 04:00:00   6.0     0   330    24  25.9  1012.0     0     1
5   2025-11-20 05:00:00   5.0     0   320    22  27.8  1012.0     0     2
6   2025-11-20 06:00:00   6.0     0   320    22  27.8  1012.0     0     2
7   2025-11-20 07:00:00   5.9     0   340    21  24.1  1013.0     0     2
8   2025-11-20 08:00:00   6.0     0   320    22  25.9  1013.0     0     2
9   2025-11-20 09:00:00   7.0     0   330    24  26.0  1013.0    20     2
10  2025-11-20 10:00:00   8.0     0   340    20  22.0  1014.0    23     2
11  2025-11-20 11:00:00   9.0     0   320    22  23.0  1014.0    21     3
12  2025-11-20 12:00:00  11.0     0   340    24  20.0  1013.0    22     3
13  2025-11-20 13:00:00  12.3     0   360    21  20.4  1013.5    25     3
14  2025-11-20 14:00:00  13.0     0   300     7  18.5  1013.0    31     3
15  2025-11-20 15:00:00  13.0     0   140     9  18.5  1012.0    36     2
16  2025-11-20 16:00:00  13.0     0   140     7  16.7  1013.0    31     2
17  2025-11-20 17:00:00  13.0     0   173     4  16.7  1013.0    28     1
18  2025-11-20 18:00:00  13.0     0   200     4  16.7  1013.0    13     2
19  2025-11-20 19:00:00  10.3     0   320    11  14.8  1013.9     0     2
20  2025-11-20 20:00:00   9.0     0   320     9  14.8  1014.0     0     2
21  2025-11-20 21:00:00   8.0     0   290     7  16.7  1014.0     0     2
22  2025-11-20 22:00:00   9.0     0   300    17  18.5  1014.0     0     2
23  2025-11-20 23:00:00   9.0     0    10     4  16.7  1013.0     0     2

In [5]:
df_c = pd.read_csv("clima_bcn.csv")
df_c

                    time  temp  prcp   wdir  wspd  wpgt    pres  tsun  coco
0    2025-11-16 01:00:00  13.3   1.3  270.0  13.3  27.8  1007.9   0.0   9.0
1    2025-11-16 02:00:00  13.5   2.1  232.0  11.2  31.5  1007.3   0.0   9.0
2    2025-11-16 03:00:00  14.6   0.9  211.0  21.6  35.2  1006.2   0.0   8.0
3    2025-11-16 04:00:00  15.7   0.0  230.0  27.0  35.2  1005.6   0.0   3.0
4    2025-11-16 05:00:00  15.2   0.0  256.0  18.7  35.2  1005.9   0.0   3.0
..                   ...   ...   ...    ...   ...   ...     ...   ...   ...
465  2025-12-07 18:00:00  15.5   0.0  309.0   9.3  22.2  1019.8   0.0   2.0
466  2025-12-07 19:00:00  14.5   0.0  334.0   9.3  20.4  1020.2   0.0   1.0
467  2025-12-07 20:00:00  13.5   0.0  351.0  11.1  18.5  1020.5   0.0   1.0
468  2025-12-07 21:00:00  13.1   0.0  351.0  11.1  20.4  1020.8   0.0   1.0
469  2025-12-07 22:00:00  12.6   0.0  358.0  13.0  18.5  1021.0   0.0   1.0

[470 rows x 9 columns]

In [6]:
# Primero asegúrate de que fecha + hora sean datetime
#df["datetime"] = pd.to_datetime(df_clima_total["time"] + " " + df_clima_total["hora"])
#df_c["datetime"] = pd.to_datetime(df_clima_20["time"] + " " + df_clima_20["hora"])
# Unir las tablas
df_clima_total = pd.concat([df_c, df], ignore_index=True)

# Ordenar por datetime
df_clima_total = df_clima_total.sort_values("time").reset_index(drop=True)

In [7]:
df_clima_total.head(30)

                   time  temp  prcp   wdir  wspd  wpgt    pres  tsun  coco
0   2025-11-16 01:00:00  13.3   1.3  270.0  13.3  27.8  1007.9   0.0   9.0
1   2025-11-16 02:00:00  13.5   2.1  232.0  11.2  31.5  1007.3   0.0   9.0
2   2025-11-16 03:00:00  14.6   0.9  211.0  21.6  35.2  1006.2   0.0   8.0
3   2025-11-16 04:00:00  15.7   0.0  230.0  27.0  35.2  1005.6   0.0   3.0
4   2025-11-16 05:00:00  15.2   0.0  256.0  18.7  35.2  1005.9   0.0   3.0
5   2025-11-16 06:00:00  14.4   0.0  272.0  13.0  31.5  1005.6   0.0   3.0
6   2025-11-16 07:00:00  13.7   0.0  288.0  15.1  33.3  1006.1   0.0   3.0
7   2025-11-16 08:00:00  14.3   0.0  289.0  15.5  31.5  1006.8  21.0   3.0
8   2025-11-16 09:00:00  15.5   0.0  285.0  14.0  33.3  1007.3  30.0   1.0
9   2025-11-16 10:00:00  16.6   0.0  281.0  14.4  35.2  1007.4  36.0   1.0
10  2025-11-16 11:00:00  17.5   0.0  283.0  15.8  37.0  1007.2  41.0   1.0
11  2025-11-16 12:00:00  18.2   0.0  278.0  16.2  38.9  1006.6  45.0   1.0
12  2025-11-16 13:00:00  18.5   0.0  276.0  15.5  40.8  1006.3  51.0   2.0
13  2025-11-16 14:00:00  18.3   0.0  274.0  15.1  42.6  1006.1  54.0   3.0
14  2025-11-16 15:00:00  17.8   0.0  271.0  14.8  42.6  1006.3  48.0   3.0
15  2025-11-16 16:00:00  16.7   0.0  267.0  13.0  38.9  1006.9  38.0   1.0
16  2025-11-16 17:00:00  15.1   0.0  265.0  11.2  33.3  1007.6  22.0   2.0
17  2025-11-16 18:00:00  13.7   0.0  268.0   7.9  29.6  1008.5   0.0   2.0
18  2025-11-16 19:00:00  12.7   0.0  280.0   7.9  25.9  1009.3   0.0   1.0
19  2025-11-16 20:00:00  11.9   0.0  280.0   7.2  24.1  1009.6   0.0   1.0
20  2025-11-16 21:00:00  11.0   0.0  288.0   6.5  24.1  1009.9   0.0   1.0
21  2025-11-16 22:00:00  10.3   0.0  294.0   7.2  22.2  1010.1   0.0   1.0
22  2025-11-16 23:00:00  10.0   0.0  298.0   7.9  20.4  1010.2   0.0   1.0
23  2025-11-17 01:00:00  10.0   0.0  284.0   9.0  20.4  1009.8   0.0   1.0
24  2025-11-17 02:00:00  10.2   0.0  289.0   9.7  22.2  1009.9   0.0   1.0
25  2025-11-17 03:00:00  10.5   0.0  288.0   9.7  24.1  1009.8   0.0   1.0
26  2025-11-17 04:00:00  10.5   0.0  297.0   9.7  24.1  1010.0   0.0   1.0
27  2025-11-17 05:00:00  10.0   0.0  305.0  10.4  24.1  1010.3   0.0   1.0
28  2025-11-17 06:00:00   9.6   0.0  314.0  10.4  22.2  1010.7   0.0   1.0
29  2025-11-17 07:00:00   9.0   0.0  316.0  10.4  24.1  1011.1   0.0   1.0

In [8]:
df_c2 = pd.read_csv("export(1).csv")
df_c3 = pd.read_csv("export(4).csv")
df_c2.drop(columns=['dwpt','rhum', 'snow'], inplace=True)
df_c3.drop(columns=['dwpt','rhum', 'snow'], inplace=True)
df_c2

                    time  temp  prcp  wdir  wspd  wpgt    pres  tsun  coco
0    2025-12-07 00:00:00  10.0   0.0   330  13.0  14.8  1019.0     0     2
1    2025-12-07 01:00:00  10.3   0.0   360  18.0  14.8  1019.4     0     1
2    2025-12-07 02:00:00  10.0   0.0   330  17.0  16.7  1019.0     0     2
3    2025-12-07 03:00:00  10.0   0.0   330  19.0  16.7  1019.0     0     2
4    2025-12-07 04:00:00  10.0   0.0   330  19.0  20.4  1019.0     0     2
..                   ...   ...   ...   ...   ...   ...     ...   ...   ...
259  2025-12-17 19:00:00  11.9   0.0    62  14.8   1.8  1024.3     0     2
260  2025-12-17 20:00:00  11.2   0.0    52  13.0   7.4  1024.7     0     2
261  2025-12-17 21:00:00  11.1   0.0    37  13.0   5.5  1025.0     0     2
262  2025-12-17 22:00:00  11.0   0.0    24  11.1   5.5  1025.3     0     2
263  2025-12-17 23:00:00  10.8   0.0    14  11.1   5.5  1025.6     0     2

[264 rows x 9 columns]

In [9]:

# Opcional: Asegurar que las columnas de fecha estén en formato datetime
df_clima_total['time'] = pd.to_datetime(df_clima_total['time'])
df_c2['time'] = pd.to_datetime(df_c2['time'])
#
df_c3['time'] = pd.to_datetime(df_c3['time'])

In [10]:
df_combinado = pd.concat([df_clima_total, df_c2, df_c3], ignore_index=True)


# 2. Eliminar duplicados basándose en las claves.
#    La clave de duplicación es la combinación de la columna de ID y la FECHA.
claves_duplicadas = ['time']

In [11]:
df_clima_final = df_combinado.drop_duplicates(
    subset=claves_duplicadas,
    keep='first'
).reset_index(drop=True)

In [12]:
df_clima_final

                   time  temp  prcp   wdir  wspd  wpgt    pres  tsun  coco
0   2025-11-16 01:00:00  13.3   1.3  270.0  13.3  27.8  1007.9   0.0   9.0
1   2025-11-16 02:00:00  13.5   2.1  232.0  11.2  31.5  1007.3   0.0   9.0
2   2025-11-16 03:00:00  14.6   0.9  211.0  21.6  35.2  1006.2   0.0   8.0
3   2025-11-16 04:00:00  15.7   0.0  230.0  27.0  35.2  1005.6   0.0   3.0
4   2025-11-16 05:00:00  15.2   0.0  256.0  18.7  35.2  1005.9   0.0   3.0
..                  ...   ...   ...    ...   ...   ...     ...   ...   ...
827 2025-12-21 19:00:00  10.8   0.0  286.0   9.3  25.9  1007.0   0.0   3.0
828 2025-12-21 20:00:00  10.6   0.0  299.0   9.3  24.1  1006.8   0.0   3.0
829 2025-12-21 21:00:00  10.6   0.0  319.0  11.1  25.9  1006.9   0.0   2.0
830 2025-12-21 22:00:00  10.5   0.0  349.0  11.1  25.9  1006.8   0.0   2.0
831 2025-12-21 23:00:00  10.4   0.0  354.0  13.0  27.8  1006.4   0.0   2.0

[832 rows x 9 columns]

In [13]:
df_clima_final["time"] = pd.to_datetime(df_clima_final["time"])

In [14]:
df_clima_final.columns = ["fecha_scrapeo", "temperatura", "lluvia", "d_viento", "v_viento", 
                          "racha_max", "presion_hpa", "dur_sol", "estado_clima"]

In [15]:
df_clima_final["fecha"] = df_clima_final["fecha_scrapeo"].dt.date
df_clima_final["hora"] = df_clima_final["fecha_scrapeo"].dt.hour

In [16]:
df_clima_final

,fecha_scrapeo,temperatura,lluvia,d_viento,v_viento,racha_max,presion_hpa,dur_sol,estado_clima,fecha,hora
0,2025-11-16 01:00:00,13.3,1.3,270.0,13.3,27.8,1007.9,0.0,9.0,2025-11-16,1
1,2025-11-16 02:00:00,13.5,2.1,232.0,11.2,31.5,1007.3,0.0,9.0,2025-11-16,2
2,2025-11-16 03:00:00,14.6,0.9,211.0,21.6,35.2,1006.2,0.0,8.0,2025-11-16,3
3,2025-11-16 04:00:00,15.7,0.0,230.0,27.0,35.2,1005.6,0.0,3.0,2025-11-16,4
4,2025-11-16 05:00:00,15.2,0.0,256.0,18.7,35.2,1005.9,0.0,3.0,2025-11-16,5
...,...,...,...,...,...,...,...,...,...,...,...
827,2025-12-21 19:00:00,10.8,0.0,286.0,9.3,25.9,1007.0,0.0,3.0,2025-12-21,19
828,2025-12-21 20:00:00,10.6,0.0,299.0,9.3,24.1,1006.8,0.0,3.0,2025-12-21,20
829,2025-12-21 21:00:00,10.6,0.0,319.0,11.1,25.9,1006.9,0.0,2.0,2025-12-21,21
830,2025-12-21 22:00:00,10.5,0.0,349.0,11.1,25.9,1006.8,0.0,2.0,2025-12-21,22
831,2025-12-21 23:00:00,10.4,0.0,354.0,13.0,27.8,1006.4,0.0,2.0,2025-12-21,23

In [17]:
df_clima_final["fecha"] = pd.to_datetime(df_clima_final["fecha"])

In [18]:
#df_clima_total = df_clima_total[df_clima_total['fecha'] != '2025-11-16']

In [19]:
#df_clima_total = df_clima_total[df_clima_total['fecha'] != '2025-12-03']

In [20]:
#df_clima_total = df_clima_total[df_clima_total['fecha'] != '2025-12-02']

In [21]:
#df_clima_total = df_clima_total[df_clima_total['fecha'] != '2025-12-01']

In [22]:
#df_clima_total = df_clima_total[~df_clima_total["hora"].isin([1, 2, 3,22, 23, 00,])]

In [23]:
"""
cols = list(df_clima_total.columns)

# 1. quitar "hora" de donde esté
cols.remove("hora")

# 2. insertarla en la posición 1
cols.insert(1, "hora")

# 3. reordenar el dataframe
df_clima_total = df_clima_total[cols]
"""

'\ncols = list(df_clima_total.columns)\n\n# 1. quitar "hora" de donde esté\ncols.remove("hora")\n\n# 2. insertarla en la posición 1\ncols.insert(1, "hora")\n\n# 3. reordenar el dataframe\ndf_clima_total = df_clima_total[cols]\n'

In [24]:
#cols = ['fecha_scrapeo'] + [col for col in df_clima_total.columns if col != 'fecha_scrapeo']
#df_clima_total = df_clima_total[cols]

In [25]:
df_clima_final

,fecha_scrapeo,temperatura,lluvia,d_viento,v_viento,racha_max,presion_hpa,dur_sol,estado_clima,fecha,hora
0,2025-11-16 01:00:00,13.3,1.3,270.0,13.3,27.8,1007.9,0.0,9.0,2025-11-16,1
1,2025-11-16 02:00:00,13.5,2.1,232.0,11.2,31.5,1007.3,0.0,9.0,2025-11-16,2
2,2025-11-16 03:00:00,14.6,0.9,211.0,21.6,35.2,1006.2,0.0,8.0,2025-11-16,3
3,2025-11-16 04:00:00,15.7,0.0,230.0,27.0,35.2,1005.6,0.0,3.0,2025-11-16,4
4,2025-11-16 05:00:00,15.2,0.0,256.0,18.7,35.2,1005.9,0.0,3.0,2025-11-16,5
...,...,...,...,...,...,...,...,...,...,...,...
827,2025-12-21 19:00:00,10.8,0.0,286.0,9.3,25.9,1007.0,0.0,3.0,2025-12-21,19
828,2025-12-21 20:00:00,10.6,0.0,299.0,9.3,24.1,1006.8,0.0,3.0,2025-12-21,20
829,2025-12-21 21:00:00,10.6,0.0,319.0,11.1,25.9,1006.9,0.0,2.0,2025-12-21,21
830,2025-12-21 22:00:00,10.5,0.0,349.0,11.1,25.9,1006.8,0.0,2.0,2025-12-21,22
831,2025-12-21 23:00:00,10.4,0.0,354.0,13.0,27.8,1006.4,0.0,2.0,2025-12-21,23

In [26]:
df_clima_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 832 entries, 0 to 831
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fecha_scrapeo  832 non-null    datetime64[ns]
 1   temperatura    832 non-null    float64
 2   lluvia         832 non-null    float64
 3   d_viento       832 non-null    float64
 4   v_viento       832 non-null    float64
 5   racha_max      832 non-null    float64
 6   presion_hpa    832 non-null    float64
 7   dur_sol        832 non-null    float64
 8   estado_clima   832 non-null    float64
 9   fecha          832 non-null    datetime64[ns]
 10  hora           832 non-null    int32
dtypes: datetime64[ns](2), float64(8), int32(1)
memory usage: 68.4 KB

In [27]:
df_clima_final

,fecha_scrapeo,temperatura,lluvia,d_viento,v_viento,racha_max,presion_hpa,dur_sol,estado_clima,fecha,hora
0,2025-11-16 01:00:00,13.3,1.3,270.0,13.3,27.8,1007.9,0.0,9.0,2025-11-16,1
1,2025-11-16 02:00:00,13.5,2.1,232.0,11.2,31.5,1007.3,0.0,9.0,2025-11-16,2
2,2025-11-16 03:00:00,14.6,0.9,211.0,21.6,35.2,1006.2,0.0,8.0,2025-11-16,3
3,2025-11-16 04:00:00,15.7,0.0,230.0,27.0,35.2,1005.6,0.0,3.0,2025-11-16,4
4,2025-11-16 05:00:00,15.2,0.0,256.0,18.7,35.2,1005.9,0.0,3.0,2025-11-16,5
...,...,...,...,...,...,...,...,...,...,...,...
827,2025-12-21 19:00:00,10.8,0.0,286.0,9.3,25.9,1007.0,0.0,3.0,2025-12-21,19
828,2025-12-21 20:00:00,10.6,0.0,299.0,9.3,24.1,1006.8,0.0,3.0,2025-12-21,20
829,2025-12-21 21:00:00,10.6,0.0,319.0,11.1,25.9,1006.9,0.0,2.0,2025-12-21,21
830,2025-12-21 22:00:00,10.5,0.0,349.0,11.1,25.9,1006.8,0.0,2.0,2025-12-21,22
831,2025-12-21 23:00:00,10.4,0.0,354.0,13.0,27.8,1006.4,0.0,2.0,2025-12-21,23

In [28]:
df_clima_final["hora"].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23,  0])

In [30]:
df_clima_final["fecha_scrapeo"].unique()

<DatetimeArray>
['2025-11-16 01:00:00', '2025-11-16 02:00:00', '2025-11-16 03:00:00',
 '2025-11-16 04:00:00', '2025-11-16 05:00:00', '2025-11-16 06:00:00',
 '2025-11-16 07:00:00', '2025-11-16 08:00:00', '2025-11-16 09:00:00',
 '2025-11-16 10:00:00',
 ...
 '2025-12-21 14:00:00', '2025-12-21 15:00:00', '2025-12-21 16:00:00',
 '2025-12-21 17:00:00', '2025-12-21 18:00:00', '2025-12-21 19:00:00',
 '2025-12-21 20:00:00', '2025-12-21 21:00:00', '2025-12-21 22:00:00',
 '2025-12-21 23:00:00']
Length: 832, dtype: datetime64[ns]

In [31]:
df_clima_final = df_clima_final.drop(columns=['hora', 'fecha'])

In [32]:
df_clima_final

,fecha_scrapeo,temperatura,lluvia,d_viento,v_viento,racha_max,presion_hpa,dur_sol,estado_clima
0,2025-11-16 01:00:00,13.3,1.3,270.0,13.3,27.8,1007.9,0.0,9.0
1,2025-11-16 02:00:00,13.5,2.1,232.0,11.2,31.5,1007.3,0.0,9.0
2,2025-11-16 03:00:00,14.6,0.9,211.0,21.6,35.2,1006.2,0.0,8.0
3,2025-11-16 04:00:00,15.7,0.0,230.0,27.0,35.2,1005.6,0.0,3.0
4,2025-11-16 05:00:00,15.2,0.0,256.0,18.7,35.2,1005.9,0.0,3.0
...,...,...,...,...,...,...,...,...,...
827,2025-12-21 19:00:00,10.8,0.0,286.0,9.3,25.9,1007.0,0.0,3.0
828,2025-12-21 20:00:00,10.6,0.0,299.0,9.3,24.1,1006.8,0.0,3.0
829,2025-12-21 21:00:00,10.6,0.0,319.0,11.1,25.9,1006.9,0.0,2.0
830,2025-12-21 22:00:00,10.5,0.0,349.0,11.1,25.9,1006.8,0.0,2.0
831,2025-12-21 23:00:00,10.4,0.0,354.0,13.0,27.8,1006.4,0.0,2.0

In [33]:
df_clima_final.sort_values(by='fecha_scrapeo', ascending=True)

,fecha_scrapeo,temperatura,lluvia,d_viento,v_viento,racha_max,presion_hpa,dur_sol,estado_clima
0,2025-11-16 01:00:00,13.3,1.3,270.0,13.3,27.8,1007.9,0.0,9.0
1,2025-11-16 02:00:00,13.5,2.1,232.0,11.2,31.5,1007.3,0.0,9.0
2,2025-11-16 03:00:00,14.6,0.9,211.0,21.6,35.2,1006.2,0.0,8.0
3,2025-11-16 04:00:00,15.7,0.0,230.0,27.0,35.2,1005.6,0.0,3.0
4,2025-11-16 05:00:00,15.2,0.0,256.0,18.7,35.2,1005.9,0.0,3.0
...,...,...,...,...,...,...,...,...,...
827,2025-12-21 19:00:00,10.8,0.0,286.0,9.3,25.9,1007.0,0.0,3.0
828,2025-12-21 20:00:00,10.6,0.0,299.0,9.3,24.1,1006.8,0.0,3.0
829,2025-12-21 21:00:00,10.6,0.0,319.0,11.1,25.9,1006.9,0.0,2.0
830,2025-12-21 22:00:00,10.5,0.0,349.0,11.1,25.9,1006.8,0.0,2.0
831,2025-12-21 23:00:00,10.4,0.0,354.0,13.0,27.8,1006.4,0.0,2.0

In [35]:
df_clima_final.to_csv("df_clima_hora.csv")

In [36]:
df_clima_final.to_csv("clima.csv")