In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("vuelos_dia20.csv") 
df.head(10)

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state
0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido
1,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido
2,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido
3,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido
4,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido
5,20/11/2025 14-38-34,Ryanair,FR3049,Krakow (KRK),06:40,Ha salido
6,20/11/2025 14-38-34,Ryanair,FR3028,Ibiza (IBZ),06:45,Ha salido
7,20/11/2025 14-38-34,Lauda Europe,LW2495,NaN,07:20,Ha salido
8,20/11/2025 14-38-34,Ryanair,FR133,Berlin (BER),07:25,Ha salido
9,20/11/2025 14-38-34,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:30,Ha salido

In [2]:
df.shape

NameError: name 'df' is not defined

In [11]:
df.isna().sum()

fecha_scrapeo    0
Name_company     0
Num_flight       0
Name_Destiny     0
Time_flight      0
flight_state     0
dtype: int64

In [9]:
df.loc[ (df['Name_Destiny'].isna())]

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state
7,20/11/2025 14-38-34,Lauda Europe,LW2495,NaN,07:20,Ha salido
32,20/11/2025 14-38-34,Ryanair,FR1165,NaN,10:20,"Retrasado, Ha salido"
42,20/11/2025 14-38-34,Ryanair,FR483,NaN,11:10,Ha salido
99,20/11/2025 14-38-34,Ryanair,FR1342,NaN,19:25,Programado

In [10]:
df.loc[df['Num_flight'] == 'LW2495', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'
df.loc[df['Num_flight'] == 'FR1165', 'Name_Destiny'] = 'Sevilla (SVQ)'
df.loc[df['Num_flight']== 'FR483', 'Name_Destiny'] = 'Malaga (AGP)'
df.loc[df['Num_flight']== 'FR1342', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'

In [6]:
df = df.dropna(subset=['Name_company'])

In [12]:
df

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state
0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido
1,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido
2,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido
3,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido
4,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido
...,...,...,...,...,...,...
126,20/11/2025 14-38-34,BUZZ,RR3035,Krakow (KRK),21:30,Programado
127,20/11/2025 14-38-34,BUZZ,RR4084,Warsaw (WMI),21:30,Programado
128,20/11/2025 14-38-34,Wizz Air Malta,W46020,Rome (FCO),21:35,Programado
129,20/11/2025 14-38-34,Wizz Air,W64116,Belgrade (BEG),22:10,Programado
130,20/11/2025 14-38-34,Wizz Air Malta,W45154,Tirana (TIA),22:45,Programado

In [ ]:
df.loc[df['Num_flight'] == 'FR2402', 'flight_capacity'] = 189

In [13]:
df['flight_capacity'] = np.nan
df['flight_Aircraft'] = np.nan
df['Gate'] = np.nan

In [32]:
df['Gate'] = pd.Series(dtype='object')
df['flight_Aircraft'] = pd.Series(dtype='object') # cambiarlo a objeto categorico y no numerico
df['flight_capacity'] = pd.Series(dtype='float')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 130 entries, 0 to 130
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha_scrapeo    130 non-null    object
 1   Name_company     130 non-null    object
 2   Num_flight       130 non-null    object
 3   Name_Destiny     130 non-null    object
 4   Time_flight      130 non-null    object
 5   flight_state     130 non-null    object
 6   flight_capacity  0 non-null      float64
 7   flight_Aircraft  0 non-null      object
 8   Gate             0 non-null      object
 9   Aircraft         10 non-null     object
dtypes: float64(1), object(9)
memory usage: 11.2+ KB

In [35]:
df.head(10)

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,flight_Aircraft,Gate,Aircraft
0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido,189.0,Boeing 737-800,Y,Boeing 737-800
1,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,189.0,Boeing 737-800,U,Boeing 737-800
2,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,156.0,Airbus A319,NaN,Airbus A319
3,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido,197.0,Boeing 737 MAX 8,W,Boeing 737 MAX 8
4,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido,156.0,Airbus A319,W,Airbus A319
5,20/11/2025 14-38-34,Ryanair,FR3049,Krakow (KRK),06:40,Ha salido,197.0,Boeing 737 MAX 8,S,Boeing 737 MAX 8
6,20/11/2025 14-38-34,Ryanair,FR3028,Ibiza (IBZ),06:45,Ha salido,189.0,Boeing 737-800,S,Boeing 737-800
7,20/11/2025 14-38-34,Lauda Europe,LW2495,Palma de Mallorca (PMI),07:20,Ha salido,180.0,Airbus A320,R,Airbus A320
8,20/11/2025 14-38-34,Ryanair,FR133,Berlin (BER),07:25,Ha salido,189.0,Boeing 737-800,U,Boeing 737-800
9,20/11/2025 14-38-34,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:30,Ha salido,156.0,Airbus A319,NaN,Airbus A319

In [59]:
df.loc[(df['flight_capacity'].isna())].head(30)

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,flight_Aircraft,Gate
90,20/11/2025 14-38-34,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),18:15,Programado,NaN,NaN,R

In [58]:
df.loc[df['Num_flight'] == 'W45154', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W45154', 'flight_Aircraft'] = 'Airbus A321neo'
#df.loc[df['Num_flight'] == 'W45154', 'Gate'] = 'W'

In [56]:
df.loc[df['Num_flight'] == 'EW9443', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EW9443', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'EW9443', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'W64406', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W64406', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W64406', 'Gate'] = 'U'

df.loc[df['Num_flight'] == '3O378', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == '3O378', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == '3O378', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'EW2521', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EW2521', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'EW2521', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'W61478', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W61478', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W61478', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR8598', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR8598', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR8598', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'U28058', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'U28058', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR8631', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR8631', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR8631', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'V72167', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'V72167', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'V72167', 'Gate'] = 'R'

df.loc[df['Num_flight'] == 'HV6788', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'HV6788', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'HV6788', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'EC1956', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EC1956', 'flight_Aircraft'] = 'Airbus A320'

df.loc[df['Num_flight'] == '3O376', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == '3O376', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == '3O376', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR3143', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3143', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3143', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'HV6064', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'HV6064', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'HV6064', 'Gate'] = 'U'  # CANCELADO?

df.loc[df['Num_flight'] == 'FR4587', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR4587', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR4587', 'Gate'] = 'S' 

df.loc[df['Num_flight'] == 'W62378', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W62378', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W62378', 'Gate'] = 'U' 

df.loc[df['Num_flight'] == 'TO4759', 'flight_capacity'] = 186
df.loc[df['Num_flight'] == 'TO4759', 'flight_Aircraft'] = 'Airbus A320neo'
df.loc[df['Num_flight'] == 'TO4759', 'Gate'] = 'U' 

df.loc[df['Num_flight'] == 'U22324', 'flight_capacity'] = 186
df.loc[df['Num_flight'] == 'U22324', 'flight_Aircraft'] = 'Airbus A320neo'

df.loc[df['Num_flight'] == 'W64738', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W64738', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W64738', 'Gate'] = 'W' 

df.loc[df['Num_flight'] == 'RR333', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'RR333', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'RR333', 'Gate'] = 'S' 

df.loc[df['Num_flight'] == 'EI565', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EI565', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'EI565', 'Gate'] = 'W' 

df.loc[df['Num_flight'] == 'EC1380', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EC1380', 'flight_Aircraft'] = 'Airbus A320'

df.loc[df['Num_flight'] == 'FR1527', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR1527', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR1527', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W43178', 'flight_capacity'] = 230
df.loc[df['Num_flight'] == 'W43178', 'flight_Aircraft'] = 'Airbus A321'
df.loc[df['Num_flight'] == 'W43178', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W43406', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W43406', 'flight_Aircraft'] = 'Airbus A320neo'
df.loc[df['Num_flight'] == 'W43406', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'RR3035', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'RR3035', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'RR3035', 'Gate'] = 'R'

df.loc[df['Num_flight'] == 'RR4084', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'RR4084', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'RR4084', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'W46020', 'flight_capacity'] =230
df.loc[df['Num_flight'] == 'W46020', 'flight_Aircraft'] = 'Airbus A321'
df.loc[df['Num_flight'] == 'W46020', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W64116', 'flight_capacity'] =230
df.loc[df['Num_flight'] == 'W64116', 'flight_Aircraft'] = 'Airbus A321'
df.loc[df['Num_flight'] == 'W64116', 'Gate'] = 'W'

In [53]:
df.loc[df['Num_flight'] == 'QS1059', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'QS1059', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'QS1059', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR3189', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3189', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3189', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR149', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR149', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR149', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'W46728', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W46728', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W46728', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR2922', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR2922', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR2922', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'V73573', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'V73573', 'flight_Aircraft'] = 'Airbus A319'
df.loc[df['Num_flight'] == 'V73573', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'V73700', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'V73700', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'V73700', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR9045', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR9045', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR9045', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'FR9913', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR9913', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR9913', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR4585', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR4585', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR4585', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'EC1378', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EC1378', 'flight_Aircraft'] = 'Airbus A320'

df.loc[df['Num_flight'] == 'FR2098', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR2098', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR2098', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'EC7173', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7173', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'RR8394', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'RR8394', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'RR8394', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'V72327', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'V72327', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'V72327', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'HV5136', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'HV5136', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'HV5136', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'RR6300', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'RR6300', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'RR6300', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR5718', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR5718', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR5718', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR6341', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR6341', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR6341', 'Gate'] = 'R'

df.loc[df['Num_flight'] == 'FR3078', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3078', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3078', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR6394', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR6394', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR6394', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'EC7103', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7103', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR3800', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3800', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3800', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'W43180', 'flight_capacity'] = 230
df.loc[df['Num_flight'] == 'W43180', 'flight_Aircraft'] = 'Airbus A321'
df.loc[df['Num_flight'] == 'W43180', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W61176', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'W61176', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'W61176', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'RR3193', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'RR3193', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'RR3193', 'Gate'] = 'R'

df.loc[df['Num_flight'] == 'EC7155', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7155', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR1342', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR1342', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR1342', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR8217', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR8217', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR8217', 'Gate'] = 'W'

In [50]:
df.loc[df['Num_flight'] == 'W67022', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W67022', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W67022', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR1681', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR1681', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR1681', 'Gate'] = 'R'

df.loc[df['Num_flight'] == 'V71445', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'V71445', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'V71445', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'D81741', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'D81741', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'D81741', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'EW521', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EW521', 'flight_Aircraft'] = 'Airbus A319'
df.loc[df['Num_flight'] == 'EW521', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR3039', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR3039', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR3039', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'LG3592', 'flight_capacity'] = 76
df.loc[df['Num_flight'] == 'LG3592', 'flight_Aircraft'] = 'De Havilland Dash 8-400'
df.loc[df['Num_flight'] == 'LG3592', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR269', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR269', 'flight_Aircraft'] = 'DBoeing 737-800'
df.loc[df['Num_flight'] == 'FR269', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR6267', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR6267', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR6267', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR846', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR846', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR846', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'TO4755', 'flight_capacity'] = 186
df.loc[df['Num_flight'] == 'TO4755', 'flight_Aircraft'] = 'Airbus A320neo'
df.loc[df['Num_flight'] == 'TO4755', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'LS804', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'LS804', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'LS804', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR2233', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR2233', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR2233', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'BT684', 'flight_capacity'] = 145
df.loc[df['Num_flight'] == 'BT684', 'flight_Aircraft'] = 'Airbus A220-300'
df.loc[df['Num_flight'] == 'BT684', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'EC7153', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7153', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'XQ895', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'XQ895', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'XQ895', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'KU136', 'flight_capacity'] = 278
df.loc[df['Num_flight'] == 'KU136', 'flight_Aircraft'] = 'Airbus A330-900'
df.loc[df['Num_flight'] == 'KU136', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'D85502', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'D85502', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'D85502', 'Gate'] = 'R'

df.loc[df['Num_flight'] == 'BZ251', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'BZ251', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'BZ251', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'EW7521', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EW7521', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'EW7521', 'Gate'] = 'U'

In [48]:
df.loc[df['Num_flight'] == 'W61476', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W61476', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W61476', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR1165', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR1165', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR1165', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR3121', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3121', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3121', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'RR8384', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'RR8384', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'RR8384', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'U28056', 'flight_capacity'] = 186
df.loc[df['Num_flight'] == 'U28056', 'flight_Aircraft'] = 'Airbus A320neo'

df.loc[df['Num_flight'] == 'U25716', 'flight_capacity'] = 186
df.loc[df['Num_flight'] == 'U25716', 'flight_Aircraft'] = 'Airbus A320neo'

df.loc[df['Num_flight'] == 'J246', 'flight_capacity'] = 186
df.loc[df['Num_flight'] == 'J246', 'flight_Aircraft'] = 'Airbus A320neo'
df.loc[df['Num_flight'] == 'J246', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'FR3792', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3792', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3792', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR4545', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR4545', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR4545', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'U22704', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'U22704', 'flight_Aircraft'] = 'Airbus A320'

df.loc[df['Num_flight'] == 'FR3076', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3076', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3076', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR483', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR483', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR483', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR6597', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR6597', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR6597', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'EI563', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'EI563', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'EI563', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'LS1338', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'LS1338', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'LS1338', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'EC7131', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7131', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'EC8064', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7131', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR2239', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR2239', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR2239', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR3160', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3160', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3160', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'PC1092', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'PC1092', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'PC1092', 'Gate'] = 'W'

In [40]:
df.loc[df['Num_flight'] == 'EC7151', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7151', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR2507', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR2507', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR2507', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'D85510', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'D85510', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'D85510', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR575', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR575', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR575', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'FR774', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR774', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR774', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR3928', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3928', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3928', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR6973', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR6973', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR6973', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'W43938', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'W43938', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'W43938', 'Gate'] = 'Y'

df.loc[df['Num_flight'] == 'FR5710', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR5710', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR5710', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'W62048', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W62048', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W62048', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'LW12', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'LW12', 'flight_Aircraft'] = 'Airbus A320'
df.loc[df['Num_flight'] == 'LW12', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W61914', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W61914', 'flight_Aircraft'] = 'Airbus A321neo'

df.loc[df['Num_flight'] == 'W43176', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W43176', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W43176', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W62376', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'W62376', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W62376', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'FR3320', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3320', 'flight_Aircraft'] = 'Boeing 737-800'
df.loc[df['Num_flight'] == 'FR3320', 'Gate'] = 'U'

df.loc[df['Num_flight'] == 'W42938', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'W42938', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'W42938', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'JU581', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'JU581', 'flight_Aircraft'] = 'Airbus A319'
df.loc[df['Num_flight'] == 'JU581', 'Gate'] = 'W'

df.loc[df['Num_flight'] == 'EC7656', 'flight_capacity'] = 230
df.loc[df['Num_flight'] == 'EC7656', 'flight_Aircraft'] = 'Airbus A321'

df.loc[df['Num_flight'] == 'FR1279', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR1279', 'flight_Aircraft'] = 'Boeing 737 MAX 8'
df.loc[df['Num_flight'] == 'FR1279', 'Gate'] = 'S'

df.loc[df['Num_flight'] == 'HV5132', 'flight_capacity'] = 239
df.loc[df['Num_flight'] == 'HV5132', 'flight_Aircraft'] = 'Airbus A321neo'
df.loc[df['Num_flight'] == 'HV5132', 'Gate'] = 'S'

In [38]:
df.loc[df['Name_company'] == 'easyJet Europe', 'Gate'] = 'R'
df.loc[df['Name_company'] == 'EasyJet', 'Gate'] = 'M' # Airbus A319
df.loc[df['Name_company'] == 'Easyjet', 'Gate'] = 'M'
df.loc[df['Name_company'] == 'EasyJet Europe', 'Gate'] = 'R'
df.loc[df['Name_company'] == 'easyJet', 'Gate'] = 'M'

In [34]:
df.loc[df['Num_flight'] == 'FR8215', 'Gate'] = 'Y'
df.loc[df['Num_flight'] == 'FR8215', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR8215', 'flight_Aircraft'] = 'Boeing 737-800'

df.loc[df['Num_flight'] == 'FR2918', 'Gate'] = 'U'
df.loc[df['Num_flight'] == 'FR2918', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR2918', 'flight_Aircraft'] = 'Boeing 737-800'

df.loc[df['Num_flight'] == 'EC7105', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7105', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR3976', 'Gate'] = 'W'
df.loc[df['Num_flight'] == 'FR3976', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR3976', 'flight_Aircraft'] = 'Boeing 737 MAX 8'

df.loc[df['Num_flight'] == 'EC7191', 'Gate'] = 'W'
df.loc[df['Num_flight'] == 'EC7191', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7191', 'flight_Aircraft'] = 'Airbus A319'

df.loc[df['Num_flight'] == 'FR3049', 'Gate'] = 'S'
df.loc[df['Num_flight'] == 'FR3049', 'flight_capacity'] = 197
df.loc[df['Num_flight'] == 'FR3049', 'flight_Aircraft'] = 'Boeing 737 MAX 8'

df.loc[df['Num_flight'] == 'FR3028', 'Gate'] = 'S'
df.loc[df['Num_flight'] == 'FR3028', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR3028', 'flight_Aircraft'] = 'Boeing 737-800'

df.loc[df['Num_flight'] == 'LW2495', 'Gate'] = 'R'
df.loc[df['Num_flight'] == 'LW2495', 'flight_capacity'] = 180
df.loc[df['Num_flight'] == 'LW2495', 'flight_Aircraft'] = 'Airbus A320'

df.loc[df['Num_flight'] == 'FR133', 'Gate'] = 'U'
df.loc[df['Num_flight'] == 'FR133', 'flight_capacity'] = 189
df.loc[df['Num_flight'] == 'FR133', 'flight_Aircraft'] = 'Boeing 737-800'

df.loc[df['Num_flight'] == 'EC7101', 'flight_capacity'] = 156
df.loc[df['Num_flight'] == 'EC7101', 'flight_Aircraft'] = 'Airbus A319'

In [60]:
df.isna().sum()

fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    1
flight_Aircraft    1
Gate               2
dtype: int64

In [44]:
df = df.drop(columns='Aircraft')

In [45]:
df

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,flight_Aircraft,Gate
0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido,189.0,Boeing 737-800,Y
1,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,189.0,Boeing 737-800,U
2,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,156.0,Airbus A319,R
3,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido,197.0,Boeing 737 MAX 8,W
4,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido,156.0,Airbus A319,R
...,...,...,...,...,...,...,...,...,...
126,20/11/2025 14-38-34,BUZZ,RR3035,Krakow (KRK),21:30,Programado,NaN,NaN,NaN
127,20/11/2025 14-38-34,BUZZ,RR4084,Warsaw (WMI),21:30,Programado,NaN,NaN,NaN
128,20/11/2025 14-38-34,Wizz Air Malta,W46020,Rome (FCO),21:35,Programado,NaN,NaN,NaN
129,20/11/2025 14-38-34,Wizz Air,W64116,Belgrade (BEG),22:10,Programado,NaN,NaN,NaN
130,20/11/2025 14-38-34,Wizz Air Malta,W45154,Tirana (TIA),22:45,Programado,NaN,NaN,NaN

In [62]:
df.to_csv("vuelos_limpio20.csv")