In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("vuelos_bcn_sindup.csv") 
df.head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,0.0,16/11/2025 23-03-05,Ryanair,FR3166,Palermo (PMO),11:00,Ha salido,NaN,NaN,NaN
1,1.0,16/11/2025 23-03-05,Norwegian Air Sweden AOC,D81741,Oslo (OSL),11:15,Ha salido,197.0,Boeing 737 MAX 8-200,NaN
2,2.0,16/11/2025 23-03-05,Aer Lingus,EI563,Dublin (DUB),11:30,Ha salido,189.0,Boeing 737-8AS,NaN
3,3.0,16/11/2025 23-03-05,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),11:45,Ha salido,NaN,NaN,NaN
4,4.0,16/11/2025 23-03-05,Icelandair,FI597,Keflavik (KEF),11:50,Ha salido,NaN,NaN,NaN
5,5.0,16/11/2025 23-03-05,Lauda Europe,LW2889,Palma de Mallorca (PMI),11:55,Ha salido,NaN,NaN,R
6,6.0,16/11/2025 23-03-05,Ryanair,FR3129,Ibiza (IBZ),12:05,"Retrasado, Ha salido",189.0,Boeing 737-8AS,NaN
7,7.0,16/11/2025 23-03-05,Ryanair,FR3976,Dublin (DUB),12:25,"Retrasado, Ha salido",NaN,NaN,NaN
8,8.0,16/11/2025 23-03-05,Ryanair,FR1527,Valletta (MLA),12:30,Ha salido,NaN,NaN,NaN
9,9.0,16/11/2025 23-03-05,Ryanair,FR2402,Sevilla (SVQ),12:30,Ha salido,189.0,Boeing 737-8AS,NaN

In [3]:
df.shape

(2143, 10)

In [4]:
# Dividir en diccionario por fecha
df_por_fecha = {fecha: df_fecha.copy() for fecha, df_fecha in df.groupby('fecha_scrapeo')}
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido              NaN
 117      Milan (BGY)       06:10  Retrasado, Ha salido              NaN
 118     Geneva (GVA)       06:15             Ha salido              NaN
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido              NaN
 120   Budapest (BUD)       06:25             Ha salido              NaN
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido              NaN
 282    Bristol (BRS)       21:55             Ha salido              NaN
 283   Belgrade (BEG)       21:55             Ha salido              NaN
 284       Rome (FCO)       22:20             Ha salido              NaN
 285     Tirana (TIA)       22:45             Ha salido              NaN

     Aircraft Gate
 116      NaN  NaN
 117      NaN  NaN
 118      NaN  NaN
 119      NaN  NaN
 120      NaN  NaN
 ..       ...  ...
 281      NaN  NaN
 282      NaN  NaN
 283      NaN  NaN
 284      NaN  NaN
 285      NaN  NaN

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity Aircraft  \
 286        Geneva (GVA)       06:00    Ha salido              NaN      NaN
 287           Fes (FEZ)       06:15    Ha salido              NaN      NaN
 288  Cologne-Bonn (CGN)       06:20    Ha salido              NaN      NaN
 289         Porto (OPO)       06:35    Ha salido              NaN      NaN
 290        London (LGW)       07:30    Ha salido              NaN      NaN
 ..                  ...         ...          ...              ...      ...
 349         Paris (ORY)       20:45    Ha salido              NaN      NaN
 350        Geneva (GVA)       21:15    Ha salido              NaN      NaN
 351        Dublin (DUB)       21:15   Programado              NaN      NaN
 352          Rome (FCO)       21:35    Ha salido              NaN      NaN
 353         Porto (OPO)       22:00    Ha salido              NaN      NaN

     Gate
 286  NaN
 287  NaN
 288  NaN
 289  NaN
 290  NaN
 ..   ...
 349  NaN
 350  NaN
 351  NaN
 352  NaN
 353  NaN

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido              NaN
 355        Rabat (RBA)       06:05             Ha salido              NaN
 356          Fes (FEZ)       06:05             Ha salido              NaN
 357       Geneva (GVA)       06:10             Ha salido              NaN
 358       Malaga (AGP)       06:15             Ha salido              NaN
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido              NaN
 434       Geneva (GVA)       21:15  Retrasado, Ha salido              NaN
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido              NaN
 436         Rome (FCO)       21:35             Ha salido              NaN
 437       Dublin (DUB)       22:05             Ha salido              NaN

     Aircraft Gate
 354      NaN  NaN
 355      NaN  NaN
 356      NaN  NaN
 357      NaN  NaN
 358      NaN  NaN
 ..       ...  ...
 433      NaN  NaN
 434      NaN  NaN
 435      NaN  NaN
 436      NaN  NaN
 437      NaN  NaN

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 438       440.0  20/11/2025 14-38-34         Ryanair     FR8215
 439       441.0  20/11/2025 14-38-34         Ryanair     FR2918
 440       442.0  20/11/2025 14-38-34  easyJet Europe     EC7105
 441       443.0  20/11/2025 14-38-34         Ryanair     FR3976
 442       444.0  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 563       566.0  20/11/2025 14-38-34            BUZZ     RR3035
 564       567.0  20/11/2025 14-38-34            BUZZ     RR4084
 565       568.0  20/11/2025 14-38-34  Wizz Air Malta     W46020
 566       569.0  20/11/2025 14-38-34        Wizz Air     W64116
 567       570.0  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 438    London (STN)       06:00             Ha salido              NaN
 439  Brussels (BRU)       06:05             Ha salido              NaN
 440    Geneva (GVA)       06:10             Ha salido              NaN
 441    Dublin (DUB)       06:15             Ha salido              NaN
 442   Glasgow (GLA)       06:40             Ha salido              NaN
 ..              ...         ...                   ...              ...
 563    Krakow (KRK)       21:30  Retrasado, Ha salido              NaN
 564    Warsaw (WMI)       21:30  Retrasado, Ha salido              NaN
 565      Rome (FCO)       21:35             Ha salido              NaN
 566  Belgrade (BEG)       22:10  Retrasado, Ha salido              NaN
 567    Tirana (TIA)       22:45             Ha salido              NaN

     Aircraft Gate
 438      NaN  NaN
 439      NaN  NaN
 440      NaN  NaN
 441      NaN  NaN
 442      NaN  NaN
 ..       ...  ...
 563      NaN  NaN
 564      NaN  NaN
 565      NaN  NaN
 566      NaN  NaN
 567      NaN  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido              NaN
 569   Bologna (BLQ)       06:10             Ha salido              NaN
 570    London (STN)       06:10             Ha salido              NaN
 571    Venice (VCE)       06:20             Ha salido              NaN
 572     Milan (BGY)       06:25             Ha salido              NaN
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido              NaN
 732    Malaga (AGP)       22:30            Programado              NaN
 733    Tirana (TIA)       22:45            Programado              NaN
 734    Gdansk (GDN)       22:50             Ha salido              NaN
 735    London (STN)       23:10            Programado              NaN

     Aircraft Gate
 568      NaN  NaN
 569      NaN  NaN
 570      NaN  NaN
 571      NaN  NaN
 572      NaN  NaN
 ..       ...  ...
 731      NaN  NaN
 732      NaN  NaN
 733      NaN  NaN
 734      NaN  NaN
 735      NaN  NaN

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight      Name_Destiny  \
 736         NaN   22/Nov/2025           Ryanair      FR846       Milan (BGY)
 737         NaN   22/Nov/2025    easyJet Europe     EC7105      Geneva (GVA)
 738         NaN   22/Nov/2025           Ryanair     FR5718  Bratislava (BTS)
 739         NaN   22/Nov/2025           Ryanair     FR4545       Porto (OPO)
 740         NaN   22/Nov/2025           Ryanair     FR1342               NaN
 ..          ...           ...               ...        ...               ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020        Rome (FCO)
 848         NaN   22/Nov/2025           Ryanair     FR3800  Birmingham (BHX)
 849         NaN   22/Nov/2025           Ryanair     FR8574        Rome (FCO)
 850         NaN   22/Nov/2025          Wizz Air     W64116    Belgrade (BEG)
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642      Tanger (TNG)

     Time_flight                flight_state  flight_capacity Aircraft Gate
 736       06:00  Retrasado, Ha salido 06:15              NaN      NaN  S21
 737       06:10          En hora, Ha salido              NaN      NaN   R9
 738       06:10          En hora, Ha salido              NaN      NaN  S22
 739       06:15          En hora, Ha salido              NaN      NaN  U31
 740       06:20          En hora, Ha salido              NaN      NaN  S24
 ..          ...                         ...              ...      ...  ...
 847       21:35          En hora, Ha salido              NaN      NaN  S22
 848       21:55          En hora, Ha salido              NaN      NaN  Y57
 849       22:10  Retrasado, Ha salido 22:28              NaN      NaN  U34
 850       22:10          En hora, Ha salido              NaN      NaN  Y58
 851       22:15          En hora, Ha salido              NaN      NaN  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46
 ...               ...      ...  ...
 1009              NaN      NaN  W45
 1010              NaN      NaN  W42
 1011              NaN      NaN  R13
 1012              NaN      NaN  U31
 1013              NaN      NaN  W44

 [162 rows x 10 columns],
 '24/Nov/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight     Name_Destiny  \
 1014         NaN   24/Nov/2025         Ryanair     FR3180       Rome (FCO)
 1015         NaN   24/Nov/2025         Ryanair      FR846      Milan (BGY)
 1016         NaN   24/Nov/2025  easyJet Europe     EC7105     Geneva (GVA)
 1017         NaN   24/Nov/2025         Ryanair     FR2233  Al Aaroui (NDR)

In [5]:
df_16 = df_por_fecha['16/11/2025 23-03-05'].copy()
df_16

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,0.0,16/11/2025 23-03-05,Ryanair,FR3166,Palermo (PMO),11:00,Ha salido,NaN,NaN,NaN
1,1.0,16/11/2025 23-03-05,Norwegian Air Sweden AOC,D81741,Oslo (OSL),11:15,Ha salido,197.0,Boeing 737 MAX 8-200,NaN
2,2.0,16/11/2025 23-03-05,Aer Lingus,EI563,Dublin (DUB),11:30,Ha salido,189.0,Boeing 737-8AS,NaN
3,3.0,16/11/2025 23-03-05,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),11:45,Ha salido,NaN,NaN,NaN
4,4.0,16/11/2025 23-03-05,Icelandair,FI597,Keflavik (KEF),11:50,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
111,113.0,16/11/2025 23-03-05,Wizz Air,W64116,Belgrade (BEG),21:55,"Retrasado, Ha salido",NaN,NaN,NaN
112,114.0,16/11/2025 23-03-05,Wizz Air Malta,W45154,Tirana (TIA),22:45,Ha salido,NaN,NaN,NaN
113,115.0,16/11/2025 23-03-05,Ryanair,FR5220,Bologna (BLQ),22:50,"Retrasado, Ha salido",NaN,NaN,NaN
114,116.0,16/11/2025 23-03-05,Wizz Air,W61706,Gdansk (GDN),22:50,Ha salido,NaN,NaN,NaN
115,117.0,16/11/2025 23-03-05,Ryanair,FR9406,Fes (FEZ),23:15,Ha salido,NaN,NaN,NaN

In [6]:
df_16[(df_16['Gate'].isna())].shape

(107, 10)

In [7]:
df_16[(df_16['Gate'].isna())].head(20)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,0.0,16/11/2025 23-03-05,Ryanair,FR3166,Palermo (PMO),11:00,Ha salido,NaN,NaN,NaN
1,1.0,16/11/2025 23-03-05,Norwegian Air Sweden AOC,D81741,Oslo (OSL),11:15,Ha salido,197.0,Boeing 737 MAX 8-200,NaN
2,2.0,16/11/2025 23-03-05,Aer Lingus,EI563,Dublin (DUB),11:30,Ha salido,189.0,Boeing 737-8AS,NaN
3,3.0,16/11/2025 23-03-05,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),11:45,Ha salido,NaN,NaN,NaN
4,4.0,16/11/2025 23-03-05,Icelandair,FI597,Keflavik (KEF),11:50,Ha salido,NaN,NaN,NaN
6,6.0,16/11/2025 23-03-05,Ryanair,FR3129,Ibiza (IBZ),12:05,"Retrasado, Ha salido",189.0,Boeing 737-8AS,NaN
7,7.0,16/11/2025 23-03-05,Ryanair,FR3976,Dublin (DUB),12:25,"Retrasado, Ha salido",NaN,NaN,NaN
8,8.0,16/11/2025 23-03-05,Ryanair,FR1527,Valletta (MLA),12:30,Ha salido,NaN,NaN,NaN
9,9.0,16/11/2025 23-03-05,Ryanair,FR2402,Sevilla (SVQ),12:30,Ha salido,189.0,Boeing 737-8AS,NaN
10,10.0,16/11/2025 23-03-05,Volotea,V72167,Lille/Lesquin (LIL),12:35,Ha salido,189.0,Boeing 737-8AS,NaN
12,12.0,16/11/2025 23-03-05,Pegasus Airlines,PC1092,Istanbul (SAW),12:45,"Retrasado, Ha salido",189.0,Boeing 737-8AS,NaN
13,13.0,16/11/2025 23-03-05,Ryanair,FR2511,Cologne-Bonn (CGN),12:55,"Retrasado, Ha salido",189.0,Boeing 737-8AS,NaN
14,14.0,16/11/2025 23-03-05,Ryanair,FR8598,Reggio Calabria (REG),13:05,Ha salido,NaN,NaN,NaN
15,15.0,16/11/2025 23-03-05,Volotea,V71445,Olbia (OLB),13:05,Ha salido,189.0,Boeing 737-8AS,NaN
16,16.0,16/11/2025 23-03-05,Wizz Air Malta,W46330,Milan (MXP),13:10,Ha salido,NaN,NaN,NaN
17,17.0,16/11/2025 23-03-05,Ryanair,FR3121,Beauvais (BVA),13:20,Ha salido,189.0,Boeing 737-8AS,NaN
18,18.0,16/11/2025 23-03-05,Easyjet,U28056,London (LGW),13:25,Ha salido,189.0,Boeing 737-8AS,NaN
19,19.0,16/11/2025 23-03-05,easyJet Europe,EC1380,Geneva (GVA),13:40,Ha salido,NaN,NaN,NaN
20,20.0,16/11/2025 23-03-05,Ryanair,FR9811,London (STN),13:40,"Retrasado, Ha salido",NaN,NaN,NaN
21,21.0,16/11/2025 23-03-05,Ryanair,FR483,Malaga (AGP),13:50,"Retrasado, Ha salido",189.0,Boeing 737-8AS,NaN

In [8]:
df_16.loc[df_16['Num_flight'] == 'FR6394', 'Gate'] = 'W'
df_16.loc[df_16['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_16.loc[df_16['Num_flight'] == 'FR6394', 'flight_capacity'] = 197
 
df_16.loc[df_16['Num_flight'] == 'V73700', 'Gate'] = 'S'
df_16.loc[df_16['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_16.loc[df_16['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_16.loc[df_16['Num_flight'] == 'RR5252', 'Gate'] = 'U'
df_16.loc[df_16['Num_flight'] == 'RR5252', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'RR5252', 'flight_capacity'] = 189

df_16.loc[df_16['Num_flight'] == 'FR2250', 'Gate'] = 'W'
df_16.loc[df_16['Num_flight'] == 'RR5252', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'RR5252', 'flight_capacity'] = 189

df_16.loc[df_16['Num_flight'] == 'FR2922', 'Gate'] = 'U'
df_16.loc[df_16['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737 MAX 8'
df_16.loc[df_16['Num_flight'] == 'FR2922', 'flight_capacity'] = 197

df_16.loc[df_16['Num_flight'] == 'W46728', 'Gate'] = 'S'
df_16.loc[df_16['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_16.loc[df_16['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_16.loc[df_16['Num_flight'] == 'FR4585', 'Gate'] = 'S'
df_16.loc[df_16['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_16.loc[df_16['Num_flight'] == 'FR3121', 'Gate'] = 'U'
df_16.loc[df_16['Num_flight'] == 'RR5252', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'RR5252', 'flight_capacity'] = 189

df_16.loc[df_16['Num_flight'] == 'FR3129', 'Gate'] = 'U'
df_16.loc[df_16['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_16.loc[df_16['Num_flight'] == 'EI563', 'Gate'] = 'Y'
df_16.loc[df_16['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_16.loc[df_16['Num_flight'] == 'EI563', 'flight_capacity'] = 180

df_16.loc[df_16['Num_flight'] == 'PC1092', 'Gate'] = 'W'
df_16.loc[df_16['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_16.loc[df_16['Num_flight'] == 'PC1092', 'flight_capacity'] = 180

In [9]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
    df_16.loc[df_16['Num_flight'] == 'TO4759', 'flight_capacity'] = 186
    df_16.loc[df_16['Num_flight'] == 'TO4759', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A320neo'
    df_16.loc[df_16['Num_flight'] == 'HV5134', 'flight_capacity'] = 186
    df_16.loc[df_16['Num_flight'] == 'HV5134', 'Gate'] = 'U'
        
    df_16.loc[df_16['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'EI565', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'EI565', 'Gate'] = 'Y'
            
    df_16.loc[df_16['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR3792', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR3792', 'Gate'] = 'W'
            
    df_16.loc[df_16['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'W43406', 'flight_capacity'] = 180
    
    df_16.loc[df_16['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'FR5752', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR5752', 'Gate'] = 'R'

    df_16.loc[df_16['Num_flight'] == 'U28060', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'U28060', 'flight_capacity'] = 156
                    
    df_16.loc[df_16['Num_flight'] == 'W45154', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'W45154', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'W45154', 'Gate'] = 'W'
                        
    df_16.loc[df_16['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W46020', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W46020', 'Gate'] = 'S'

In [10]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR5718', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR5718', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR12', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR12', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'V73573', 'flight_capacity'] = 156
    df_16.loc[df_16['Num_flight'] == 'V73573', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR1681', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR1681', 'Gate'] = 'U'
        
    df_16.loc[df_16['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR777', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR777', 'Gate'] = 'R'
    
    df_16.loc[df_16['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR6305', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR6305', 'Gate'] = 'U'
        
    df_16.loc[df_16['Num_flight'] == 'EC7109', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'EC7109', 'flight_capacity'] = 156
      
    df_16.loc[df_16['Num_flight'] == 'FR2406', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR2406', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR2406', 'Gate'] = 'U'
          
    df_16.loc[df_16['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'W43686', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'W43686', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'LS804', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'LS804', 'Gate'] = 'W'
    
    df_16.loc[df_16['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR8631', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR8631', 'Gate'] = 'W'
       
    df_16.loc[df_16['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'W61176', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'W61176', 'Gate'] = 'S'
           
    df_16.loc[df_16['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321'
    df_16.loc[df_16['Num_flight'] == 'W61478', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'W61478', 'Gate'] = 'S'
               
    df_16.loc[df_16['Num_flight'] == 'EC7159', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'EC7159', 'flight_capacity'] = 156
    
    df_16.loc[df_16['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321'
    df_16.loc[df_16['Num_flight'] == 'W64406', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'W64406', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'EC3750', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'EC3750', 'flight_capacity'] = 180
        
    df_16.loc[df_16['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR9015', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR9015', 'Gate'] = 'Y'
            
    df_16.loc[df_16['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'U28058', 'flight_capacity'] = 156
        
    df_16.loc[df_16['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'EC4212', 'flight_capacity'] = 180
         
    df_16.loc[df_16['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W67022', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W67022', 'Gate'] = 'S'

In [11]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'BZ251', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'BZ251', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'BZ251', 'Gate'] = 'W'
    
    df_16.loc[df_16['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR3320', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR3320', 'Gate'] = 'U'
        
    df_16.loc[df_16['Num_flight'] == 'EC7694', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'EC7694', 'flight_capacity'] = 180
    
    df_16.loc[df_16['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'FR6973', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR6973', 'Gate'] = 'S'
        
    df_16.loc[df_16['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == '3O378', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == '3O378', 'Gate'] = 'W'
    
    df_16.loc[df_16['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR133', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR133', 'Gate'] = 'R'
    
    df_16.loc[df_16['Num_flight'] == 'FR9814', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR9814', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR9814', 'Gate'] = 'R'

    df_16.loc[df_16['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR8669', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR8669', 'Gate'] = 'W'

    df_16.loc[df_16['Num_flight'] == '3O374', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == '3O374', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == '3O374', 'Gate'] = 'Y'

    df_16.loc[df_16['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'RR8394', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'RR8394', 'Gate'] = 'S'

In [12]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR3166', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR3166', 'Gate'] = 'S'

    df_16.loc[df_16['Num_flight'] == 'EC7139', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'EC7139', 'flight_capacity'] = 156
    
    df_16.loc[df_16['Num_flight'] == 'LW2889', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'LW2889', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'LW2889', 'Gate'] = 'U'

    df_16.loc[df_16['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'FR3976', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR3976', 'Gate'] = 'W'

    df_16.loc[df_16['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR1527', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR1527', 'Gate'] = 'S'

    df_16.loc[df_16['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR6300', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR6300', 'Gate'] = 'U'

    df_16.loc[df_16['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'EC1380', 'flight_capacity'] = 180
    
    df_16.loc[df_16['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR1342', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR1342', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'HV5132', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'HV5132', 'Gate'] = 'U'

    df_16.loc[df_16['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'FI597', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FI597', 'Gate'] = 'R'

In [13]:
df_16.loc[df_16['Name_company'] == 'easyJet Europe', 'Gate'] = 'R'
df_16.loc[df_16['Name_company'] == 'EasyJet', 'Gate'] = 'M' # Airbus A319
df_16.loc[df_16['Name_company'] == 'Easyjet', 'Gate'] = 'M'
df_16.loc[df_16['Name_company'] == 'EasyJet Europe', 'Gate'] = 'R'
df_16.loc[df_16['Name_company'] == 'easyJet', 'Gate'] = 'M'

In [14]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR2402', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR2402', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'FR2402', 'Name_Destiny'] = 'Sevilla (SVQ)'
    
    df_16.loc[df_16['Num_flight'] == 'V72167', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'V72167', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'V72167', 'Aircraft'] = 'Airbus A320'
    
    df_16.loc[df_16['Num_flight'] == 'FR2511', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'FR2511', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR2511', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'FR8598', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'FR8598', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR8598', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'V71445', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'V71445', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'V71445', 'Aircraft'] = 'Airbus A320'
    
    df_16.loc[df_16['Num_flight'] == 'W46330', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'W46330', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
    
    df_16.loc[df_16['Num_flight'] == 'W46330', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'W46330', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'W46330', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'FR9811', 'Gate'] = 'Y'
    df_16.loc[df_16['Num_flight'] == 'FR9811', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737 MAX 8'
    
    df_16.loc[df_16['Num_flight'] == 'FR483', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'FR483', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR483', 'Name_Destiny'] = 'Malaga (AGP)'
    
    df_16.loc[df_16['Num_flight'] == 'BT684', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'BT684', 'flight_capacity'] = 148
    df_16.loc[df_16['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
    
    df_16.loc[df_16['Num_flight'] == 'FR6920', 'Gate'] = 'W'
    df_16.loc[df_16['Num_flight'] == 'FR6920', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737 MAX 8'
    
    df_16.loc[df_16['Num_flight'] == 'PC7184', 'Gate'] = 'W'
    df_16.loc[df_16['Num_flight'] == 'PC7184', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'PC7184', 'Aircraft'] = 'Boeing 737 MAX 8'
    
    df_16.loc[df_16['Num_flight'] == 'XQ895', 'Gate'] = 'Y'
    df_16.loc[df_16['Num_flight'] == 'XQ895', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'XQ895', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'D85502', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'D85502', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'FR269', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'FR269', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'QS1059', 'Gate'] = 'S'
    df_16.loc[df_16['Num_flight'] == 'QS1059', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'FR774', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'FR774', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'RR3072', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'RR3072', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'RR3072', 'Aircraft'] = 'Boeing 737-800'
    
    df_16.loc[df_16['Num_flight'] == 'TO4755', 'Gate'] = 'U'
    df_16.loc[df_16['Num_flight'] == 'TO4755', 'flight_capacity'] = 186
    df_16.loc[df_16['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'

In [15]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'HV6066', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'HV6066', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'HV6066', 'Gate'] = 'U'

    df_16.loc[df_16['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
    df_16.loc[df_16['Num_flight'] == 'U25716', 'flight_capacity'] = 186
    df_16.loc[df_16['Num_flight'] == 'U25716', 'Gate'] = 'M'
    
    df_16.loc[df_16['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
    df_16.loc[df_16['Num_flight'] == 'W43180', 'flight_capacity'] = 230
    df_16.loc[df_16['Num_flight'] == 'W43180', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'FR3160', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR3160', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR3160', 'Gate'] = 'Y'
    
    df_16.loc[df_16['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
    df_16.loc[df_16['Num_flight'] == 'V72165', 'flight_capacity'] = 156
    df_16.loc[df_16['Num_flight'] == 'V72165', 'Gate'] = 'R'
    
    df_16.loc[df_16['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR2233', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR2233', 'Gate'] = 'W'
    
    df_16.loc[df_16['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR5710', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR5710', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'LS1338', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'LS1338', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'LS1338', 'Gate'] = 'Y'
    
    df_16.loc[df_16['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W64666', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W64666', 'Gate'] = 'Y'

In [16]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'FR8136', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR8136', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR8136', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W62096', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W62096', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'HV6788', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'HV6788', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'FR6985', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR6985', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'JU585', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'JU585', 'Gate'] = 'W'
    
    df_16.loc[df_16['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'D83659', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'D83659', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'EW2521', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'EW2521', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR4587', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR4587', 'Gate'] = 'R'

In [17]:
if (df_16['fecha_scrapeo'] == "16/11/2025 23-03-05").any():
    df_16.loc[df_16['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'D81741', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'D81741', 'Gate'] = 'U'
    
    df_16.loc[df_16['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR9406', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR9406', 'Gate'] = 'Y'
    
    df_16.loc[df_16['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W61706', 'flight_capacity'] = 239 
    df_16.loc[df_16['Num_flight'] == 'W61706', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR5220', 'flight_capacity'] = 189 
    df_16.loc[df_16['Num_flight'] == 'FR5220', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W64116', 'flight_capacity'] = 239 
    df_16.loc[df_16['Num_flight'] == 'W64116', 'Gate'] = 'Y'
    
    df_16.loc[df_16['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
    df_16.loc[df_16['Num_flight'] == 'V71415', 'flight_capacity'] = 180
    df_16.loc[df_16['Num_flight'] == 'V71415', 'Gate'] = 'S'
    
    df_16.loc[df_16['Num_flight'] == 'U22706', 'Aircraft'] = 'Airbus A320neo'
    df_16.loc[df_16['Num_flight'] == 'U22706', 'flight_capacity'] = 186
    df_16.loc[df_16['Num_flight'] == 'U22706', 'Gate'] = 'M'
    
    df_16.loc[df_16['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
    df_16.loc[df_16['Num_flight'] == 'W43178', 'flight_capacity'] = 230
    df_16.loc[df_16['Num_flight'] == 'W43178', 'Gate'] = 'S' 
    
    df_16.loc[df_16['Num_flight'] == 'FR2896', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'FR2896', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'FR2896', 'Gate'] = "R"
    df_16.loc[df_16['Num_flight'] == 'FR2896', 'Name_Destiny'] = "Palma de Mallorca (PMI)"
    
    df_16.loc[df_16['Num_flight'] == 'RR8615', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'RR8615', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'RR8615', 'Gate'] = "R"
    
    df_16.loc[df_16['Num_flight'] == 'W64738', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W64738', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W64738', 'Gate'] = "W"
    
    df_16.loc[df_16['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
    df_16.loc[df_16['Num_flight'] == 'U22326', 'flight_capacity'] = 186
    df_16.loc[df_16['Num_flight'] == 'U22326', 'Gate'] = "M"
    
    df_16.loc[df_16['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'RR6944', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'RR6944', 'Gate'] = "R"
    
    df_16.loc[df_16['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_16.loc[df_16['Num_flight'] == 'FR6275', 'flight_capacity'] = 197
    df_16.loc[df_16['Num_flight'] == 'FR6275', 'Gate'] = "Y"
    
    df_16.loc[df_16['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
    df_16.loc[df_16['Num_flight'] == 'W62378', 'flight_capacity'] = 239
    df_16.loc[df_16['Num_flight'] == 'W62378', 'Gate'] = "U"
    
    df_16.loc[df_16['Num_flight'] == 'LG3596', 'Aircraft'] = 'Boeing 737-800'
    df_16.loc[df_16['Num_flight'] == 'LG3596', 'flight_capacity'] = 189
    df_16.loc[df_16['Num_flight'] == 'LG3596', 'Gate'] = "R"

In [18]:
df_16.isna().sum()

Unnamed: 0         0
fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    0
Aircraft           0
Gate               1
dtype: int64

In [19]:
df_16['Aircraft'].unique()

array(['Boeing 737-800', 'Airbus A320', 'Airbus A319', 'Boeing 737 MAX 8',
       'Airbus A321', 'Boeing 737-8AS', 'Airbus A220-300',
       'Boeing 737 MAX 8-200', 'Airbus A321neo', 'Airbus A320neo'],
      dtype=object)

In [20]:
df_16[(df_16['Aircraft'] == 'Boeing 737-800')].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,0.0,16/11/2025 23-03-05,Ryanair,FR3166,Palermo (PMO),11:00,Ha salido,189.0,Boeing 737-800,S
1,1.0,16/11/2025 23-03-05,Norwegian Air Sweden AOC,D81741,Oslo (OSL),11:15,Ha salido,189.0,Boeing 737-800,U
6,6.0,16/11/2025 23-03-05,Ryanair,FR3129,Ibiza (IBZ),12:05,"Retrasado, Ha salido",189.0,Boeing 737-800,U
8,8.0,16/11/2025 23-03-05,Ryanair,FR1527,Valletta (MLA),12:30,Ha salido,189.0,Boeing 737-800,S
9,9.0,16/11/2025 23-03-05,Ryanair,FR2402,Sevilla (SVQ),12:30,Ha salido,189.0,Boeing 737-800,U
11,11.0,16/11/2025 23-03-05,Ryanair,FR6300,Sofia (SOF),12:45,Ha salido,189.0,Boeing 737-800,U
13,13.0,16/11/2025 23-03-05,Ryanair,FR2511,Cologne-Bonn (CGN),12:55,"Retrasado, Ha salido",189.0,Boeing 737-800,S
14,14.0,16/11/2025 23-03-05,Ryanair,FR8598,Reggio Calabria (REG),13:05,Ha salido,189.0,Boeing 737-800,S
16,16.0,16/11/2025 23-03-05,Wizz Air Malta,W46330,Milan (MXP),13:10,Ha salido,189.0,Boeing 737-800,U
21,21.0,16/11/2025 23-03-05,Ryanair,FR483,Malaga (AGP),13:50,"Retrasado, Ha salido",189.0,Boeing 737-800,S

In [21]:
df_16.loc[df_16['Num_flight'] == 'W64406', 'flight_capacity'] = 230
df_16.loc[df_16['Num_flight'] == 'W61478', 'flight_capacity'] = 230
df_16.loc[df_16['Num_flight'] == 'PC1092', 'flight_capacity'] = 230

In [22]:
df_16[(df_16['Aircraft'] == 'Boeing 737 MAX 8-200')].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
23,23.0,16/11/2025 23-03-05,easyJet Europe,EC7153,Milan (MXP),14:05,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8-200,R

In [23]:
df_16.loc[df_16['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_16.loc[df_16['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

In [24]:
df_16[(df_16['Aircraft'] == 'Boeing 737-8AS')].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
17,17.0,16/11/2025 23-03-05,Ryanair,FR3121,Beauvais (BVA),13:20,Ha salido,189.0,Boeing 737-8AS,U
18,18.0,16/11/2025 23-03-05,Easyjet,U28056,London (LGW),13:25,Ha salido,189.0,Boeing 737-8AS,M
30,30.0,16/11/2025 23-03-05,easyJet Europe,EC7107,Geneva (GVA),14:25,Ha salido,189.0,Boeing 737-8AS,R
45,45.0,16/11/2025 23-03-05,easyJet Europe,EC7173,Berlin (BER),16:30,Ha salido,189.0,Boeing 737-8AS,R
49,49.0,16/11/2025 23-03-05,Ryanair,FR2250,Marrakech (RAK),17:00,Ha salido,189.0,Boeing 737-8AS,W
63,63.0,16/11/2025 23-03-05,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:45,Ha salido,189.0,Boeing 737-8AS,R

In [25]:
df_16.loc[df_16['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_16.loc[df_16['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_16.loc[df_16['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_16.loc[df_16['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_16.loc[df_16['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_16.loc[df_16['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

df_16.loc[df_16['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_16.loc[df_16['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_16.loc[df_16['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_16.loc[df_16['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'

In [26]:
df_16.shape

(116, 10)

In [27]:
#df_por_fecha['16/11/2025 23-03-05'] = df_16

In [28]:
#df_por_fecha

In [29]:
df_17 = df_por_fecha['17/11/2025 14-06-56'].copy()
df_17

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
116,118.0,17/11/2025 14-06-56,Ryanair,FR3180,Rome (FCO),06:00,Ha salido,NaN,NaN,NaN
117,119.0,17/11/2025 14-06-56,Ryanair,FR846,Milan (BGY),06:10,"Retrasado, Ha salido",NaN,NaN,NaN
118,120.0,17/11/2025 14-06-56,easyJet Europe,EC7105,Geneva (GVA),06:15,Ha salido,NaN,NaN,NaN
119,121.0,17/11/2025 14-06-56,Ryanair,FR2233,Al Aaroui (NDR),06:20,"Retrasado, Ha salido",NaN,NaN,NaN
120,122.0,17/11/2025 14-06-56,Ryanair,FR8384,Budapest (BUD),06:25,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
281,283.0,17/11/2025 14-06-56,Ryanair,FR2250,Marrakech (RAK),21:50,Ha salido,NaN,NaN,NaN
282,284.0,17/11/2025 14-06-56,Easyjet,U22706,Bristol (BRS),21:55,Ha salido,NaN,NaN,NaN
283,285.0,17/11/2025 14-06-56,Wizz Air,W64116,Belgrade (BEG),21:55,Ha salido,NaN,NaN,NaN
284,286.0,17/11/2025 14-06-56,Ryanair,FR8574,Rome (FCO),22:20,Ha salido,NaN,NaN,NaN
285,287.0,17/11/2025 14-06-56,Wizz Air Malta,W45154,Tirana (TIA),22:45,Ha salido,NaN,NaN,NaN

In [30]:
df_17[(df_17['Aircraft'].isna())].head(20)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
116,118.0,17/11/2025 14-06-56,Ryanair,FR3180,Rome (FCO),06:00,Ha salido,NaN,NaN,NaN
117,119.0,17/11/2025 14-06-56,Ryanair,FR846,Milan (BGY),06:10,"Retrasado, Ha salido",NaN,NaN,NaN
118,120.0,17/11/2025 14-06-56,easyJet Europe,EC7105,Geneva (GVA),06:15,Ha salido,NaN,NaN,NaN
119,121.0,17/11/2025 14-06-56,Ryanair,FR2233,Al Aaroui (NDR),06:20,"Retrasado, Ha salido",NaN,NaN,NaN
120,122.0,17/11/2025 14-06-56,Ryanair,FR8384,Budapest (BUD),06:25,Ha salido,NaN,NaN,NaN
121,123.0,17/11/2025 14-06-56,Ryanair,FR3078,Lisbon (LIS),06:30,Ha salido,NaN,NaN,NaN
122,124.0,17/11/2025 14-06-56,easyJet Europe,EC8062,London (LGW),06:45,"Retrasado, Ha salido",NaN,NaN,NaN
123,125.0,17/11/2025 14-06-56,Ryanair,FR3035,Krakow (KRK),06:45,Ha salido,NaN,NaN,NaN
124,126.0,17/11/2025 14-06-56,Ryanair,FR8215,London (STN),06:45,Ha salido,NaN,NaN,NaN
125,127.0,17/11/2025 14-06-56,easyJet Europe,EC7141,Strasbourg (SXB),07:20,Ha salido,NaN,NaN,NaN
126,128.0,17/11/2025 14-06-56,easyJet Europe,EC7151,Milan (MXP),07:20,Ha salido,NaN,NaN,NaN
127,129.0,17/11/2025 14-06-56,Ryanair,FR3028,Ibiza (IBZ),07:35,Ha salido,NaN,NaN,NaN
128,130.0,17/11/2025 14-06-56,Lauda Europe,LW1342,Palma de Mallorca (PMI),07:40,Ha salido,NaN,NaN,NaN
129,131.0,17/11/2025 14-06-56,Ryanair,FR1165,Sevilla (SVQ),07:55,Ha salido,NaN,NaN,NaN
130,132.0,17/11/2025 14-06-56,Norwegian Air Sweden AOC,D85510,Copenhagen (CPH),08:00,Ha salido,NaN,NaN,NaN
131,133.0,17/11/2025 14-06-56,Ryanair,FR58,Napoli (NAP),08:35,Ha salido,NaN,NaN,NaN
132,134.0,17/11/2025 14-06-56,Ryanair,FR575,Bologna (BLQ),08:40,Ha salido,NaN,NaN,NaN
133,135.0,17/11/2025 14-06-56,easyJet Europe,EC1376,Geneva (GVA),08:45,Ha salido,NaN,NaN,NaN
134,136.0,17/11/2025 14-06-56,Lauda Europe,LW12,Vienna (VIE),09:00,Ha salido,NaN,NaN,NaN
135,137.0,17/11/2025 14-06-56,Ryanair,FR6078,Ouarzazate (OZZ),09:05,Ha salido,NaN,NaN,NaN

In [31]:
df_17.loc[df_17['Num_flight'] == 'W45154', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'W45154', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'W64116', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'W64116', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'FR8574', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR8574', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR8574', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'U22706', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'U22706', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR1527', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR1527', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR2250', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR2250', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR4587', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR4587', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR3168', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR3168', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3168', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W46020', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W46020', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'RR4084', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'RR4084', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2402', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR2402', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W43406', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W43406', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'W43178', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'EC1380', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR6920', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR6920', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR6275', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR6275', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'

In [32]:
df_17.loc[df_17['Num_flight'] == 'EI565', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'EI565', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR878', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR878', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'V72165', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'V72165', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR3928', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR3928', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2098', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR2098', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W62378', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'W62378', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'W62378', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'TO4759', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'TO4759', 'flight_capacity'] = 186
df_17.loc[df_17['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'

df_17.loc[df_17['Num_flight'] == 'RR8394', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'RR8394', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR5710', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR5710', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'JU585', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'JU585', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'V72135', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'V72135', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'V72135', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'TW408', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'TW408', 'flight_capacity'] = 246
df_17.loc[df_17['Num_flight'] == 'TW408', 'Aircraft'] = 'Airbus A330-200'

df_17.loc[df_17['Num_flight'] == 'EC1010', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC1010', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'W42940', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W42940', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'EC1956', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR6597', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR6597', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR6341', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR6341', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3807', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR3807', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3185', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR3185', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'

In [33]:
df_17.loc[df_17['Num_flight'] == '3O378', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == '3O378', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR3080', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR3080', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3080', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W64666', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'W64666', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'V71415', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'V71415', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'U28058', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'LW7351', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'LW7351', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR133', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR133', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'W61706', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W61706', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'LW2896', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'LW2896', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'LW2896', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'EW7521', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'EW7521', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR8231', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR8231', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR9307', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR9307', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR9307', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W61478', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W61478', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'FR3174', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR3174', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC7205', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7205', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR269', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR269', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'RR333', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'RR333', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'HV5134', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'HV5134', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'

In [34]:
df_17.loc[df_17['Num_flight'] == 'W43686', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'W43686', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR3320', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR3320', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR3320', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR3320', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'EC7199', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7199', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'EC3737', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR2922', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR2922', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR1786', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR1786', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR1786', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W67920', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'W67920', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'V73700', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'V73700', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'EC7173', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'RR6300', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'RR6300', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR5270', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR5270', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'U23372', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'U23372', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'RR6874', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'RR6874', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'RR6874', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR6305', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR6305', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR5718', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR5718', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2507', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR2507', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'

In [35]:
df_17.loc[df_17['Num_flight'] == 'V73735', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'V73735', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'V73735', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'V73735', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'W43564', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W43564', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'W43564', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR9811', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR9811', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR867', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR867', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'PC1094', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'PC1094', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'W46728', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W46728', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'FR1681', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3146', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR3146', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3146', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == '3O376', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'QS1059', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'QS1059', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC4212', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'W64406', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W64406', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'V71443', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'V71443', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'V71443', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'EC7107', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'BZ251', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'BZ251', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'D85502', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'D85502', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2889', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR2889', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2889', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'BT684', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'BT684', 'flight_capacity'] = 148
df_17.loc[df_17['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'

df_17.loc[df_17['Num_flight'] == 'FR3792', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR3792', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'LS804', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'LS804', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'

In [36]:
df_17.loc[df_17['Num_flight'] == 'FR3189', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR3189', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'TK608', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'TK608', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR4585', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR4585', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC7153', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'LG3592', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'LG3592', 'flight_capacity'] = 76
df_17.loc[df_17['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'

df_17.loc[df_17['Num_flight'] == 'PC1528', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'PC1528', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'EW521', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'EW521', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'D81741', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'D81741', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'H4264', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'H4264', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR8631', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR8631', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W46330', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'W46330', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'FR3108', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3108', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'W67022', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W67022', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'EC7137', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7137', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'D83657', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'D83657', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'PC1092', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'PC1092', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR774', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR774', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR6973', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR6973', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR8217', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR8217', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR777', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR777', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'

In [37]:
df_17.loc[df_17['Num_flight'] == 'FR3129', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR3129', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'LS232', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'LS232', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'LS232', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3129', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR3129', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC7197', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7197', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR1279', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR1279', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'TO4755', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'TO4755', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR7539', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR7539', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EI563', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'EI563', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == '3F232', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == '3F232', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == '3F232', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'U22002', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR9045', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR9045', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3039', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3039', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3976', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR3976', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR3121', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3121', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2239', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR2239', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'U28056', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'EC7131', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR7808', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR7808', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'U22324', 'flight_capacity'] = 186
df_17.loc[df_17['Num_flight'] == 'U22324', 'Aircraft'] = 'Airbus A320neo'

In [38]:
df_17.loc[df_17['Num_flight'] == 'FR3143', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3143', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W61476', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W61476', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'FR6559', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR6559', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR6559', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'W46018', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'W46018', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'TO4751', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'TO4751', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'HV5132', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'HV5132', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'HV5132', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC7656', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'JU581', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'JU581', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR4545', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR4545', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2495', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR2495', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2495', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EW9441', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'EW9441', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EW9441', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'HV6062', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'HV6062', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'HV6062', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR2834', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR2834', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC1030', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EC1030', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'V73573', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'V73573', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'W62376', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'W62376', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'W45088', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'W45088', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'W43176', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'W43176', 'flight_capacity'] = 230
df_17.loc[df_17['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'

df_17.loc[df_17['Num_flight'] == 'EW2521', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'EW2521', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == '3O398', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == '3O398', 'Aircraft'] = 'Airbus A320'

In [39]:
df_17.loc[df_17['Num_flight'] == 'V72327', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'V72327', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'W62048', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'W62048', 'flight_capacity'] = 239
df_17.loc[df_17['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'

df_17.loc[df_17['Num_flight'] == 'FR6078', 'Gate'] = 'W'
df_17.loc[df_17['Num_flight'] == 'FR6078', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR6078', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'LW12', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'LW12', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'EC1376', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR575', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR575', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR58', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR58', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'D85510', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'D85510', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR1165', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR1165', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'LW1342', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'LW1342', 'flight_capacity'] = 180
df_17.loc[df_17['Num_flight'] == 'LW1342', 'Aircraft'] = 'Airbus A320'

df_17.loc[df_17['Num_flight'] == 'FR3028', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3028', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC7151', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'EC7141', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7141', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR8215', 'Gate'] = 'Y'
df_17.loc[df_17['Num_flight'] == 'FR8215', 'flight_capacity'] = 197
df_17.loc[df_17['Num_flight'] == 'FR8215', 'Aircraft'] = 'Boeing 737 MAX 8'

df_17.loc[df_17['Num_flight'] == 'FR3035', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR3035', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC8062', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR3078', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3078', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR8384', 'Gate'] = 'R'
df_17.loc[df_17['Num_flight'] == 'FR8384', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR8384', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'EC7105', 'flight_capacity'] = 156
df_17.loc[df_17['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'

df_17.loc[df_17['Num_flight'] == 'FR2233', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'

In [40]:
df_17.loc[df_17['Name_company'] == 'easyJet Europe', 'Gate'] = 'R'
df_17.loc[df_17['Name_company'] == 'EasyJet', 'Gate'] = 'M' # Airbus A319
df_17.loc[df_17['Name_company'] == 'Easyjet', 'Gate'] = 'M'
df_17.loc[df_17['Name_company'] == 'EasyJet Europe', 'Gate'] = 'R'
df_17.loc[df_17['Name_company'] == 'easyJet', 'Gate'] = 'M'

In [41]:
df_17.loc[df_17['Num_flight'] == 'FR3180', 'Gate'] = 'U'
df_17.loc[df_17['Num_flight'] == 'FR3180', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'

df_17.loc[df_17['Num_flight'] == 'FR846', 'Gate'] = 'S'
df_17.loc[df_17['Num_flight'] == 'FR846', 'flight_capacity'] = 189
df_17.loc[df_17['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'

In [42]:
df_17.shape

(170, 10)

In [43]:
df_17.isna().sum()

Unnamed: 0         0
fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    1
Aircraft           1
Gate               8
dtype: int64

In [44]:
df_17['flight_capacity'].unique()

array([189., 156., 197., 180., 239., 230., 186.,  76., 148.,  nan, 246.])

In [45]:
df_17['Aircraft'].unique()

array(['Boeing 737-800', 'Airbus A319', 'Boeing 737 MAX 8', 'Airbus A320',
       'Airbus A321neo', 'Airbus A321', 'Airbus A320neo',
       'de Havilland Dash 8-400', 'Airbus A220-300', nan,
       'Airbus A330-200'], dtype=object)

In [46]:
df_17[(df_17['Aircraft'] == 'Boeing 737-800')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
116,118.0,17/11/2025 14-06-56,Ryanair,FR3180,Rome (FCO),06:00,Ha salido,189.0,Boeing 737-800,U
117,119.0,17/11/2025 14-06-56,Ryanair,FR846,Milan (BGY),06:10,"Retrasado, Ha salido",189.0,Boeing 737-800,S
119,121.0,17/11/2025 14-06-56,Ryanair,FR2233,Al Aaroui (NDR),06:20,"Retrasado, Ha salido",189.0,Boeing 737-800,NaN
120,122.0,17/11/2025 14-06-56,Ryanair,FR8384,Budapest (BUD),06:25,Ha salido,189.0,Boeing 737-800,R
121,123.0,17/11/2025 14-06-56,Ryanair,FR3078,Lisbon (LIS),06:30,Ha salido,189.0,Boeing 737-800,U
...,...,...,...,...,...,...,...,...,...,...
271,273.0,17/11/2025 14-06-56,Ryanair,FR6920,Dublin (DUB),21:10,Ha salido,189.0,Boeing 737-800,Y
275,277.0,17/11/2025 14-06-56,Ryanair,FR2402,Sevilla (SVQ),21:30,"Retrasado, Ha salido",189.0,Boeing 737-800,U
276,278.0,17/11/2025 14-06-56,BUZZ,RR4084,Warsaw (WMI),21:30,"Retrasado, Ha salido",189.0,Boeing 737-800,R
278,280.0,17/11/2025 14-06-56,Ryanair,FR3168,Newcastle (NCL),21:45,Ha salido,189.0,Boeing 737-800,W
284,286.0,17/11/2025 14-06-56,Ryanair,FR8574,Rome (FCO),22:20,Ha salido,189.0,Boeing 737-800,U

In [47]:
# AL ACABAR DE MODIFICAR GUARDARLO EN EL DICCIONARIO 
df_por_fecha['17/11/2025 14-06-56'] = df_17

In [48]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity Aircraft  \
 286        Geneva (GVA)       06:00    Ha salido              NaN      NaN
 287           Fes (FEZ)       06:15    Ha salido              NaN      NaN
 288  Cologne-Bonn (CGN)       06:20    Ha salido              NaN      NaN
 289         Porto (OPO)       06:35    Ha salido              NaN      NaN
 290        London (LGW)       07:30    Ha salido              NaN      NaN
 ..                  ...         ...          ...              ...      ...
 349         Paris (ORY)       20:45    Ha salido              NaN      NaN
 350        Geneva (GVA)       21:15    Ha salido              NaN      NaN
 351        Dublin (DUB)       21:15   Programado              NaN      NaN
 352          Rome (FCO)       21:35    Ha salido              NaN      NaN
 353         Porto (OPO)       22:00    Ha salido              NaN      NaN

     Gate
 286  NaN
 287  NaN
 288  NaN
 289  NaN
 290  NaN
 ..   ...
 349  NaN
 350  NaN
 351  NaN
 352  NaN
 353  NaN

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido              NaN
 355        Rabat (RBA)       06:05             Ha salido              NaN
 356          Fes (FEZ)       06:05             Ha salido              NaN
 357       Geneva (GVA)       06:10             Ha salido              NaN
 358       Malaga (AGP)       06:15             Ha salido              NaN
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido              NaN
 434       Geneva (GVA)       21:15  Retrasado, Ha salido              NaN
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido              NaN
 436         Rome (FCO)       21:35             Ha salido              NaN
 437       Dublin (DUB)       22:05             Ha salido              NaN

     Aircraft Gate
 354      NaN  NaN
 355      NaN  NaN
 356      NaN  NaN
 357      NaN  NaN
 358      NaN  NaN
 ..       ...  ...
 433      NaN  NaN
 434      NaN  NaN
 435      NaN  NaN
 436      NaN  NaN
 437      NaN  NaN

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 438       440.0  20/11/2025 14-38-34         Ryanair     FR8215
 439       441.0  20/11/2025 14-38-34         Ryanair     FR2918
 440       442.0  20/11/2025 14-38-34  easyJet Europe     EC7105
 441       443.0  20/11/2025 14-38-34         Ryanair     FR3976
 442       444.0  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 563       566.0  20/11/2025 14-38-34            BUZZ     RR3035
 564       567.0  20/11/2025 14-38-34            BUZZ     RR4084
 565       568.0  20/11/2025 14-38-34  Wizz Air Malta     W46020
 566       569.0  20/11/2025 14-38-34        Wizz Air     W64116
 567       570.0  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 438    London (STN)       06:00             Ha salido              NaN
 439  Brussels (BRU)       06:05             Ha salido              NaN
 440    Geneva (GVA)       06:10             Ha salido              NaN
 441    Dublin (DUB)       06:15             Ha salido              NaN
 442   Glasgow (GLA)       06:40             Ha salido              NaN
 ..              ...         ...                   ...              ...
 563    Krakow (KRK)       21:30  Retrasado, Ha salido              NaN
 564    Warsaw (WMI)       21:30  Retrasado, Ha salido              NaN
 565      Rome (FCO)       21:35             Ha salido              NaN
 566  Belgrade (BEG)       22:10  Retrasado, Ha salido              NaN
 567    Tirana (TIA)       22:45             Ha salido              NaN

     Aircraft Gate
 438      NaN  NaN
 439      NaN  NaN
 440      NaN  NaN
 441      NaN  NaN
 442      NaN  NaN
 ..       ...  ...
 563      NaN  NaN
 564      NaN  NaN
 565      NaN  NaN
 566      NaN  NaN
 567      NaN  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido              NaN
 569   Bologna (BLQ)       06:10             Ha salido              NaN
 570    London (STN)       06:10             Ha salido              NaN
 571    Venice (VCE)       06:20             Ha salido              NaN
 572     Milan (BGY)       06:25             Ha salido              NaN
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido              NaN
 732    Malaga (AGP)       22:30            Programado              NaN
 733    Tirana (TIA)       22:45            Programado              NaN
 734    Gdansk (GDN)       22:50             Ha salido              NaN
 735    London (STN)       23:10            Programado              NaN

     Aircraft Gate
 568      NaN  NaN
 569      NaN  NaN
 570      NaN  NaN
 571      NaN  NaN
 572      NaN  NaN
 ..       ...  ...
 731      NaN  NaN
 732      NaN  NaN
 733      NaN  NaN
 734      NaN  NaN
 735      NaN  NaN

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight      Name_Destiny  \
 736         NaN   22/Nov/2025           Ryanair      FR846       Milan (BGY)
 737         NaN   22/Nov/2025    easyJet Europe     EC7105      Geneva (GVA)
 738         NaN   22/Nov/2025           Ryanair     FR5718  Bratislava (BTS)
 739         NaN   22/Nov/2025           Ryanair     FR4545       Porto (OPO)
 740         NaN   22/Nov/2025           Ryanair     FR1342               NaN
 ..          ...           ...               ...        ...               ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020        Rome (FCO)
 848         NaN   22/Nov/2025           Ryanair     FR3800  Birmingham (BHX)
 849         NaN   22/Nov/2025           Ryanair     FR8574        Rome (FCO)
 850         NaN   22/Nov/2025          Wizz Air     W64116    Belgrade (BEG)
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642      Tanger (TNG)

     Time_flight                flight_state  flight_capacity Aircraft Gate
 736       06:00  Retrasado, Ha salido 06:15              NaN      NaN  S21
 737       06:10          En hora, Ha salido              NaN      NaN   R9
 738       06:10          En hora, Ha salido              NaN      NaN  S22
 739       06:15          En hora, Ha salido              NaN      NaN  U31
 740       06:20          En hora, Ha salido              NaN      NaN  S24
 ..          ...                         ...              ...      ...  ...
 847       21:35          En hora, Ha salido              NaN      NaN  S22
 848       21:55          En hora, Ha salido              NaN      NaN  Y57
 849       22:10  Retrasado, Ha salido 22:28              NaN      NaN  U34
 850       22:10          En hora, Ha salido              NaN      NaN  Y58
 851       22:15          En hora, Ha salido              NaN      NaN  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46
 ...               ...      ...  ...
 1009              NaN      NaN  W45
 1010              NaN      NaN  W42
 1011              NaN      NaN  R13
 1012              NaN      NaN  U31
 1013              NaN      NaN  W44

 [162 rows x 10 columns],
 '24/Nov/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight     Name_Destiny  \
 1014         NaN   24/Nov/2025         Ryanair     FR3180       Rome (FCO)
 1015         NaN   24/Nov/2025         Ryanair      FR846      Milan (BGY)

In [49]:
df_18 = df_por_fecha['18/11/2025 14-12-47'].copy()
df_18

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
286,288.0,18/11/2025 14-12-47,easyJet Europe,EC7105,Geneva (GVA),06:00,Ha salido,NaN,NaN,NaN
287,289.0,18/11/2025 14-12-47,Ryanair,FR3189,Fes (FEZ),06:15,Ha salido,NaN,NaN,NaN
288,290.0,18/11/2025 14-12-47,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,Ha salido,NaN,NaN,NaN
289,291.0,18/11/2025 14-12-47,Ryanair,FR4545,Porto (OPO),06:35,Ha salido,NaN,NaN,NaN
290,292.0,18/11/2025 14-12-47,easyJet Europe,EC8062,London (LGW),07:30,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
349,351.0,18/11/2025 14-12-47,Transavia,TO4759,Paris (ORY),20:45,Ha salido,NaN,NaN,NaN
350,352.0,18/11/2025 14-12-47,easyJet Europe,EC1380,Geneva (GVA),21:15,Ha salido,NaN,NaN,NaN
351,353.0,18/11/2025 14-12-47,Ryanair,FR6394,Dublin (DUB),21:15,Programado,NaN,NaN,NaN
352,354.0,18/11/2025 14-12-47,Wizz Air Malta,W46020,Rome (FCO),21:35,Ha salido,NaN,NaN,NaN
353,355.0,18/11/2025 14-12-47,Ryanair,FR4585,Porto (OPO),22:00,Ha salido,NaN,NaN,NaN

In [50]:
df_18[(df_18['Aircraft'].isna())]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
286,288.0,18/11/2025 14-12-47,easyJet Europe,EC7105,Geneva (GVA),06:00,Ha salido,NaN,NaN,NaN
287,289.0,18/11/2025 14-12-47,Ryanair,FR3189,Fes (FEZ),06:15,Ha salido,NaN,NaN,NaN
288,290.0,18/11/2025 14-12-47,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,Ha salido,NaN,NaN,NaN
289,291.0,18/11/2025 14-12-47,Ryanair,FR4545,Porto (OPO),06:35,Ha salido,NaN,NaN,NaN
290,292.0,18/11/2025 14-12-47,easyJet Europe,EC8062,London (LGW),07:30,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
349,351.0,18/11/2025 14-12-47,Transavia,TO4759,Paris (ORY),20:45,Ha salido,NaN,NaN,NaN
350,352.0,18/11/2025 14-12-47,easyJet Europe,EC1380,Geneva (GVA),21:15,Ha salido,NaN,NaN,NaN
351,353.0,18/11/2025 14-12-47,Ryanair,FR6394,Dublin (DUB),21:15,Programado,NaN,NaN,NaN
352,354.0,18/11/2025 14-12-47,Wizz Air Malta,W46020,Rome (FCO),21:35,Ha salido,NaN,NaN,NaN
353,355.0,18/11/2025 14-12-47,Ryanair,FR4585,Porto (OPO),22:00,Ha salido,NaN,NaN,NaN

In [51]:
df_18.loc[df_18['Num_flight'] == 'EC7151', 'flight_capacity'] = 156
df_18.loc[df_18['Num_flight'] == 'EC7151', 'Aircraft'] = "Airbus A319"

df_18.loc[df_18['Num_flight'] == 'EC7103', 'flight_capacity'] = 156
df_18.loc[df_18['Num_flight'] == 'EC7103', 'Aircraft'] = "Airbus A319"

df_18.loc[df_18['Num_flight'] == 'EC1956', 'flight_capacity'] = 180
df_18.loc[df_18['Num_flight'] == 'EC1956', 'Aircraft'] = "Airbus A320"

df_18.loc[df_18['Num_flight'] == 'EC1380', 'flight_capacity'] = 180
df_18.loc[df_18['Num_flight'] == 'EC1380', 'Aircraft'] = "Airbus A320"

In [52]:
df_18.loc[df_18['Num_flight'] == 'FR2507', 'flight_capacity'] = 197
df_18.loc[df_18['Num_flight'] == 'FR3193', 'flight_capacity'] = 189

In [53]:
df_18.loc[df_18['Name_company'] == 'easyJet Europe', 'Gate'] = 'R'
df_18.loc[df_18['Name_company'] == 'EasyJet', 'Gate'] = 'M' # Airbus A319
df_18.loc[df_18['Name_company'] == 'Easyjet', 'Gate'] = 'M'
df_18.loc[df_18['Name_company'] == 'EasyJet Europe', 'Gate'] = 'R'
df_18.loc[df_18['Name_company'] == 'easyJet', 'Gate'] = 'M'

In [54]:
if (df_18['fecha_scrapeo'] == "18/11/2025 14-12-47").any():
    
    df_18.loc[df_18['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == '3O642', 'flight_capacity'] = 180
    df_18.loc[df_18['Num_flight'] == '3O642', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'RR4084', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'RR4084', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
    df_18.loc[df_18['Num_flight'] == 'TO4759', 'flight_capacity'] = 186
    df_18.loc[df_18['Num_flight'] == 'TO4759', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR6394', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR6394', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W46020', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'W46020', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR4585', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR4585', 'Gate'] = 'U'

In [55]:
if (df_18['fecha_scrapeo'] == "18/11/2025 14-12-47").any():
    
    df_18.loc[df_18['Num_flight'] == 'W43176', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'W43176', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3076', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR3076', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-800'
    df_18.loc[df_18['Num_flight'] == 'KU136', 'flight_capacity'] = 235
    df_18.loc[df_18['Num_flight'] == 'KU136', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'BZ251', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'BZ251', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR3792', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR3792', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR3792', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR3792', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR846', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR846', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR1165', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR1165', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR575', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR575', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'HV5134', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'HV5134', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3180', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR3180', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'RR6300', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'RR6300', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR777', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR777', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR2834', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR2834', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W61176', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'W61176', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W61478', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'W61478', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR9015', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR9015', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == 'EW9443', 'flight_capacity'] = 180
    df_18.loc[df_18['Num_flight'] == 'EW9443', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321'
    df_18.loc[df_18['Num_flight'] == 'W64406', 'flight_capacity'] = 230
    df_18.loc[df_18['Num_flight'] == 'W64406', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
    df_18.loc[df_18['Num_flight'] == 'U28058', 'flight_capacity'] = 156
    df_18.loc[df_18['Num_flight'] == 'U28058', 'Gate'] = 'M'
    
    df_18.loc[df_18['Num_flight'] == 'HV6790', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'HV6790', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'HV6790', 'Gate'] = 'U'

In [56]:
if (df_18['fecha_scrapeo'] == "18/11/2025 14-12-47").any():
    
    df_18.loc[df_18['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W43176', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'W43176', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'EW9441', 'Aircraft'] = 'Airbus A319'
    df_18.loc[df_18['Num_flight'] == 'EW9441', 'flight_capacity'] = 156
    df_18.loc[df_18['Num_flight'] == 'EW9441', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
    df_18.loc[df_18['Num_flight'] == 'JU581', 'flight_capacity'] = 156
    df_18.loc[df_18['Num_flight'] == 'JU581', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == 'LW12', 'flight_capacity'] = 180
    df_18.loc[df_18['Num_flight'] == 'LW12', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W61476', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'W61476', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR1279', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR1279', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR5270', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR5270', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320neo'
    df_18.loc[df_18['Num_flight'] == 'J246', 'flight_capacity'] = 186
    df_18.loc[df_18['Num_flight'] == 'J246', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == 'EI563', 'flight_capacity'] = 180
    df_18.loc[df_18['Num_flight'] == 'EI563', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR58', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR58', 'Gate'] = 'S'
    
    df_18.loc[df_18['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FI597', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FI597', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3108', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR3108', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'D83657', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'D83657', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR8384', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR8384', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'PC1092', 'flight_capacity'] = 239
    df_18.loc[df_18['Num_flight'] == 'PC1092', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR6267', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'FR6267', 'Gate'] = 'Y'
    
    df_18.loc[df_18['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'DY1741', 'flight_capacity'] = 197
    df_18.loc[df_18['Num_flight'] == 'DY1741', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == '5F5512', 'Aircraft'] = 'Airbus A321'
    df_18.loc[df_18['Num_flight'] == '5F5512', 'flight_capacity'] = 230
    df_18.loc[df_18['Num_flight'] == '5F5512', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'LG3592', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'LG3592', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'LG3592', 'Gate'] = 'U'
    
    df_18.loc[df_18['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR2239', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR2239', 'Gate'] = 'W'

In [57]:
if (df_18['fecha_scrapeo'] == "18/11/2025 14-12-47").any():
    
    df_18.loc[df_18['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'# Airbus A319
    df_18.loc[df_18['Num_flight'] == 'EC7105', 'flight_capacity'] = 156 # FR3189 	
    
    df_18.loc[df_18['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3189', 'flight_capacity'] = 189
    df_18.loc[df_18['Num_flight'] == 'FR3189', 'Gate'] = 'W'
    
    df_18.loc[df_18['Num_flight'] == 'FR2507', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR2507', 'flight_capacity'] = 197
    
    df_18.loc[df_18['Num_flight'] == 'FR4545', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_18.loc[df_18['Num_flight'] == 'FR4545', 'flight_capacity'] = 197
    
    df_18.loc[df_18['Num_flight'] == 'EC8062', 'flight_capacity'] = 156
    df_18.loc[df_18['Num_flight'] == 'EC8062', 'Aircraft'] =  'Airbus A319' # FR3166
    
    df_18.loc[df_18['Num_flight'] == 'FR3166', 'Gate'] = 'S'
    df_18.loc[df_18['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3166', 'flight_capacity'] = 189 # FR5718
    
    df_18.loc[df_18['Num_flight'] == 'FR5718', 'Gate'] = 'U' 
    df_18.loc[df_18['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR5718', 'flight_capacity'] = 189 # FR3193
    
    df_18.loc[df_18['Num_flight'] == 'FR3193', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'FR3193', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR5718', 'flight_capacity'] = 189
    
    df_18.loc[df_18['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == 'EC3737', 'flight_capacity'] = 180
    
    df_18.loc[df_18['Num_flight'] == 'FR133', 'Gate'] = 'S'
    df_18.loc[df_18['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR133', 'flight_capacity'] = 189
    
    df_18.loc[df_18['Num_flight'] == 'W43938', 'Gate'] = 'W'
    df_18.loc[df_18['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == 'W43938', 'flight_capacity'] = 180
    
    df_18.loc[df_18['Num_flight'] == 'W62048', 'Gate'] = 'S'
    df_18.loc[df_18['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W62048', 'flight_capacity'] = 239
    
    df_18.loc[df_18['Num_flight'] == 'FR3035', 'Gate'] = 'R'
    df_18.loc[df_18['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3035', 'flight_capacity'] = 189
    
    df_18.loc[df_18['Num_flight'] == 'FR3807', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737-800'
    df_18.loc[df_18['Num_flight'] == 'FR3807', 'flight_capacity'] = 189
    
    df_18.loc[df_18['Num_flight'] == 'W61914', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W61914', 'flight_capacity'] = 239
    
    df_18.loc[df_18['Num_flight'] == 'W62376', 'Gate'] = 'S'
    df_18.loc[df_18['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W62376', 'flight_capacity'] = 239
    
    df_18.loc[df_18['Num_flight'] == 'TO4751', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'TO4751', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'TO4751', 'flight_capacity'] = 239 #TO4751
    
    df_18.loc[df_18['Num_flight'] == 'W42938', 'Gate'] = 'U'
    df_18.loc[df_18['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
    df_18.loc[df_18['Num_flight'] == 'W42938', 'flight_capacity'] = 239 #3O378
    
    df_18.loc[df_18['Num_flight'] == '3O378', 'Gate'] = 'Y'
    df_18.loc[df_18['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
    df_18.loc[df_18['Num_flight'] == '3O378', 'flight_capacity'] = 180

In [58]:
df_18.isna().sum()

Unnamed: 0         0
fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    0
Aircraft           0
Gate               0
dtype: int64

In [59]:
#df_18.tail(60)

In [60]:
df_18

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
286,288.0,18/11/2025 14-12-47,easyJet Europe,EC7105,Geneva (GVA),06:00,Ha salido,156.0,Airbus A319,R
287,289.0,18/11/2025 14-12-47,Ryanair,FR3189,Fes (FEZ),06:15,Ha salido,189.0,Boeing 737-800,W
288,290.0,18/11/2025 14-12-47,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,Ha salido,197.0,Boeing 737 MAX 8,U
289,291.0,18/11/2025 14-12-47,Ryanair,FR4545,Porto (OPO),06:35,Ha salido,197.0,Boeing 737 MAX 8,U
290,292.0,18/11/2025 14-12-47,easyJet Europe,EC8062,London (LGW),07:30,Ha salido,156.0,Airbus A319,R
...,...,...,...,...,...,...,...,...,...,...
349,351.0,18/11/2025 14-12-47,Transavia,TO4759,Paris (ORY),20:45,Ha salido,186.0,Airbus A320neo,S
350,352.0,18/11/2025 14-12-47,easyJet Europe,EC1380,Geneva (GVA),21:15,Ha salido,180.0,Airbus A320,R
351,353.0,18/11/2025 14-12-47,Ryanair,FR6394,Dublin (DUB),21:15,Programado,197.0,Boeing 737 MAX 8,W
352,354.0,18/11/2025 14-12-47,Wizz Air Malta,W46020,Rome (FCO),21:35,Ha salido,239.0,Airbus A321neo,S
353,355.0,18/11/2025 14-12-47,Ryanair,FR4585,Porto (OPO),22:00,Ha salido,197.0,Boeing 737 MAX 8,U

In [61]:
df_por_fecha['18/11/2025 14-12-47'] = df_18.copy()

In [62]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido              NaN
 355        Rabat (RBA)       06:05             Ha salido              NaN
 356          Fes (FEZ)       06:05             Ha salido              NaN
 357       Geneva (GVA)       06:10             Ha salido              NaN
 358       Malaga (AGP)       06:15             Ha salido              NaN
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido              NaN
 434       Geneva (GVA)       21:15  Retrasado, Ha salido              NaN
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido              NaN
 436         Rome (FCO)       21:35             Ha salido              NaN
 437       Dublin (DUB)       22:05             Ha salido              NaN

     Aircraft Gate
 354      NaN  NaN
 355      NaN  NaN
 356      NaN  NaN
 357      NaN  NaN
 358      NaN  NaN
 ..       ...  ...
 433      NaN  NaN
 434      NaN  NaN
 435      NaN  NaN
 436      NaN  NaN
 437      NaN  NaN

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 438       440.0  20/11/2025 14-38-34         Ryanair     FR8215
 439       441.0  20/11/2025 14-38-34         Ryanair     FR2918
 440       442.0  20/11/2025 14-38-34  easyJet Europe     EC7105
 441       443.0  20/11/2025 14-38-34         Ryanair     FR3976
 442       444.0  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 563       566.0  20/11/2025 14-38-34            BUZZ     RR3035
 564       567.0  20/11/2025 14-38-34            BUZZ     RR4084
 565       568.0  20/11/2025 14-38-34  Wizz Air Malta     W46020
 566       569.0  20/11/2025 14-38-34        Wizz Air     W64116
 567       570.0  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 438    London (STN)       06:00             Ha salido              NaN
 439  Brussels (BRU)       06:05             Ha salido              NaN
 440    Geneva (GVA)       06:10             Ha salido              NaN
 441    Dublin (DUB)       06:15             Ha salido              NaN
 442   Glasgow (GLA)       06:40             Ha salido              NaN
 ..              ...         ...                   ...              ...
 563    Krakow (KRK)       21:30  Retrasado, Ha salido              NaN
 564    Warsaw (WMI)       21:30  Retrasado, Ha salido              NaN
 565      Rome (FCO)       21:35             Ha salido              NaN
 566  Belgrade (BEG)       22:10  Retrasado, Ha salido              NaN
 567    Tirana (TIA)       22:45             Ha salido              NaN

     Aircraft Gate
 438      NaN  NaN
 439      NaN  NaN
 440      NaN  NaN
 441      NaN  NaN
 442      NaN  NaN
 ..       ...  ...
 563      NaN  NaN
 564      NaN  NaN
 565      NaN  NaN
 566      NaN  NaN
 567      NaN  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido              NaN
 569   Bologna (BLQ)       06:10             Ha salido              NaN
 570    London (STN)       06:10             Ha salido              NaN
 571    Venice (VCE)       06:20             Ha salido              NaN
 572     Milan (BGY)       06:25             Ha salido              NaN
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido              NaN
 732    Malaga (AGP)       22:30            Programado              NaN
 733    Tirana (TIA)       22:45            Programado              NaN
 734    Gdansk (GDN)       22:50             Ha salido              NaN
 735    London (STN)       23:10            Programado              NaN

     Aircraft Gate
 568      NaN  NaN
 569      NaN  NaN
 570      NaN  NaN
 571      NaN  NaN
 572      NaN  NaN
 ..       ...  ...
 731      NaN  NaN
 732      NaN  NaN
 733      NaN  NaN
 734      NaN  NaN
 735      NaN  NaN

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight      Name_Destiny  \
 736         NaN   22/Nov/2025           Ryanair      FR846       Milan (BGY)
 737         NaN   22/Nov/2025    easyJet Europe     EC7105      Geneva (GVA)
 738         NaN   22/Nov/2025           Ryanair     FR5718  Bratislava (BTS)
 739         NaN   22/Nov/2025           Ryanair     FR4545       Porto (OPO)
 740         NaN   22/Nov/2025           Ryanair     FR1342               NaN
 ..          ...           ...               ...        ...               ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020        Rome (FCO)
 848         NaN   22/Nov/2025           Ryanair     FR3800  Birmingham (BHX)
 849         NaN   22/Nov/2025           Ryanair     FR8574        Rome (FCO)
 850         NaN   22/Nov/2025          Wizz Air     W64116    Belgrade (BEG)
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642      Tanger (TNG)

     Time_flight                flight_state  flight_capacity Aircraft Gate
 736       06:00  Retrasado, Ha salido 06:15              NaN      NaN  S21
 737       06:10          En hora, Ha salido              NaN      NaN   R9
 738       06:10          En hora, Ha salido              NaN      NaN  S22
 739       06:15          En hora, Ha salido              NaN      NaN  U31
 740       06:20          En hora, Ha salido              NaN      NaN  S24
 ..          ...                         ...              ...      ...  ...
 847       21:35          En hora, Ha salido              NaN      NaN  S22
 848       21:55          En hora, Ha salido              NaN      NaN  Y57
 849       22:10  Retrasado, Ha salido 22:28              NaN      NaN  U34
 850       22:10          En hora, Ha salido              NaN      NaN  Y58
 851       22:15          En hora, Ha salido              NaN      NaN  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46
 ...               ...      ...  ...
 1009              NaN      NaN  W45
 1010              NaN      NaN  W42
 1011              NaN      NaN  R13
 1012              NaN      NaN  U31
 1013              NaN      NaN  W44

 [162 rows x 10 columns],
 '24/Nov/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight     Name_Destiny  \
 1014         NaN   24/Nov/2025         Ryanair     FR3180       Rome (FCO)

In [63]:
df_19 = df_por_fecha['19/11/2025 14-33-06'].copy()
df_19

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
354,356.0,19/11/2025 14-33-06,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,NaN,NaN,NaN
355,357.0,19/11/2025 14-33-06,Ryanair,FR3185,Rabat (RBA),06:05,Ha salido,NaN,NaN,NaN
356,358.0,19/11/2025 14-33-06,Ryanair,FR9406,Fes (FEZ),06:05,Ha salido,NaN,NaN,NaN
357,359.0,19/11/2025 14-33-06,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,NaN,NaN,NaN
358,360.0,19/11/2025 14-33-06,Ryanair,FR483,Malaga (AGP),06:15,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
433,435.0,19/11/2025 14-33-06,Easyjet,U22326,London (LTN),20:55,Ha salido,NaN,NaN,NaN
434,436.0,19/11/2025 14-33-06,easyJet Europe,EC1380,Geneva (GVA),21:15,"Retrasado, Ha salido",NaN,NaN,NaN
435,437.0,19/11/2025 14-33-06,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"Retrasado, Ha salido",NaN,NaN,NaN
436,438.0,19/11/2025 14-33-06,Wizz Air Malta,W46020,Rome (FCO),21:35,Ha salido,NaN,NaN,NaN
437,439.0,19/11/2025 14-33-06,Ryanair,FR6394,Dublin (DUB),22:05,Ha salido,NaN,NaN,NaN

In [64]:
df_19.loc[df_19['Name_company'] == 'easyJet Europe', 'Gate'] = 'R'
df_19.loc[df_19['Name_company'] == 'EasyJet', 'Gate'] = 'M' # Airbus A319
df_19.loc[df_19['Name_company'] == 'Easyjet', 'Gate'] = 'M'
df_19.loc[df_19['Name_company'] == 'EasyJet Europe', 'Gate'] = 'R'
df_19.loc[df_19['Name_company'] == 'easyJet', 'Gate'] = 'M'

In [65]:
df_19.isna().sum()

Unnamed: 0          0
fecha_scrapeo       0
Name_company        0
Num_flight          0
Name_Destiny        0
Time_flight         0
flight_state        0
flight_capacity    84
Aircraft           84
Gate               72
dtype: int64

In [66]:
df_19[(df_19['Gate'].isna())].tail(20)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
414,416.0,19/11/2025 14-33-06,Ryanair,FR8231,London (STN),19:00,Ha salido,NaN,NaN,NaN
415,417.0,19/11/2025 14-33-06,Wizz Air,W61478,Warsaw (WAW),19:00,"Retrasado, Ha salido",NaN,NaN,NaN
416,418.0,19/11/2025 14-33-06,Ryanair,FR1165,Sevilla (SVQ),19:10,Ha salido,NaN,NaN,NaN
417,419.0,19/11/2025 14-33-06,Ryanair,FR9334,Marrakech (RAK),19:10,Ha salido,NaN,NaN,NaN
418,420.0,19/11/2025 14-33-06,Ryanair,FR1342,Palma de Mallorca (PMI),19:15,Ha salido,NaN,NaN,NaN
419,421.0,19/11/2025 14-33-06,Eurowings,EW9443,Dusseldorf (DUS),19:35,"Retrasado, Ha salido",NaN,NaN,NaN
420,422.0,19/11/2025 14-33-06,Ryanair,FR133,Berlin (BER),19:35,Ha salido,NaN,NaN,NaN
421,423.0,19/11/2025 14-33-06,Transavia,HV6064,Rotterdam (RTM),19:40,"Retrasado, Ha salido",NaN,NaN,NaN
423,425.0,19/11/2025 14-33-06,Wizz Air,W61706,Gdansk (GDN),19:50,"Retrasado, Ha salido",NaN,NaN,NaN
424,426.0,19/11/2025 14-33-06,Ryanair,FR3143,Milan (BGY),19:55,Ha salido,NaN,NaN,NaN
425,427.0,19/11/2025 14-33-06,Ryanair,FR58,Napoli (NAP),20:10,Ha salido,NaN,NaN,NaN
426,428.0,19/11/2025 14-33-06,BUZZ,RR5246,Vilnius (VNO),20:10,"Retrasado, Ha salido",NaN,NaN,NaN
428,430.0,19/11/2025 14-33-06,Air Arabia Maroc,3O378,Tanger (TNG),20:20,Ha salido,NaN,NaN,NaN
429,431.0,19/11/2025 14-33-06,T'Way Air,TW408,Seoul/Incheon (ICN),20:30,"Retrasado, Ha salido",NaN,NaN,NaN
430,432.0,19/11/2025 14-33-06,Air Serbia,JU585,Belgrade (BEG),20:35,Ha salido,NaN,NaN,NaN
431,433.0,19/11/2025 14-33-06,Wizz Air,W62378,Budapest (BUD),20:45,"Retrasado, Ha salido",NaN,NaN,NaN
432,434.0,19/11/2025 14-33-06,Transavia,TO4759,Paris (ORY),20:50,"Retrasado, Ha salido",NaN,NaN,NaN
435,437.0,19/11/2025 14-33-06,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"Retrasado, Ha salido",NaN,NaN,NaN
436,438.0,19/11/2025 14-33-06,Wizz Air Malta,W46020,Rome (FCO),21:35,Ha salido,NaN,NaN,NaN
437,439.0,19/11/2025 14-33-06,Ryanair,FR6394,Dublin (DUB),22:05,Ha salido,NaN,NaN,NaN

In [67]:
df_19.loc[df_19['Num_flight'] == 'FR2918', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'FR3185', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3185', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR9406', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'FR483', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR483', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'EC7193', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EC7193', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'FR2239', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'FR3028', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'FR3108', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR3108', 'flight_capacity'] = 197

In [68]:

df_19.loc[df_19['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EC8062', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'EC3737', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'EC7161', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EC7161', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'W43176', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_19.loc[df_19['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_19.loc[df_19['Num_flight'] == 'W62376', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'RR8384', 'Gate'] = 'R'
df_19.loc[df_19['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == '3O376', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'W42940', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W42940', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'EW9441', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'EW9441', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EW9441', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'FR2834', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR2834', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'FR4545', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'RR3049', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'RR3049', 'flight_capacity'] = 197

In [69]:
df_19.loc[df_19['Num_flight'] == '3O642', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == '3O642', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'HV5132', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'HV5132', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'FR3078', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'W61476', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321'
df_19.loc[df_19['Num_flight'] == 'W61476', 'flight_capacity'] = 230

df_19.loc[df_19['Num_flight'] == 'FR3039', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3039', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'BT878', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'BT878', 'Aircraft'] = 'Airbus A220-300'
df_19.loc[df_19['Num_flight'] == 'BT878', 'flight_capacity'] = 148

df_19.loc[df_19['Num_flight'] == 'FR6267', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR6267', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'U5406', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'U5406', 'Aircraft'] = 'Boeing 737-700'
df_19.loc[df_19['Num_flight'] == 'U5406', 'flight_capacity'] = 149

df_19.loc[df_19['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320neo'
df_19.loc[df_19['Num_flight'] == 'U22704', 'flight_capacity'] = 186

df_19.loc[df_19['Num_flight'] == 'FR2507', 'Gate'] = 'R'
df_19.loc[df_19['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR2507', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'EI563', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'EI563', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'FR575', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR575', 'flight_capacity'] = 189

In [70]:
df_19.loc[df_19['Num_flight'] == 'FR9925', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR9925', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR9925', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'PC1092', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'PC1092', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'FR6597', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR6597', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'FR3792', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'H4264', 'Gate'] = 'R'
df_19.loc[df_19['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'H4264', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'DY1741', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'EW521', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A321'
df_19.loc[df_19['Num_flight'] == 'EW521', 'flight_capacity'] = 230

df_19.loc[df_19['Num_flight'] == 'LG3592', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'
df_19.loc[df_19['Num_flight'] == 'LG3592', 'flight_capacity'] = 76

df_19.loc[df_19['Num_flight'] == 'TK608', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'TK608', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'BZ251', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'BZ251', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'BZ251', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'D83659', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'D83659', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'EW2521', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EW2521', 'flight_capacity'] = 156

In [71]:
df_19.loc[df_19['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR777', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'FR12', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR12', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'PC1094', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321'
df_19.loc[df_19['Num_flight'] == 'PC1094', 'flight_capacity'] = 230

df_19.loc[df_19['Num_flight'] == 'V71415', 'Gate'] = 'R'
df_19.loc[df_19['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'FR3035', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR3035', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_19.loc[df_19['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_19.loc[df_19['Num_flight'] == 'FR3928', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'FR5718', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'W67920', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W67920', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'FR4585', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'E9803', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'E9803', 'Aircraft'] = 'Airbus A350-900'
df_19.loc[df_19['Num_flight'] == 'E9803', 'flight_capacity'] = 432

df_19.loc[df_19['Num_flight'] == 'FR3180', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'FR8231', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'W61478', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'FR1165', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR1165', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'FR9334', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'FR9334', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR9334', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

In [72]:
df_19.loc[df_19['Num_flight'] == 'FR1342', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'EW9443', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'EW9443', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'FR133', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR133', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'HV6064', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'HV6064', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'HV6064', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'U28058', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'W61706', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W61706', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'FR3143', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR3143', 'flight_capacity'] = 189

df_19.loc[df_19['Num_flight'] == 'FR58', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'FR58', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'RR5246', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'RR5246', 'Aircraft'] = 'Boeing 737 MAX 8'
df_19.loc[df_19['Num_flight'] == 'RR5246', 'flight_capacity'] = 197

df_19.loc[df_19['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == '3O378', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == '3O378', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'TW408', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'TW408', 'Aircraft'] = 'BOEING 777-300ER'
df_19.loc[df_19['Num_flight'] == 'TW408', 'flight_capacity'] = 294

df_19.loc[df_19['Num_flight'] == 'JU585', 'Gate'] = 'Y'
df_19.loc[df_19['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'JU585', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'TO4759', 'Gate'] = 'S'
df_19.loc[df_19['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_19.loc[df_19['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_19.loc[df_19['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A319'
df_19.loc[df_19['Num_flight'] == 'U22326', 'flight_capacity'] = 156

df_19.loc[df_19['Num_flight'] == 'W43406', 'Gate'] = 'U'
df_19.loc[df_19['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_19.loc[df_19['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_19.loc[df_19['Num_flight'] == 'W46020', 'Gate'] = 'R'
df_19.loc[df_19['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_19.loc[df_19['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_19.loc[df_19['Num_flight'] == 'FR6394', 'Gate'] = 'W'
df_19.loc[df_19['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737-800'
df_19.loc[df_19['Num_flight'] == 'FR6394', 'flight_capacity'] = 189

In [73]:
df_19['Aircraft'].unique()

array(['Boeing 737-800', 'Airbus A319', 'Boeing 737 MAX 8', 'Airbus A320',
       'Airbus A321', 'Airbus A321neo', 'Airbus A220-300',
       'Boeing 737-700', 'Airbus A320neo', 'de Havilland Dash 8-400',
       'Airbus A350-900', 'BOEING 777-300ER'], dtype=object)

In [74]:
df_19['Gate'].unique()

array(['U', 'Y', nan, 'R', 'S', 'W', 'M'], dtype=object)

In [75]:
df_19['flight_capacity'].unique()

array([189., 156., 197., 180., 230., 239., 148., 149., 186.,  76., 432.,
       294.])

In [76]:
df_19[(df_19['Gate'] == 'U')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
354,356.0,19/11/2025 14-33-06,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,189.0,Boeing 737-800,U
358,360.0,19/11/2025 14-33-06,Ryanair,FR483,Malaga (AGP),06:15,Ha salido,189.0,Boeing 737-800,U
361,363.0,19/11/2025 14-33-06,Ryanair,FR3028,Ibiza (IBZ),06:45,Ha salido,189.0,Boeing 737-800,U
362,364.0,19/11/2025 14-33-06,Ryanair,FR3108,Luxembourg (LUX),06:50,Ha salido,197.0,Boeing 737 MAX 8,U
366,368.0,19/11/2025 14-33-06,Wizz Air Malta,W43176,Bucharest (OTP),09:25,Ha salido,230.0,Airbus A321,U
367,369.0,19/11/2025 14-33-06,Wizz Air,W62376,Budapest (BUD),09:25,Ha salido,239.0,Airbus A321neo,U
372,374.0,19/11/2025 14-33-06,Ryanair,FR2834,Charleroi (CRL),09:45,Ha salido,197.0,Boeing 737 MAX 8,U
373,375.0,19/11/2025 14-33-06,Ryanair,FR4545,Porto (OPO),09:45,Ha salido,197.0,Boeing 737 MAX 8,U
374,376.0,19/11/2025 14-33-06,BUZZ,RR3049,Krakow (KRK),09:55,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8,U
376,378.0,19/11/2025 14-33-06,Transavia,HV5132,Amsterdam (AMS),10:05,Ha salido,239.0,Airbus A321neo,U
380,382.0,19/11/2025 14-33-06,Air Baltic,BT878,Tallinn (TLL),10:35,"Retrasado, Ha salido",148.0,Airbus A220-300,U
386,388.0,19/11/2025 14-33-06,Ryanair,FR575,Bologna (BLQ),11:40,Ha salido,189.0,Boeing 737-800,U
387,389.0,19/11/2025 14-33-06,Ryanair,FR9925,Frankfurt-Hahn (HHN),12:35,Ha salido,189.0,Boeing 737-800,U
392,394.0,19/11/2025 14-33-06,Norwegian Air Shuttle,DY1741,Oslo (OSL),13:25,"Retrasado, Ha salido",189.0,Boeing 737-800,U
393,395.0,19/11/2025 14-33-06,Eurowings,EW521,Cologne-Bonn (CGN),13:25,"Retrasado, Ha salido",230.0,Airbus A321,U
394,396.0,19/11/2025 14-33-06,Luxair,LG3592,Luxembourg (LUX),13:40,"Retrasado, Ha salido",76.0,de Havilland Dash 8-400,U
400,402.0,19/11/2025 14-33-06,Ryanair,FR12,Vienna (VIE),15:15,Ha salido,197.0,Boeing 737 MAX 8,U
403,405.0,19/11/2025 14-33-06,Ryanair,FR3035,Krakow (KRK),16:15,Ha salido,197.0,Boeing 737 MAX 8,U
405,407.0,19/11/2025 14-33-06,Ryanair,FR3928,Trieste (TRS),16:50,Ha salido,189.0,Boeing 737-800,U
406,408.0,19/11/2025 14-33-06,Ryanair,FR5718,Bratislava (BTS),16:50,Ha salido,189.0,Boeing 737-800,U
408,410.0,19/11/2025 14-33-06,Ryanair,FR4585,Porto (OPO),17:30,Ha salido,189.0,Boeing 737-800,U
418,420.0,19/11/2025 14-33-06,Ryanair,FR1342,Palma de Mallorca (PMI),19:15,Ha salido,189.0,Boeing 737-800,U
420,422.0,19/11/2025 14-33-06,Ryanair,FR133,Berlin (BER),19:35,Ha salido,197.0,Boeing 737 MAX 8,U
421,423.0,19/11/2025 14-33-06,Transavia,HV6064,Rotterdam (RTM),19:40,"Retrasado, Ha salido",189.0,Boeing 737-800,U
423,425.0,19/11/2025 14-33-06,Wizz Air,W61706,Gdansk (GDN),19:50,"Retrasado, Ha salido",239.0,Airbus A321neo,U
424,426.0,19/11/2025 14-33-06,Ryanair,FR3143,Milan (BGY),19:55,Ha salido,189.0,Boeing 737-800,U
425,427.0,19/11/2025 14-33-06,Ryanair,FR58,Napoli (NAP),20:10,Ha salido,197.0,Boeing 737 MAX 8,U
426,428.0,19/11/2025 14-33-06,BUZZ,RR5246,Vilnius (VNO),20:10,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8,U
435,437.0,19/11/2025 14-33-06,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"Retrasado, Ha salido",180.0,Airbus A320,U

In [77]:
df_19[(df_19['Aircraft'] == 'BOEING 777-300ER')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
429,431.0,19/11/2025 14-33-06,T'Way Air,TW408,Seoul/Incheon (ICN),20:30,"Retrasado, Ha salido",294.0,BOEING 777-300ER,Y

In [78]:
df_por_fecha['19/11/2025 14-33-06'] = df_19.copy()

In [79]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 438       440.0  20/11/2025 14-38-34         Ryanair     FR8215
 439       441.0  20/11/2025 14-38-34         Ryanair     FR2918
 440       442.0  20/11/2025 14-38-34  easyJet Europe     EC7105
 441       443.0  20/11/2025 14-38-34         Ryanair     FR3976
 442       444.0  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 563       566.0  20/11/2025 14-38-34            BUZZ     RR3035
 564       567.0  20/11/2025 14-38-34            BUZZ     RR4084
 565       568.0  20/11/2025 14-38-34  Wizz Air Malta     W46020
 566       569.0  20/11/2025 14-38-34        Wizz Air     W64116
 567       570.0  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 438    London (STN)       06:00             Ha salido              NaN
 439  Brussels (BRU)       06:05             Ha salido              NaN
 440    Geneva (GVA)       06:10             Ha salido              NaN
 441    Dublin (DUB)       06:15             Ha salido              NaN
 442   Glasgow (GLA)       06:40             Ha salido              NaN
 ..              ...         ...                   ...              ...
 563    Krakow (KRK)       21:30  Retrasado, Ha salido              NaN
 564    Warsaw (WMI)       21:30  Retrasado, Ha salido              NaN
 565      Rome (FCO)       21:35             Ha salido              NaN
 566  Belgrade (BEG)       22:10  Retrasado, Ha salido              NaN
 567    Tirana (TIA)       22:45             Ha salido              NaN

     Aircraft Gate
 438      NaN  NaN
 439      NaN  NaN
 440      NaN  NaN
 441      NaN  NaN
 442      NaN  NaN
 ..       ...  ...
 563      NaN  NaN
 564      NaN  NaN
 565      NaN  NaN
 566      NaN  NaN
 567      NaN  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido              NaN
 569   Bologna (BLQ)       06:10             Ha salido              NaN
 570    London (STN)       06:10             Ha salido              NaN
 571    Venice (VCE)       06:20             Ha salido              NaN
 572     Milan (BGY)       06:25             Ha salido              NaN
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido              NaN
 732    Malaga (AGP)       22:30            Programado              NaN
 733    Tirana (TIA)       22:45            Programado              NaN
 734    Gdansk (GDN)       22:50             Ha salido              NaN
 735    London (STN)       23:10            Programado              NaN

     Aircraft Gate
 568      NaN  NaN
 569      NaN  NaN
 570      NaN  NaN
 571      NaN  NaN
 572      NaN  NaN
 ..       ...  ...
 731      NaN  NaN
 732      NaN  NaN
 733      NaN  NaN
 734      NaN  NaN
 735      NaN  NaN

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight      Name_Destiny  \
 736         NaN   22/Nov/2025           Ryanair      FR846       Milan (BGY)
 737         NaN   22/Nov/2025    easyJet Europe     EC7105      Geneva (GVA)
 738         NaN   22/Nov/2025           Ryanair     FR5718  Bratislava (BTS)
 739         NaN   22/Nov/2025           Ryanair     FR4545       Porto (OPO)
 740         NaN   22/Nov/2025           Ryanair     FR1342               NaN
 ..          ...           ...               ...        ...               ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020        Rome (FCO)
 848         NaN   22/Nov/2025           Ryanair     FR3800  Birmingham (BHX)
 849         NaN   22/Nov/2025           Ryanair     FR8574        Rome (FCO)
 850         NaN   22/Nov/2025          Wizz Air     W64116    Belgrade (BEG)
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642      Tanger (TNG)

     Time_flight                flight_state  flight_capacity Aircraft Gate
 736       06:00  Retrasado, Ha salido 06:15              NaN      NaN  S21
 737       06:10          En hora, Ha salido              NaN      NaN   R9
 738       06:10          En hora, Ha salido              NaN      NaN  S22
 739       06:15          En hora, Ha salido              NaN      NaN  U31
 740       06:20          En hora, Ha salido              NaN      NaN  S24
 ..          ...                         ...              ...      ...  ...
 847       21:35          En hora, Ha salido              NaN      NaN  S22
 848       21:55          En hora, Ha salido              NaN      NaN  Y57
 849       22:10  Retrasado, Ha salido 22:28              NaN      NaN  U34
 850       22:10          En hora, Ha salido              NaN      NaN  Y58
 851       22:15          En hora, Ha salido              NaN      NaN  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46
 ...               ...      ...  ...
 1009              NaN      NaN  W45
 1010              NaN      NaN  W42
 1011              NaN      NaN  R13
 1012              NaN      NaN  U31
 1013              NaN      NaN  W44

 [162 rows x 10 columns],
 '24/Nov/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight     Name_Destiny  \

In [80]:
df_20 = df_por_fecha['20/11/2025 14-38-34'].copy()
df_20

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
438,440.0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido,NaN,NaN,NaN
439,441.0,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,NaN,NaN,NaN
440,442.0,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,NaN,NaN,NaN
441,443.0,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido,NaN,NaN,NaN
442,444.0,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
563,566.0,20/11/2025 14-38-34,BUZZ,RR3035,Krakow (KRK),21:30,"Retrasado, Ha salido",NaN,NaN,NaN
564,567.0,20/11/2025 14-38-34,BUZZ,RR4084,Warsaw (WMI),21:30,"Retrasado, Ha salido",NaN,NaN,NaN
565,568.0,20/11/2025 14-38-34,Wizz Air Malta,W46020,Rome (FCO),21:35,Ha salido,NaN,NaN,NaN
566,569.0,20/11/2025 14-38-34,Wizz Air,W64116,Belgrade (BEG),22:10,"Retrasado, Ha salido",NaN,NaN,NaN
567,570.0,20/11/2025 14-38-34,Wizz Air Malta,W45154,Tirana (TIA),22:45,Ha salido,NaN,NaN,NaN

In [81]:
df20 = pd.read_csv("vuelos_limpio20.csv") 
df20.head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,flight_Aircraft,Gate
0,0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido,189.0,Boeing 737-800,Y
1,1,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,189.0,Boeing 737-800,U
2,2,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,156.0,Airbus A319,R
3,3,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido,197.0,Boeing 737 MAX 8,W
4,4,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido,156.0,Airbus A319,R
5,5,20/11/2025 14-38-34,Ryanair,FR3049,Krakow (KRK),06:40,Ha salido,197.0,Boeing 737 MAX 8,S
6,6,20/11/2025 14-38-34,Ryanair,FR3028,Ibiza (IBZ),06:45,Ha salido,189.0,Boeing 737-800,S
7,7,20/11/2025 14-38-34,Lauda Europe,LW2495,Palma de Mallorca (PMI),07:20,Ha salido,180.0,Airbus A320,R
8,8,20/11/2025 14-38-34,Ryanair,FR133,Berlin (BER),07:25,Ha salido,189.0,Boeing 737-800,U
9,9,20/11/2025 14-38-34,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:30,Ha salido,156.0,Airbus A319,R

In [82]:
df20.loc[df20['Num_flight'] == 'W43406', 'flight_capacity'] = 186

In [83]:
df20.loc[df20['Num_flight'] == 'W62376', 'flight_capacity'] = 239

In [84]:
df20.loc[df20['Num_flight'] == 'V73735', 'flight_capacity'] = 156
df20.loc[df20['Num_flight'] == 'V73573', 'flight_capacity'] = 156
df20.loc[df20['Num_flight'] == 'V72165', 'flight_capacity'] = 156

In [85]:
df_20 = df20

In [86]:
df_20

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,flight_Aircraft,Gate
0,0,20/11/2025 14-38-34,Ryanair,FR8215,London (STN),06:00,Ha salido,189.0,Boeing 737-800,Y
1,1,20/11/2025 14-38-34,Ryanair,FR2918,Brussels (BRU),06:05,Ha salido,189.0,Boeing 737-800,U
2,2,20/11/2025 14-38-34,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,156.0,Airbus A319,R
3,3,20/11/2025 14-38-34,Ryanair,FR3976,Dublin (DUB),06:15,Ha salido,197.0,Boeing 737 MAX 8,W
4,4,20/11/2025 14-38-34,easyJet Europe,EC7191,Glasgow (GLA),06:40,Ha salido,156.0,Airbus A319,R
...,...,...,...,...,...,...,...,...,...,...
125,126,20/11/2025 14-38-34,BUZZ,RR3035,Krakow (KRK),21:30,Programado,197.0,Boeing 737 MAX 8,R
126,127,20/11/2025 14-38-34,BUZZ,RR4084,Warsaw (WMI),21:30,Programado,189.0,Boeing 737-800,S
127,128,20/11/2025 14-38-34,Wizz Air Malta,W46020,Rome (FCO),21:35,Programado,230.0,Airbus A321,U
128,129,20/11/2025 14-38-34,Wizz Air,W64116,Belgrade (BEG),22:10,Programado,230.0,Airbus A321,W
129,130,20/11/2025 14-38-34,Wizz Air Malta,W45154,Tirana (TIA),22:45,Programado,239.0,Airbus A321neo,NaN

In [87]:
df_20 = df_20.rename(columns={'flight_Aircraft': 'Aircraft'})

In [88]:
df_por_fecha['20/11/2025 14-38-34'] = df_20.copy()

In [89]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido              NaN
 569   Bologna (BLQ)       06:10             Ha salido              NaN
 570    London (STN)       06:10             Ha salido              NaN
 571    Venice (VCE)       06:20             Ha salido              NaN
 572     Milan (BGY)       06:25             Ha salido              NaN
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido              NaN
 732    Malaga (AGP)       22:30            Programado              NaN
 733    Tirana (TIA)       22:45            Programado              NaN
 734    Gdansk (GDN)       22:50             Ha salido              NaN
 735    London (STN)       23:10            Programado              NaN

     Aircraft Gate
 568      NaN  NaN
 569      NaN  NaN
 570      NaN  NaN
 571      NaN  NaN
 572      NaN  NaN
 ..       ...  ...
 731      NaN  NaN
 732      NaN  NaN
 733      NaN  NaN
 734      NaN  NaN
 735      NaN  NaN

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight      Name_Destiny  \
 736         NaN   22/Nov/2025           Ryanair      FR846       Milan (BGY)
 737         NaN   22/Nov/2025    easyJet Europe     EC7105      Geneva (GVA)
 738         NaN   22/Nov/2025           Ryanair     FR5718  Bratislava (BTS)
 739         NaN   22/Nov/2025           Ryanair     FR4545       Porto (OPO)
 740         NaN   22/Nov/2025           Ryanair     FR1342               NaN
 ..          ...           ...               ...        ...               ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020        Rome (FCO)
 848         NaN   22/Nov/2025           Ryanair     FR3800  Birmingham (BHX)
 849         NaN   22/Nov/2025           Ryanair     FR8574        Rome (FCO)
 850         NaN   22/Nov/2025          Wizz Air     W64116    Belgrade (BEG)
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642      Tanger (TNG)

     Time_flight                flight_state  flight_capacity Aircraft Gate
 736       06:00  Retrasado, Ha salido 06:15              NaN      NaN  S21
 737       06:10          En hora, Ha salido              NaN      NaN   R9
 738       06:10          En hora, Ha salido              NaN      NaN  S22
 739       06:15          En hora, Ha salido              NaN      NaN  U31
 740       06:20          En hora, Ha salido              NaN      NaN  S24
 ..          ...                         ...              ...      ...  ...
 847       21:35          En hora, Ha salido              NaN      NaN  S22
 848       21:55          En hora, Ha salido              NaN      NaN  Y57
 849       22:10  Retrasado, Ha salido 22:28              NaN      NaN  U34
 850       22:10          En hora, Ha salido              NaN      NaN  Y58
 851       22:15          En hora, Ha salido              NaN      NaN  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46
 ...               ...      ...  ...
 1009              NaN      NaN  W45
 1010              NaN      NaN  W42
 1011              NaN      NaN  R13
 1012              NaN      NaN  U31
 1013              NaN      NaN  W44

 [162 rows x 10 columns],
 '24/Nov/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight     Name_Destiny  \

In [90]:
df_21 = df_por_fecha['21/11/2025 14-58-40'].copy()
df_21

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
568,571.0,21/11/2025 14-58-40,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,NaN,NaN,NaN
569,572.0,21/11/2025 14-58-40,Ryanair,FR8183,Bologna (BLQ),06:10,Ha salido,NaN,NaN,NaN
570,573.0,21/11/2025 14-58-40,Ryanair,FR8231,London (STN),06:10,Ha salido,NaN,NaN,NaN
571,574.0,21/11/2025 14-58-40,Ryanair,FR777,Venice (VCE),06:20,Ha salido,NaN,NaN,NaN
572,575.0,21/11/2025 14-58-40,Ryanair,FR846,Milan (BGY),06:25,Ha salido,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
731,736.0,21/11/2025 14-58-40,Wizz Air,W64116,Belgrade (BEG),21:55,"Retrasado, Ha salido",NaN,NaN,NaN
732,737.0,21/11/2025 14-58-40,Ryanair,FR3080,Malaga (AGP),22:30,Programado,NaN,NaN,NaN
733,738.0,21/11/2025 14-58-40,Wizz Air Malta,W45154,Tirana (TIA),22:45,Programado,NaN,NaN,NaN
734,739.0,21/11/2025 14-58-40,Wizz Air,W61706,Gdansk (GDN),22:50,Ha salido,NaN,NaN,NaN
735,740.0,21/11/2025 14-58-40,Ryanair,FR9814,London (STN),23:10,Programado,NaN,NaN,NaN

In [91]:
df_21.loc[df_21['Name_company'] == 'easyJet Europe', 'Gate'] = 'R'
df_21.loc[df_21['Name_company'] == 'EasyJet', 'Gate'] = 'M' # Airbus A319
df_21.loc[df_21['Name_company'] == 'Easyjet', 'Gate'] = 'M'
df_21.loc[df_21['Name_company'] == 'EasyJet Europe', 'Gate'] = 'R'
df_21.loc[df_21['Name_company'] == 'easyJet', 'Gate'] = 'M'

In [92]:
df_21[(df_21['Aircraft'].isna())].shape

(168, 10)

In [93]:
df_21[(df_21['Aircraft'].isna())].head(40)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
568,571.0,21/11/2025 14-58-40,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,NaN,NaN,R
569,572.0,21/11/2025 14-58-40,Ryanair,FR8183,Bologna (BLQ),06:10,Ha salido,NaN,NaN,NaN
570,573.0,21/11/2025 14-58-40,Ryanair,FR8231,London (STN),06:10,Ha salido,NaN,NaN,NaN
571,574.0,21/11/2025 14-58-40,Ryanair,FR777,Venice (VCE),06:20,Ha salido,NaN,NaN,NaN
572,575.0,21/11/2025 14-58-40,Ryanair,FR846,Milan (BGY),06:25,Ha salido,NaN,NaN,NaN
573,576.0,21/11/2025 14-58-40,Ryanair,FR133,Berlin (BER),06:35,Ha salido,NaN,NaN,NaN
574,577.0,21/11/2025 14-58-40,Ryanair,FR4545,Porto (OPO),06:45,Ha salido,NaN,NaN,NaN
575,578.0,21/11/2025 14-58-40,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,Ha salido,NaN,NaN,R
576,579.0,21/11/2025 14-58-40,easyJet Europe,EC7199,Edinburgh (EDI),07:20,Ha salido,NaN,NaN,R
577,580.0,21/11/2025 14-58-40,Lauda Europe,LW2889,Palma de Mallorca (PMI),07:40,Ha salido,NaN,NaN,NaN
578,581.0,21/11/2025 14-58-40,Norwegian Air Sweden AOC,D85502,Stockholm (ARN),08:00,Ha salido,NaN,NaN,NaN
579,582.0,21/11/2025 14-58-40,Ryanair,FR3976,Dublin (DUB),08:00,Ha salido,NaN,NaN,NaN
580,583.0,21/11/2025 14-58-40,Ryanair,FR3185,Rabat (RBA),08:10,Ha salido,NaN,NaN,NaN
581,584.0,21/11/2025 14-58-40,Ryanair,FR6973,Rome (FCO),08:15,Ha salido,NaN,NaN,NaN
582,585.0,21/11/2025 14-58-40,easyJet Europe,EC1376,Geneva (GVA),08:40,"Retrasado, Ha salido",NaN,NaN,R
583,586.0,21/11/2025 14-58-40,Ryanair,FR5752,Valletta (MLA),08:40,Ha salido,NaN,NaN,NaN
584,587.0,21/11/2025 14-58-40,Ryanair,FR1165,Sevilla (SVQ),09:00,Ha salido,NaN,NaN,NaN
585,588.0,21/11/2025 14-58-40,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido",NaN,NaN,NaN
586,589.0,21/11/2025 14-58-40,easyJet Europe,EC3737,Milan (MXP),09:10,Ha salido,NaN,NaN,R
587,590.0,21/11/2025 14-58-40,Ryanair,FR2834,Charleroi (CRL),09:15,Ha salido,NaN,NaN,NaN
588,591.0,21/11/2025 14-58-40,Air Arabia Maroc,3O374,Casablanca (CMN),09:25,Ha salido,NaN,NaN,NaN
589,592.0,21/11/2025 14-58-40,Lauda Europe,LW12,Vienna (VIE),09:25,"Retrasado, Ha salido",NaN,NaN,NaN
590,593.0,21/11/2025 14-58-40,Wizz Air Malta,W43176,Bucharest (OTP),09:25,Ha salido,NaN,NaN,NaN
591,594.0,21/11/2025 14-58-40,Wizz Air Malta,W45088,Tirana (TIA),09:25,"Retrasado, Ha salido",NaN,NaN,NaN
592,595.0,21/11/2025 14-58-40,Wizz Air,W62376,Budapest (BUD),09:25,Ha salido,NaN,NaN,NaN
593,596.0,21/11/2025 14-58-40,Ryanair,FR3028,Ibiza (IBZ),09:40,Ha salido,NaN,NaN,NaN
594,598.0,21/11/2025 14-58-40,Ryanair,FR3320,Milan (BGY),09:45,Ha salido,NaN,NaN,NaN
595,599.0,21/11/2025 14-58-40,Transavia,HV6788,Eindhoven (EIN),09:45,Ha salido,NaN,NaN,NaN
596,600.0,21/11/2025 14-58-40,Easyjet,U26654,Birmingham (BHX),09:45,Ha salido,NaN,NaN,M
597,601.0,21/11/2025 14-58-40,Air Arabia Maroc,3O378,Tanger (TNG),09:50,"Retrasado, Ha salido",NaN,NaN,NaN
598,602.0,21/11/2025 14-58-40,easyJet Europe,EC7656,Lisbon (LIS),09:55,"Retrasado, Ha salido",NaN,NaN,R
599,603.0,21/11/2025 14-58-40,Air Serbia,JU581,Belgrade (BEG),09:55,"Retrasado, Ha salido",NaN,NaN,NaN
600,604.0,21/11/2025 14-58-40,Ryanair,FR9015,London (STN),10:00,Ha salido,NaN,NaN,NaN
601,605.0,21/11/2025 14-58-40,Wizz Air Malta,W46018,Rome (FCO),10:00,Ha salido,NaN,NaN,NaN
602,606.0,21/11/2025 14-58-40,Ryanair,FR6920,Dublin (DUB),10:05,Ha salido,NaN,NaN,NaN
603,607.0,21/11/2025 14-58-40,Transavia,HV5132,Amsterdam (AMS),10:05,"Retrasado, Ha salido",NaN,NaN,NaN
604,608.0,21/11/2025 14-58-40,Eurowings,EW7521,Hamburg (HAM),10:10,"Retrasado, Ha salido",NaN,NaN,NaN
605,609.0,21/11/2025 14-58-40,Wizz Air,W61476,Warsaw (WAW),10:15,"Retrasado, Ha salido",NaN,NaN,NaN
606,610.0,21/11/2025 14-58-40,Ryanair,FR2239,Marrakech (RAK),10:20,"Retrasado, Ha salido",NaN,NaN,NaN
607,611.0,21/11/2025 14-58-40,Easyjet,U22002,Manchester (MAN),10:25,Ha salido,NaN,NaN,M

In [94]:
df_21.loc[df_21['Num_flight'] == 'FR1342', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR5718', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'V73735', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'V73735', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'W46728', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W46728', 'flight_capacity'] = 239

In [95]:
df_21.loc[df_21['Num_flight'] == 'FR878', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR878', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR483', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR483', 'flight_capacity'] = 197

#df_21.loc[df_21['Num_flight'] == 'V73735', 'Gate'] = 'U'
#df_21.loc[df_21['Num_flight'] == 'V73735', 'Aircraft'] = 'Boeing 737 MAX 8'
#df_21.loc[df_21['Num_flight'] == 'V73735', 'flight_capacity'] = 197

In [96]:
df_21.loc[df_21['Num_flight'] == 'FR774', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR774', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'TO4755', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_21.loc[df_21['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_21.loc[df_21['Num_flight'] == 'FR8215', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR8215', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR8215', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'V71443', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'V71443', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'V71443', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'W64406', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'FR2507', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR867', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR867', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'QS1059', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'QS1059', 'flight_capacity'] = 189

In [97]:
df_21.loc[df_21['Num_flight'] == 'RR3049', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'RR3049', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'FI597', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FI597', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'LS232', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'LS232', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'LS232', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'EC8064', 'Gate'] = 'M'
df_21.loc[df_21['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'FR4585', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'D83657', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'D83657', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'FR575', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR58', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'PC1092', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_21.loc[df_21['Num_flight'] == 'PC1092', 'flight_capacity'] = 230

df_21.loc[df_21['Num_flight'] == 'FR6874', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR6874', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'W67022', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'W46330', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321'
df_21.loc[df_21['Num_flight'] == 'W46330', 'flight_capacity'] = 230

df_21.loc[df_21['Num_flight'] == 'DY1741', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'PC1528', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'PC1528', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'TK608', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'TK608', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR6078', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'FR6078', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR6078', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'LS804', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR3180', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'BT684', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_21.loc[df_21['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_21.loc[df_21['Num_flight'] == 'S4507', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'S4507', 'Aircraft'] = 'Airbus A320neo'
df_21.loc[df_21['Num_flight'] == 'S4507', 'flight_capacity'] = 186

df_21.loc[df_21['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'LW7351', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

In [98]:
df_21.loc[df_21['Num_flight'] == 'FR6920', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR6920', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'HV5132', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'HV5132', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'EW7521', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'EW7521', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'W61476', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'FR2239', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320neo'
df_21.loc[df_21['Num_flight'] == 'U22002', 'flight_capacity'] = 186

df_21.loc[df_21['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'FR6267', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'HV6064', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'HV6064', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'HV6064', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'U22704', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'FR5270', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR5270', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'RR8384', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR3166', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR269', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == '3F232', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == '3F232', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == '3F232', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'EI563', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'EI563', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'FR3121', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR3121', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'LW2896', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'LW2896', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'LW2896', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'EC7141', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7141', 'flight_capacity'] = 156

In [99]:
df_21.loc[df_21['Num_flight'] == 'FR5752', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'FR1165', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR1165', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'W62048', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'EC3737', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == '3O374', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == '3O374', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == '3O374', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'LW12', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'W43176', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_21.loc[df_21['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_21.loc[df_21['Num_flight'] == 'W45088', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321'
df_21.loc[df_21['Num_flight'] == 'W45088', 'flight_capacity'] = 230

df_21.loc[df_21['Num_flight'] == 'W62376', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'FR3028', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR3320', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'HV6788', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'U26654', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'U26654', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == '3O378', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == '3O378', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_21.loc[df_21['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_21.loc[df_21['Num_flight'] == 'JU581', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'JU581', 'flight_capacity'] = 157

df_21.loc[df_21['Num_flight'] == 'FR9015', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR9015', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'W46018', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_21.loc[df_21['Num_flight'] == 'W45088', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321'
df_21.loc[df_21['Num_flight'] == 'W45088', 'flight_capacity'] = 230

df_21.loc[df_21['Num_flight'] == 'W62376', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_21.loc[df_21['Num_flight'] == 'W62376', 'flight_capacity'] = 239

In [100]:
df_21.loc[df_21['Num_flight'] == 'EC7105', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'FR8183', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'FR8183', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR8183', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR8231', 'Gate'] = 'Y'
df_21.loc[df_21['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR777', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR846', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR133', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR4545', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'EC7199', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC7199', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'FR4545', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_21.loc[df_21['Num_flight'] == 'LW2889', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'LW2889', 'Aircraft'] = 'Airbus A320'
df_21.loc[df_21['Num_flight'] == 'LW2889', 'flight_capacity'] = 180

df_21.loc[df_21['Num_flight'] == 'D85502', 'Gate'] = 'U'
df_21.loc[df_21['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR3976', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR3976', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR3185', 'Gate'] = 'W'
df_21.loc[df_21['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR3185', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'FR6973', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737-800'
df_21.loc[df_21['Num_flight'] == 'FR6973', 'flight_capacity'] = 189

df_21.loc[df_21['Num_flight'] == 'EC1376', 'Gate'] = 'R'
df_21.loc[df_21['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_21.loc[df_21['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_21.loc[df_21['Num_flight'] == 'FR2834', 'Gate'] = 'S'
df_21.loc[df_21['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
df_21.loc[df_21['Num_flight'] == 'FR2834', 'flight_capacity'] = 197

In [101]:
if (df_21['fecha_scrapeo'] == "21/11/2025 14-58-40").any():
    df_21.loc[df_21['Num_flight'] == 'FR6353', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'FR6353', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR6353', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'FR6341', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR6341', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'HV5134', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'HV5134', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'V73573', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'V73573', 'flight_capacity'] = 156
        
    df_21.loc[df_21['Num_flight'] == 'FR3076', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR3076', 'flight_capacity'] = 197
        
    df_21.loc[df_21['Num_flight'] == 'W67920', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W67920', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'FR4587', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR4587', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'FR4587', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR4587', 'flight_capacity'] = 189

    df_21.loc[df_21['Num_flight'] == 'V73700', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'V73700', 'flight_capacity'] = 180

    df_21.loc[df_21['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

    df_21.loc[df_21['Num_flight'] == 'FR3129', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR3129', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'W43564', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'W43564', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'W43564', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == 'FR6985', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR6985', 'flight_capacity'] = 189

    df_21.loc[df_21['Num_flight'] == 'FR2925', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'FR2925', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR2925', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'D85510', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'D85510', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'FR9045', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

    df_21.loc[df_21['Num_flight'] == 'PC1094', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321'
    df_21.loc[df_21['Num_flight'] == 'PC1094', 'flight_capacity'] = 230

In [102]:
if (df_21['fecha_scrapeo'] == "21/11/2025 14-58-40").any():
    df_21.loc[df_21['Num_flight'] == 'V71415', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'V71415', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == 'EW2521', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A321'
    df_21.loc[df_21['Num_flight'] == 'EW2521', 'flight_capacity'] = 230
    
    df_21.loc[df_21['Num_flight'] == 'FR6374', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR6374', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR6374', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'U28058', 'flight_capacity'] = 156
        
    df_21.loc[df_21['Num_flight'] == 'LW7362', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'LW7362', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'LW7362', 'flight_capacity'] = 180
            
    df_21.loc[df_21['Num_flight'] == 'FR2330', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'FR2330', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR2330', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'EW9443', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'EW9443', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'V72165', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'V72165', 'flight_capacity'] = 156
    
    df_21.loc[df_21['Num_flight'] == 'RR6330', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'RR6330', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'RR6330', 'flight_capacity'] = 189
        
    df_21.loc[df_21['Num_flight'] == 'FR3078', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR3078', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'FR149', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR149', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

    df_21.loc[df_21['Num_flight'] == 'W61478', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W61478', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'FR3189', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

    df_21.loc[df_21['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

    df_21.loc[df_21['Num_flight'] == 'FR2098', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR2098', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'W43686', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'W43686', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == '5F5512', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == '5F5512', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == '5F5512', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == '3O398', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == '3O398', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == '3O398', 'flight_capacity'] = 180
        
    df_21.loc[df_21['Num_flight'] == 'EC7205', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'EC7205', 'flight_capacity'] = 156

In [103]:
if (df_21['fecha_scrapeo'] == "21/11/2025 14-58-40").any():
    
    df_21.loc[df_21['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'U22326', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == 'TO4759', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
    df_21.loc[df_21['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

    df_21.loc[df_21['Num_flight'] == 'FR5710', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR5710', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'W62378', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W62378', 'flight_capacity'] = 239

    df_21.loc[df_21['Num_flight'] == 'LG3592', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'LG3592', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'LG3592', 'flight_capacity'] = 189

    df_21.loc[df_21['Num_flight'] == 'RR1786', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'RR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'RR1786', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'JU585', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
    df_21.loc[df_21['Num_flight'] == 'JU585', 'flight_capacity'] = 157
    
    df_21.loc[df_21['Num_flight'] == 'FR8631', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR8631', 'flight_capacity'] = 189
        
    df_21.loc[df_21['Num_flight'] == 'FR7539', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR7539', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'V72135', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'V72135', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'V72135', 'flight_capacity'] = 180
        
    df_21.loc[df_21['Num_flight'] == 'TW408', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'TW408', 'Aircraft'] = 'Airbus A330-200'
    df_21.loc[df_21['Num_flight'] == 'TW408', 'flight_capacity'] = 246
    
    df_21.loc[df_21['Num_flight'] == 'FR3792', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR3792', 'flight_capacity'] = 189
        
    df_21.loc[df_21['Num_flight'] == 'W42940', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W42940', 'flight_capacity'] = 239

    df_21.loc[df_21['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

    df_21.loc[df_21['Num_flight'] == 'W62096', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W62096', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'FR6305', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR6305', 'flight_capacity'] = 189
        
    df_21.loc[df_21['Num_flight'] == 'FR6275', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR6275', 'flight_capacity'] = 197
            
    df_21.loc[df_21['Num_flight'] == 'FR2402', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR2402', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'FR1527', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR1527', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
    df_21.loc[df_21['Num_flight'] == 'EC7656', 'flight_capacity'] = 230
    
    df_21.loc[df_21['Num_flight'] == 'W64666', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
    df_21.loc[df_21['Num_flight'] == 'W64666', 'flight_capacity'] = 230

In [104]:
if (df_21['fecha_scrapeo'] == "21/11/2025 14-58-40").any():
    df_21.loc[df_21['Num_flight'] == 'FR9814', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'FR9814', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR9814', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'W61706', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W61706', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'W45154', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'
    df_21.loc[df_21['Num_flight'] == 'W45154', 'flight_capacity'] = 230
    
    df_21.loc[df_21['Num_flight'] == 'FR3080', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'FR3080', 'Aircraft'] = 'Boeing 737 MAX 8'
    df_21.loc[df_21['Num_flight'] == 'FR3080', 'flight_capacity'] = 197
    
    df_21.loc[df_21['Num_flight'] == 'W64116', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W64116', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'FR2250', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR2250', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'FR6597', 'Gate'] = 'W'
    df_21.loc[df_21['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR6597', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'FR2495', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'FR2495', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR2495', 'flight_capacity'] = 189
    df_21.loc[df_21['Num_flight'] == 'FR9811', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR9811', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'FR8669', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR8669', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'W46020', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
    df_21.loc[df_21['Num_flight'] == 'W46020', 'flight_capacity'] = 239
    
    df_21.loc[df_21['Num_flight'] == 'FR7808', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR7808', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'RR6944', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'RR6944', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'W43406', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320neo'
    df_21.loc[df_21['Num_flight'] == 'W43406', 'flight_capacity'] = 186
    
    df_21.loc[df_21['Num_flight'] == 'W43178', 'Gate'] = 'U'
    df_21.loc[df_21['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
    df_21.loc[df_21['Num_flight'] == 'W43178', 'flight_capacity'] = 230
    
    df_21.loc[df_21['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'EC1380', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == 'FR3174', 'Gate'] = 'R'
    df_21.loc[df_21['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'FR3174', 'flight_capacity'] = 189
    
    df_21.loc[df_21['Num_flight'] == 'U23374', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'U23374', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == 'EI565', 'Gate'] = 'Y'
    df_21.loc[df_21['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
    df_21.loc[df_21['Num_flight'] == 'EI565', 'flight_capacity'] = 180
    
    df_21.loc[df_21['Num_flight'] == 'RR8394', 'Gate'] = 'S'
    df_21.loc[df_21['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737-800'
    df_21.loc[df_21['Num_flight'] == 'RR8394', 'flight_capacity'] = 189

In [105]:
df_21.isna().sum()

Unnamed: 0         0
fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    0
Aircraft           0
Gate               0
dtype: int64

In [106]:
df_21['Aircraft'].unique()

array(['Airbus A319', 'Boeing 737-800', 'Boeing 737 MAX 8', 'Airbus A320',
       'Airbus A321neo', 'Airbus A321', 'Airbus A320neo',
       'Airbus A220-300', 'Airbus A330-200'], dtype=object)

In [107]:
df_21[(df_21['Gate'] == 'R')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
568,571.0,21/11/2025 14-58-40,easyJet Europe,EC7105,Geneva (GVA),06:10,Ha salido,156.0,Airbus A319,R
575,578.0,21/11/2025 14-58-40,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,Ha salido,156.0,Airbus A319,R
576,579.0,21/11/2025 14-58-40,easyJet Europe,EC7199,Edinburgh (EDI),07:20,Ha salido,156.0,Airbus A319,R
582,585.0,21/11/2025 14-58-40,easyJet Europe,EC1376,Geneva (GVA),08:40,"Retrasado, Ha salido",156.0,Airbus A319,R
586,589.0,21/11/2025 14-58-40,easyJet Europe,EC3737,Milan (MXP),09:10,Ha salido,180.0,Airbus A320,R
589,592.0,21/11/2025 14-58-40,Lauda Europe,LW12,Vienna (VIE),09:25,"Retrasado, Ha salido",180.0,Airbus A320,R
598,602.0,21/11/2025 14-58-40,easyJet Europe,EC7656,Lisbon (LIS),09:55,"Retrasado, Ha salido",230.0,Airbus A321,R
608,612.0,21/11/2025 14-58-40,easyJet Europe,EC7131,Nice/Cote D'Azur (NCE),10:30,Ha salido,156.0,Airbus A319,R
610,614.0,21/11/2025 14-58-40,easyJet Europe,EC4212,Napoli (NAP),10:35,"Retrasado, Ha salido",180.0,Airbus A320,R
614,618.0,21/11/2025 14-58-40,BUZZ,RR8384,Budapest (BUD),11:00,"Retrasado, Ha salido",189.0,Boeing 737-800,R
619,623.0,21/11/2025 14-58-40,Ryanair,FR3121,Beauvais (BVA),11:35,Ha salido,197.0,Boeing 737 MAX 8,R
621,625.0,21/11/2025 14-58-40,easyJet Europe,EC7141,Strasbourg (SXB),11:45,Ha salido,156.0,Airbus A319,R
644,648.0,21/11/2025 14-58-40,easyJet Europe,EC7153,Milan (MXP),14:20,Ha salido,156.0,Airbus A319,R
645,649.0,21/11/2025 14-58-40,Lauda Europe,LW7351,Vienna (VIE),14:20,Ha salido,180.0,Airbus A320,R
648,652.0,21/11/2025 14-58-40,easyJet Europe,EC7107,Geneva (GVA),14:40,Ha salido,156.0,Airbus A319,R
651,655.0,21/11/2025 14-58-40,Ryanair,FR2507,Cologne-Bonn (CGN),14:55,Programado,189.0,Boeing 737-800,R
654,658.0,21/11/2025 14-58-40,Ryanair,FR1342,Palma de Mallorca (PMI),15:00,Ha salido,189.0,Boeing 737-800,R
666,671.0,21/11/2025 14-58-40,easyJet Europe,EC7173,Berlin (BER),16:50,Ha salido,156.0,Airbus A319,R
667,672.0,21/11/2025 14-58-40,Volotea,V73700,Vitoria (VIT),16:50,"Retrasado, Ha salido",180.0,Airbus A320,R
675,680.0,21/11/2025 14-58-40,Ryanair,FR6353,Milan (BGY),18:00,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8,R
676,681.0,21/11/2025 14-58-40,easyJet Europe,EC7205,Southampton (SOU),18:10,Ha salido,156.0,Airbus A319,R
681,686.0,21/11/2025 14-58-40,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:45,Ha salido,156.0,Airbus A319,R
684,689.0,21/11/2025 14-58-40,easyJet Europe,EC7155,Milan (MXP),19:10,Ha salido,156.0,Airbus A319,R
685,690.0,21/11/2025 14-58-40,Ryanair,FR149,Berlin (BER),19:15,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8,R
698,703.0,21/11/2025 14-58-40,Ryanair,FR2402,Sevilla (SVQ),20:10,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8,R
700,705.0,21/11/2025 14-58-40,Ryanair,FR6305,Milan (BGY),20:10,"Retrasado, Ha salido",189.0,Boeing 737-800,R
702,707.0,21/11/2025 14-58-40,easyJet Europe,EC1956,Milan (LIN),20:15,"Retrasado, Ha salido",180.0,Airbus A320,R
706,711.0,21/11/2025 14-58-40,Volotea,V72135,Bordeaux (BOD),20:30,"Retrasado, Ha salido",180.0,Airbus A320,R
719,724.0,21/11/2025 14-58-40,Ryanair,FR3174,Ibiza (IBZ),21:10,Ha salido,189.0,Boeing 737-800,R
720,725.0,21/11/2025 14-58-40,easyJet Europe,EC1380,Geneva (GVA),21:15,"Retrasado, Ha salido",180.0,Airbus A320,R
722,727.0,21/11/2025 14-58-40,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,Ha salido,186.0,Airbus A320neo,R

In [108]:
df_21.info()

<class 'pandas.core.frame.DataFrame'>
Index: 168 entries, 568 to 735
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       168 non-null    float64
 1   fecha_scrapeo    168 non-null    object
 2   Name_company     168 non-null    object
 3   Num_flight       168 non-null    object
 4   Name_Destiny     168 non-null    object
 5   Time_flight      168 non-null    object
 6   flight_state     168 non-null    object
 7   flight_capacity  168 non-null    float64
 8   Aircraft         168 non-null    object
 9   Gate             168 non-null    object
dtypes: float64(2), object(8)
memory usage: 14.4+ KB

In [109]:
df_por_fecha['21/11/2025 14-58-40'] = df_21.copy()

In [110]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight      Name_Destiny  \
 736         NaN   22/Nov/2025           Ryanair      FR846       Milan (BGY)
 737         NaN   22/Nov/2025    easyJet Europe     EC7105      Geneva (GVA)
 738         NaN   22/Nov/2025           Ryanair     FR5718  Bratislava (BTS)
 739         NaN   22/Nov/2025           Ryanair     FR4545       Porto (OPO)
 740         NaN   22/Nov/2025           Ryanair     FR1342               NaN
 ..          ...           ...               ...        ...               ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020        Rome (FCO)
 848         NaN   22/Nov/2025           Ryanair     FR3800  Birmingham (BHX)
 849         NaN   22/Nov/2025           Ryanair     FR8574        Rome (FCO)
 850         NaN   22/Nov/2025          Wizz Air     W64116    Belgrade (BEG)
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642      Tanger (TNG)

     Time_flight                flight_state  flight_capacity Aircraft Gate
 736       06:00  Retrasado, Ha salido 06:15              NaN      NaN  S21
 737       06:10          En hora, Ha salido              NaN      NaN   R9
 738       06:10          En hora, Ha salido              NaN      NaN  S22
 739       06:15          En hora, Ha salido              NaN      NaN  U31
 740       06:20          En hora, Ha salido              NaN      NaN  S24
 ..          ...                         ...              ...      ...  ...
 847       21:35          En hora, Ha salido              NaN      NaN  S22
 848       21:55          En hora, Ha salido              NaN      NaN  Y57
 849       22:10  Retrasado, Ha salido 22:28              NaN      NaN  U34
 850       22:10          En hora, Ha salido              NaN      NaN  Y58
 851       22:15          En hora, Ha salido              NaN      NaN  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46
 ...               ...      ...  ...
 1009              NaN      NaN  W45
 1010              NaN      NaN  W42
 1011              NaN      NaN  R13
 1012              NaN      NaN  U31
 1013              NaN      NaN  W44

 [162 rows x 10 columns],

In [111]:
df_22 = df_por_fecha['22/Nov/2025'].copy()
df_22

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
736,NaN,22/Nov/2025,Ryanair,FR846,Milan (BGY),06:00,"Retrasado, Ha salido 06:15",NaN,NaN,S21
737,NaN,22/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R9
738,NaN,22/Nov/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S22
739,NaN,22/Nov/2025,Ryanair,FR4545,Porto (OPO),06:15,"En hora, Ha salido",NaN,NaN,U31
740,NaN,22/Nov/2025,Ryanair,FR1342,NaN,06:20,"En hora, Ha salido",NaN,NaN,S24
...,...,...,...,...,...,...,...,...,...,...
847,NaN,22/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",NaN,NaN,S22
848,NaN,22/Nov/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"En hora, Ha salido",NaN,NaN,Y57
849,NaN,22/Nov/2025,Ryanair,FR8574,Rome (FCO),22:10,"Retrasado, Ha salido 22:28",NaN,NaN,U34
850,NaN,22/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",NaN,NaN,Y58
851,NaN,22/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Ha salido",NaN,NaN,W44

In [112]:
df_22.isna().sum()

Unnamed: 0         116
fecha_scrapeo        0
Name_company         1
Num_flight           0
Name_Destiny         6
Time_flight          0
flight_state         0
flight_capacity    116
Aircraft           108
Gate                 0
dtype: int64

In [113]:
df_22[(df_22['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
736,NaN,22/Nov/2025,Ryanair,FR846,Milan (BGY),06:00,"Retrasado, Ha salido 06:15",NaN,NaN,S21
737,NaN,22/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R9
738,NaN,22/Nov/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S22
739,NaN,22/Nov/2025,Ryanair,FR4545,Porto (OPO),06:15,"En hora, Ha salido",NaN,NaN,U31
740,NaN,22/Nov/2025,Ryanair,FR1342,NaN,06:20,"En hora, Ha salido",NaN,NaN,S24
741,NaN,22/Nov/2025,Ryanair,FR777,Venice (VCE),06:30,"Retrasado, Ha salido 06:43",NaN,NaN,S23
742,NaN,22/Nov/2025,easyJet Europe,EC7151,Milan (MXP),07:30,"En hora, Ha salido",NaN,NaN,R10
743,NaN,22/Nov/2025,Ryanair,FR2918,Brussels (BRU),08:05,"En hora, Ha salido",NaN,NaN,S20
744,NaN,22/Nov/2025,Ryanair,FR3180,Rome (FCO),08:15,"En hora, Ha salido",NaN,NaN,U32
745,NaN,22/Nov/2025,Air Arabia Maroc,3O376,Al Aaroui (NDR),08:35,"En hora, Ha salido",NaN,NaN,W45

In [114]:
df_22[(df_22['Name_Destiny'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
740,NaN,22/Nov/2025,Ryanair,FR1342,NaN,06:20,"En hora, Ha salido",NaN,NaN,S24
746,NaN,22/Nov/2025,Ryanair,FR1165,NaN,08:50,"En hora, Ha salido",NaN,NaN,R12
785,NaN,22/Nov/2025,Ryanair,FR483,NaN,13:05,"Retrasado, Ha salido 13:24",NaN,NaN,S21
800,NaN,22/Nov/2025,Ryanair,FR3070,NaN,14:40,"Retrasado, Ha salido 14:51",NaN,NaN,S24
834,NaN,22/Nov/2025,Ryanair,FR9581,NaN,20:25,"En hora, Ha salido",NaN,NaN,R13
836,NaN,22/Nov/2025,Ryanair,FR3182,NaN,20:45,"En hora, Ha salido",NaN,NaN,U33

In [115]:
df_22.loc[df_22['Num_flight'] == 'FR3070', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'
df_22.loc[df_22['Num_flight'] == 'FR9581', 'Name_Destiny'] = 'Sevilla (SVQ)'

In [116]:
df_22.loc[df_22['Num_flight'] == 'RR3039', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'RR3039', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == '3O642', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W64116', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'FR8574', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR8574', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR3800', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3800', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W46020', 'flight_capacity'] = 239

In [117]:
df_22.loc[df_22['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR5220', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_22.loc[df_22['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_22.loc[df_22['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3174', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_22.loc[df_22['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_22.loc[df_22['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR3182', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3182', 'flight_capacity'] = 189
df_22.loc[df_22['Num_flight'] == 'FR3182', 'Name_Destiny'] = 'Malaga (AGP)'

In [118]:
df_22.loc[df_22['Num_flight'] == 'TW408', 'Aircraft'] = 'BOEING 777-300ER'
df_22.loc[df_22['Num_flight'] == 'TW408', 'flight_capacity'] = 294

df_22.loc[df_22['Num_flight'] == 'FR9581', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR9581', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR867', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'BT878', 'Aircraft'] = 'Airbus A220-300'
df_22.loc[df_22['Num_flight'] == 'BT878', 'flight_capacity'] = 148

df_22.loc[df_22['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR149', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR5270', 'flight_capacity'] = 189

In [119]:
df_22.loc[df_22['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W61176', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR3792', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR3035', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'HV5134', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR878', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'D81741', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'FR6353', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR6353', 'flight_capacity'] = 189

In [120]:
df_22.loc[df_22['Num_flight'] == 'FR2925', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR2925', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR6874', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR9015', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR3146', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3146', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR7543', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR7543', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR3807', 'flight_capacity'] = 197

In [121]:
df_22.loc[df_22['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR3070', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3070', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-900'
df_22.loc[df_22['Num_flight'] == 'KU136', 'flight_capacity'] = 278

df_22.loc[df_22['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'RR6920', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'RR6920', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_22.loc[df_22['Num_flight'] == 'BT684', 'flight_capacity'] = 148

In [122]:
df_22.loc[df_22['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'VF608', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'VF608', 'flight_capacity'] = 180
df_22.loc[df_22['Num_flight'] == 'VF608', 'Name_company'] = 'Ajet'

df_22.loc[df_22['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == '3O378', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR2098', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'RK6597', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'RK6597', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR7808', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321'
df_22.loc[df_22['Num_flight'] == 'W46330', 'flight_capacity'] = 230

df_22.loc[df_22['Num_flight'] == 'OB775', 'Aircraft'] = 'Airbus A330-200'
df_22.loc[df_22['Num_flight'] == 'OB775', 'flight_capacity'] = 246

In [123]:
df_22.loc[df_22['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR483', 'flight_capacity'] = 189
df_22.loc[df_22['Num_flight'] == 'FR483', 'Name_Destiny'] = 'Malaga (AGP)'

df_22.loc[df_22['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_22.loc[df_22['Num_flight'] == 'PC1092', 'flight_capacity'] = 230

df_22.loc[df_22['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3108', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'EI563', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'EC7193', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC7193', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'FR4597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR4597', 'flight_capacity'] = 197

In [124]:
df_22.loc[df_22['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'U22704', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'U5406', 'Aircraft'] = 'Boeing 737-700'
df_22.loc[df_22['Num_flight'] == 'U5406', 'flight_capacity'] = 149

df_22.loc[df_22['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320neo'
df_22.loc[df_22['Num_flight'] == 'J246', 'flight_capacity'] = 186

df_22.loc[df_22['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'FR9307', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR9307', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR3168', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3168', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'U22326', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'FR9171', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR9171', 'flight_capacity'] = 197

In [125]:
df_22.loc[df_22['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'HV5132', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'FR6559', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR6559', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'JU581', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'RR3049', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W61914', 'flight_capacity'] = 239

In [126]:
df_22.loc[df_22['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'TO4751', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'TO4751', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR2834', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_22.loc[df_22['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_22.loc[df_22['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == 'W43938', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR1165', 'flight_capacity'] = 189
df_22.loc[df_22['Num_flight'] == 'FR1165', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'

df_22.loc[df_22['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == '3O376', 'flight_capacity'] = 180

In [127]:
df_22.loc[df_22['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_22.loc[df_22['Num_flight'] == '3O376', 'flight_capacity'] = 180

df_22.loc[df_22['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR1342', 'flight_capacity'] = 189
df_22.loc[df_22['Num_flight'] == 'FR1342', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'

df_22.loc[df_22['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_22.loc[df_22['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_22.loc[df_22['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_22.loc[df_22['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_22.loc[df_22['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_22.loc[df_22['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_22.loc[df_22['Num_flight'] == 'FR846', 'flight_capacity'] = 189

In [128]:
df_22.isna().sum()

Unnamed: 0         116
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity      0
Aircraft             0
Gate                 0
dtype: int64

In [129]:
df_22[(df_22.Name_Destiny == 'Valletta (MLA)')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
812,NaN,22/Nov/2025,Ryanair,FR5752,Valletta (MLA),17:10,"En hora, Ha salido",197.0,Boeing 737 MAX 8,W44

In [130]:
df_22.tail(60)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
792,NaN,22/Nov/2025,Air Arabia Maroc,3O378,Tanger (TNG),13:35,"Retrasado, Ha salido 14:05",180.0,Airbus A320,Y58
793,NaN,22/Nov/2025,easyJet Europe,EC7153,Milan (MXP),13:35,"En hora, Ha salido",156.0,Airbus A319,R19
794,NaN,22/Nov/2025,Ajet,VF608,Ankara (ESB),13:40,"Retrasado, Ha salido 13:56",180.0,Airbus A320,W45
795,NaN,22/Nov/2025,Ryanair,FR1681,Frankfurt-Hahn (HHN),14:00,"En hora, Ha salido",189.0,Boeing 737-800,U35
796,NaN,22/Nov/2025,Air Baltic,BT684,Riga (RIX),14:05,"Retrasado, Programado 15:00",148.0,Airbus A220-300,S20
797,NaN,22/Nov/2025,BUZZ,RR6920,Dublin (DUB),14:05,"Retrasado, Ha salido 14:33",189.0,Boeing 737-800,Y57
798,NaN,22/Nov/2025,Ryanair,FR58,Napoli (NAP),14:15,"En hora, Ha salido",189.0,Boeing 737-800,U34
799,NaN,22/Nov/2025,Kuwait Airways,KU136,Kuwait City (KWI),14:25,"En hora, Ha salido",278.0,Airbus A330-900,W44
800,NaN,22/Nov/2025,Ryanair,FR3070,Palma de Mallorca (PMI),14:40,"Retrasado, Ha salido 14:51",189.0,Boeing 737-800,S24
801,NaN,22/Nov/2025,Ryanair,FR774,Torino (TRN),14:45,"En hora, Ha salido",189.0,Boeing 737-800,S22
802,NaN,22/Nov/2025,Ryanair,FR3121,Beauvais (BVA),14:50,"En hora, Ha salido",189.0,Boeing 737-800,U37
803,NaN,22/Nov/2025,Ryanair,FR6300,Sofia (SOF),14:55,"En hora, Programado",189.0,Boeing 737-800,R12
804,NaN,22/Nov/2025,Ryanair,FR3189,Fes (FEZ),15:30,"En hora, Programado",189.0,Boeing 737-800,W42
805,NaN,22/Nov/2025,Wizz Air Malta,W46728,Venice (VCE),15:40,"En hora, Ha salido",239.0,Airbus A321neo,W42
806,NaN,22/Nov/2025,Ryanair,FR3807,Charleroi (CRL),16:05,"En hora, Ha salido",197.0,Boeing 737 MAX 8,S21
807,NaN,22/Nov/2025,BUZZ,RR8384,Budapest (BUD),16:10,"Retrasado, Ha salido 16:40",189.0,Boeing 737-800,U32
808,NaN,22/Nov/2025,Ryanair,FR7543,Manchester (MAN),16:20,"En hora, Ha salido",189.0,Boeing 737-800,S25
809,NaN,22/Nov/2025,Ryanair,FR3146,Oujda (OUD),16:45,"En hora, Ha salido",189.0,Boeing 737-800,Y54
810,NaN,22/Nov/2025,Ryanair,FR269,Milan (MXP),16:50,"En hora, Ha salido",189.0,Boeing 737-800,W49
811,NaN,22/Nov/2025,Ryanair,FR9015,London (STN),17:00,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U37
812,NaN,22/Nov/2025,Ryanair,FR5752,Valletta (MLA),17:10,"En hora, Ha salido",197.0,Boeing 737 MAX 8,W44
813,NaN,22/Nov/2025,Ryanair,FR6874,Dublin (DUB),17:40,"En hora, Ha salido",189.0,Boeing 737-800,U34
814,NaN,22/Nov/2025,Ryanair,FR2233,Al Aaroui (NDR),17:50,"Retrasado, Ha salido 18:08",189.0,Boeing 737-800,Y54
815,NaN,22/Nov/2025,Ryanair,FR2925,Brussels (BRU),17:50,"En hora, Ha salido",197.0,Boeing 737 MAX 8,W42
816,NaN,22/Nov/2025,Ryanair,FR6353,Milan (BGY),17:55,"En hora, Ha salido",189.0,Boeing 737-800,U33
817,NaN,22/Nov/2025,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:00,"En hora, Ha salido",156.0,Airbus A319,S24
818,NaN,22/Nov/2025,Norwegian Air Sweden AOC,D81741,Oslo (OSL),18:15,"En hora, Ha salido",189.0,Boeing 737-800,R11
819,NaN,22/Nov/2025,Ryanair,FR878,Venice (VCE),18:15,"En hora, Ha salido",189.0,Boeing 737-800,U32
820,NaN,22/Nov/2025,Transavia,HV5134,Amsterdam (AMS),18:15,"En hora, Ha salido",239.0,Airbus A321neo,U36
821,NaN,22/Nov/2025,Ryanair,FR3035,Krakow (KRK),18:20,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U41
822,NaN,22/Nov/2025,Ryanair,FR3792,Birmingham (BHX),18:55,"En hora, Ha salido",197.0,Boeing 737 MAX 8,Y58
823,NaN,22/Nov/2025,Wizz Air,W61176,Katowice (KTW),18:55,"En hora, Ha salido",239.0,Airbus A321neo,S20
824,NaN,22/Nov/2025,Wizz Air,W61478,Warsaw (WAW),19:00,"En hora, Ha salido",239.0,Airbus A321neo,S21
825,NaN,22/Nov/2025,Ryanair,FR9045,London (STN),19:05,"En hora, Ha salido",189.0,Boeing 737-800,W42
826,NaN,22/Nov/2025,Ryanair,FR5270,Manchester (MAN),19:20,"En hora, Ha salido",189.0,Boeing 737-800,Y57
827,NaN,22/Nov/2025,Ryanair,FR149,Berlin (BER),19:35,"Retrasado, Ha salido 19:59",197.0,Boeing 737 MAX 8,U34
828,NaN,22/Nov/2025,Wizz Air,W64406,Sofia (SOF),19:35,"En hora, Ha salido",239.0,Airbus A321neo,S22
829,NaN,22/Nov/2025,Air Baltic,BT878,Tallinn (TLL),19:40,"En hora, Ha salido",148.0,Airbus A220-300,U35
830,NaN,22/Nov/2025,Ryanair,FR3078,Lisbon (LIS),19:55,"En hora, Ha salido",189.0,Boeing 737-800,S24
831,NaN,22/Nov/2025,Lauda Europe,LW7351,Vienna (VIE),20:05,"En hora, Ha salido",180.0,Airbus A320,R14
832,NaN,22/Nov/2025,easyJet Europe,EC1380,Geneva (GVA),20:10,"En hora, Ha salido",180.0,Airbus A320,R11
833,NaN,22/Nov/2025,Ryanair,FR867,Venice (VCE),20:20,"En hora, Ha salido",189.0,Boeing 737-800,U36
834,NaN,22/Nov/2025,Ryanair,FR9581,Sevilla (SVQ),20:25,"En hora, Ha salido",197.0,Boeing 737 MAX 8,R13
835,NaN,22/Nov/2025,T'Way Air,TW408,Seoul/Incheon (ICN),20:30,"En hora, Ha salido",294.0,BOEING 777-300ER,Y55
836,NaN,22/Nov/2025,Ryanair,FR3182,Malaga (AGP),20:45,"En hora, Ha salido",189.0,Boeing 737-800,U33
837,NaN,22/Nov/2025,Ryanair,FR3928,Trieste (TRS),20:45,"En hora, Ha salido",189.0,Boeing 737-800,S25
838,NaN,22/Nov/2025,Transavia,TO4759,Paris (ORY),20:45,"Retrasado, Ha salido 21:41",186.0,Airbus A320neo,U31
839,NaN,22/Nov/2025,Wizz Air,W62378,Budapest (BUD),20:45,"Retrasado, Ha salido 20:55",239.0,Airbus A321neo,U32
840,NaN,22/Nov/2025,Ryanair,FR4585,Porto (OPO),20:50,"Retrasado, Ha salido 21:10",189.0,Boeing 737-800,S23
841,NaN,22/Nov/2025,Ryanair,FR6267,Edinburgh (EDI),20:55,"En hora, Ha salido",189.0,Boeing 737-800,W42
842,NaN,22/Nov/2025,Ryanair,FR3174,Ibiza (IBZ),21:20,"En hora, Ha salido",189.0,Boeing 737-800,U34
843,NaN,22/Nov/2025,Wizz Air Malta,W43178,Bucharest (BBU),21:20,"En hora, Ha salido",230.0,Airbus A321,S20
844,NaN,22/Nov/2025,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"En hora, Ha salido",180.0,Airbus A320,S21
845,NaN,22/Nov/2025,Ryanair,FR5220,Bologna (BLQ),21:30,"En hora, Ha salido",189.0,Boeing 737-800,U35
846,NaN,22/Nov/2025,BUZZ,RR3039,Prague (PRG),21:35,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U36
847,NaN,22/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",239.0,Airbus A321neo,S22
848,NaN,22/Nov/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"En hora, Ha salido",189.0,Boeing 737-800,Y57
849,NaN,22/Nov/2025,Ryanair,FR8574,Rome (FCO),22:10,"Retrasado, Ha salido 22:28",189.0,Boeing 737-800,U34
850,NaN,22/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",239.0,Airbus A321neo,Y58
851,NaN,22/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Ha salido",180.0,Airbus A320,W44

In [131]:
# Rango a corregir
start, end = 805, 818

# Reemplazar los valores desplazando hacia arriba dentro del rango
df_22.loc[start:end, 'Gate'] = df_22.loc[start+1:end+1, 'Gate'].values

In [132]:
df_22.tail(60)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
792,NaN,22/Nov/2025,Air Arabia Maroc,3O378,Tanger (TNG),13:35,"Retrasado, Ha salido 14:05",180.0,Airbus A320,Y58
793,NaN,22/Nov/2025,easyJet Europe,EC7153,Milan (MXP),13:35,"En hora, Ha salido",156.0,Airbus A319,R19
794,NaN,22/Nov/2025,Ajet,VF608,Ankara (ESB),13:40,"Retrasado, Ha salido 13:56",180.0,Airbus A320,W45
795,NaN,22/Nov/2025,Ryanair,FR1681,Frankfurt-Hahn (HHN),14:00,"En hora, Ha salido",189.0,Boeing 737-800,U35
796,NaN,22/Nov/2025,Air Baltic,BT684,Riga (RIX),14:05,"Retrasado, Programado 15:00",148.0,Airbus A220-300,S20
797,NaN,22/Nov/2025,BUZZ,RR6920,Dublin (DUB),14:05,"Retrasado, Ha salido 14:33",189.0,Boeing 737-800,Y57
798,NaN,22/Nov/2025,Ryanair,FR58,Napoli (NAP),14:15,"En hora, Ha salido",189.0,Boeing 737-800,U34
799,NaN,22/Nov/2025,Kuwait Airways,KU136,Kuwait City (KWI),14:25,"En hora, Ha salido",278.0,Airbus A330-900,W44
800,NaN,22/Nov/2025,Ryanair,FR3070,Palma de Mallorca (PMI),14:40,"Retrasado, Ha salido 14:51",189.0,Boeing 737-800,S24
801,NaN,22/Nov/2025,Ryanair,FR774,Torino (TRN),14:45,"En hora, Ha salido",189.0,Boeing 737-800,S22
802,NaN,22/Nov/2025,Ryanair,FR3121,Beauvais (BVA),14:50,"En hora, Ha salido",189.0,Boeing 737-800,U37
803,NaN,22/Nov/2025,Ryanair,FR6300,Sofia (SOF),14:55,"En hora, Programado",189.0,Boeing 737-800,R12
804,NaN,22/Nov/2025,Ryanair,FR3189,Fes (FEZ),15:30,"En hora, Programado",189.0,Boeing 737-800,W42
805,NaN,22/Nov/2025,Wizz Air Malta,W46728,Venice (VCE),15:40,"En hora, Ha salido",239.0,Airbus A321neo,S21
806,NaN,22/Nov/2025,Ryanair,FR3807,Charleroi (CRL),16:05,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U32
807,NaN,22/Nov/2025,BUZZ,RR8384,Budapest (BUD),16:10,"Retrasado, Ha salido 16:40",189.0,Boeing 737-800,S25
808,NaN,22/Nov/2025,Ryanair,FR7543,Manchester (MAN),16:20,"En hora, Ha salido",189.0,Boeing 737-800,Y54
809,NaN,22/Nov/2025,Ryanair,FR3146,Oujda (OUD),16:45,"En hora, Ha salido",189.0,Boeing 737-800,W49
810,NaN,22/Nov/2025,Ryanair,FR269,Milan (MXP),16:50,"En hora, Ha salido",189.0,Boeing 737-800,U37
811,NaN,22/Nov/2025,Ryanair,FR9015,London (STN),17:00,"En hora, Ha salido",197.0,Boeing 737 MAX 8,W44
812,NaN,22/Nov/2025,Ryanair,FR5752,Valletta (MLA),17:10,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U34
813,NaN,22/Nov/2025,Ryanair,FR6874,Dublin (DUB),17:40,"En hora, Ha salido",189.0,Boeing 737-800,Y54
814,NaN,22/Nov/2025,Ryanair,FR2233,Al Aaroui (NDR),17:50,"Retrasado, Ha salido 18:08",189.0,Boeing 737-800,W42
815,NaN,22/Nov/2025,Ryanair,FR2925,Brussels (BRU),17:50,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U33
816,NaN,22/Nov/2025,Ryanair,FR6353,Milan (BGY),17:55,"En hora, Ha salido",189.0,Boeing 737-800,S24
817,NaN,22/Nov/2025,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:00,"En hora, Ha salido",156.0,Airbus A319,R11
818,NaN,22/Nov/2025,Norwegian Air Sweden AOC,D81741,Oslo (OSL),18:15,"En hora, Ha salido",189.0,Boeing 737-800,U32
819,NaN,22/Nov/2025,Ryanair,FR878,Venice (VCE),18:15,"En hora, Ha salido",189.0,Boeing 737-800,U32
820,NaN,22/Nov/2025,Transavia,HV5134,Amsterdam (AMS),18:15,"En hora, Ha salido",239.0,Airbus A321neo,U36
821,NaN,22/Nov/2025,Ryanair,FR3035,Krakow (KRK),18:20,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U41
822,NaN,22/Nov/2025,Ryanair,FR3792,Birmingham (BHX),18:55,"En hora, Ha salido",197.0,Boeing 737 MAX 8,Y58
823,NaN,22/Nov/2025,Wizz Air,W61176,Katowice (KTW),18:55,"En hora, Ha salido",239.0,Airbus A321neo,S20
824,NaN,22/Nov/2025,Wizz Air,W61478,Warsaw (WAW),19:00,"En hora, Ha salido",239.0,Airbus A321neo,S21
825,NaN,22/Nov/2025,Ryanair,FR9045,London (STN),19:05,"En hora, Ha salido",189.0,Boeing 737-800,W42
826,NaN,22/Nov/2025,Ryanair,FR5270,Manchester (MAN),19:20,"En hora, Ha salido",189.0,Boeing 737-800,Y57
827,NaN,22/Nov/2025,Ryanair,FR149,Berlin (BER),19:35,"Retrasado, Ha salido 19:59",197.0,Boeing 737 MAX 8,U34
828,NaN,22/Nov/2025,Wizz Air,W64406,Sofia (SOF),19:35,"En hora, Ha salido",239.0,Airbus A321neo,S22
829,NaN,22/Nov/2025,Air Baltic,BT878,Tallinn (TLL),19:40,"En hora, Ha salido",148.0,Airbus A220-300,U35
830,NaN,22/Nov/2025,Ryanair,FR3078,Lisbon (LIS),19:55,"En hora, Ha salido",189.0,Boeing 737-800,S24
831,NaN,22/Nov/2025,Lauda Europe,LW7351,Vienna (VIE),20:05,"En hora, Ha salido",180.0,Airbus A320,R14
832,NaN,22/Nov/2025,easyJet Europe,EC1380,Geneva (GVA),20:10,"En hora, Ha salido",180.0,Airbus A320,R11
833,NaN,22/Nov/2025,Ryanair,FR867,Venice (VCE),20:20,"En hora, Ha salido",189.0,Boeing 737-800,U36
834,NaN,22/Nov/2025,Ryanair,FR9581,Sevilla (SVQ),20:25,"En hora, Ha salido",197.0,Boeing 737 MAX 8,R13
835,NaN,22/Nov/2025,T'Way Air,TW408,Seoul/Incheon (ICN),20:30,"En hora, Ha salido",294.0,BOEING 777-300ER,Y55
836,NaN,22/Nov/2025,Ryanair,FR3182,Malaga (AGP),20:45,"En hora, Ha salido",189.0,Boeing 737-800,U33
837,NaN,22/Nov/2025,Ryanair,FR3928,Trieste (TRS),20:45,"En hora, Ha salido",189.0,Boeing 737-800,S25
838,NaN,22/Nov/2025,Transavia,TO4759,Paris (ORY),20:45,"Retrasado, Ha salido 21:41",186.0,Airbus A320neo,U31
839,NaN,22/Nov/2025,Wizz Air,W62378,Budapest (BUD),20:45,"Retrasado, Ha salido 20:55",239.0,Airbus A321neo,U32
840,NaN,22/Nov/2025,Ryanair,FR4585,Porto (OPO),20:50,"Retrasado, Ha salido 21:10",189.0,Boeing 737-800,S23
841,NaN,22/Nov/2025,Ryanair,FR6267,Edinburgh (EDI),20:55,"En hora, Ha salido",189.0,Boeing 737-800,W42
842,NaN,22/Nov/2025,Ryanair,FR3174,Ibiza (IBZ),21:20,"En hora, Ha salido",189.0,Boeing 737-800,U34
843,NaN,22/Nov/2025,Wizz Air Malta,W43178,Bucharest (BBU),21:20,"En hora, Ha salido",230.0,Airbus A321,S20
844,NaN,22/Nov/2025,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"En hora, Ha salido",180.0,Airbus A320,S21
845,NaN,22/Nov/2025,Ryanair,FR5220,Bologna (BLQ),21:30,"En hora, Ha salido",189.0,Boeing 737-800,U35
846,NaN,22/Nov/2025,BUZZ,RR3039,Prague (PRG),21:35,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U36
847,NaN,22/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",239.0,Airbus A321neo,S22
848,NaN,22/Nov/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"En hora, Ha salido",189.0,Boeing 737-800,Y57
849,NaN,22/Nov/2025,Ryanair,FR8574,Rome (FCO),22:10,"Retrasado, Ha salido 22:28",189.0,Boeing 737-800,U34
850,NaN,22/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",239.0,Airbus A321neo,Y58
851,NaN,22/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Ha salido",180.0,Airbus A320,W44

In [133]:
# indice 805 tiene en la columna gate el valor w42 que es duplicada de la fila de arriba
# remplazar ese valor por el valor de abajo s21 y asi susesivamente a la siguientes filas hasta
# el indice 818 que reemplazamos su gate por u32 de abajo pero dejamos para la fila 819 el gate u32

In [134]:
# 819 es u31 en 818 u32 arrastrar arriba 803 elimina r2 y subir w42 y todo el resto

In [135]:
# dub -> y54 / tanger correcto

In [136]:
df_por_fecha['22/Nov/2025'] = df_22.copy()

In [137]:
df_por_fecha   #GURDAMOS EN DICC VISUALIZAMOS DICC

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity Aircraft Gate
 852               NaN      NaN  U34
 853               NaN      NaN  S20
 854               NaN      NaN  R12
 855               NaN      NaN  S21
 856               NaN     B738  W46

In [138]:
# CONCATENAMOS COLUMNAS DE PRIMERA SEMANA Y LO GUARDAMOS EN UNA VARIABLE 
df_semana1 = pd.concat([df_17, df_18, df_19, df_20, df_21, df_22], ignore_index=True)

In [139]:
df_semana1

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,118.0,17/11/2025 14-06-56,Ryanair,FR3180,Rome (FCO),06:00,Ha salido,189.0,Boeing 737-800,U
1,119.0,17/11/2025 14-06-56,Ryanair,FR846,Milan (BGY),06:10,"Retrasado, Ha salido",189.0,Boeing 737-800,S
2,120.0,17/11/2025 14-06-56,easyJet Europe,EC7105,Geneva (GVA),06:15,Ha salido,156.0,Airbus A319,R
3,121.0,17/11/2025 14-06-56,Ryanair,FR2233,Al Aaroui (NDR),06:20,"Retrasado, Ha salido",189.0,Boeing 737-800,NaN
4,122.0,17/11/2025 14-06-56,Ryanair,FR8384,Budapest (BUD),06:25,Ha salido,189.0,Boeing 737-800,R
...,...,...,...,...,...,...,...,...,...,...
731,NaN,22/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",239.0,Airbus A321neo,S22
732,NaN,22/Nov/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"En hora, Ha salido",189.0,Boeing 737-800,Y57
733,NaN,22/Nov/2025,Ryanair,FR8574,Rome (FCO),22:10,"Retrasado, Ha salido 22:28",189.0,Boeing 737-800,U34
734,NaN,22/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",239.0,Airbus A321neo,Y58
735,NaN,22/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Ha salido",180.0,Airbus A320,W44

In [140]:
df_semana1.isna().sum()

Unnamed: 0         116
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity      2
Aircraft             2
Gate                16
dtype: int64

In [141]:
df_semana1[(df_semana1['flight_capacity'].isna())].head(40) # QUE NULOS TENEMOS
# EL VUELO DE CARGO NOS LO CARGAMOS YA QUE NO INFLUYE EN AFLUENCIA DE PASAJEROS

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
125,243.0,17/11/2025 14-06-56,Eurowings,E69443,Dusseldorf (DUS),19:35,"Retrasado, Ha salido",NaN,NaN,NaN
411,90.0,20/11/2025 14-38-34,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),18:15,Programado,NaN,NaN,R

In [142]:
# AÑADIMOS INFO FALTANTE 
df_semana1.loc[df_semana1['Num_flight'] == 'EC7139', 'Aircraft'] = 'Airbus A320'
df_semana1.loc[df_semana1['Num_flight'] == 'EC7139', 'flight_capacity'] =  180

In [143]:
df_semana1[(df_semana1['Gate'].isna())].head(40)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
3,121.0,17/11/2025 14-06-56,Ryanair,FR2233,Al Aaroui (NDR),06:20,"Retrasado, Ha salido",189.0,Boeing 737-800,NaN
22,140.0,17/11/2025 14-06-56,Air Arabia Maroc,3O398,Rabat (RBA),09:20,Ha salido,180.0,Airbus A320,NaN
37,155.0,17/11/2025 14-06-56,Transavia,TO4751,Paris (ORY),10:05,"Retrasado, Ha salido",189.0,Boeing 737-800,NaN
55,173.0,17/11/2025 14-06-56,Transavia,TO4755,Paris (ORY),11:30,Ha salido,189.0,Boeing 737-800,NaN
91,209.0,17/11/2025 14-06-56,Air Arabia Maroc,3O376,Al Aaroui (NDR),15:00,Ha salido,180.0,Airbus A320,NaN
93,211.0,17/11/2025 14-06-56,Ryanair,FR1681,Frankfurt-Hahn (HHN),15:35,Ha salido,189.0,Boeing 737-800,NaN
125,243.0,17/11/2025 14-06-56,Eurowings,E69443,Dusseldorf (DUS),19:35,"Retrasado, Ha salido",NaN,NaN,NaN
157,275.0,17/11/2025 14-06-56,Wizz Air Malta,W43178,Bucharest (BBU),21:20,"Retrasado, Ha salido",230.0,Airbus A321,NaN
240,358.0,19/11/2025 14-33-06,Ryanair,FR9406,Fes (FEZ),06:05,Ha salido,189.0,Boeing 737-800,NaN
253,371.0,19/11/2025 14-33-06,Air Arabia Maroc,3O376,Al Aaroui (NDR),09:35,Ha salido,180.0,Airbus A320,NaN
283,401.0,19/11/2025 14-33-06,Ryanair,FR777,Venice (VCE),15:10,"Retrasado, Ha salido",197.0,Boeing 737 MAX 8,NaN
288,406.0,19/11/2025 14-33-06,Transavia,TO4755,Paris (ORY),16:45,Ha salido,186.0,Airbus A320neo,NaN
295,413.0,19/11/2025 14-33-06,Wizz Air Malta,W43686,Iasi (IAS),18:30,Ha salido,180.0,Airbus A320,NaN
315,433.0,19/11/2025 14-33-06,Wizz Air,W62378,Budapest (BUD),20:45,"Retrasado, Ha salido",239.0,Airbus A321neo,NaN
343,21.0,20/11/2025 14-38-34,Wizz Air,W61914,Vilnius (VNO),09:20,"Retrasado, Ha salido",239.0,Airbus A321neo,NaN
451,130.0,20/11/2025 14-38-34,Wizz Air Malta,W45154,Tirana (TIA),22:45,Programado,239.0,Airbus A321neo,NaN

In [144]:
df_semana1.drop([241], inplace=True)   # ELIMINAR VUELO DE CARGO

In [145]:
df_semana1.reset_index(drop=True, inplace=True) # RESETEAR INDICE

In [146]:
df_semana1

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,118.0,17/11/2025 14-06-56,Ryanair,FR3180,Rome (FCO),06:00,Ha salido,189.0,Boeing 737-800,U
1,119.0,17/11/2025 14-06-56,Ryanair,FR846,Milan (BGY),06:10,"Retrasado, Ha salido",189.0,Boeing 737-800,S
2,120.0,17/11/2025 14-06-56,easyJet Europe,EC7105,Geneva (GVA),06:15,Ha salido,156.0,Airbus A319,R
3,121.0,17/11/2025 14-06-56,Ryanair,FR2233,Al Aaroui (NDR),06:20,"Retrasado, Ha salido",189.0,Boeing 737-800,NaN
4,122.0,17/11/2025 14-06-56,Ryanair,FR8384,Budapest (BUD),06:25,Ha salido,189.0,Boeing 737-800,R
...,...,...,...,...,...,...,...,...,...,...
730,NaN,22/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",239.0,Airbus A321neo,S22
731,NaN,22/Nov/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"En hora, Ha salido",189.0,Boeing 737-800,Y57
732,NaN,22/Nov/2025,Ryanair,FR8574,Rome (FCO),22:10,"Retrasado, Ha salido 22:28",189.0,Boeing 737-800,U34
733,NaN,22/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",239.0,Airbus A321neo,Y58
734,NaN,22/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Ha salido",180.0,Airbus A320,W44

In [147]:
#df_semana1.to_csv("vuelos_bcn_s1.csv") # GUARDAR EN CSV

## **SEMANA 2 :**

In [148]:
df_23 = df_por_fecha['23/11/2025 15-34-22'].copy()
df_23.head(88)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
852,NaN,23/11/2025 15-34-22,Ryanair,FR3180,Rome (FCO),06:00,Ha salido,NaN,NaN,U34
853,NaN,23/11/2025 15-34-22,Ryanair,FR2834,Charleroi (CRL),06:10,Ha salido,NaN,NaN,S20
854,NaN,23/11/2025 15-34-22,Ryanair,FR2918,Brussels (BRU),06:25,Ha salido,NaN,NaN,R12
855,NaN,23/11/2025 15-34-22,Ryanair,FR4084,Warsaw (WMI),06:25,"Retrasado, Ha salido",NaN,NaN,S21
856,NaN,23/11/2025 15-34-22,Ryanair,FR2239,Marrakech (RAK),06:30,Ha salido,NaN,B738,W46
...,...,...,...,...,...,...,...,...,...,...
935,NaN,23/11/2025 15-34-22,easyJet Europe,EC7694,Lisbon (LIS),15:20,"Retrasado, Ha salido 15:25",NaN,NaN,U36
936,NaN,23/11/2025 15-34-22,Ryanair,FR6973,Rome (FCO),15:30,"Retrasado, Ha salido 15:40",NaN,NaN,R10
937,NaN,23/11/2025 15-34-22,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"En hora, Ha salido",NaN,NaN,S20
938,NaN,23/11/2025 15-34-22,Wizz Air Malta,W46728,Venice (VCE),15:40,"En hora, Ha salido",NaN,NaN,Y55
939,NaN,23/11/2025 15-34-22,Ryanair,FR133,Berlin (BER),16:15,"En hora, Ha salido",NaN,NaN,U34

In [149]:
df_23.loc[929:983]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
929,NaN,23/11/2025 15-34-22,Ryanair,FR269,Milan (MXP),14:55,"Retrasado, Ha salido",NaN,NaN,S25
930,NaN,23/11/2025 15-34-22,SmartWings,QS1059,Prague (PRG),14:55,Ha salido,NaN,NaN,U35
931,NaN,23/11/2025 15-34-22,Ryanair,FR3320,Milan (BGY),15:00,Ha salido,NaN,NaN,R14
932,NaN,23/11/2025 15-34-22,Ryanair,FR774,Torino (TRN),15:15,"En hora, Ha salido",NaN,NaN,R14
933,NaN,23/11/2025 15-34-22,BUZZ,RR3072,Prague (PRG),15:15,"Retrasado, Ha salido 15:30",NaN,NaN,U33
934,NaN,23/11/2025 15-34-22,Transavia,TO4755,Paris (ORY),15:15,"En hora, Ha salido",NaN,NaN,S21
935,NaN,23/11/2025 15-34-22,easyJet Europe,EC7694,Lisbon (LIS),15:20,"Retrasado, Ha salido 15:25",NaN,NaN,U36
936,NaN,23/11/2025 15-34-22,Ryanair,FR6973,Rome (FCO),15:30,"Retrasado, Ha salido 15:40",NaN,NaN,R10
937,NaN,23/11/2025 15-34-22,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"En hora, Ha salido",NaN,NaN,S20
938,NaN,23/11/2025 15-34-22,Wizz Air Malta,W46728,Venice (VCE),15:40,"En hora, Ha salido",NaN,NaN,Y55
939,NaN,23/11/2025 15-34-22,Ryanair,FR133,Berlin (BER),16:15,"En hora, Ha salido",NaN,NaN,U34
940,NaN,23/11/2025 15-34-22,Ryanair,FR2922,Brussels (BRU),16:15,"En hora, Ha salido",NaN,NaN,U31
941,NaN,23/11/2025 15-34-22,easyJet Europe,EC7173,Berlin (BER),16:30,"Retrasado, Ha salido 16:30",NaN,NaN,U32
942,NaN,23/11/2025 15-34-22,Ryanair,FR9814,London (STN),16:40,"En hora, Ha salido",NaN,NaN,R11
943,NaN,23/11/2025 15-34-22,Ryanair,FR8669,Dublin (DUB),16:55,"Retrasado, Ha salido 17:10",NaN,NaN,W42
944,NaN,23/11/2025 15-34-22,Air Arabia Maroc,3O374,Casablanca (CMN),17:00,"En hora, Ha salido",NaN,B738,W45
945,NaN,23/11/2025 15-34-22,Ryanair,FR2250,Marrakech (RAK),17:00,"Retrasado, Ha salido 17:14",NaN,NaN,W46
946,NaN,23/11/2025 15-34-22,BUZZ,RR8394,Budapest (BUD),17:15,"Retrasado, Ha salido 17:20",NaN,NaN,Y55
947,NaN,23/11/2025 15-34-22,Ryanair,FR5718,Bratislava (BTS),17:20,"Retrasado, Ha salido 17:32",NaN,NaN,S21
948,NaN,23/11/2025 15-34-22,Ryanair,FR12,Vienna (VIE),17:40,"Retrasado, Ha salido 17:31",NaN,NaN,S22
949,NaN,23/11/2025 15-34-22,Volotea,V73573,Asturias (OVD),17:40,"En hora, Ha salido",NaN,B738,U34
950,NaN,23/11/2025 15-34-22,BUZZ,RR5252,Krakow (KRK),17:50,"En hora, Ha salido",NaN,NaN,S25
951,NaN,23/11/2025 15-34-22,Ryanair,FR1681,Frankfurt-Hahn (HHN),18:00,"Retrasado, Ha salido 21:04",NaN,NaN,R9
952,NaN,23/11/2025 15-34-22,Ryanair,FR777,Venice (VCE),18:00,"En hora, Ha salido",NaN,NaN,R10
953,NaN,23/11/2025 15-34-22,Ryanair,FR6305,Milan (BGY),18:05,"En hora, Ha salido",NaN,NaN,U37
954,NaN,23/11/2025 15-34-22,easyJet Europe,EC7109,Geneva (GVA),18:15,"En hora, Ha salido",NaN,NaN,S20
955,NaN,23/11/2025 15-34-22,Volotea,V73700,Vitoria (VIT),18:20,"En hora, Ha salido",NaN,NaN,R15
956,NaN,23/11/2025 15-34-22,Ryanair,FR2406,NaN,18:30,"En hora, Ha salido",NaN,NaN,S24
957,NaN,23/11/2025 15-34-22,Wizz Air Malta,W43686,Iasi (IAS),18:30,"En hora, Ha salido",NaN,NaN,S26
958,NaN,23/11/2025 15-34-22,Jet2,LS804,Manchester (MAN),18:35,"En hora, Ha salido",NaN,NaN,S23
959,NaN,23/11/2025 15-34-22,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:45,"Retrasado, Ha salido 19:32",NaN,NaN,Y54
960,NaN,23/11/2025 15-34-22,Ryanair,FR8631,Tanger (TNG),18:45,"Retrasado, Ha salido 18:58",NaN,NaN,R11
961,NaN,23/11/2025 15-34-22,Transavia,HV6066,Rotterdam (RTM),18:50,"Retrasado, Ha salido 19:20",NaN,NaN,W42
962,NaN,23/11/2025 15-34-22,Easyjet,U25716,Southend (SEN),18:55,"En hora, Ha salido",NaN,B738,U31
963,NaN,23/11/2025 15-34-22,Wizz Air,W61176,Katowice (KTW),18:55,"Retrasado, Ha salido 19:14",NaN,NaN,M6
964,NaN,23/11/2025 15-34-22,Wizz Air,W61478,Warsaw (WAW),19:00,"En hora, Ha salido",NaN,NaN,U32
965,NaN,23/11/2025 15-34-22,easyJet Europe,EC7159,Milan (LIN),19:05,"Retrasado, Ha salido 19:50",NaN,NaN,U33
966,NaN,23/11/2025 15-34-22,Wizz Air Malta,W43180,Bucharest (OTP),19:05,"En hora, Ha salido",NaN,NaN,R12
967,NaN,23/11/2025 15-34-22,Ryanair,FR6394,Dublin (DUB),19:10,"En hora, Ha salido",NaN,NaN,U35
968,NaN,23/11/2025 15-34-22,Ryanair,FR3160,Bristol (BRS),19:25,"En hora, Ha salido",NaN,NaN,Y57
969,NaN,23/11/2025 15-34-22,Volotea,V72165,Nantes/Atlantique (NTE),19:30,"En hora, Ha salido",NaN,NaN,Y58
970,NaN,23/11/2025 15-34-22,Eurowings,EW9443,Dusseldorf (DUS),19:35,"En hora, Ha salido",NaN,NaN,S25
971,NaN,23/11/2025 15-34-22,Wizz Air,W64406,Sofia (SOF),19:35,"En hora, Ha salido",NaN,A319,U34
972,NaN,23/11/2025 15-34-22,Ryanair,FR2233,Al Aaroui (NDR),19:40,"En hora, Ha salido",NaN,NaN,U36
973,NaN,23/11/2025 15-34-22,easyJet Europe,EC3750,Milan (MXP),19:45,"Retrasado, Ha salido 20:25",NaN,NaN,R13
974,NaN,23/11/2025 15-34-22,Ryanair,FR5710,Napoli (NAP),19:45,"Retrasado, Ha salido 20:23",NaN,NaN,R10
975,NaN,23/11/2025 15-34-22,Ryanair,FR9015,London (STN),19:45,"Retrasado, Ha salido 20:05",NaN,NaN,W49
976,NaN,23/11/2025 15-34-22,Easyjet,U28058,London (LGW),19:45,"En hora, Ha salido",NaN,NaN,M8
977,NaN,23/11/2025 15-34-22,Jet2,LS1338,Birmingham (BHX),19:55,"Retrasado, Programado 01:15",NaN,NaN,W46
978,NaN,23/11/2025 15-34-22,Wizz Air,W64666,Larnaca (LCA),19:55,"Retrasado, Ha salido 20:27",NaN,NaN,W45
979,NaN,23/11/2025 15-34-22,Ryanair,FR8136,Ibiza (IBZ),20:10,"Retrasado, Ha salido 21:08",NaN,NaN,S20
980,NaN,23/11/2025 15-34-22,Wizz Air,W62096,Krakow (KRK),20:10,"Retrasado, Programado 01:44",NaN,NaN,NaN
981,NaN,23/11/2025 15-34-22,easyJet Europe,EC4212,Napoli (NAP),20:20,"En hora, Ha salido",NaN,NaN,R12
982,NaN,23/11/2025 15-34-22,Transavia,HV6788,Eindhoven (EIN),20:20,"Retrasado, Ha salido 20:35",NaN,NaN,S22
983,NaN,23/11/2025 15-34-22,Wizz Air,W67022,Bratislava (BTS),20:20,"En hora, Ha salido",NaN,NaN,S24

In [150]:
# Rango a corregir
start, end = 932, 971

# Reemplazar los valores desplazando hacia arriba dentro del rango
df_23.loc[start:end, 'Gate'] = df_23.loc[start+1:end+1, 'Gate'].values

In [151]:
# 931 s20/  932 - u33  971 - u36 / 973 - w

In [152]:
df_23.loc[930:983]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
930,NaN,23/11/2025 15-34-22,SmartWings,QS1059,Prague (PRG),14:55,Ha salido,NaN,NaN,U35
931,NaN,23/11/2025 15-34-22,Ryanair,FR3320,Milan (BGY),15:00,Ha salido,NaN,NaN,R14
932,NaN,23/11/2025 15-34-22,Ryanair,FR774,Torino (TRN),15:15,"En hora, Ha salido",NaN,NaN,U33
933,NaN,23/11/2025 15-34-22,BUZZ,RR3072,Prague (PRG),15:15,"Retrasado, Ha salido 15:30",NaN,NaN,S21
934,NaN,23/11/2025 15-34-22,Transavia,TO4755,Paris (ORY),15:15,"En hora, Ha salido",NaN,NaN,U36
935,NaN,23/11/2025 15-34-22,easyJet Europe,EC7694,Lisbon (LIS),15:20,"Retrasado, Ha salido 15:25",NaN,NaN,R10
936,NaN,23/11/2025 15-34-22,Ryanair,FR6973,Rome (FCO),15:30,"Retrasado, Ha salido 15:40",NaN,NaN,S20
937,NaN,23/11/2025 15-34-22,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"En hora, Ha salido",NaN,NaN,Y55
938,NaN,23/11/2025 15-34-22,Wizz Air Malta,W46728,Venice (VCE),15:40,"En hora, Ha salido",NaN,NaN,U34
939,NaN,23/11/2025 15-34-22,Ryanair,FR133,Berlin (BER),16:15,"En hora, Ha salido",NaN,NaN,U31
940,NaN,23/11/2025 15-34-22,Ryanair,FR2922,Brussels (BRU),16:15,"En hora, Ha salido",NaN,NaN,U32
941,NaN,23/11/2025 15-34-22,easyJet Europe,EC7173,Berlin (BER),16:30,"Retrasado, Ha salido 16:30",NaN,NaN,R11
942,NaN,23/11/2025 15-34-22,Ryanair,FR9814,London (STN),16:40,"En hora, Ha salido",NaN,NaN,W42
943,NaN,23/11/2025 15-34-22,Ryanair,FR8669,Dublin (DUB),16:55,"Retrasado, Ha salido 17:10",NaN,NaN,W45
944,NaN,23/11/2025 15-34-22,Air Arabia Maroc,3O374,Casablanca (CMN),17:00,"En hora, Ha salido",NaN,B738,W46
945,NaN,23/11/2025 15-34-22,Ryanair,FR2250,Marrakech (RAK),17:00,"Retrasado, Ha salido 17:14",NaN,NaN,Y55
946,NaN,23/11/2025 15-34-22,BUZZ,RR8394,Budapest (BUD),17:15,"Retrasado, Ha salido 17:20",NaN,NaN,S21
947,NaN,23/11/2025 15-34-22,Ryanair,FR5718,Bratislava (BTS),17:20,"Retrasado, Ha salido 17:32",NaN,NaN,S22
948,NaN,23/11/2025 15-34-22,Ryanair,FR12,Vienna (VIE),17:40,"Retrasado, Ha salido 17:31",NaN,NaN,U34
949,NaN,23/11/2025 15-34-22,Volotea,V73573,Asturias (OVD),17:40,"En hora, Ha salido",NaN,B738,S25
950,NaN,23/11/2025 15-34-22,BUZZ,RR5252,Krakow (KRK),17:50,"En hora, Ha salido",NaN,NaN,R9
951,NaN,23/11/2025 15-34-22,Ryanair,FR1681,Frankfurt-Hahn (HHN),18:00,"Retrasado, Ha salido 21:04",NaN,NaN,R10
952,NaN,23/11/2025 15-34-22,Ryanair,FR777,Venice (VCE),18:00,"En hora, Ha salido",NaN,NaN,U37
953,NaN,23/11/2025 15-34-22,Ryanair,FR6305,Milan (BGY),18:05,"En hora, Ha salido",NaN,NaN,S20
954,NaN,23/11/2025 15-34-22,easyJet Europe,EC7109,Geneva (GVA),18:15,"En hora, Ha salido",NaN,NaN,R15
955,NaN,23/11/2025 15-34-22,Volotea,V73700,Vitoria (VIT),18:20,"En hora, Ha salido",NaN,NaN,S24
956,NaN,23/11/2025 15-34-22,Ryanair,FR2406,NaN,18:30,"En hora, Ha salido",NaN,NaN,S26
957,NaN,23/11/2025 15-34-22,Wizz Air Malta,W43686,Iasi (IAS),18:30,"En hora, Ha salido",NaN,NaN,S23
958,NaN,23/11/2025 15-34-22,Jet2,LS804,Manchester (MAN),18:35,"En hora, Ha salido",NaN,NaN,Y54
959,NaN,23/11/2025 15-34-22,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:45,"Retrasado, Ha salido 19:32",NaN,NaN,R11
960,NaN,23/11/2025 15-34-22,Ryanair,FR8631,Tanger (TNG),18:45,"Retrasado, Ha salido 18:58",NaN,NaN,W42
961,NaN,23/11/2025 15-34-22,Transavia,HV6066,Rotterdam (RTM),18:50,"Retrasado, Ha salido 19:20",NaN,NaN,U31
962,NaN,23/11/2025 15-34-22,Easyjet,U25716,Southend (SEN),18:55,"En hora, Ha salido",NaN,B738,M6
963,NaN,23/11/2025 15-34-22,Wizz Air,W61176,Katowice (KTW),18:55,"Retrasado, Ha salido 19:14",NaN,NaN,U32
964,NaN,23/11/2025 15-34-22,Wizz Air,W61478,Warsaw (WAW),19:00,"En hora, Ha salido",NaN,NaN,U33
965,NaN,23/11/2025 15-34-22,easyJet Europe,EC7159,Milan (LIN),19:05,"Retrasado, Ha salido 19:50",NaN,NaN,R12
966,NaN,23/11/2025 15-34-22,Wizz Air Malta,W43180,Bucharest (OTP),19:05,"En hora, Ha salido",NaN,NaN,U35
967,NaN,23/11/2025 15-34-22,Ryanair,FR6394,Dublin (DUB),19:10,"En hora, Ha salido",NaN,NaN,Y57
968,NaN,23/11/2025 15-34-22,Ryanair,FR3160,Bristol (BRS),19:25,"En hora, Ha salido",NaN,NaN,Y58
969,NaN,23/11/2025 15-34-22,Volotea,V72165,Nantes/Atlantique (NTE),19:30,"En hora, Ha salido",NaN,NaN,S25
970,NaN,23/11/2025 15-34-22,Eurowings,EW9443,Dusseldorf (DUS),19:35,"En hora, Ha salido",NaN,NaN,U34
971,NaN,23/11/2025 15-34-22,Wizz Air,W64406,Sofia (SOF),19:35,"En hora, Ha salido",NaN,A319,U36
972,NaN,23/11/2025 15-34-22,Ryanair,FR2233,Al Aaroui (NDR),19:40,"En hora, Ha salido",NaN,NaN,U36
973,NaN,23/11/2025 15-34-22,easyJet Europe,EC3750,Milan (MXP),19:45,"Retrasado, Ha salido 20:25",NaN,NaN,R13
974,NaN,23/11/2025 15-34-22,Ryanair,FR5710,Napoli (NAP),19:45,"Retrasado, Ha salido 20:23",NaN,NaN,R10
975,NaN,23/11/2025 15-34-22,Ryanair,FR9015,London (STN),19:45,"Retrasado, Ha salido 20:05",NaN,NaN,W49
976,NaN,23/11/2025 15-34-22,Easyjet,U28058,London (LGW),19:45,"En hora, Ha salido",NaN,NaN,M8
977,NaN,23/11/2025 15-34-22,Jet2,LS1338,Birmingham (BHX),19:55,"Retrasado, Programado 01:15",NaN,NaN,W46
978,NaN,23/11/2025 15-34-22,Wizz Air,W64666,Larnaca (LCA),19:55,"Retrasado, Ha salido 20:27",NaN,NaN,W45
979,NaN,23/11/2025 15-34-22,Ryanair,FR8136,Ibiza (IBZ),20:10,"Retrasado, Ha salido 21:08",NaN,NaN,S20
980,NaN,23/11/2025 15-34-22,Wizz Air,W62096,Krakow (KRK),20:10,"Retrasado, Programado 01:44",NaN,NaN,NaN
981,NaN,23/11/2025 15-34-22,easyJet Europe,EC4212,Napoli (NAP),20:20,"En hora, Ha salido",NaN,NaN,R12
982,NaN,23/11/2025 15-34-22,Transavia,HV6788,Eindhoven (EIN),20:20,"Retrasado, Ha salido 20:35",NaN,NaN,S22
983,NaN,23/11/2025 15-34-22,Wizz Air,W67022,Bratislava (BTS),20:20,"En hora, Ha salido",NaN,NaN,S24

In [153]:
df_23[(df_23['Num_flight'] == '3O378')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
937,NaN,23/11/2025 15-34-22,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"En hora, Ha salido",NaN,NaN,Y55

In [154]:
df_23.loc[df_23['Num_flight'] == 'FR2233', 'Gate'] = 'W'

In [155]:
df_23[df_23['Name_Destiny'].isna()].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
862,NaN,23/11/2025 15-34-22,Ryanair,FR1165,NaN,07:50,Ha salido,NaN,NaN,S24
868,NaN,23/11/2025 15-34-22,Volotea,V73735,NaN,08:40,"Retrasado, Ha salido",NaN,NaN,U35
883,NaN,23/11/2025 15-34-22,Ryanair,FR2495,NaN,09:50,Ha salido,NaN,NaN,R14
902,NaN,23/11/2025 15-34-22,Lauda Europe,LW2889,NaN,11:55,Ha salido,NaN,NaN,R14
906,NaN,23/11/2025 15-34-22,Ryanair,FR2402,NaN,12:30,"Retrasado, Ha salido",NaN,NaN,S25
918,NaN,23/11/2025 15-34-22,Ryanair,FR483,NaN,13:50,Ha salido,NaN,NaN,R13
921,NaN,23/11/2025 15-34-22,Ryanair,FR1342,NaN,14:05,"Retrasado, Ha salido",NaN,NaN,S23
956,NaN,23/11/2025 15-34-22,Ryanair,FR2406,NaN,18:30,"En hora, Ha salido",NaN,NaN,S26
1000,NaN,23/11/2025 15-34-22,Ryanair,FR2896,NaN,21:15,"Retrasado, Ha salido 22:01",NaN,NaN,R14

In [156]:
df_23.loc[df_23['Num_flight'] == 'V73735', 'Name_Destiny'] = 'Murcia (RMU)'
df_23.loc[df_23['Num_flight'] == 'FR2495', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'
df_23.loc[df_23['Num_flight'] == 'LW2889', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'
df_23.loc[df_23['Num_flight'] == 'FR2402', 'Name_Destiny'] = 'Sevilla (SVQ)'
df_23.loc[df_23['Num_flight'] == 'FR1342', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'
df_23.loc[df_23['Num_flight'] == 'FR2896', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'

In [157]:
df_23.loc[df_23['Num_flight'] == 'BZ251', 'Gate'] = 'Y'
#df_23.loc[df_23['Num_flight'] == 'W62096', 'Gate'] = 'Y'

In [158]:
df_23.loc[df_23['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR9406', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W61706', 'flight_capacity'] = 239

In [159]:
#df_23.loc[df_23['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'
#df_23.loc[df_23['Num_flight'] == 'W45154', 'flight_capacity'] = 230
df_23.loc[df_23['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR5220', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321'
df_23.loc[df_23['Num_flight'] == 'W64116', 'flight_capacity'] = 230

df_23.loc[df_23['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'U22706', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'U22706', 'flight_capacity'] = 186

df_23.loc[df_23['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'U28060', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'U28060', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'W43406', 'flight_capacity'] = 180

In [160]:
df_23 = df_23.drop([873]) # AVION DE CARGO

In [161]:
df_23 = df_23.drop([985])  # AVION DE CARGO

In [162]:
df_23.loc[df_23['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_23.loc[df_23['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_23.loc[df_23['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR2896', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2896', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'EI565', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'RR8615', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'RR8615', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W64738', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W64738', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'U22326', 'flight_capacity'] = 186

In [163]:
df_23.loc[df_23['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'RR6944', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'HV5134', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR6275', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_23.loc[df_23['Num_flight'] == 'LG3596', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'LG3596', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR4587', 'flight_capacity'] = 189

In [164]:
df_23.loc[df_23['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'EW2521', 'flight_capacity'] = 186

df_23.loc[df_23['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'D83659', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'JU585', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR6985', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

In [165]:
df_23.loc[df_23['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W62096', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'FR8136', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR8136', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
df_23.loc[df_23['Num_flight'] == 'W64666', 'flight_capacity'] = 230

df_23.loc[df_23['Num_flight'] == 'LS1338', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'LS1338', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'U28058', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR9015', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR5710', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC3750', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'EC3750', 'flight_capacity'] = 180

In [166]:
df_23.loc[df_23['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EW9443', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'V72165', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR3160', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3160', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_23.loc[df_23['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_23.loc[df_23['Num_flight'] == 'EC7159', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7159', 'flight_capacity'] = 156

In [167]:
df_23.loc[df_23['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'W61176', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'U25716', 'flight_capacity'] = 186

df_23.loc[df_23['Num_flight'] == 'HV6066', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'HV6066', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR8631', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'W43686', 'flight_capacity'] = 180

In [168]:
df_23.loc[df_23['Num_flight'] == 'FR2406', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2406', 'flight_capacity'] = 189
df_23.loc[df_23['Num_flight'] == 'FR2406', 'Name_Destiny'] = 'Sevilla (SVQ)'

df_23.loc[df_23['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'EC7109', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7109', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR6305', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR777', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'RR5252', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'RR5252', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'V73573', 'flight_capacity'] = 156

In [169]:
df_23.loc[df_23['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR12', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'RR8394', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2250', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == '3O374', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == '3O374', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR8669', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR9814', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR9814', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

In [170]:
df_23.loc[df_23['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2922', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == '3O378', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR6973', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'EC7694', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'EC7694', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_23.loc[df_23['Num_flight'] == 'RR3072', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'RR3072', 'flight_capacity'] = 189

In [171]:
df_23.loc[df_23['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'QS1059', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'BZ251', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'BZ251', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'HV5132', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'HV5132', 'flight_capacity'] = 189

In [172]:
df_23.loc[df_23['Num_flight'] == 'XQ895', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'XQ895', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR6920', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_23.loc[df_23['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_23.loc[df_23['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR483', 'flight_capacity'] = 189
df_23.loc[df_23['Num_flight'] == 'FR483', 'Name_Destiny'] = 'Malaga (AGP)'

df_23.loc[df_23['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR9811', 'flight_capacity'] = 189

In [173]:
df_23.loc[df_23['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W46330', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'V71445', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'V71445', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'FR8598', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR8598', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR2511', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2511', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_23.loc[df_23['Num_flight'] == 'PC1092', 'flight_capacity'] = 230

In [174]:
df_23.loc[df_23['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'V72167', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'V72167', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2402', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR1527', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR3976', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'LW2889', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'LW2889', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FI597', 'flight_capacity'] = 197

In [175]:
df_23.loc[df_23['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320neo'
df_23.loc[df_23['Num_flight'] == 'EI563', 'flight_capacity'] = 186

df_23.loc[df_23['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'D81741', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'J246', 'flight_capacity'] = 122

df_23.loc[df_23['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR3143', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR1279', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR7543', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR7543', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR575', 'flight_capacity'] = 189

In [176]:
df_23.loc[df_23['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR6874', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'RR3049', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR2495', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2495', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'RR8384', 'flight_capacity'] = 197

In [177]:
df_23.loc[df_23['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'RR333', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_23.loc[df_23['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_23.loc[df_23['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W45088', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EW7521', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'RR3193', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'RR3193', 'flight_capacity'] = 189

In [178]:
df_23.loc[df_23['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_23.loc[df_23['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_23.loc[df_23['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR3028', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'RR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'RR1786', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'V73735', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR878', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC3754', 'Aircraft'] = 'Airbus A320'
df_23.loc[df_23['Num_flight'] == 'EC3754', 'flight_capacity'] = 180

df_23.loc[df_23['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'D85510', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR1165', 'flight_capacity'] = 189
df_23.loc[df_23['Num_flight'] == 'FR1165', 'Name_Destiny'] = 'Sevilla (SVQ)'

In [179]:
df_23.loc[df_23['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3108', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR6597', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'EC7191', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7191', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_23.loc[df_23['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_23.loc[df_23['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR4084', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR4084', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_23.loc[df_23['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
df_23.loc[df_23['Num_flight'] == 'FR2834', 'flight_capacity'] = 197

df_23.loc[df_23['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_23.loc[df_23['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

In [180]:
df_23.isna().sum()

Unnamed: 0         160
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity      2
Aircraft             2
Gate                 1
dtype: int64

In [181]:
df_23['flight_capacity'].unique()

array([189., 197., 156., 180., 239., 230., 122., 186.,  nan, 148.])

In [182]:
df_23['Aircraft'].unique()

array(['Boeing 737-800', 'Boeing 737 MAX 8', 'Airbus A319', 'Airbus A320',
       'Airbus A321neo', 'Airbus A321', 'Airbus A320neo', nan,
       'Airbus A220-300'], dtype=object)

In [183]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A319') & 
(df_23['Name_company'] == 'Eurowings'),
'flight_capacity'
] = 150   # si es eurowings y tiene ese tipo de avion ponerle estas capacidades

In [184]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A320') & 
(df_23['Name_company'] == 'Eurowings'),
'flight_capacity'
] = 180   # si es eurowings y tiene ese tipo de avion ponerle estas capacidades

In [185]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A320') & 
(df_23['Name_company'] == 'Air Arabia Maroc'),
'flight_capacity'
] = 174   # si es eurowings y tiene ese tipo de avion ponerle estas capacidades

In [186]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A320') & 
(df_23['Name_company'] == 'Aer Lingus'),
'flight_capacity'
] = 174   # si es eurowings y tiene ese tipo de avion ponerle estas capacidades

In [187]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A319') & 
(df_23['Name_company'] == 'Air Serbia'),
'flight_capacity'
] = 144   # si es airserbia y tiene ese tipo de avion ponerle estas capacidades

In [188]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A321') & 
(df_23['Name_company'] == 'Pegasus Airlines'),
'flight_capacity'
] = 220   # si es airserbia y tiene ese tipo de avion ponerle estas capacidades

In [189]:
df_23.loc[
(df_23['Aircraft'] == 'Airbus A321neo') & 
(df_23['Name_company'] == 'Jet2'),
'flight_capacity'
] = 232  # si es airserbia y tiene ese tipo de avion ponerle estas capacidades

In [190]:
df_23[(df_23['Aircraft'] == 'Airbus A220-300')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
919,NaN,23/11/2025 15-34-22,Air Baltic,BT684,Riga (RIX),14:05,Ha salido,148.0,Airbus A220-300,S24

In [191]:
df_por_fecha['23/11/2025 15-34-22'] = df_23.copy()

In [192]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [193]:
df_semanac = pd.concat([df_semana1, df_23], ignore_index=True)

In [194]:
df_semanac.to_csv("vuelos_bcn_s1.csv") # GUARDAR EN CSV

In [195]:
df_24 = df_por_fecha['24/Nov/2025'].copy()
df_24.tail(40)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1140,NaN,24/Nov/2025,Ryanair,FR133,Berlin (BER),19:45,"En hora, Ha salido",NaN,NaN,R12
1141,NaN,24/Nov/2025,Lauda Europe,LW7351,Vienna (VIE),19:45,"Retrasado, Ha salido 20:05",NaN,NaN,S22
1142,NaN,24/Nov/2025,Easyjet,U28058,London (LGW),19:45,"En hora, Ha salido",NaN,NaN,M6
1143,NaN,24/Nov/2025,Volotea,V71415,Verona (VRN),19:55,"En hora, Ha salido",NaN,NaN,U33
1144,NaN,24/Nov/2025,Wizz Air,W64666,Larnaca (LCA),19:55,"En hora, Ha salido",NaN,A321,W45
1145,NaN,24/Nov/2025,Ryanair,FR3080,NaN,20:00,"En hora, Ha salido",NaN,NaN,S24
1146,NaN,24/Nov/2025,Air Arabia Maroc,3O378,Tanger (TNG),20:05,"En hora, Ha salido",NaN,NaN,Y54
1147,NaN,24/Nov/2025,Ryanair,FR3807,Charleroi (CRL),20:05,"Retrasado, Ha salido 20:39",NaN,NaN,U36
1148,NaN,24/Nov/2025,Ryanair,FR6341,Rome (FCO),20:10,"En hora, Ha salido",NaN,NaN,U34
1149,NaN,24/Nov/2025,Ryanair,FR6597,Manchester (MAN),20:10,"En hora, Ha salido",NaN,NaN,Y58
1150,NaN,24/Nov/2025,easyJet Europe,EC1956,Milan (LIN),20:15,"Retrasado, Ha salido 20:31",NaN,NaN,R10
1151,NaN,24/Nov/2025,Wizz Air Malta,W42940,Vienna (VIE),20:20,"En hora, Ha salido",NaN,NaN,S23
1152,NaN,24/Nov/2025,easyJet Europe,EC1010,"Basel, Switzerland/Mulhouse (BSL)",20:30,"En hora, Ha salido",NaN,NaN,R13
1153,NaN,24/Nov/2025,T'Way Air,TW408,Seoul/Incheon (ICN),20:30,"Retrasado, Ha salido 21:33",NaN,NaN,W44
1154,NaN,24/Nov/2025,Volotea,V72135,Bordeaux (BOD),20:30,"En hora, Ha salido",NaN,NaN,U35
1155,NaN,24/Nov/2025,Ryanair,FR5710,Napoli (NAP),20:40,"Retrasado, Ha salido 21:12",NaN,NaN,U31
1156,NaN,24/Nov/2025,BUZZ,RR8394,Budapest (BUD),20:40,"Retrasado, Ha salido 21:25",NaN,NaN,U34
1157,NaN,24/Nov/2025,Transavia,TO4759,Paris (ORY),20:45,"En hora, Ha salido",NaN,NaN,S20
1158,NaN,24/Nov/2025,Wizz Air,W62378,Budapest (BUD),20:45,"Retrasado, Ha salido 21:10",NaN,NaN,S21
1159,NaN,24/Nov/2025,Ryanair,FR2098,Bologna (BLQ),20:50,"Retrasado, Ha salido 21:43",NaN,NaN,R14
1160,NaN,24/Nov/2025,Ryanair,FR3928,Trieste (TRS),20:50,"En hora, Ha salido",NaN,NaN,U32
1161,NaN,24/Nov/2025,Volotea,V72165,Nantes/Atlantique (NTE),20:50,"Retrasado, Ha salido 21:24",NaN,NaN,S25
1162,NaN,24/Nov/2025,Ryanair,FR878,Venice (VCE),20:55,"Retrasado, Ha salido 21:16",NaN,NaN,U33
1163,NaN,24/Nov/2025,Aer Lingus,EI565,Dublin (DUB),21:05,"En hora, Ha salido",NaN,NaN,W46
1164,NaN,24/Nov/2025,Ryanair,FR6275,Edinburgh (EDI),21:05,"Retrasado, Ha salido 21:25",NaN,NaN,Y55
1165,NaN,24/Nov/2025,Ryanair,FR6920,Dublin (DUB),21:10,"Retrasado, Ha salido 21:54",NaN,NaN,W42
1166,NaN,24/Nov/2025,easyJet Europe,EC1380,Geneva (GVA),21:20,"Retrasado, Ha salido 21:32",NaN,NaN,R12
1167,NaN,24/Nov/2025,Wizz Air Malta,W43178,Bucharest (BBU),21:20,"Retrasado, Ha salido 21:31",NaN,NaN,S22
1168,NaN,24/Nov/2025,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"Retrasado, Ha salido 21:55",NaN,NaN,S24
1169,NaN,24/Nov/2025,Ryanair,FR2402,NaN,21:30,"Retrasado, Ha salido 22:10",NaN,NaN,R9
1170,NaN,24/Nov/2025,BUZZ,RR4084,Warsaw (WMI),21:30,"Retrasado, Ha salido 21:53",NaN,NaN,U36
1171,NaN,24/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"Retrasado, Ha salido 22:49",NaN,NaN,S23
1172,NaN,24/Nov/2025,Ryanair,FR3168,Newcastle (NCL),21:45,"En hora, Ha salido",NaN,NaN,Y54
1173,NaN,24/Nov/2025,Ryanair,FR4587,Porto (OPO),21:45,"En hora, Ha salido",NaN,NaN,U35
1174,NaN,24/Nov/2025,Ryanair,FR1527,Valletta (MLA),21:50,"Retrasado, Ha salido 22:07",NaN,NaN,S21
1175,NaN,24/Nov/2025,Ryanair,FR2250,Marrakech (RAK),21:50,"Retrasado, Ha salido 22:00",NaN,NaN,Y58
1176,NaN,24/Nov/2025,Easyjet,U22706,Bristol (BRS),21:55,"En hora, Ha salido",NaN,NaN,M6
1177,NaN,24/Nov/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"Retrasado, Ha salido 22:10",NaN,NaN,W45
1178,NaN,24/Nov/2025,Ryanair,FR8574,Rome (FCO),22:20,"En hora, Ha salido",NaN,NaN,U32
1179,NaN,24/Nov/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,W44

In [196]:
df_24.isna().sum()

Unnamed: 0         166
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         8
Time_flight          0
flight_state         0
flight_capacity    166
Aircraft           147
Gate                 3
dtype: int64

In [197]:
df_24[(df_24['Name_Destiny'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1026,NaN,24/Nov/2025,Lauda Europe,LW1342,NaN,07:40,"En hora, Ha salido",NaN,NaN,R14
1027,NaN,24/Nov/2025,Ryanair,FR1165,NaN,07:55,"En hora, Ha salido",NaN,NaN,S20
1046,NaN,24/Nov/2025,Ryanair,FR2495,NaN,09:45,"En hora, Ha salido",NaN,NaN,R14
1095,NaN,24/Nov/2025,Ryanair,FR2889,NaN,14:05,"En hora, Programado",NaN,NaN,S21
1111,NaN,24/Nov/2025,Volotea,V73735,NaN,16:35,"En hora, Ha salido",NaN,NaN,S20
1138,NaN,24/Nov/2025,Lauda Europe,LW2896,NaN,19:40,"Retrasado, Ha salido 20:09",NaN,NaN,R14
1145,NaN,24/Nov/2025,Ryanair,FR3080,NaN,20:00,"En hora, Ha salido",NaN,NaN,S24
1169,NaN,24/Nov/2025,Ryanair,FR2402,NaN,21:30,"Retrasado, Ha salido 22:10",NaN,NaN,R9

In [198]:
df_24.loc[df_24['Num_flight'] == 'LW1342', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'
df_24.loc[df_24['Num_flight'] == 'FR1165', 'Name_Destiny'] =  'Sevilla (SVQ)'
df_24.loc[df_24['Num_flight'] == 'FR2889', 'Name_Destiny'] =  'Palma de Mallorca (PMI)'
df_24.loc[df_24['Num_flight'] == 'LW2896', 'Name_Destiny'] = 'Palma de Mallorca (PMI)'

In [199]:
df_24[(df_24['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1014,NaN,24/Nov/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,U36
1015,NaN,24/Nov/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",NaN,NaN,S21
1016,NaN,24/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",NaN,NaN,R11
1017,NaN,24/Nov/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",NaN,NaN,W44
1018,NaN,24/Nov/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",NaN,B38M,S24
1019,NaN,24/Nov/2025,Ryanair,FR3078,Lisbon (LIS),06:30,"En hora, Ha salido",NaN,NaN,U35
1020,NaN,24/Nov/2025,easyJet Europe,EC8062,London (LGW),06:45,"En hora, Ha salido",NaN,NaN,M8
1021,NaN,24/Nov/2025,Ryanair,FR3035,Krakow (KRK),06:45,"Retrasado, Ha salido 07:00",NaN,NaN,U32
1022,NaN,24/Nov/2025,Ryanair,FR8215,London (STN),06:45,"En hora, Ha salido",NaN,NaN,Y55
1023,NaN,24/Nov/2025,easyJet Europe,EC7141,Strasbourg (SXB),07:20,"En hora, Ha salido",NaN,NaN,R10

In [200]:
df_24.loc[df_24['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W45154', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'FR8574', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR8574', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'W64116', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'U22706', 'Aircraft'] = 'Airbus A320neo'
df_24.loc[df_24['Num_flight'] == 'U22706', 'flight_capacity'] =  186

In [201]:
df_24.loc[df_24['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2250', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR1527', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR4587', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'FR3168', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3168', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W46020', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'RR4084', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2402', 'flight_capacity'] =  189
df_24.loc[df_24['Num_flight'] == 'FR2402', 'Name_Destiny'] =  'Sevilla (SVQ)'

df_24.loc[df_24['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320neo'
df_24.loc[df_24['Num_flight'] == 'W43406', 'flight_capacity'] =  186

df_24.loc[df_24['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W43178', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EC1380', 'flight_capacity'] =  180

In [202]:
df_24.loc[df_24['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR6920', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR6275', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EI565', 'flight_capacity'] =  174

df_24.loc[df_24['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR878', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'V72165', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3928', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2098', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W62378', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_24.loc[df_24['Num_flight'] == 'TO4759', 'flight_capacity'] =  186

df_24.loc[df_24['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'RR8394', 'flight_capacity'] =  197

In [203]:
df_24.loc[df_24['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR5710', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'V72135', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'V72135', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'TW408', 'Aircraft'] = 'Airbus A330-200'
df_24.loc[df_24['Num_flight'] == 'TW408', 'flight_capacity'] =  246

df_24.loc[df_24['Num_flight'] == 'EC1010', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC1010', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W42940', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EC1956', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR6597', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR6341', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR3807', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'FR3080', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3080', 'flight_capacity'] =  189
df_24.loc[df_24['Num_flight'] == 'FR3080', 'Name_Destiny'] =  'Malaga (AGP)'

In [204]:
df_24.loc[df_24['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'W64666', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'V71415', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'U28058', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'LW7351', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR133', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'W61706', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'LW2896', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'LW2896', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'EW7521', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR8231', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR9307', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR9307', 'flight_capacity'] =  189

In [205]:
df_24.loc[df_24['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3185', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W61478', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3174', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'W43686', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR3320', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'EC7205', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7205', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR269', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'RR333', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'HV5134', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'EC7199', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7199', 'flight_capacity'] =  156

In [206]:
df_24.loc[df_24['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EC3737', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2922', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR1786', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W67920', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'V73700', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7173', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'RR6300', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR5270', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'U23372', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'U23372', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'RR6874', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'RR6874', 'flight_capacity'] =  189

In [207]:
df_24.loc[df_24['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR6305', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR5718', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR2507', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'V73735', 'flight_capacity'] =  180
df_24.loc[df_24['Num_flight'] == 'V73735', 'Name_Destiny'] =  'Murcia (RMU)'

df_24.loc[df_24['Num_flight'] == 'W43564', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'W43564', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR9811', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR867', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'PC1094', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W46728', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR1681', 'flight_capacity'] =  189

In [208]:
df_24.loc[df_24['Num_flight'] == 'FR3146', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3146', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'QS1059', 'flight_capacity'] =  189
df_24.loc[df_24['Num_flight'] == 'QS1059', 'Gate'] =  'U'

df_24.loc[df_24['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EC4212', 'flight_capacity'] =  180
df_24.loc[df_24['Num_flight'] == 'EC4212', 'Gate'] =  'R'

df_24.loc[df_24['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'W64406', 'flight_capacity'] =  180
df_24.loc[df_24['Num_flight'] == 'W64406', 'Gate'] =  'U'

df_24.loc[df_24['Num_flight'] == 'V71443', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'V71443', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7107', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'BZ251', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'D85502', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR2889', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2889', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_24.loc[df_24['Num_flight'] == 'BT684', 'flight_capacity'] =  148

In [209]:
df_24.loc[df_24['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3792', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'LS804', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3189', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'TK608', 'flight_capacity'] =  165

df_24.loc[df_24['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR4585', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7153', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'
df_24.loc[df_24['Num_flight'] == 'LG3592', 'flight_capacity'] =  76

df_24.loc[df_24['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'PC1528', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EW521', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'D81741', 'flight_capacity'] =  189

In [210]:
df_24.loc[df_24['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'H4264', 'flight_capacity'] =  186

df_24.loc[df_24['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR8631', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W46330', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR3108', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W67022', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'EC7137', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7137', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'D83657', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'PC1092', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR774', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR6973', 'flight_capacity'] =  197

In [211]:
df_24.loc[df_24['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3129', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'LS232', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'LS232', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR8217', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR777', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'EC7197', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7197', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR1279', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'TO4755', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'TO4755', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR7539', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EI563', 'flight_capacity'] =  174

df_24.loc[df_24['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'U22002', 'flight_capacity'] =  180

In [212]:
df_24.loc[df_24['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR9045', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3039', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3976', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3121', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2239', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'U28056', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7131', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR7808', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'U22324', 'Aircraft'] = 'Airbus A320neo'
df_24.loc[df_24['Num_flight'] == 'U22324', 'flight_capacity'] =  186

df_24.loc[df_24['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3143', 'flight_capacity'] =  189

In [213]:
df_24.loc[df_24['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W61476', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'FR6559', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR6559', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W46018', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'HV5132', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'HV5132', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'EC7656', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'JU581', 'flight_capacity'] =  144

df_24.loc[df_24['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR4545', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR2495', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2495', 'flight_capacity'] =  189
df_24.loc[df_24['Num_flight'] == 'FR2495', 'Name_Destiny'] =  'Palma de Mallorca (PMI)'

df_24.loc[df_24['Num_flight'] == 'EW9441', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EW9441', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'HV6062', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'HV6062', 'flight_capacity'] =  189

In [214]:
df_24.loc[df_24['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2834', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EC1030', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'EC1030', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'V73573', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W62376', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W45088', 'flight_capacity'] =  239

df_24.loc[df_24['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_24.loc[df_24['Num_flight'] == 'W43176', 'flight_capacity'] =  230

df_24.loc[df_24['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EW2521', 'flight_capacity'] =  156

df_24.loc[df_24['Name_company'] == 'Air Arabia Maroc', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] =  174

df_24.loc[df_24['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'V72327', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_24.loc[df_24['Num_flight'] == 'W62048', 'flight_capacity'] =  239

In [215]:
df_24.loc[df_24['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR1165', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR6078', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR6078', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'LW12', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC1376', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR575', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR58', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'D85510', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'LW1342', 'Aircraft'] = 'Airbus A320'
df_24.loc[df_24['Num_flight'] == 'LW1342', 'flight_capacity'] =  180

df_24.loc[df_24['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3028', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7151', 'flight_capacity'] =  156

In [216]:
df_24.loc[df_24['Num_flight'] == 'EC7141', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7141', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR8215', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR8215', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3035', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC8062', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3078', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_24.loc[df_24['Num_flight'] == 'FR8384', 'flight_capacity'] =  197

df_24.loc[df_24['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR2233', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_24.loc[df_24['Num_flight'] == 'EC7105', 'flight_capacity'] =  156

df_24.loc[df_24['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR846', 'flight_capacity'] =  189

df_24.loc[df_24['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_24.loc[df_24['Num_flight'] == 'FR3180', 'flight_capacity'] =  189

In [217]:
df_por_fecha['24/Nov/2025'] = df_24.copy()

In [218]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [219]:
df_25 = df_por_fecha['25/Nov/2025'].copy()
df_25.tail(40)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1206,NaN,25/Nov/2025,Aer Lingus,EI563,Dublin (DUB),11:30,"En hora, Ha salido",NaN,NaN,Y54
1207,NaN,25/Nov/2025,Ryanair,FR58,Napoli (NAP),11:40,"En hora, Ha salido",NaN,NaN,S20
1208,NaN,25/Nov/2025,Icelandair,FI597,Keflavik (KEF),11:50,"Retrasado, Ha salido 12:19",NaN,NaN,U37
1209,NaN,25/Nov/2025,Ryanair,FR3108,Luxembourg (LUX),12:15,"En hora, Ha salido",NaN,NaN,U33
1210,NaN,25/Nov/2025,easyJet Europe,EC7151,Milan (MXP),12:20,"En hora, Ha salido",NaN,NaN,R10
1211,NaN,25/Nov/2025,Norwegian Air Sweden AOC,D83657,Copenhagen (CPH),12:30,"En hora, Ha salido",NaN,NaN,S21
1212,NaN,25/Nov/2025,Ryanair,FR8384,Budapest (BUD),12:35,"En hora, Ha salido",NaN,NaN,S22
1213,NaN,25/Nov/2025,Pegasus Airlines,PC1092,Istanbul (SAW),12:45,"En hora, Ha salido",NaN,NaN,W45
1214,NaN,25/Nov/2025,Ryanair,FR6267,Edinburgh (EDI),12:55,"En hora, Ha salido",NaN,NaN,Y57
1215,NaN,25/Nov/2025,Norwegian Air Sweden AOC,D81741,Oslo (OSL),13:25,"En hora, Ha salido",NaN,NaN,S24
1216,NaN,25/Nov/2025,FlyOne,5F5512,Chisinau (KIV),13:30,"En hora, Ha salido",NaN,NaN,Y58
1217,NaN,25/Nov/2025,Ryanair,FR2239,Marrakech (RAK),14:00,"En hora, Ha salido",NaN,NaN,Y55
1218,NaN,25/Nov/2025,Ryanair,FR3076,Stockholm (ARN),14:05,"En hora, Programado",NaN,NaN,U31
1219,NaN,25/Nov/2025,Kuwait Airways,KU136,Kuwait City (KWI),14:25,"En hora, Programado",NaN,NaN,W44
1220,NaN,25/Nov/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"En hora, Programado",NaN,NaN,NaN
1221,NaN,25/Nov/2025,Ryanair,FR3792,Birmingham (BHX),16:20,"En hora, Ha salido",NaN,B38M,Y55
1222,NaN,25/Nov/2025,Ryanair,FR846,Milan (BGY),16:55,"En hora, Ha salido",NaN,NaN,U32
1223,NaN,25/Nov/2025,Ryanair,FR1165,Sevilla (SVQ),17:05,"Retrasado, Ha salido 17:17",NaN,NaN,S23
1224,NaN,25/Nov/2025,Ryanair,FR575,Bologna (BLQ),17:25,"En hora, Ha salido",NaN,NaN,U35
1225,NaN,25/Nov/2025,Transavia,HV5134,Amsterdam (AMS),17:45,"En hora, Ha salido",NaN,NaN,U31
1226,NaN,25/Nov/2025,Ryanair,FR3180,Rome (FCO),18:00,"En hora, Ha salido",NaN,NaN,U34
1227,NaN,25/Nov/2025,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:10,"En hora, Ha salido",NaN,NaN,R11
1228,NaN,25/Nov/2025,BUZZ,RR6300,Sofia (SOF),18:15,"En hora, Ha salido",NaN,NaN,U33
1229,NaN,25/Nov/2025,Ryanair,FR777,Venice (VCE),18:40,"En hora, Ha salido",NaN,NaN,U32
1230,NaN,25/Nov/2025,Ryanair,FR2834,Charleroi (CRL),18:45,"En hora, Ha salido",NaN,NaN,S22
1231,NaN,25/Nov/2025,Wizz Air,W61176,Katowice (KTW),18:55,"En hora, Ha salido",NaN,NaN,S24
1232,NaN,25/Nov/2025,Wizz Air,W61478,Warsaw (WAW),19:00,"En hora, Ha salido",NaN,NaN,U35
1233,NaN,25/Nov/2025,Ryanair,FR9015,London (STN),19:25,"En hora, Ha salido",NaN,NaN,Y59
1234,NaN,25/Nov/2025,Eurowings,EW9443,Dusseldorf (DUS),19:35,"En hora, Ha salido",NaN,NaN,U31
1235,NaN,25/Nov/2025,Wizz Air,W64406,Sofia (SOF),19:35,"En hora, Ha salido",NaN,NaN,U34
1236,NaN,25/Nov/2025,Easyjet,U28058,London (LGW),19:45,"Retrasado, Ha salido 20:17",NaN,NaN,M8
1237,NaN,25/Nov/2025,Transavia,HV6790,Eindhoven (EIN),19:55,"Retrasado, Ha salido 20:09",NaN,NaN,S23
1238,NaN,25/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),20:00,"En hora, Ha salido",NaN,NaN,Y58
1239,NaN,25/Nov/2025,easyJet Europe,EC1956,Milan (LIN),20:15,"En hora, Ha salido",NaN,NaN,R10
1240,NaN,25/Nov/2025,BUZZ,RR4084,Warsaw (WMI),20:15,"Retrasado, Ha salido 20:31",NaN,NaN,S24
1241,NaN,25/Nov/2025,Transavia,TO4759,Paris (ORY),20:45,"En hora, Ha salido",NaN,NaN,U32
1242,NaN,25/Nov/2025,easyJet Europe,EC1380,Geneva (GVA),21:15,"Retrasado, Ha salido 21:55",NaN,NaN,R11
1243,NaN,25/Nov/2025,Ryanair,FR6394,Dublin (DUB),21:15,"En hora, Ha salido",NaN,NaN,W46
1244,NaN,25/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",NaN,NaN,U33
1245,NaN,25/Nov/2025,Ryanair,FR4585,Porto (OPO),22:00,"En hora, Ha salido",NaN,NaN,S25

In [220]:
df_25[(df_25['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1180,NaN,25/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:00,"En hora, Ha salido",NaN,NaN,R11
1181,NaN,25/Nov/2025,Ryanair,FR3189,Fes (FEZ),06:15,"En hora, Ha salido",NaN,NaN,W46
1182,NaN,25/Nov/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,"En hora, Ha salido",NaN,NaN,S20
1183,NaN,25/Nov/2025,Ryanair,FR4545,Porto (OPO),06:35,"En hora, Ha salido",NaN,NaN,U32
1184,NaN,25/Nov/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:25,"En hora, Ha salido",NaN,NaN,R10
1185,NaN,25/Nov/2025,easyJet Europe,EC8062,London (LGW),07:30,"En hora, Ha salido",NaN,NaN,M6
1186,NaN,25/Nov/2025,Ryanair,FR3166,Palermo (PMO),07:35,"En hora, Ha salido",NaN,NaN,S24
1187,NaN,25/Nov/2025,Ryanair,FR5718,Bratislava (BTS),07:35,"En hora, Ha salido",NaN,NaN,U35
1188,NaN,25/Nov/2025,Ryanair,FR3193,Riga (RIX),07:55,"En hora, Ha salido",NaN,NaN,U34
1189,NaN,25/Nov/2025,easyJet Europe,EC3737,Milan (MXP),08:00,"En hora, Ha salido",NaN,NaN,R12

In [221]:
df_25.loc[df_25['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR4585', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W46020', 'flight_capacity'] =  239

df_25.loc[df_25['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR6394', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'EC1380', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_25.loc[df_25['Num_flight'] == 'TO4759', 'flight_capacity'] =  186

df_25.loc[df_25['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'RR4084', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'EC1956', 'flight_capacity'] =  180

In [222]:
df_25.loc[df_25['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == '3O642', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'HV6790', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'HV6790', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'U28058', 'flight_capacity'] =  156

df_25.loc[df_25['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W64406', 'flight_capacity'] =  239

df_25.loc[df_25['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'EW9443', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR9015', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W61478', 'flight_capacity'] =  239

df_25.loc[df_25['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321'
df_25.loc[df_25['Num_flight'] == 'W61176', 'flight_capacity'] =  230

df_25.loc[df_25['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR2834', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR777', 'flight_capacity'] =  189

In [223]:
df_25.loc[df_25['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'RR6300', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'RR6300', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'EC7103', 'flight_capacity'] =  156

df_25.loc[df_25['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3180', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'HV5134', 'flight_capacity'] =  239

df_25.loc[df_25['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR575', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR1165', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR846', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR3792', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'BZ251', 'Gate'] = 'Y'
df_25.loc[df_25['Num_flight'] == 'BZ251', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'BZ251', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-900'
df_25.loc[df_25['Num_flight'] == 'KU136', 'flight_capacity'] =  278

In [224]:
df_25.loc[df_25['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3076', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR2239', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == '5F5512', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == '5F5512', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'D81741', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR6267', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_25.loc[df_25['Num_flight'] == 'PC1092', 'flight_capacity'] =  230

df_25.loc[df_25['Num_flight'] == 'FR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR8384', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'D83657', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'EC7151', 'flight_capacity'] =  156

df_25.loc[df_25['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3108', 'flight_capacity'] =  189

In [225]:
df_25.loc[df_25['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FI597', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR58', 'flight_capacity'] =  189

df_25.loc[df_25['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'EI563', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320neo'
df_25.loc[df_25['Num_flight'] == 'J246', 'flight_capacity'] =  186

df_25.loc[df_25['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR5270', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR1279', 'flight_capacity'] =  197

df_25.loc[df_25['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W61476', 'flight_capacity'] =  239

df_25.loc[df_25['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'LW12', 'flight_capacity'] =  180

df_25.loc[df_25['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'JU581', 'flight_capacity'] =  156

df_25.loc[df_25['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W62376', 'flight_capacity'] =  239

In [226]:
df_25.loc[df_25['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == '3O378', 'flight_capacity'] = 180

df_25.loc[df_25['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_25.loc[df_25['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_25.loc[df_25['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_25.loc[df_25['Num_flight'] == 'W61914', 'flight_capacity'] = 239

df_25.loc[df_25['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737 MAX 8'
df_25.loc[df_25['Num_flight'] == 'FR3807', 'flight_capacity'] = 197

df_25.loc[df_25['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3035', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321'
df_25.loc[df_25['Num_flight'] == 'W62048', 'flight_capacity'] = 230

df_25.loc[df_25['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'W43938', 'flight_capacity'] = 180

df_25.loc[df_25['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR133', 'flight_capacity'] = 189

In [227]:
df_25.loc[df_25['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_25.loc[df_25['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_25.loc[df_25['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_25.loc[df_25['Num_flight'] == 'EC8062', 'flight_capacity'] = 156

df_25.loc[df_25['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'FR3193', 'Aircraft'] = 'Boeing 737-800'
df_25.loc[df_25['Num_flight'] == 'FR3193', 'flight_capacity'] = 189

df_25.loc[df_25['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_25.loc[df_25['Num_flight'] == 'EC3737', 'flight_capacity'] = 180

In [228]:
df_25.isna().sum()

Unnamed: 0         66
fecha_scrapeo       0
Name_company        0
Num_flight          0
Name_Destiny        0
Time_flight         0
flight_state        0
flight_capacity     0
Aircraft            0
Gate                0
dtype: int64

In [229]:
df_25['Aircraft'].unique()

array(['Airbus A319', 'Boeing 737-800', 'Airbus A320', 'Airbus A321',
       'Boeing 737 MAX 8', 'Airbus A321neo', 'Airbus A320neo',
       'Airbus A330-900'], dtype=object)

In [230]:
df_25[(df_25['Aircraft'] == 'Airbus A320neo')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1205,NaN,25/Nov/2025,Azerbaijan Airlines,J246,Baku (GYD),10:45,"En hora, Ha salido",186.0,Airbus A320neo,W45
1241,NaN,25/Nov/2025,Transavia,TO4759,Paris (ORY),20:45,"En hora, Ha salido",186.0,Airbus A320neo,U32

In [231]:
df_por_fecha['25/Nov/2025'] = df_25.copy()

In [232]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [233]:
df_26 = df_por_fecha['26/Nov/2025'].copy()
df_26

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1246,NaN,26/Nov/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S20
1247,NaN,26/Nov/2025,Ryanair,FR3185,Rabat (RBA),06:05,"En hora, Ha salido",NaN,NaN,W46
1248,NaN,26/Nov/2025,Ryanair,FR9406,Fes (FEZ),06:05,"En hora, Ha salido",NaN,NaN,Y59
1249,NaN,26/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"Retrasado, Ha salido 06:31",NaN,NaN,R15
1250,NaN,26/Nov/2025,Ryanair,FR483,Malaga (AGP),06:15,"En hora, Ha salido",NaN,NaN,U32
...,...,...,...,...,...,...,...,...,...,...
1325,NaN,26/Nov/2025,Easyjet,U22326,London (LTN),20:55,"En hora, Ha salido",NaN,NaN,M8
1326,NaN,26/Nov/2025,easyJet Europe,EC1380,Geneva (GVA),21:15,"Retrasado, Programado 21:41",NaN,NaN,R10
1327,NaN,26/Nov/2025,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"En hora, Ha salido",NaN,NaN,U35
1328,NaN,26/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",NaN,NaN,U34
1329,NaN,26/Nov/2025,Ryanair,FR6394,Dublin (DUB),22:05,"En hora, Programado",NaN,NaN,Y57

In [234]:
df_26.isna().sum()

Unnamed: 0         84
fecha_scrapeo       0
Name_company        0
Num_flight          0
Name_Destiny        0
Time_flight         0
flight_state        0
flight_capacity    84
Aircraft           75
Gate                2
dtype: int64

In [235]:
df_26[(df_26['Gate'].isna())]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1264,NaN,26/Nov/2025,Ryanair,FR2834,Charleroi (CRL),09:45,Cancelado 09:45,NaN,NaN,NaN
1287,NaN,26/Nov/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"Retrasado, Programado 14:56",NaN,NaN,NaN

In [236]:
df_26.loc[df_26['Num_flight'] == 'BZ251', 'Gate'] = 'W'
df_26.loc[df_26['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

In [237]:
df_26 = df_26.drop(1264)  # cancelado vuelo

In [238]:
df_26.reset_index(drop=True, inplace=True)

In [239]:
df_26[(df_26['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,NaN,26/Nov/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S20
1,NaN,26/Nov/2025,Ryanair,FR3185,Rabat (RBA),06:05,"En hora, Ha salido",NaN,NaN,W46
2,NaN,26/Nov/2025,Ryanair,FR9406,Fes (FEZ),06:05,"En hora, Ha salido",NaN,NaN,Y59
3,NaN,26/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"Retrasado, Ha salido 06:31",NaN,NaN,R15
4,NaN,26/Nov/2025,Ryanair,FR483,Malaga (AGP),06:15,"En hora, Ha salido",NaN,NaN,U32
5,NaN,26/Nov/2025,easyJet Europe,EC7193,Leeds Bradford (LBA),06:30,"En hora, Ha salido",NaN,NaN,M8
6,NaN,26/Nov/2025,Ryanair,FR2239,Marrakech (RAK),06:35,"En hora, Ha salido",NaN,NaN,W44
7,NaN,26/Nov/2025,Ryanair,FR3028,Ibiza (IBZ),06:45,"En hora, Ha salido",NaN,NaN,S21
8,NaN,26/Nov/2025,Ryanair,FR3108,Luxembourg (LUX),06:50,"En hora, Ha salido",NaN,NaN,S22
9,NaN,26/Nov/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,"En hora, Ha salido",NaN,NaN,R15

In [240]:
df_26.loc[df_26['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR6394', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W46020', 'flight_capacity'] = 239

In [241]:
df_26.loc[df_26['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_26.loc[df_26['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_26.loc[df_26['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_26.loc[df_26['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_26.loc[df_26['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'JU585', 'flight_capacity'] = 144

df_26.loc[df_26['Num_flight'] == 'TW408', 'Aircraft'] = 'BOEING 777-300ER'
df_26.loc[df_26['Num_flight'] == 'TW408', 'flight_capacity'] = 294

df_26.loc[df_26['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == '3O378', 'flight_capacity'] = 174

df_26.loc[df_26['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'RR5246', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'RR5246', 'flight_capacity'] = 197

In [242]:
df_26.loc[df_26['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3143', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W61706', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'U28058', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'HV6064', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'HV6064', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR133', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'EW9443', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR9334', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR9334', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR1165', 'flight_capacity'] = 189

In [243]:
df_26.loc[df_26['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'E9803', 'Aircraft'] = 'Airbus A350-900'
df_26.loc[df_26['Num_flight'] == 'E9803', 'flight_capacity'] = 432

df_26.loc[df_26['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W67920', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

In [244]:
df_26.loc[df_26['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_26.loc[df_26['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_26.loc[df_26['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR3035', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321'
df_26.loc[df_26['Num_flight'] == 'PC1094', 'flight_capacity'] = 230

df_26.loc[df_26['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR12', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR777', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EW2521', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'D83659', 'flight_capacity'] = 197

In [245]:
df_26.loc[df_26['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'TK608', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'
df_26.loc[df_26['Num_flight'] == 'LG3592', 'flight_capacity'] = 76

df_26.loc[df_26['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'EW521', 'flight_capacity'] = 180

df_26.loc[df_26['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'D81741', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR6597', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'PC1092', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'FR9925', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR9925', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'EI563', 'flight_capacity'] = 174

In [246]:
df_26.loc[df_26['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR2507', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320neo'
df_26.loc[df_26['Num_flight'] == 'U22704', 'flight_capacity'] = 186

df_26.loc[df_26['Num_flight'] == 'U5406', 'Aircraft'] = 'Boeing 737-700'
df_26.loc[df_26['Num_flight'] == 'U5406', 'flight_capacity'] = 149

df_26.loc[df_26['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR6267', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'BT878', 'Aircraft'] = 'Airbus A220-300'
df_26.loc[df_26['Num_flight'] == 'BT878', 'flight_capacity'] = 148

df_26.loc[df_26['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3039', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'HV5132', 'flight_capacity'] = 239

In [247]:
df_26.loc[df_26['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == '3O642', 'flight_capacity'] = 174

df_26.loc[df_26['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'RR3049', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W42940', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == '3O376', 'flight_capacity'] = 174

df_26.loc[df_26['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_26.loc[df_26['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_26.loc[df_26['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_26.loc[df_26['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_26.loc[df_26['Num_flight'] == 'EC7161', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC7161', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_26.loc[df_26['Num_flight'] == 'EC3737', 'flight_capacity'] = 180

In [248]:
df_26.loc[df_26['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC8062', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737 MAX 8'
df_26.loc[df_26['Num_flight'] == 'FR3108', 'flight_capacity'] = 197

df_26.loc[df_26['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'EC7193', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC7193', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR483', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_26.loc[df_26['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_26.loc[df_26['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR9406', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR3185', 'flight_capacity'] = 189

df_26.loc[df_26['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_26.loc[df_26['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

In [249]:
df_16['Aircraft'].unique()

array(['Boeing 737-800', 'Airbus A320', 'Airbus A319', 'Boeing 737 MAX 8',
       'Airbus A321', 'Airbus A220-300', 'Airbus A321neo',
       'Airbus A320neo'], dtype=object)

In [250]:
df_por_fecha['26/Nov/2025'] = df_26.copy()

In [251]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [252]:
df_27 = df_por_fecha['27/Nov/2025'].copy()
df_27

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1330,NaN,27/Nov/2025,Ryanair,FR8215,London (STN),06:00,"En hora, Ha salido",NaN,NaN,W42
1331,NaN,27/Nov/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,B738,U32
1332,NaN,27/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R13
1333,NaN,27/Nov/2025,Ryanair,FR3976,Dublin (DUB),06:15,"En hora, Ha salido",NaN,NaN,W46
1334,NaN,27/Nov/2025,easyJet Europe,EC7191,Glasgow (GLA),06:40,"En hora, Ha salido",NaN,NaN,M3
...,...,...,...,...,...,...,...,...,...,...
1451,NaN,27/Nov/2025,BUZZ,RR3035,Krakow (KRK),21:30,"En hora, Ha salido",NaN,NaN,U32
1452,NaN,27/Nov/2025,BUZZ,RR4084,Warsaw (WMI),21:30,"En hora, Ha salido",NaN,NaN,S21
1453,NaN,27/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",NaN,NaN,S20
1454,NaN,27/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"Retrasado, Programado 22:27",NaN,NaN,W45
1455,NaN,27/Nov/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,Y57

In [253]:
df_27.isna().sum()

Unnamed: 0         126
fecha_scrapeo        0
Name_company         1
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    126
Aircraft           109
Gate                 2
dtype: int64

In [254]:
df_27[(df_27['Gate'].isna())]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1396,NaN,27/Nov/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"En hora, Programado",NaN,NaN,NaN
1397,NaN,27/Nov/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",NaN,NaN,NaN

In [255]:
df_27.loc[df_27['Num_flight'] == 'BZ251', 'Gate'] = 'W'
df_27.loc[df_27['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'QS1059', 'Gate'] = 'U'
df_27.loc[df_27['Num_flight'] == 'QS1059', 'Aircraft'] = 'Airbus A220-300'
df_27.loc[df_27['Num_flight'] == 'QS1059', 'flight_capacity'] = 149

In [256]:
df_27[(df_27['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1330,NaN,27/Nov/2025,Ryanair,FR8215,London (STN),06:00,"En hora, Ha salido",NaN,NaN,W42
1331,NaN,27/Nov/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,B738,U32
1332,NaN,27/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R13
1333,NaN,27/Nov/2025,Ryanair,FR3976,Dublin (DUB),06:15,"En hora, Ha salido",NaN,NaN,W46
1334,NaN,27/Nov/2025,easyJet Europe,EC7191,Glasgow (GLA),06:40,"En hora, Ha salido",NaN,NaN,M3
1335,NaN,27/Nov/2025,Ryanair,FR3049,Krakow (KRK),06:40,"En hora, Ha salido",NaN,NaN,U33
1336,NaN,27/Nov/2025,Ryanair,FR3028,Ibiza (IBZ),06:45,"En hora, Ha salido",NaN,NaN,U41
1337,NaN,27/Nov/2025,Lauda Europe,LW2495,Palma de Mallorca (PMI),07:20,"En hora, Ha salido",NaN,NaN,S23
1338,NaN,27/Nov/2025,Ryanair,FR133,Berlin (BER),07:25,"En hora, Ha salido",NaN,B738,U34
1339,NaN,27/Nov/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:30,"En hora, Ha salido",NaN,NaN,R11

In [257]:
df_27.loc[df_27['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'
df_27.loc[df_27['Num_flight'] == 'W45154', 'flight_capacity'] = 230

df_27.loc[df_27['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W64116', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321'
df_27.loc[df_27['Num_flight'] == 'W46020', 'flight_capacity'] = 230

df_27.loc[df_27['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'RR4084', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'RR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'RR3035', 'flight_capacity'] = 197

In [258]:
df_27.loc[df_27['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_27.loc[df_27['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_27.loc[df_27['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR8217', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'W61176', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'TO4755', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'TO4755', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'TO4755', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'TO4755', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR846', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR3039', 'flight_capacity'] = 197

In [259]:
df_27.loc[df_27['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'V71445', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'V71445', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'U28056', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321'
df_27.loc[df_27['Num_flight'] == 'W42938', 'flight_capacity'] = 230

df_27.loc[df_27['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W61914', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'D85510', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

In [260]:
df_27.loc[df_27['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR1527', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'EI565', 'flight_capacity'] = 174

df_27.loc[df_27['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'RR333', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W64738', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W64738', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'U22324', 'Aircraft'] = 'Airbus A320neo'
df_27.loc[df_27['Num_flight'] == 'U22324', 'flight_capacity'] = 186

df_27.loc[df_27['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_27.loc[df_27['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_27.loc[df_27['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR4587', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR3143', 'flight_capacity'] = 197

In [261]:
df_27.loc[df_27['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == '3O376', 'flight_capacity'] = 174

df_27.loc[df_27['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'V72167', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'V72167', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR8631', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'U28058', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR8598', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR8598', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'EW2521', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == '3O378', 'flight_capacity'] = 174

In [262]:
df_27= df_27.drop(1427)

In [263]:

df_27.loc[df_27['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'RR3193', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'RR3193', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_27.loc[df_27['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_27.loc[df_27['Num_flight'] == 'FR3800', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3800', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC7139', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'EC7139', 'flight_capacity'] = 180

In [264]:
df_27.loc[df_27['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'RR6300', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'HV5136', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'HV5136', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'V72327', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'RR8394', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR2098', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC1378', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'EC1378', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

In [265]:
df_27.loc[df_27['Num_flight'] == 'FR9913', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR9913', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR9045', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'V73573', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR2922', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR149', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-900'
df_27.loc[df_27['Num_flight'] == 'KU136', 'flight_capacity'] = 278

In [266]:
df_27.loc[df_27['Num_flight'] == 'XQ895', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'XQ895', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_27.loc[df_27['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_27.loc[df_27['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR6267', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'
df_27.loc[df_27['Num_flight'] == 'LG3592', 'flight_capacity'] = 76

df_27.loc[df_27['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'PC1092', 'flight_capacity'] = 239

In [267]:
df_27.loc[df_27['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'U22704', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3076', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR483', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR3160', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3160', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'EI563', 'flight_capacity'] = 174

df_27.loc[df_27['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR6597', 'flight_capacity'] = 189

In [268]:
df_27.loc[df_27['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320neo'
df_27.loc[df_27['Num_flight'] == 'J246', 'flight_capacity'] = 186

df_27.loc[df_27['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
df_27.loc[df_27['Num_flight'] == 'U25716', 'flight_capacity'] = 186

df_27.loc[df_27['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR1165', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'HV5132', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR1279', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_27.loc[df_27['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_27.loc[df_27['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'JU581', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

In [269]:
df_27.loc[df_27['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_27.loc[df_27['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_27.loc[df_27['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR5710', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'W43938', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR6973', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR575', 'flight_capacity'] = 189

In [270]:
df_27.loc[df_27['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR2507', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'LW2495', 'Aircraft'] = 'Airbus A320'
df_27.loc[df_27['Num_flight'] == 'LW2495', 'flight_capacity'] = 180

df_27.loc[df_27['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_27.loc[df_27['Num_flight'] == 'FR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR3049', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'EC7191', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7191', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737 MAX 8'
df_27.loc[df_27['Num_flight'] == 'FR3976', 'flight_capacity'] = 197

df_27.loc[df_27['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_27.loc[df_27['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_27.loc[df_27['Num_flight'] == 'FR8215', 'Aircraft'] = 'Boeing 737-800'
df_27.loc[df_27['Num_flight'] == 'FR8215', 'flight_capacity'] = 189

In [271]:
df_por_fecha['27/Nov/2025'] = df_27.copy()

In [272]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [273]:
df_28 = df_por_fecha['28/Nov/2025'].copy()
df_28

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1456,NaN,28/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R11
1457,NaN,28/Nov/2025,Ryanair,FR8183,Bologna (BLQ),06:10,"En hora, Ha salido",NaN,NaN,U33
1458,NaN,28/Nov/2025,Ryanair,FR8231,London (STN),06:10,"En hora, Ha salido",NaN,NaN,W44
1459,NaN,28/Nov/2025,Ryanair,FR777,Venice (VCE),06:20,"En hora, Ha salido",NaN,B738,U35
1460,NaN,28/Nov/2025,Ryanair,FR846,Milan (BGY),06:25,"Retrasado, Ha salido 06:35",NaN,NaN,S23
...,...,...,...,...,...,...,...,...,...,...
1619,NaN,28/Nov/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",NaN,NaN,W44
1620,NaN,28/Nov/2025,Ryanair,FR3080,Malaga (AGP),22:30,"En hora, Programado",NaN,Boeing 737 MAX 8,R
1621,NaN,28/Nov/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,Y57
1622,NaN,28/Nov/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",NaN,NaN,S24
1623,NaN,28/Nov/2025,Ryanair,FR9814,London (STN),23:10,"En hora, Programado",NaN,NaN,Y58

In [274]:
df_28.isna().sum()

Unnamed: 0         168
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    168
Aircraft           142
Gate                 3
dtype: int64

In [275]:
df_28[(df_28['Gate'].isna())]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1504,NaN,28/Nov/2025,Ryanair,FR269,Milan (MXP),11:20,Cancelado 11:20,NaN,NaN,NaN
1521,NaN,28/Nov/2025,Wizz Air,W67022,Bratislava (BTS),12:55,"Retrasado, Programado 15:25",NaN,NaN,NaN
1537,NaN,28/Nov/2025,Wizz Air,W64406,Sofia (SOF),14:50,"Retrasado, Programado 15:20",NaN,NaN,NaN

In [276]:
df_28= df_28.drop(1504)

In [277]:
df_28.loc[df_28['Num_flight'] == 'W67022', 'Gate'] = 'S'

In [278]:
df_28.loc[df_28['Num_flight'] == 'W64406', 'Gate'] = 'R'

In [279]:
df_28[(df_28['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1456,NaN,28/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R11
1457,NaN,28/Nov/2025,Ryanair,FR8183,Bologna (BLQ),06:10,"En hora, Ha salido",NaN,NaN,U33
1458,NaN,28/Nov/2025,Ryanair,FR8231,London (STN),06:10,"En hora, Ha salido",NaN,NaN,W44
1459,NaN,28/Nov/2025,Ryanair,FR777,Venice (VCE),06:20,"En hora, Ha salido",NaN,B738,U35
1460,NaN,28/Nov/2025,Ryanair,FR846,Milan (BGY),06:25,"Retrasado, Ha salido 06:35",NaN,NaN,S23
1461,NaN,28/Nov/2025,Ryanair,FR133,Berlin (BER),06:35,"Retrasado, Ha salido 06:45",NaN,NaN,U31
1462,NaN,28/Nov/2025,Ryanair,FR4545,Porto (OPO),06:45,"En hora, Ha salido",NaN,NaN,S21
1463,NaN,28/Nov/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,"En hora, Ha salido",NaN,NaN,R10
1464,NaN,28/Nov/2025,easyJet Europe,EC7199,Edinburgh (EDI),07:20,"En hora, Ha salido",NaN,NaN,M3
1465,NaN,28/Nov/2025,Lauda Europe,LW2889,Palma de Mallorca (PMI),07:40,"En hora, Ha salido",NaN,Airbus A320,R13

In [280]:
df_28.loc[df_28['Num_flight'] == 'FR9814', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR9814', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W61706', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W45154', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR3080', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR3080', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W64116', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2250', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6597', 'flight_capacity'] = 189

In [281]:
df_28.loc[df_28['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'RR6944', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR2495', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2495', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC7682', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'EC7682', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR9811', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR8669', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR7808', 'flight_capacity'] = 189

In [282]:
df_28.loc[df_28['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3174', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'U23374', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'U23374', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EI565', 'flight_capacity'] = 174

df_28.loc[df_28['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'RR8394', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_28.loc[df_28['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_28.loc[df_28['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_28.loc[df_28['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_28.loc[df_28['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR5710', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'LG3592', 'Aircraft'] = 'Boeing 737-700'
df_28.loc[df_28['Num_flight'] == 'LG3592', 'flight_capacity'] = 142

df_28.loc[df_28['Num_flight'] == 'RR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'RR1786', 'flight_capacity'] = 197

In [283]:
df_28.loc[df_28['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'JU585', 'flight_capacity'] = 144

df_28.loc[df_28['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR8631', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR7539', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'V72135', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'V72135', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'TW408', 'Aircraft'] = 'Airbus A330-200'
df_28.loc[df_28['Num_flight'] == 'TW408', 'flight_capacity'] = 246

df_28.loc[df_28['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W42940', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W62096', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6305', 'flight_capacity'] = 189

In [284]:
df_28.loc[df_28['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6275', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR2402', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR1527', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W64666', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'EW2521', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR6374', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6374', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'U28058', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'LW7362', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'LW7362', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'FR2330', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2330', 'flight_capacity'] = 189

In [285]:
df_28.loc[df_28['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'EW9443', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'V72165', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'RR6330', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'RR6330', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR149', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W61478', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2098', 'flight_capacity'] = 189

In [286]:
df_28.loc[df_28['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == '5F5512', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == '5F5512', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == '3O398', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == '3O398', 'flight_capacity'] = 174

df_28.loc[df_28['Num_flight'] == 'EC7205', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7205', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR6353', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR6353', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'HV5134', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'V73573', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR3076', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W67920', 'flight_capacity'] = 239

In [287]:
df_28.loc[df_28['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR4587', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR878', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W43564', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'W43564', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6985', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR2925', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2925', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'D85510', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

In [288]:
df_28.loc[df_28['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'PC1094', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR483', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR483', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'V73735', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'QS1059', 'Aircraft'] = 'Airbus A220-300'
df_28.loc[df_28['Num_flight'] == 'QS1059', 'flight_capacity'] = 149

df_28.loc[df_28['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR867', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W64406', 'flight_capacity'] = 239

In [289]:
df_28.loc[df_28['Num_flight'] == 'V71443', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'V71443', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR8215', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR8215', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_28.loc[df_28['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_28.loc[df_28['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_28.loc[df_28['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_28.loc[df_28['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR6078', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6078', 'flight_capacity'] = 189

In [290]:
df_28.loc[df_28['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'TK608', 'flight_capacity'] = 165

df_28.loc[df_28['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'PC1528', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'H4264', 'flight_capacity'] = 186

df_28.loc[df_28['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W46330', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W67022', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6874', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'PC1092', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR575', 'flight_capacity'] = 197

In [291]:
df_28.loc[df_28['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'D83657', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 757-200'
df_28.loc[df_28['Num_flight'] == 'FI597', 'flight_capacity'] = 184

df_28.loc[df_28['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'RR3049', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC7141', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7141', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'LW2896', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'LW2896', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR3121', 'flight_capacity'] = 197

In [292]:
df_28.loc[df_28['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EI563', 'flight_capacity'] = 174

df_28.loc[df_28['Num_flight'] == '3F232', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == '3F232', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR5270', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320neo'
df_28.loc[df_28['Num_flight'] == 'U22704', 'flight_capacity'] = 186

df_28.loc[df_28['Num_flight'] == 'HV6064', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'HV6064', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

In [293]:
df_28.loc[df_28['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320neo'
df_28.loc[df_28['Num_flight'] == 'U22002', 'flight_capacity'] = 186

df_28.loc[df_28['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EW7521', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'HV5132', 'flight_capacity'] = 232

df_28.loc[df_28['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR6920', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR9015', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'JU581', 'flight_capacity'] = 144

df_28.loc[df_28['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

In [294]:
df_28.loc[df_28['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == '3O378', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'U26654', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'U26654', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR3028', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W45088', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_28.loc[df_28['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_28.loc[df_28['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == '3O374', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == '3O374', 'flight_capacity'] = 180

In [295]:
df_28.loc[df_28['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR2834', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'EC3737', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_28.loc[df_28['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_28.loc[df_28['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR1165', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR6973', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR3185', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR3976', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'D85502', 'flight_capacity'] = 189

In [296]:
df_28.loc[df_28['Num_flight'] == 'LW2889', 'Aircraft'] = 'Airbus A320'
df_28.loc[df_28['Num_flight'] == 'LW2889', 'flight_capacity'] = 180

df_28.loc[df_28['Num_flight'] == 'EC7199', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7199', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_28.loc[df_28['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_28.loc[df_28['Num_flight'] == 'FR777', 'flight_capacity'] = 197

df_28.loc[df_28['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'FR8183', 'Aircraft'] = 'Boeing 737-800'
df_28.loc[df_28['Num_flight'] == 'FR8183', 'flight_capacity'] = 189

df_28.loc[df_28['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_28.loc[df_28['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

In [297]:
df_por_fecha['28/Nov/2025'] = df_28.copy()

In [298]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [299]:
df_29 = df_por_fecha['29/Nov/2025'].copy()
df_29

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1624,NaN,29/Nov/2025,Ryanair,FR846,Milan (BGY),06:00,"En hora, Ha salido",NaN,NaN,U31
1625,NaN,29/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R11
1626,NaN,29/Nov/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S22
1627,NaN,29/Nov/2025,Ryanair,FR4545,Porto (OPO),06:15,"En hora, Ha salido",NaN,NaN,U35
1628,NaN,29/Nov/2025,Ryanair,FR1342,Palma de Mallorca (PMI),06:20,"En hora, Ha salido",189.0,Boeing 737-800,S25
...,...,...,...,...,...,...,...,...,...,...
1737,NaN,29/Nov/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Programado",NaN,NaN,S23
1738,NaN,29/Nov/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"Retrasado, Programado 22:05",NaN,NaN,Y55
1739,NaN,29/Nov/2025,Ryanair,FR8574,Rome (FCO),22:10,"En hora, Programado",NaN,NaN,U35
1740,NaN,29/Nov/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"Retrasado, Programado 22:45",239.0,Airbus A321neo,W
1741,NaN,29/Nov/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Programado",NaN,NaN,Y57

In [300]:
df_29.isna().sum()

Unnamed: 0         118
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    112
Aircraft            97
Gate                 1
dtype: int64

In [301]:
df_29[(df_29['Gate'].isna())]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1686,NaN,29/Nov/2025,Kuwait Airways,KU136,Kuwait City (KWI),14:25,"En hora, Programado",NaN,NaN,NaN

In [302]:
df_29.loc[df_29['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-800'
df_29.loc[df_29['Num_flight'] == 'KU136', 'Gate'] = 'W'
df_29.loc[df_29['Num_flight'] == 'KU136', 'flight_capacity'] = 235

In [303]:
df_29[(df_29['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1624,NaN,29/Nov/2025,Ryanair,FR846,Milan (BGY),06:00,"En hora, Ha salido",NaN,NaN,U31
1625,NaN,29/Nov/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R11
1626,NaN,29/Nov/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S22
1627,NaN,29/Nov/2025,Ryanair,FR4545,Porto (OPO),06:15,"En hora, Ha salido",NaN,NaN,U35
1629,NaN,29/Nov/2025,Ryanair,FR777,Venice (VCE),06:30,"En hora, Ha salido",NaN,NaN,U32
1630,NaN,29/Nov/2025,easyJet Europe,EC7151,Milan (MXP),07:30,"En hora, Ha salido",NaN,NaN,R15
1631,NaN,29/Nov/2025,Ryanair,FR2918,Brussels (BRU),08:05,"En hora, Ha salido",NaN,NaN,U34
1632,NaN,29/Nov/2025,Ryanair,FR3180,Rome (FCO),08:15,"En hora, Ha salido",NaN,NaN,R13
1633,NaN,29/Nov/2025,Air Arabia Maroc,3O376,Al Aaroui (NDR),08:35,"En hora, Ha salido",NaN,NaN,W44
1635,NaN,29/Nov/2025,Ryanair,FR575,Bologna (BLQ),08:50,"En hora, Ha salido",NaN,NaN,U31

In [304]:
df_29.loc[df_29['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == '3O642', 'flight_capacity'] = 174

df_29.loc[df_29['Num_flight'] == 'FR8574', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR8574', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR3800', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3800', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'RR3039', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'RR3039', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR5220', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'W43406', 'flight_capacity'] = 180

In [305]:
df_29.loc[df_29['Num_flight'] == 'TW408', 'Aircraft'] = 'BOEING 777-300ER'
df_29.loc[df_29['Num_flight'] == 'TW408', 'flight_capacity'] = 294

df_29.loc[df_29['Num_flight'] == 'FR9581', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR9581', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR3182', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3182', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_29.loc[df_29['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_29.loc[df_29['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_29.loc[df_29['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_29.loc[df_29['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3174', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_29.loc[df_29['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

In [306]:
df_29.loc[df_29['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR867', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_29.loc[df_29['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_29.loc[df_29['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR5270', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W61176', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR3792', 'flight_capacity'] = 197

In [307]:
df_29.loc[df_29['Num_flight'] == 'BT878', 'Aircraft'] = 'Airbus A220-300'
df_29.loc[df_29['Num_flight'] == 'BT878', 'flight_capacity'] = 148

df_29.loc[df_29['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321'
df_29.loc[df_29['Num_flight'] == 'W64406', 'flight_capacity'] = 230

df_29.loc[df_29['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR149', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'TO4757', 'Aircraft'] = 'Airbus A320neo'
df_29.loc[df_29['Num_flight'] == 'TO4757', 'flight_capacity'] = 186

df_29.loc[df_29['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'V72327', 'flight_capacity'] = 180

In [308]:
df_29.loc[df_29['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR3035', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'HV5134', 'flight_capacity'] = 232

df_29.loc[df_29['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR878', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'BZ251', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'BZ251', 'flight_capacity'] = 180

df_29.loc[df_29['Num_flight'] == 'FR6353', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR6353', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR2925', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR2925', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR6874', 'flight_capacity'] = 189

In [309]:
df_29.loc[df_29['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR9015', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR3146', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3146', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR7543', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR7543', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR3807', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

In [310]:
df_29.loc[df_29['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'RR6920', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'RR6920', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_29.loc[df_29['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_29.loc[df_29['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == '3O378', 'flight_capacity'] = 174

df_29.loc[df_29['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR2098', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'RK6597', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'RK6597', 'flight_capacity'] = 189

In [311]:
df_29.loc[df_29['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR7808', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W46330', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'OB775', 'Aircraft'] = 'Airbus A330-200'
df_29.loc[df_29['Num_flight'] == 'OB775', 'flight_capacity'] = 246

df_29.loc[df_29['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_29.loc[df_29['Num_flight'] == 'PC1092', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3108', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

In [312]:
df_29.loc[df_29['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'EI563', 'flight_capacity'] = 174

df_29.loc[df_29['Num_flight'] == 'EC7193', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC7193', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'FR4597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR4597', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320neo'
df_29.loc[df_29['Num_flight'] == 'U22704', 'flight_capacity'] = 186

df_29.loc[df_29['Num_flight'] == 'U5406', 'Aircraft'] = 'Boeing 737-700'
df_29.loc[df_29['Num_flight'] == 'U5406', 'flight_capacity'] = 149

df_29.loc[df_29['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'J246', 'flight_capacity'] = 122

df_29.loc[df_29['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_29.loc[df_29['Num_flight'] == 'FR9307', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR9307', 'flight_capacity'] = 197

In [313]:
df_29.loc[df_29['Num_flight'] == 'FR3168', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3168', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'U22326', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'FR9171', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR9171', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'HV5132', 'flight_capacity'] = 232

df_29.loc[df_29['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'FR6559', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR6559', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'JU581', 'flight_capacity'] = 144

df_29.loc[df_29['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'RR3049', 'flight_capacity'] = 189

In [314]:
df_29.loc[df_29['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W61914', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR2834', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_29.loc[df_29['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_29.loc[df_29['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == 'W43938', 'flight_capacity'] = 180

df_29.loc[df_29['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

In [315]:
df_29.loc[df_29['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_29.loc[df_29['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_29.loc[df_29['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_29.loc[df_29['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

df_29.loc[df_29['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_29.loc[df_29['Num_flight'] == '3O376', 'flight_capacity'] = 189

df_29.loc[df_29['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_29.loc[df_29['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

In [316]:
df_por_fecha['29/Nov/2025'] = df_29.copy()

In [317]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [318]:
df_30 = df_por_fecha['30/Nov/2025'].copy()
df_30

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1742,NaN,30/Nov/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,S20
1743,NaN,30/Nov/2025,Ryanair,FR2834,Charleroi (CRL),06:10,"En hora, Ha salido",NaN,NaN,U34
1744,NaN,30/Nov/2025,Ryanair,FR2918,Brussels (BRU),06:25,"En hora, Ha salido",NaN,NaN,S24
1745,NaN,30/Nov/2025,Ryanair,FR4084,Warsaw (WMI),06:25,"En hora, Ha salido",NaN,NaN,U35
1746,NaN,30/Nov/2025,Ryanair,FR2239,Marrakech (RAK),06:30,"En hora, Ha salido",NaN,B738,W45
...,...,...,...,...,...,...,...,...,...,...
1897,NaN,30/Nov/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",NaN,NaN,W44
1898,NaN,30/Nov/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"Retrasado, Programado 23:18",NaN,NaN,W
1899,NaN,30/Nov/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",NaN,NaN,S24
1900,NaN,30/Nov/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",NaN,NaN,U31
1901,NaN,30/Nov/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",NaN,NaN,Y

In [319]:
df_30.isna().sum()

Unnamed: 0         160
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    150
Aircraft           144
Gate                 3
dtype: int64

In [320]:
df_30[(df_30['flight_capacity'].isna())].head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1742,NaN,30/Nov/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,S20
1743,NaN,30/Nov/2025,Ryanair,FR2834,Charleroi (CRL),06:10,"En hora, Ha salido",NaN,NaN,U34
1744,NaN,30/Nov/2025,Ryanair,FR2918,Brussels (BRU),06:25,"En hora, Ha salido",NaN,NaN,S24
1745,NaN,30/Nov/2025,Ryanair,FR4084,Warsaw (WMI),06:25,"En hora, Ha salido",NaN,NaN,U35
1746,NaN,30/Nov/2025,Ryanair,FR2239,Marrakech (RAK),06:30,"En hora, Ha salido",NaN,B738,W45
1747,NaN,30/Nov/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:40,"En hora, Ha salido",NaN,NaN,U31
1748,NaN,30/Nov/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",06:50,"En hora, Ha salido",NaN,NaN,R10
1749,NaN,30/Nov/2025,easyJet Europe,EC7191,Glasgow (GLA),07:20,"En hora, Ha salido",NaN,NaN,M8
1750,NaN,30/Nov/2025,Ryanair,FR6597,Manchester (MAN),07:30,"En hora, Ha salido",NaN,B738,W44
1751,NaN,30/Nov/2025,Ryanair,FR3108,Luxembourg (LUX),07:35,"En hora, Ha salido",NaN,NaN,S23

In [321]:
df_30.loc[df_30['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR9406', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W61706', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR5220', 'flight_capacity'] = 197

In [322]:
df_30.loc[df_30['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W45154', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W64116', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'U22706', 'Aircraft'] = 'Airbus A320neo'
df_30.loc[df_30['Num_flight'] == 'U22706', 'flight_capacity'] = 186

df_30.loc[df_30['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'U28060', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'U28060', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

In [323]:
df_30.loc[df_30['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'HV5134', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EI565', 'flight_capacity'] = 174

df_30.loc[df_30['Num_flight'] == 'RR8615', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'RR8615', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W64738', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W64738', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_30.loc[df_30['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_30.loc[df_30['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'RR6944', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR6275', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'TO4759', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'TO4759', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'LG3596', 'Aircraft'] = 'Boeing 737-700'
df_30.loc[df_30['Num_flight'] == 'LG3596', 'flight_capacity'] = 142

In [324]:
df_30.loc[df_30['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR4587', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EW2521', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'D83659', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'JU585', 'flight_capacity'] = 144

df_30.loc[df_30['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EW521', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR6985', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W62096', 'flight_capacity'] = 239

In [325]:
df_30.loc[df_30['Num_flight'] == 'FR8136', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR8136', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W64666', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'U28058', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR9015', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR5710', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC3750', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC3750', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'V72165', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FR3160', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3160', 'flight_capacity'] = 189

In [326]:
df_30.loc[df_30['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'EC7159', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7159', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'W61176', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
df_30.loc[df_30['Num_flight'] == 'U25716', 'flight_capacity'] = 186

df_30.loc[df_30['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
df_30.loc[df_30['Num_flight'] == 'U25716', 'flight_capacity'] = 186

df_30.loc[df_30['Num_flight'] == 'HV6066', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'HV6066', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR8631', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'LS804', 'flight_capacity'] = 189

In [327]:
df_30.loc[df_30['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'EC7109', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7109', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR6305', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR777', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'RR5252', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'RR5252', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'V73573', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR12', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

In [328]:
df_30.loc[df_30['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'RR8394', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2250', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == '3O374', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == '3O374', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR8669', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR9814', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR9814', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC7173', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC7173', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2922', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == '3O378', 'flight_capacity'] = 174

In [329]:
df_30.loc[df_30['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR8669', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'QS1059', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR6973', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'EC7694', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC7694', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_30.loc[df_30['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_30.loc[df_30['Num_flight'] == 'RR3072', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'RR3072', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

In [330]:
df_30.loc[df_30['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'HV5132', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'HV5132', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'XQ895', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'XQ895', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR6920', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_30.loc[df_30['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_30.loc[df_30['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'PC1092', 'flight_capacity'] = 220

df_30.loc[df_30['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

In [331]:
df_30.loc[df_30['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR9811', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W46330', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'V71445', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'V71445', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR8598', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR8598', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR2511', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2511', 'flight_capacity'] = 189

In [332]:
df_30.loc[df_30['Num_flight'] == 'EC7139', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC7139', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320neo'
df_30.loc[df_30['Num_flight'] == 'EI563', 'flight_capacity'] = 186

df_30.loc[df_30['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'J246', 'flight_capacity'] = 174

df_30.loc[df_30['Num_flight'] == 'V72167', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'V72167', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR1527', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR3976', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'V72327', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FI597', 'flight_capacity'] = 160

In [333]:
df_30.loc[df_30['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR3143', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR1279', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR7543', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR7543', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR6874', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

In [334]:
df_30.loc[df_30['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'RR3049', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'RR8384', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'RR333', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W45088', 'flight_capacity'] = 230

df_30.loc[df_30['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_30.loc[df_30['Num_flight'] == 'W43176', 'flight_capacity'] = 230

In [335]:
df_30.loc[df_30['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EW7521', 'flight_capacity'] = 150

df_30.loc[df_30['Num_flight'] == 'RR3193', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'RR3193', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_30.loc[df_30['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_30.loc[df_30['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR3028', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'RR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'RR1786', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR878', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC3754', 'Aircraft'] = 'Airbus A320'
df_30.loc[df_30['Num_flight'] == 'EC3754', 'flight_capacity'] = 180

df_30.loc[df_30['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'D85510', 'flight_capacity'] = 189

In [336]:
df_30.loc[df_30['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3108', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR6597', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'EC7191', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7191', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_30.loc[df_30['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_30.loc[df_30['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR4084', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR4084', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_30.loc[df_30['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
df_30.loc[df_30['Num_flight'] == 'FR2834', 'flight_capacity'] = 197

df_30.loc[df_30['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_30.loc[df_30['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

In [337]:
df_30[(df_30['Aircraft'] == 'Airbus A320')].tail(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1755,NaN,30/Nov/2025,easyJet Europe,EC3754,Milan (MXP),08:25,"En hora, Ha salido",180.0,Airbus A320,R10
1758,NaN,30/Nov/2025,Volotea,V73735,Murcia (RMU),08:40,"En hora, Ha salido",180.0,Airbus A320,S20
1778,NaN,30/Nov/2025,Lauda Europe,LW7351,Vienna (VIE),10:10,"En hora, Ha salido",180.0,Airbus A320,S21
1785,NaN,30/Nov/2025,Azerbaijan Airlines,J246,Baku (GYD),10:45,"Retrasado, Ha salido 11:12",174.0,Airbus A320,Y58
1789,NaN,30/Nov/2025,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),11:45,"En hora, Ha salido",180.0,Airbus A320,R9
1791,NaN,30/Nov/2025,Lauda Europe,LW2889,Palma de Mallorca (PMI),11:55,"En hora, Ha salido",180.0,Airbus A320,R14
1797,NaN,30/Nov/2025,Volotea,V72167,Lille/Lesquin (LIL),12:35,"En hora, Ha salido",180.0,Airbus A320,S22
1802,NaN,30/Nov/2025,Volotea,V71445,Olbia (OLB),13:05,"En hora, Ha salido",180.0,Airbus A320,S20
1806,NaN,30/Nov/2025,easyJet Europe,EC1380,Geneva (GVA),13:40,"En hora, Ha salido",180.0,Airbus A320,R9
1825,NaN,30/Nov/2025,easyJet Europe,EC7694,Lisbon (LIS),15:20,"Retrasado, Ha salido 15:33",180.0,Airbus A320,U33
1827,NaN,30/Nov/2025,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"Retrasado, Ha salido 15:54",174.0,Airbus A320,S24
1831,NaN,30/Nov/2025,easyJet Europe,EC7173,Berlin (BER),16:30,"En hora, Ha salido",180.0,Airbus A320,S23
1834,NaN,30/Nov/2025,Air Arabia Maroc,3O374,Casablanca (CMN),17:00,"En hora, Ha salido",180.0,Airbus A320,W42
1845,NaN,30/Nov/2025,Volotea,V73700,Vitoria (VIT),18:20,"En hora, Ha salido",180.0,Airbus A320,R12
1847,NaN,30/Nov/2025,Wizz Air Malta,W43686,Iasi (IAS),18:30,"En hora, Ha salido",180.0,Airbus A320,U34
1853,NaN,30/Nov/2025,Wizz Air,W61176,Katowice (KTW),18:55,"En hora, Ha salido",180.0,Airbus A320,M8
1862,NaN,30/Nov/2025,easyJet Europe,EC3750,Milan (MXP),19:45,"Retrasado, Ha salido 19:56",180.0,Airbus A320,R11
1865,NaN,30/Nov/2025,Easyjet,U28058,London (LGW),19:45,"En hora, Ha salido",180.0,Airbus A320,M6
1869,NaN,30/Nov/2025,easyJet Europe,EC4212,Napoli (NAP),20:20,"En hora, Ha salido",180.0,Airbus A320,R9
1873,NaN,30/Nov/2025,Eurowings,EW521,Cologne-Bonn (CGN),20:35,"Retrasado, Programado 21:30",180.0,Airbus A320,U35
1876,NaN,30/Nov/2025,Eurowings,EW2521,Stuttgart (STR),20:40,"En hora, Ha salido",180.0,Airbus A320,U32
1886,NaN,30/Nov/2025,Aer Lingus,EI565,Dublin (DUB),21:05,"En hora, Ha salido",174.0,Airbus A320,W42
1891,NaN,30/Nov/2025,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"Retrasado, Ha salido 21:49",180.0,Airbus A320,U38
1896,NaN,30/Nov/2025,Volotea,V71415,Verona (VRN),21:55,"En hora, Ha salido",180.0,Airbus A320,U34

In [338]:
df_30[(df_30['Name_company'] == 'Air Arabia Maroc')]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1827,NaN,30/Nov/2025,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"Retrasado, Ha salido 15:54",174.0,Airbus A320,S24
1834,NaN,30/Nov/2025,Air Arabia Maroc,3O374,Casablanca (CMN),17:00,"En hora, Ha salido",180.0,Airbus A320,W42

In [339]:
df_30.loc[1820:1880].head(50)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1820,NaN,30/Nov/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",189.0,Boeing 737-800,NaN
1821,NaN,30/Nov/2025,Ryanair,FR3320,Milan (BGY),15:00,"En hora, Programado",189.0,Boeing 737-800,S22
1822,NaN,30/Nov/2025,Ryanair,FR774,Torino (TRN),15:15,"En hora, Ha salido",189.0,Boeing 737-800,S22
1823,NaN,30/Nov/2025,BUZZ,RR3072,Prague (PRG),15:15,"En hora, Ha salido",189.0,Boeing 737-800,S20
1824,NaN,30/Nov/2025,Transavia,TO4755,Paris (ORY),15:15,"Retrasado, Ha salido 15:28",186.0,Airbus A320neo,U31
1825,NaN,30/Nov/2025,easyJet Europe,EC7694,Lisbon (LIS),15:20,"Retrasado, Ha salido 15:33",180.0,Airbus A320,U33
1826,NaN,30/Nov/2025,Ryanair,FR6973,Rome (FCO),15:30,"Retrasado, Ha salido 15:33",197.0,Boeing 737 MAX 8,R10
1827,NaN,30/Nov/2025,Air Arabia Maroc,3O378,Tanger (TNG),15:35,"Retrasado, Ha salido 15:54",174.0,Airbus A320,S24
1828,NaN,30/Nov/2025,Wizz Air Malta,W46728,Venice (VCE),15:40,"En hora, Ha salido",239.0,Airbus A321neo,Y55
1829,NaN,30/Nov/2025,Ryanair,FR133,Berlin (BER),16:15,"En hora, Ha salido",189.0,Boeing 737-800,U35
1830,NaN,30/Nov/2025,Ryanair,FR2922,Brussels (BRU),16:15,"En hora, Ha salido",189.0,Boeing 737-800,S25
1831,NaN,30/Nov/2025,easyJet Europe,EC7173,Berlin (BER),16:30,"En hora, Ha salido",180.0,Airbus A320,S23
1832,NaN,30/Nov/2025,Ryanair,FR9814,London (STN),16:40,"En hora, Ha salido",189.0,Boeing 737-800,R11
1833,NaN,30/Nov/2025,Ryanair,FR8669,Dublin (DUB),16:55,"En hora, Ha salido",189.0,Boeing 737-800,W44
1834,NaN,30/Nov/2025,Air Arabia Maroc,3O374,Casablanca (CMN),17:00,"En hora, Ha salido",180.0,Airbus A320,W42
1835,NaN,30/Nov/2025,Ryanair,FR2250,Marrakech (RAK),17:00,"Retrasado, Ha salido 17:10",189.0,Boeing 737-800,Y57
1836,NaN,30/Nov/2025,BUZZ,RR8394,Budapest (BUD),17:15,"Retrasado, Ha salido 17:18",197.0,Boeing 737 MAX 8,Y55
1837,NaN,30/Nov/2025,Ryanair,FR5718,Bratislava (BTS),17:20,"Retrasado, Ha salido 17:25",189.0,Boeing 737-800,U33
1838,NaN,30/Nov/2025,Ryanair,FR12,Vienna (VIE),17:40,"En hora, Ha salido",189.0,Boeing 737-800,S21
1839,NaN,30/Nov/2025,Volotea,V73573,Asturias (OVD),17:40,"Retrasado, Ha salido 18:08",156.0,Airbus A319,S23
1840,NaN,30/Nov/2025,BUZZ,RR5252,Krakow (KRK),17:50,"En hora, Ha salido",189.0,Boeing 737-800,U35
1841,NaN,30/Nov/2025,Ryanair,FR1681,Frankfurt-Hahn (HHN),18:00,"En hora, Ha salido",189.0,Boeing 737-800,U32
1842,NaN,30/Nov/2025,Ryanair,FR777,Venice (VCE),18:00,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U31
1843,NaN,30/Nov/2025,Ryanair,FR6305,Milan (BGY),18:05,"En hora, Ha salido",189.0,Boeing 737-800,U37
1844,NaN,30/Nov/2025,easyJet Europe,EC7109,Geneva (GVA),18:15,"En hora, Ha salido",156.0,Airbus A319,S24
1845,NaN,30/Nov/2025,Volotea,V73700,Vitoria (VIT),18:20,"En hora, Ha salido",180.0,Airbus A320,R12
1846,NaN,30/Nov/2025,Ryanair,FR2406,Sevilla (SVQ),18:30,"En hora, Ha salido",189.0,Boeing 737-800,U33
1847,NaN,30/Nov/2025,Wizz Air Malta,W43686,Iasi (IAS),18:30,"En hora, Ha salido",180.0,Airbus A320,U34
1848,NaN,30/Nov/2025,Jet2,LS804,Manchester (MAN),18:35,"En hora, Ha salido",189.0,Boeing 737-800,S20
1849,NaN,30/Nov/2025,easyJet Europe,EC7103,"Basel, Switzerland/Mulhouse (BSL)",18:45,"Retrasado, Ha salido 18:48",156.0,Airbus A319,W45
1850,NaN,30/Nov/2025,Ryanair,FR8631,Tanger (TNG),18:45,"En hora, Ha salido",189.0,Boeing 737-800,R10
1851,NaN,30/Nov/2025,Transavia,HV6066,Rotterdam (RTM),18:50,"En hora, Ha salido",189.0,Boeing 737-800,W42
1852,NaN,30/Nov/2025,Easyjet,U25716,Southend (SEN),18:55,"En hora, Ha salido",186.0,Airbus A320neo,S25
1853,NaN,30/Nov/2025,Wizz Air,W61176,Katowice (KTW),18:55,"En hora, Ha salido",180.0,Airbus A320,M8
1854,NaN,30/Nov/2025,Wizz Air,W61478,Warsaw (WAW),19:00,"En hora, Ha salido",239.0,Airbus A321neo,S21
1855,NaN,30/Nov/2025,easyJet Europe,EC7159,Milan (LIN),19:05,"Retrasado, Ha salido 19:56",156.0,Airbus A319,S24
1856,NaN,30/Nov/2025,Wizz Air Malta,W43180,Bucharest (OTP),19:05,"En hora, Ha salido",230.0,Airbus A321,R13
1857,NaN,30/Nov/2025,Ryanair,FR6394,Dublin (DUB),19:10,"En hora, Ha salido",197.0,Boeing 737 MAX 8,S22
1858,NaN,30/Nov/2025,Ryanair,FR3160,Bristol (BRS),19:25,"Retrasado, Ha salido 19:25",189.0,Boeing 737-800,Y54
1859,NaN,30/Nov/2025,Volotea,V72165,Nantes/Atlantique (NTE),19:30,"En hora, Ha salido",156.0,Airbus A319,Y57
1860,NaN,30/Nov/2025,Wizz Air,W64406,Sofia (SOF),19:35,"En hora, Ha salido",239.0,Airbus A321neo,S20
1861,NaN,30/Nov/2025,Ryanair,FR2233,Al Aaroui (NDR),19:40,"En hora, Ha salido",189.0,Boeing 737-800,U31
1862,NaN,30/Nov/2025,easyJet Europe,EC3750,Milan (MXP),19:45,"Retrasado, Ha salido 19:56",180.0,Airbus A320,R11
1863,NaN,30/Nov/2025,Ryanair,FR5710,Napoli (NAP),19:45,"En hora, Ha salido",189.0,Boeing 737-800,U35
1864,NaN,30/Nov/2025,Ryanair,FR9015,London (STN),19:45,"En hora, Ha salido",189.0,Boeing 737-800,Y55
1865,NaN,30/Nov/2025,Easyjet,U28058,London (LGW),19:45,"En hora, Ha salido",180.0,Airbus A320,M6
1866,NaN,30/Nov/2025,Wizz Air,W64666,Larnaca (LCA),19:55,"Retrasado, Ha salido 20:52",230.0,Airbus A321,W44
1867,NaN,30/Nov/2025,Ryanair,FR8136,Ibiza (IBZ),20:10,"En hora, Ha salido",189.0,Boeing 737-800,R14
1868,NaN,30/Nov/2025,Wizz Air,W62096,Krakow (KRK),20:10,"Retrasado, Ha salido 21:04",239.0,Airbus A321neo,S20
1869,NaN,30/Nov/2025,easyJet Europe,EC4212,Napoli (NAP),20:20,"En hora, Ha salido",180.0,Airbus A320,R9

In [340]:
start, end = 1822, 1861

# Reemplazar los valores desplazando hacia arriba dentro del rango
df_30.loc[start:end, 'Gate'] = df_30.loc[start+1:end+1, 'Gate'].values

In [341]:
df_30.loc[df_30['Num_flight'] == 'FR2233', 'Gate'] = 'W'

In [342]:
# 1822 -> s20 /1860 cambiar a u31- 1861 dejar

In [343]:
df_30[(df_30['Gate'].isna())]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1815,NaN,30/Nov/2025,Transavia,HV5132,Amsterdam (AMS),14:20,"En hora, Programado",189.0,Boeing 737-800,NaN
1818,NaN,30/Nov/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"En hora, Programado",189.0,Boeing 737-800,NaN
1820,NaN,30/Nov/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",189.0,Boeing 737-800,NaN

In [344]:
df_30.loc[df_30['Num_flight'] == 'HV5132', 'Gate'] = 'U'
df_30.loc[df_30['Num_flight'] == 'BZ251', 'Gate'] = 'Y'
df_30.loc[df_30['Num_flight'] == 'QS1059', 'Gate'] = 'U'

In [345]:
df_por_fecha['30/Nov/2025'] = df_30.copy()

In [346]:
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2071       06:00   En hora, Ha salido              NaN      NaN  R10
 2072       06:05   En hora, Ha salido              NaN      NaN  S21
 2073       06:15   En hora, Ha salido              NaN      NaN  Y59
 2074       06:20   En hora, Ha salido              NaN      NaN  S23
 2075       06:35   En hora, Ha salido              NaN      NaN  U37
 ...          ...                  ...              ...      ...  ...
 2138       20:45  En hora, Programado              NaN      NaN  NaN
 2139       21:15  En hora, Programado              NaN      NaN  NaN
 2140       21:15  En hora, Programado              NaN      NaN  NaN
 2141       21:35  En hora, Programado              NaN      NaN  NaN
 2142       22:00  En hora, Programado              NaN      NaN  NaN

 [72 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido            189.0
 117      Milan (BGY)       06:10  Retrasado, Ha salido            189.0
 118     Geneva (GVA)       06:15             Ha salido            156.0
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido            189.0
 120   Budapest (BUD)       06:25             Ha salido            189.0
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido            197.0
 282    Bristol (BRS)       21:55             Ha salido            180.0
 283   Belgrade (BEG)       21:55             Ha salido            239.0
 284       Rome (FCO)       22:20             Ha salido            189.0
 285     Tirana (TIA)       22:45             Ha salido            230.0

              Aircraft Gate
 116    Boeing 737-800    U
 117    Boeing 737-800    S
 118       Airbus A319    R
 119    Boeing 737-800  NaN
 120    Boeing 737-800    R
 ..                ...  ...
 281  Boeing 737 MAX 8    S
 282       Airbus A320    M
 283    Airbus A321neo    Y
 284    Boeing 737-800    U
 285       Airbus A321    W

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 286       288.0  18/11/2025 14-12-47  easyJet Europe     EC7105
 287       289.0  18/11/2025 14-12-47         Ryanair     FR3189
 288       290.0  18/11/2025 14-12-47         Ryanair     FR2507
 289       291.0  18/11/2025 14-12-47         Ryanair     FR4545
 290       292.0  18/11/2025 14-12-47  easyJet Europe     EC8062
 ..          ...                  ...             ...        ...
 349       351.0  18/11/2025 14-12-47       Transavia     TO4759
 350       352.0  18/11/2025 14-12-47  easyJet Europe     EC1380
 351       353.0  18/11/2025 14-12-47         Ryanair     FR6394
 352       354.0  18/11/2025 14-12-47  Wizz Air Malta     W46020
 353       355.0  18/11/2025 14-12-47         Ryanair     FR4585

            Name_Destiny Time_flight flight_state  flight_capacity  \
 286        Geneva (GVA)       06:00    Ha salido            156.0
 287           Fes (FEZ)       06:15    Ha salido            189.0
 288  Cologne-Bonn (CGN)       06:20    Ha salido            197.0
 289         Porto (OPO)       06:35    Ha salido            197.0
 290        London (LGW)       07:30    Ha salido            156.0
 ..                  ...         ...          ...              ...
 349         Paris (ORY)       20:45    Ha salido            186.0
 350        Geneva (GVA)       21:15    Ha salido            180.0
 351        Dublin (DUB)       21:15   Programado            197.0
 352          Rome (FCO)       21:35    Ha salido            239.0
 353         Porto (OPO)       22:00    Ha salido            197.0

              Aircraft Gate
 286       Airbus A319    R
 287    Boeing 737-800    W
 288  Boeing 737 MAX 8    U
 289  Boeing 737 MAX 8    U
 290       Airbus A319    R
 ..                ...  ...
 349    Airbus A320neo    S
 350       Airbus A320    R
 351  Boeing 737 MAX 8    W
 352    Airbus A321neo    S
 353  Boeing 737 MAX 8    U

 [68 rows x 10 columns],
 '19/11/2025 14-33-06':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 354       356.0  19/11/2025 14-33-06         Ryanair     FR2918
 355       357.0  19/11/2025 14-33-06         Ryanair     FR3185
 356       358.0  19/11/2025 14-33-06         Ryanair     FR9406
 357       359.0  19/11/2025 14-33-06  easyJet Europe     EC7105
 358       360.0  19/11/2025 14-33-06         Ryanair      FR483
 ..          ...                  ...             ...        ...
 433       435.0  19/11/2025 14-33-06         Easyjet     U22326
 434       436.0  19/11/2025 14-33-06  easyJet Europe     EC1380
 435       437.0  19/11/2025 14-33-06  Wizz Air Malta     W43406
 436       438.0  19/11/2025 14-33-06  Wizz Air Malta     W46020
 437       439.0  19/11/2025 14-33-06         Ryanair     FR6394

           Name_Destiny Time_flight          flight_state  flight_capacity  \
 354     Brussels (BRU)       06:05             Ha salido            189.0
 355        Rabat (RBA)       06:05             Ha salido            189.0
 356          Fes (FEZ)       06:05             Ha salido            189.0
 357       Geneva (GVA)       06:10             Ha salido            156.0
 358       Malaga (AGP)       06:15             Ha salido            189.0
 ..                 ...         ...                   ...              ...
 433       London (LTN)       20:55             Ha salido            156.0
 434       Geneva (GVA)       21:15  Retrasado, Ha salido            180.0
 435  Cluj-Napoca (CLJ)       21:25  Retrasado, Ha salido            180.0
 436         Rome (FCO)       21:35             Ha salido            239.0
 437       Dublin (DUB)       22:05             Ha salido            189.0

            Aircraft Gate
 354  Boeing 737-800    U
 355  Boeing 737-800    Y
 356  Boeing 737-800  NaN
 357     Airbus A319    R
 358  Boeing 737-800    U
 ..              ...  ...
 433     Airbus A319    M
 434     Airbus A320    R
 435     Airbus A320    U
 436  Airbus A321neo    R
 437  Boeing 737-800    W

 [84 rows x 10 columns],
 '20/11/2025 14-38-34':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 0             0  20/11/2025 14-38-34         Ryanair     FR8215
 1             1  20/11/2025 14-38-34         Ryanair     FR2918
 2             2  20/11/2025 14-38-34  easyJet Europe     EC7105
 3             3  20/11/2025 14-38-34         Ryanair     FR3976
 4             4  20/11/2025 14-38-34  easyJet Europe     EC7191
 ..          ...                  ...             ...        ...
 125         126  20/11/2025 14-38-34            BUZZ     RR3035
 126         127  20/11/2025 14-38-34            BUZZ     RR4084
 127         128  20/11/2025 14-38-34  Wizz Air Malta     W46020
 128         129  20/11/2025 14-38-34        Wizz Air     W64116
 129         130  20/11/2025 14-38-34  Wizz Air Malta     W45154

        Name_Destiny Time_flight flight_state  flight_capacity  \
 0      London (STN)       06:00    Ha salido            189.0
 1    Brussels (BRU)       06:05    Ha salido            189.0
 2      Geneva (GVA)       06:10    Ha salido            156.0
 3      Dublin (DUB)       06:15    Ha salido            197.0
 4     Glasgow (GLA)       06:40    Ha salido            156.0
 ..              ...         ...          ...              ...
 125    Krakow (KRK)       21:30   Programado            197.0
 126    Warsaw (WMI)       21:30   Programado            189.0
 127      Rome (FCO)       21:35   Programado            230.0
 128  Belgrade (BEG)       22:10   Programado            230.0
 129    Tirana (TIA)       22:45   Programado            239.0

              Aircraft Gate
 0      Boeing 737-800    Y
 1      Boeing 737-800    U
 2         Airbus A319    R
 3    Boeing 737 MAX 8    W
 4         Airbus A319    R
 ..                ...  ...
 125  Boeing 737 MAX 8    R
 126    Boeing 737-800    S
 127       Airbus A321    U
 128       Airbus A321    W
 129    Airbus A321neo  NaN

 [130 rows x 10 columns],
 '21/11/2025 14-58-40':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 568       571.0  21/11/2025 14-58-40  easyJet Europe     EC7105
 569       572.0  21/11/2025 14-58-40         Ryanair     FR8183
 570       573.0  21/11/2025 14-58-40         Ryanair     FR8231
 571       574.0  21/11/2025 14-58-40         Ryanair      FR777
 572       575.0  21/11/2025 14-58-40         Ryanair      FR846
 ..          ...                  ...             ...        ...
 731       736.0  21/11/2025 14-58-40        Wizz Air     W64116
 732       737.0  21/11/2025 14-58-40         Ryanair     FR3080
 733       738.0  21/11/2025 14-58-40  Wizz Air Malta     W45154
 734       739.0  21/11/2025 14-58-40        Wizz Air     W61706
 735       740.0  21/11/2025 14-58-40         Ryanair     FR9814

        Name_Destiny Time_flight          flight_state  flight_capacity  \
 568    Geneva (GVA)       06:10             Ha salido            156.0
 569   Bologna (BLQ)       06:10             Ha salido            189.0
 570    London (STN)       06:10             Ha salido            189.0
 571    Venice (VCE)       06:20             Ha salido            189.0
 572     Milan (BGY)       06:25             Ha salido            189.0
 ..              ...         ...                   ...              ...
 731  Belgrade (BEG)       21:55  Retrasado, Ha salido            239.0
 732    Malaga (AGP)       22:30            Programado            197.0
 733    Tirana (TIA)       22:45            Programado            230.0
 734    Gdansk (GDN)       22:50             Ha salido            239.0
 735    London (STN)       23:10            Programado            189.0

              Aircraft Gate
 568       Airbus A319    R
 569    Boeing 737-800    U
 570    Boeing 737-800    Y
 571    Boeing 737-800    S
 572    Boeing 737-800    S
 ..                ...  ...
 731    Airbus A321neo    W
 732  Boeing 737 MAX 8    S
 733       Airbus A321    Y
 734    Airbus A321neo    S
 735    Boeing 737-800    W

 [168 rows x 10 columns],
 '22/Nov/2025':      Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 736         NaN   22/Nov/2025           Ryanair      FR846
 737         NaN   22/Nov/2025    easyJet Europe     EC7105
 738         NaN   22/Nov/2025           Ryanair     FR5718
 739         NaN   22/Nov/2025           Ryanair     FR4545
 740         NaN   22/Nov/2025           Ryanair     FR1342
 ..          ...           ...               ...        ...
 847         NaN   22/Nov/2025    Wizz Air Malta     W46020
 848         NaN   22/Nov/2025           Ryanair     FR3800
 849         NaN   22/Nov/2025           Ryanair     FR8574
 850         NaN   22/Nov/2025          Wizz Air     W64116
 851         NaN   22/Nov/2025  Air Arabia Maroc      3O642

                 Name_Destiny Time_flight                flight_state  \
 736              Milan (BGY)       06:00  Retrasado, Ha salido 06:15
 737             Geneva (GVA)       06:10          En hora, Ha salido
 738         Bratislava (BTS)       06:10          En hora, Ha salido
 739              Porto (OPO)       06:15          En hora, Ha salido
 740  Palma de Mallorca (PMI)       06:20          En hora, Ha salido
 ..                       ...         ...                         ...
 847               Rome (FCO)       21:35          En hora, Ha salido
 848         Birmingham (BHX)       21:55          En hora, Ha salido
 849               Rome (FCO)       22:10  Retrasado, Ha salido 22:28
 850           Belgrade (BEG)       22:10          En hora, Ha salido
 851             Tanger (TNG)       22:15          En hora, Ha salido

      flight_capacity          Aircraft Gate
 736            189.0    Boeing 737-800  S21
 737            156.0       Airbus A319   R9
 738            189.0    Boeing 737-800  S22
 739            197.0  Boeing 737 MAX 8  U31
 740            189.0    Boeing 737-800  S24
 ..               ...               ...  ...
 847            239.0    Airbus A321neo  S22
 848            189.0    Boeing 737-800  Y57
 849            189.0    Boeing 737-800  U34
 850            239.0    Airbus A321neo  Y58
 851            180.0       Airbus A320  W44

 [116 rows x 10 columns],
 '23/11/2025 15-34-22':       Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 852          NaN  23/11/2025 15-34-22         Ryanair     FR3180
 853          NaN  23/11/2025 15-34-22         Ryanair     FR2834
 854          NaN  23/11/2025 15-34-22         Ryanair     FR2918
 855          NaN  23/11/2025 15-34-22         Ryanair     FR4084
 856          NaN  23/11/2025 15-34-22         Ryanair     FR2239
 ...          ...                  ...             ...        ...
 1009         NaN  23/11/2025 15-34-22        Wizz Air     W64116
 1010         NaN  23/11/2025 15-34-22  Wizz Air Malta     W45154
 1011         NaN  23/11/2025 15-34-22         Ryanair     FR5220
 1012         NaN  23/11/2025 15-34-22        Wizz Air     W61706
 1013         NaN  23/11/2025 15-34-22         Ryanair     FR9406

          Name_Destiny Time_flight                flight_state  \
 852        Rome (FCO)       06:00                   Ha salido
 853   Charleroi (CRL)       06:10                   Ha salido
 854    Brussels (BRU)       06:25                   Ha salido
 855      Warsaw (WMI)       06:25        Retrasado, Ha salido
 856   Marrakech (RAK)       06:30                   Ha salido
 ...               ...         ...                         ...
 1009   Belgrade (BEG)       21:55  Retrasado, Ha salido 22:11
 1010     Tirana (TIA)       22:45         En hora, Programado
 1011    Bologna (BLQ)       22:50         En hora, Programado
 1012     Gdansk (GDN)       22:50          En hora, Ha salido
 1013        Fes (FEZ)       23:15          En hora, Ha salido

       flight_capacity          Aircraft Gate
 852             189.0    Boeing 737-800  U34
 853             197.0  Boeing 737 MAX 8  S20
 854             189.0    Boeing 737-800  R12
 855             189.0    Boeing 737-800  S21

In [347]:
df_mes1 = pd.concat([df_semanac, df_24, df_25, df_26, df_27, df_28, df_29, df_30 ], ignore_index=True)

In [348]:
df_mes1.reset_index(drop=True, inplace=True)

In [349]:
df_mes1.to_csv("vuelos_bcn_m1.csv")

In [350]:
#df_final = pd.concat(df_por_fecha.values(), ignore_index=True)