In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv("vuelos_bcn_sindup.csv") 
df.head(10)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,0.0,16/11/2025 23-03-05,Ryanair,FR3166,Palermo (PMO),11:00,Ha salido,NaN,NaN,NaN
1,1.0,16/11/2025 23-03-05,Norwegian Air Sweden AOC,D81741,Oslo (OSL),11:15,Ha salido,197.0,Boeing 737 MAX 8-200,NaN
2,2.0,16/11/2025 23-03-05,Aer Lingus,EI563,Dublin (DUB),11:30,Ha salido,189.0,Boeing 737-8AS,NaN
3,3.0,16/11/2025 23-03-05,easyJet Europe,EC7139,Rennes/Saint-Jacques (RNS),11:45,Ha salido,NaN,NaN,NaN
4,4.0,16/11/2025 23-03-05,Icelandair,FI597,Keflavik (KEF),11:50,Ha salido,NaN,NaN,NaN
5,5.0,16/11/2025 23-03-05,Lauda Europe,LW2889,Palma de Mallorca (PMI),11:55,Ha salido,NaN,NaN,R
6,6.0,16/11/2025 23-03-05,Ryanair,FR3129,Ibiza (IBZ),12:05,"Retrasado, Ha salido",189.0,Boeing 737-8AS,NaN
7,7.0,16/11/2025 23-03-05,Ryanair,FR3976,Dublin (DUB),12:25,"Retrasado, Ha salido",NaN,NaN,NaN
8,8.0,16/11/2025 23-03-05,Ryanair,FR1527,Valletta (MLA),12:30,Ha salido,NaN,NaN,NaN
9,9.0,16/11/2025 23-03-05,Ryanair,FR2402,Sevilla (SVQ),12:30,Ha salido,189.0,Boeing 737-8AS,NaN

In [3]:
# Dividir en diccionario por fecha
df_por_fecha = {fecha: df_fecha.copy() for fecha, df_fecha in df.groupby('fecha_scrapeo')}
df_por_fecha

{'01/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 1902         NaN   01/Dic/2025         Ryanair     FR3180        Rome (FCO)
 1903         NaN   01/Dic/2025         Ryanair      FR846       Milan (BGY)
 1904         NaN   01/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 1905         NaN   01/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 1906         NaN   01/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2066         NaN   01/Dic/2025  Wizz Air Malta     W46728      Venice (VCE)
 2067         NaN   01/Dic/2025         Ryanair     FR8574        Rome (FCO)
 2068         NaN   01/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 2069         NaN   01/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 2070         NaN   01/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 1902       06:00   En hora, Ha salido              NaN      NaN  S25
 1903       06:10   En hora, Ha salido              NaN      NaN  S20
 1904       06:15   En hora, Ha salido              NaN      NaN  R11
 1905       06:20   En hora, Ha salido              NaN      NaN  W45
 1906       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2066       22:00   En hora, Ha salido              NaN      NaN  S22
 2067       22:20  En hora, Programado              NaN      NaN  U33
 2068       22:35  En hora, Programado              NaN      NaN  R11
 2069       22:45  En hora, Programado              NaN      NaN  W44
 2070       23:00  En hora, Programado              NaN      NaN  Y55

 [169 rows x 10 columns],
 '02/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight        Name_Destiny  \
 2071         NaN   02/Dic/2025  easyJet Europe     EC7105        Geneva (GVA)
 2072         NaN   02/Dic/2025         Ryanair     FR2918      Brussels (BRU)
 2073         NaN   02/Dic/2025         Ryanair     FR3189           Fes (FEZ)
 2074         NaN   02/Dic/2025         Ryanair     FR2507  Cologne-Bonn (CGN)
 2075         NaN   02/Dic/2025         Ryanair     FR4545         Porto (OPO)
 ...          ...           ...             ...        ...                 ...
 2138         NaN   02/Dic/2025       Transavia     TO4759         Paris (ORY)
 2139         NaN   02/Dic/2025  easyJet Europe     EC1380        Geneva (GVA)
 2140         NaN   02/Dic/2025         Ryanair     FR6394        Dublin (DUB)
 2141         NaN   02/Dic/2025  Wizz Air Malta     W46020          Rome (FCO)
 2142         NaN   02/Dic/2025         Ryanair     FR4585         Porto (OPO)

      Time_flight                 flight_state  flight_capacity Aircraft Gate
 2071       06:00           En hora, Ha salido              NaN      NaN  R10
 2072       06:05           En hora, Ha salido              NaN      NaN  S21
 2073       06:15           En hora, Ha salido              NaN      NaN  Y59
 2074       06:20           En hora, Ha salido              NaN      NaN  S23
 2075       06:35           En hora, Ha salido              NaN      NaN  U37
 ...          ...                          ...              ...      ...  ...
 2138       20:45           En hora, Ha salido              NaN      NaN  S25
 2139       21:15  Retrasado, Programado 21:52              NaN      NaN  R13
 2140       21:15           En hora, Ha salido              NaN      NaN  Y58
 2141       21:35           En hora, Ha salido              NaN      NaN  S24
 2142       22:00           En hora, Ha salido              NaN      NaN  S21

 [72 rows x 10 columns],
 '03/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight       Name_Destiny  \
 2143         NaN   03/Dic/2025         Ryanair     FR2918     Brussels (BRU)
 2144         NaN   03/Dic/2025         Ryanair     FR3185        Rabat (RBA)
 2145         NaN   03/Dic/2025         Ryanair     FR9406          Fes (FEZ)
 2146         NaN   03/Dic/2025  easyJet Europe     EC7105       Geneva (GVA)
 2147         NaN   03/Dic/2025         Ryanair      FR483       Malaga (AGP)
 ...          ...           ...             ...        ...                ...
 2228         NaN   03/Dic/2025         Easyjet     U22326       London (LTN)
 2229         NaN   03/Dic/2025  easyJet Europe     EC1380       Geneva (GVA)
 2230         NaN   03/Dic/2025  Wizz Air Malta     W43406  Cluj-Napoca (CLJ)
 2231         NaN   03/Dic/2025  Wizz Air Malta     W46020         Rome (FCO)
 2232         NaN   03/Dic/2025         Ryanair     FR6394       Dublin (DUB)

      Time_flight                 flight_state  flight_capacity  \
 2143       06:05           En hora, Ha salido              NaN
 2144       06:05           En hora, Ha salido              NaN
 2145       06:05           En hora, Ha salido              NaN
 2146       06:10           En hora, Ha salido              NaN
 2147       06:15           En hora, Ha salido            189.0
 ...          ...                          ...              ...
 2228       20:55           En hora, Ha salido              NaN
 2229       21:15  Retrasado, Programado 22:17              NaN
 2230       21:25           En hora, Ha salido              NaN
 2231       21:35   Retrasado, Ha salido 21:46              NaN
 2232       22:05          En hora, Programado              NaN

             Aircraft Gate
 2143             NaN  S23
 2144             NaN  W46
 2145             NaN  W45
 2146             NaN  R10
 2147  Boeing 737-800  U41
 ...              ...  ...
 2228             NaN   M6
 2229             NaN  R13
 2230             NaN  S21
 2231             NaN  S22
 2232             NaN  W44

 [90 rows x 10 columns],
 '04/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight    Name_Destiny  \
 2233         NaN   04/Dic/2025         Ryanair     FR8215    London (STN)
 2234         NaN   04/Dic/2025  easyJet Europe     EC7105    Geneva (GVA)
 2235         NaN   04/Dic/2025         Ryanair     FR3976    Dublin (DUB)
 2236         NaN   04/Dic/2025  easyJet Europe     EC7191   Glasgow (GLA)
 2237         NaN   04/Dic/2025         Ryanair     FR3049    Krakow (KRK)
 ...          ...           ...             ...        ...             ...
 2350         NaN   04/Dic/2025            BUZZ     RR3035    Krakow (KRK)
 2351         NaN   04/Dic/2025            BUZZ     RR4084    Warsaw (WMI)
 2352         NaN   04/Dic/2025  Wizz Air Malta     W46020      Rome (FCO)
 2353         NaN   04/Dic/2025        Wizz Air     W64116  Belgrade (BEG)
 2354         NaN   04/Dic/2025  Wizz Air Malta     W45154    Tirana (TIA)

      Time_flight                 flight_state  flight_capacity Aircraft Gate
 2233       06:00           En hora, Ha salido              NaN     B738  W46
 2234       06:10           En hora, Ha salido              NaN      NaN  R10
 2235       06:15           En hora, Ha salido              NaN     B38M  W42
 2236       06:40   Retrasado, Ha salido 07:06              NaN      NaN   M6
 2237       06:40           En hora, Ha salido              NaN      NaN  U33
 ...          ...                          ...              ...      ...  ...
 2350       21:30  Retrasado, Programado 22:20              NaN      NaN  U34
 2351       21:30           En hora, Ha salido              NaN      NaN  U32
 2352       21:35   Retrasado, Ha salido 21:50              NaN     A21N  S23
 2353       22:10           En hora, Ha salido              NaN      NaN  Y53
 2354       22:45          En hora, Programado              NaN      NaN  W44

 [122 rows x 10 columns],
 '05/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight   Name_Destiny  \
 2355         NaN   05/Dic/2025  easyJet Europe     EC7105   Geneva (GVA)
 2356         NaN   05/Dic/2025         Ryanair     FR8183  Bologna (BLQ)
 2357         NaN   05/Dic/2025         Ryanair     FR8231   London (STN)
 2358         NaN   05/Dic/2025         Ryanair      FR777   Venice (VCE)
 2359         NaN   05/Dic/2025         Ryanair      FR846    Milan (BGY)
 ...          ...           ...             ...        ...            ...
 2527         NaN   05/Dic/2025         Easyjet     U28060   London (LGW)
 2528         NaN   05/Dic/2025         Ryanair     FR3080   Malaga (AGP)
 2529         NaN   05/Dic/2025  Wizz Air Malta     W45154   Tirana (TIA)
 2530         NaN   05/Dic/2025        Wizz Air     W61706   Gdansk (GDN)
 2531         NaN   05/Dic/2025         Ryanair     FR9814   London (STN)

      Time_flight                 flight_state  flight_capacity  \
 2355       06:10           En hora, Ha salido              NaN
 2356       06:10           En hora, Ha salido              NaN
 2357       06:10           En hora, Ha salido              NaN
 2358       06:20           En hora, Ha salido              NaN
 2359       06:25           En hora, Ha salido              NaN
 ...          ...                          ...              ...
 2527       22:15  Retrasado, Programado 22:32              NaN
 2528       22:30  Retrasado, Programado 23:25            197.0
 2529       22:45          En hora, Programado              NaN
 2530       22:50  Retrasado, Programado 23:24              NaN
 2531       23:10          En hora, Programado              NaN

               Aircraft Gate
 2355               NaN  R10
 2356               NaN  S24
 2357               NaN  Y59
 2358               NaN  U36
 2359               NaN  U35
 ...                ...  ...
 2527               NaN   M6
 2528  Boeing 737 MAX 8    U
 2529               NaN  Y58
 2530               NaN    U
 2531               NaN    W

 [177 rows x 10 columns],
 '06/Dic/2025':       Unnamed: 0 fecha_scrapeo      Name_company Num_flight  \
 2532         NaN   06/Dic/2025           Ryanair      FR846
 2533         NaN   06/Dic/2025    easyJet Europe     EC7105
 2534         NaN   06/Dic/2025           Ryanair     FR5718
 2535         NaN   06/Dic/2025           Ryanair     FR4545
 2536         NaN   06/Dic/2025           Ryanair     FR1342
 ...          ...           ...               ...        ...
 2656         NaN   06/Dic/2025    Wizz Air Malta     W46020
 2657         NaN   06/Dic/2025           Ryanair     FR3800
 2658         NaN   06/Dic/2025           Ryanair     FR8574
 2659         NaN   06/Dic/2025          Wizz Air     W64116
 2660         NaN   06/Dic/2025  Air Arabia Maroc      3O642

                  Name_Destiny Time_flight                flight_state  \
 2532              Milan (BGY)       06:00          En hora, Ha salido
 2533             Geneva (GVA)       06:10          En hora, Ha salido
 2534         Bratislava (BTS)       06:10          En hora, Ha salido
 2535              Porto (OPO)       06:15  Retrasado, Ha salido 06:30
 2536  Palma de Mallorca (PMI)       06:20  Retrasado, Ha salido 06:32
 ...                       ...         ...                         ...
 2656               Rome (FCO)       21:35  Retrasado, Ha salido 21:45
 2657         Birmingham (BHX)       21:55          En hora, Ha salido
 2658               Rome (FCO)       22:10         En hora, Programado
 2659           Belgrade (BEG)       22:10          En hora, Ha salido
 2660             Tanger (TNG)       22:15          En hora, Ha salido

       flight_capacity        Aircraft Gate
 2532              NaN             NaN  S22
 2533              NaN             NaN  R12
 2534              NaN             NaN  S24
 2535              NaN            B38M  U31
 2536            189.0  Boeing 737-800  R11
 ...               ...             ...  ...
 2656              NaN             NaN  S20
 2657              NaN             NaN  Y58
 2658              NaN             NaN  U32
 2659              NaN             NaN  W43
 2660              NaN             NaN  Y55

 [129 rows x 10 columns],
 '07/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight     Name_Destiny  \
 2661         NaN   07/Dic/2025         Ryanair     FR3180       Rome (FCO)
 2662         NaN   07/Dic/2025         Ryanair     FR2834  Charleroi (CRL)
 2663         NaN   07/Dic/2025         Ryanair     FR2918   Brussels (BRU)
 2664         NaN   07/Dic/2025         Ryanair     FR4084     Warsaw (WMI)
 2665         NaN   07/Dic/2025         Ryanair     FR2239  Marrakech (RAK)
 ...          ...           ...             ...        ...              ...
 2825         NaN   07/Dic/2025        Wizz Air     W64116   Belgrade (BEG)
 2826         NaN   07/Dic/2025  Wizz Air Malta     W45154     Tirana (TIA)
 2827         NaN   07/Dic/2025         Ryanair     FR5220    Bologna (BLQ)
 2828         NaN   07/Dic/2025        Wizz Air     W61706     Gdansk (GDN)
 2829         NaN   07/Dic/2025         Ryanair     FR9406        Fes (FEZ)

      Time_flight                flight_state  flight_capacity Aircraft Gate
 2661       06:00          En hora, Ha salido              NaN      NaN  U36
 2662       06:10          En hora, Ha salido              NaN      NaN  S22
 2663       06:25  Retrasado, Ha salido 08:00              NaN      NaN  U37
 2664       06:25          En hora, Ha salido              NaN     B738  U34
 2665       06:30          En hora, Ha salido              NaN      NaN  Y54
 ...          ...                         ...              ...      ...  ...
 2825       21:55          En hora, Ha salido              NaN      NaN  W43
 2826       22:45         En hora, Programado              NaN      NaN  W44
 2827       22:50         En hora, Programado              NaN      NaN  U31
 2828       22:50         En hora, Programado              NaN      NaN  S22
 2829       23:15         En hora, Programado              NaN      NaN  Y54

 [169 rows x 10 columns],
 '08/Dic/2025':       Unnamed: 0 fecha_scrapeo    Name_company Num_flight      Name_Destiny  \
 2830         NaN   08/Dic/2025         Ryanair     FR3180        Rome (FCO)
 2831         NaN   08/Dic/2025         Ryanair      FR846       Milan (BGY)
 2832         NaN   08/Dic/2025  easyJet Europe     EC7105      Geneva (GVA)
 2833         NaN   08/Dic/2025         Ryanair     FR2233   Al Aaroui (NDR)
 2834         NaN   08/Dic/2025         Ryanair     FR8384    Budapest (BUD)
 ...          ...           ...             ...        ...               ...
 2999         NaN   08/Dic/2025         Ryanair     FR8574        Rome (FCO)
 3000         NaN   08/Dic/2025  easyJet Europe     EC7682      Lisbon (LIS)
 3001         NaN   08/Dic/2025  Wizz Air Malta     W45154      Tirana (TIA)
 3002         NaN   08/Dic/2025  Wizz Air Malta     W46020        Rome (FCO)
 3003         NaN   08/Dic/2025         Ryanair     FR3800  Birmingham (BHX)

      Time_flight         flight_state  flight_capacity Aircraft Gate
 2830       06:00   En hora, Ha salido              NaN      NaN  U31
 2831       06:10   En hora, Ha salido              NaN      NaN  S20
 2832       06:15   En hora, Ha salido              NaN      NaN  R10
 2833       06:20   En hora, Ha salido              NaN      NaN  Y53
 2834       06:25   En hora, Ha salido              NaN      NaN  U33
 ...          ...                  ...              ...      ...  ...
 2999       22:20  En hora, Programado              NaN      NaN  NaN
 3000       22:35  En hora, Programado              NaN      NaN  NaN
 3001       22:45  En hora, Programado              NaN      NaN  NaN
 3002       22:55  En hora, Programado              NaN      NaN  NaN
 3003       23:00  En hora, Programado              NaN      NaN  NaN

 [174 rows x 10 columns],
 '16/11/2025 23-03-05':      Unnamed: 0        fecha_scrapeo              Name_company Num_flight  \
 0           0.0  16/11/2025 23-03-05                   Ryanair     FR3166
 1           1.0  16/11/2025 23-03-05  Norwegian Air Sweden AOC     D81741
 2           2.0  16/11/2025 23-03-05                Aer Lingus      EI563
 3           3.0  16/11/2025 23-03-05            easyJet Europe     EC7139
 4           4.0  16/11/2025 23-03-05                Icelandair      FI597
 ..          ...                  ...                       ...        ...
 111       113.0  16/11/2025 23-03-05                  Wizz Air     W64116
 112       114.0  16/11/2025 23-03-05            Wizz Air Malta     W45154
 113       115.0  16/11/2025 23-03-05                   Ryanair     FR5220
 114       116.0  16/11/2025 23-03-05                  Wizz Air     W61706
 115       117.0  16/11/2025 23-03-05                   Ryanair     FR9406

                    Name_Destiny Time_flight          flight_state  \
 0                 Palermo (PMO)       11:00             Ha salido
 1                    Oslo (OSL)       11:15             Ha salido
 2                  Dublin (DUB)       11:30             Ha salido
 3    Rennes/Saint-Jacques (RNS)       11:45             Ha salido
 4                Keflavik (KEF)       11:50             Ha salido
 ..                          ...         ...                   ...
 111              Belgrade (BEG)       21:55  Retrasado, Ha salido
 112                Tirana (TIA)       22:45             Ha salido
 113               Bologna (BLQ)       22:50  Retrasado, Ha salido
 114                Gdansk (GDN)       22:50             Ha salido
 115                   Fes (FEZ)       23:15             Ha salido

      flight_capacity              Aircraft Gate
 0                NaN                   NaN  NaN
 1              197.0  Boeing 737 MAX 8-200  NaN
 2              189.0        Boeing 737-8AS  NaN
 3                NaN                   NaN  NaN
 4                NaN                   NaN  NaN
 ..               ...                   ...  ...
 111              NaN                   NaN  NaN
 112              NaN                   NaN  NaN
 113              NaN                   NaN  NaN
 114              NaN                   NaN  NaN
 115              NaN                   NaN  NaN

 [116 rows x 10 columns],
 '17/11/2025 14-06-56':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \
 116       118.0  17/11/2025 14-06-56         Ryanair     FR3180
 117       119.0  17/11/2025 14-06-56         Ryanair      FR846
 118       120.0  17/11/2025 14-06-56  easyJet Europe     EC7105
 119       121.0  17/11/2025 14-06-56         Ryanair     FR2233
 120       122.0  17/11/2025 14-06-56         Ryanair     FR8384
 ..          ...                  ...             ...        ...
 281       283.0  17/11/2025 14-06-56         Ryanair     FR2250
 282       284.0  17/11/2025 14-06-56         Easyjet     U22706
 283       285.0  17/11/2025 14-06-56        Wizz Air     W64116
 284       286.0  17/11/2025 14-06-56         Ryanair     FR8574
 285       287.0  17/11/2025 14-06-56  Wizz Air Malta     W45154

         Name_Destiny Time_flight          flight_state  flight_capacity  \
 116       Rome (FCO)       06:00             Ha salido              NaN
 117      Milan (BGY)       06:10  Retrasado, Ha salido              NaN
 118     Geneva (GVA)       06:15             Ha salido              NaN
 119  Al Aaroui (NDR)       06:20  Retrasado, Ha salido              NaN
 120   Budapest (BUD)       06:25             Ha salido              NaN
 ..               ...         ...                   ...              ...
 281  Marrakech (RAK)       21:50             Ha salido              NaN
 282    Bristol (BRS)       21:55             Ha salido              NaN
 283   Belgrade (BEG)       21:55             Ha salido              NaN
 284       Rome (FCO)       22:20             Ha salido              NaN
 285     Tirana (TIA)       22:45             Ha salido              NaN

     Aircraft Gate
 116      NaN  NaN
 117      NaN  NaN
 118      NaN  NaN
 119      NaN  NaN
 120      NaN  NaN
 ..       ...  ...
 281      NaN  NaN
 282      NaN  NaN
 283      NaN  NaN
 284      NaN  NaN
 285      NaN  NaN

 [170 rows x 10 columns],
 '18/11/2025 14-12-47':      Unnamed: 0        fecha_scrapeo    Name_company Num_flight  \

In [4]:
df_01 = df_por_fecha['01/Dic/2025'].copy()
df_01
# Lunes

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1902,NaN,01/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,S25
1903,NaN,01/Dic/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",NaN,NaN,S20
1904,NaN,01/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",NaN,NaN,R11
1905,NaN,01/Dic/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",NaN,NaN,W45
1906,NaN,01/Dic/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",NaN,NaN,U33
...,...,...,...,...,...,...,...,...,...,...
2066,NaN,01/Dic/2025,Wizz Air Malta,W46728,Venice (VCE),22:00,"En hora, Ha salido",NaN,NaN,S22
2067,NaN,01/Dic/2025,Ryanair,FR8574,Rome (FCO),22:20,"En hora, Programado",NaN,NaN,U33
2068,NaN,01/Dic/2025,easyJet Europe,EC7682,Lisbon (LIS),22:35,"En hora, Programado",NaN,NaN,R11
2069,NaN,01/Dic/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,W44
2070,NaN,01/Dic/2025,Ryanair,FR3800,Birmingham (BHX),23:00,"En hora, Programado",NaN,NaN,Y55

In [5]:
df_01.isna().sum()

Unnamed: 0         169
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    162
Aircraft           149
Gate                 4
dtype: int64

In [6]:
df_01.loc[1990:2015]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1990,NaN,01/Dic/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",NaN,NaN,NaN
1991,NaN,01/Dic/2025,Air Arabia Maroc,3O376,Al Aaroui (NDR),15:00,"En hora, Programado",NaN,NaN,Y55
1992,NaN,01/Dic/2025,Ryanair,FR3146,Oujda (OUD),15:10,"Retrasado, Ha salido 15:13",NaN,NaN,Y55
1993,NaN,01/Dic/2025,Ryanair,FR2330,Al Aaroui (NDR),15:15,"En hora, Ha salido",NaN,NaN,W42
1994,NaN,01/Dic/2025,Ryanair,FR1681,Frankfurt-Hahn (HHN),15:35,"En hora, Ha salido",NaN,NaN,Y57
1995,NaN,01/Dic/2025,Wizz Air,W61412,Warsaw (WMI),15:40,"En hora, Ha salido",NaN,NaN,U31
1996,NaN,01/Dic/2025,Pegasus Airlines,PC1094,Istanbul (SAW),15:45,"Retrasado, Ha salido 15:50",NaN,NaN,U32
1997,NaN,01/Dic/2025,Ryanair,FR867,Venice (VCE),16:05,"Retrasado, Ha salido 16:06",NaN,NaN,W45
1998,NaN,01/Dic/2025,Ryanair,FR9811,London (STN),16:05,"En hora, Ha salido",NaN,NaN,U35
1999,NaN,01/Dic/2025,Wizz Air Malta,W43564,Timisoara (TSR),16:25,"Retrasado, Ha salido 16:55",NaN,NaN,Y54
2000,NaN,01/Dic/2025,Volotea,V73735,Murcia (RMU),16:35,"En hora, Ha salido",NaN,NaN,R13
2001,NaN,01/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),16:45,"En hora, Ha salido",NaN,NaN,R14
2002,NaN,01/Dic/2025,Ryanair,FR5718,Bratislava (BTS),16:50,"Retrasado, Ha salido 17:02",NaN,B38M,S21
2003,NaN,01/Dic/2025,Ryanair,FR6305,Milan (BGY),16:50,"Retrasado, Ha salido 18:42",NaN,NaN,S24
2004,NaN,01/Dic/2025,Ryanair,FR6874,Dublin (DUB),16:55,"En hora, Ha salido",NaN,NaN,U33
2005,NaN,01/Dic/2025,Easyjet,U23372,Liverpool (LPL),17:00,"En hora, Ha salido",NaN,NaN,W46
2006,NaN,01/Dic/2025,Ryanair,FR5270,Manchester (MAN),17:05,En hora,156.0,Airbus A319,M
2007,NaN,01/Dic/2025,BUZZ,RR6300,Sofia (SOF),17:05,"En hora, Ha salido",NaN,NaN,W42
2008,NaN,01/Dic/2025,easyJet Europe,EC7173,Berlin (BER),17:10,"En hora, Ha salido",NaN,NaN,S24
2009,NaN,01/Dic/2025,Volotea,V73700,Vitoria (VIT),17:15,"En hora, Ha salido",NaN,NaN,R10
2010,NaN,01/Dic/2025,Wizz Air,W67920,Kopitnari (KUT),17:15,"En hora, Ha salido",NaN,NaN,S23
2011,NaN,01/Dic/2025,Ryanair,FR1786,Vilnius (VNO),17:30,"En hora, Ha salido",NaN,NaN,W44
2012,NaN,01/Dic/2025,Ryanair,FR2922,Brussels (BRU),17:30,"Retrasado, Ha salido 18:20",NaN,NaN,U32
2013,NaN,01/Dic/2025,easyJet Europe,EC3737,Milan (MXP),17:35,"En hora, Ha salido",NaN,B738,U34
2014,NaN,01/Dic/2025,easyJet Europe,EC7199,Edinburgh (EDI),17:35,"En hora, Ha salido",NaN,NaN,M8
2015,NaN,01/Dic/2025,Transavia,HV5134,Amsterdam (AMS),17:50,"Retrasado, Ha salido 18:41",NaN,NaN,S22

In [7]:
# 2004 -> U23372 M / 2013 EC3737 R

In [8]:
# 1992 y-> w / 2013 mantener igual

In [9]:
# 2013 subir a 2012

In [10]:
# 2011 error no es w es u

In [11]:
# 17;10  y 10:35 milan u34 -> R

In [12]:
# Rango a corregir
start, end = 1992,2013

# Reemplazar los valores desplazando hacia arriba dentro del rango
df_01.loc[start:end, 'Gate'] = df_01.loc[start+1:end+1, 'Gate'].values

In [13]:
df_01.loc[1990:2015]

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1990,NaN,01/Dic/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",NaN,NaN,NaN
1991,NaN,01/Dic/2025,Air Arabia Maroc,3O376,Al Aaroui (NDR),15:00,"En hora, Programado",NaN,NaN,Y55
1992,NaN,01/Dic/2025,Ryanair,FR3146,Oujda (OUD),15:10,"Retrasado, Ha salido 15:13",NaN,NaN,W42
1993,NaN,01/Dic/2025,Ryanair,FR2330,Al Aaroui (NDR),15:15,"En hora, Ha salido",NaN,NaN,Y57
1994,NaN,01/Dic/2025,Ryanair,FR1681,Frankfurt-Hahn (HHN),15:35,"En hora, Ha salido",NaN,NaN,U31
1995,NaN,01/Dic/2025,Wizz Air,W61412,Warsaw (WMI),15:40,"En hora, Ha salido",NaN,NaN,U32
1996,NaN,01/Dic/2025,Pegasus Airlines,PC1094,Istanbul (SAW),15:45,"Retrasado, Ha salido 15:50",NaN,NaN,W45
1997,NaN,01/Dic/2025,Ryanair,FR867,Venice (VCE),16:05,"Retrasado, Ha salido 16:06",NaN,NaN,U35
1998,NaN,01/Dic/2025,Ryanair,FR9811,London (STN),16:05,"En hora, Ha salido",NaN,NaN,Y54
1999,NaN,01/Dic/2025,Wizz Air Malta,W43564,Timisoara (TSR),16:25,"Retrasado, Ha salido 16:55",NaN,NaN,R13
2000,NaN,01/Dic/2025,Volotea,V73735,Murcia (RMU),16:35,"En hora, Ha salido",NaN,NaN,R14
2001,NaN,01/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),16:45,"En hora, Ha salido",NaN,NaN,S21
2002,NaN,01/Dic/2025,Ryanair,FR5718,Bratislava (BTS),16:50,"Retrasado, Ha salido 17:02",NaN,B38M,S24
2003,NaN,01/Dic/2025,Ryanair,FR6305,Milan (BGY),16:50,"Retrasado, Ha salido 18:42",NaN,NaN,U33
2004,NaN,01/Dic/2025,Ryanair,FR6874,Dublin (DUB),16:55,"En hora, Ha salido",NaN,NaN,W46
2005,NaN,01/Dic/2025,Easyjet,U23372,Liverpool (LPL),17:00,"En hora, Ha salido",NaN,NaN,M
2006,NaN,01/Dic/2025,Ryanair,FR5270,Manchester (MAN),17:05,En hora,156.0,Airbus A319,W42
2007,NaN,01/Dic/2025,BUZZ,RR6300,Sofia (SOF),17:05,"En hora, Ha salido",NaN,NaN,S24
2008,NaN,01/Dic/2025,easyJet Europe,EC7173,Berlin (BER),17:10,"En hora, Ha salido",NaN,NaN,R10
2009,NaN,01/Dic/2025,Volotea,V73700,Vitoria (VIT),17:15,"En hora, Ha salido",NaN,NaN,S23
2010,NaN,01/Dic/2025,Wizz Air,W67920,Kopitnari (KUT),17:15,"En hora, Ha salido",NaN,NaN,W44
2011,NaN,01/Dic/2025,Ryanair,FR1786,Vilnius (VNO),17:30,"En hora, Ha salido",NaN,NaN,U32
2012,NaN,01/Dic/2025,Ryanair,FR2922,Brussels (BRU),17:30,"Retrasado, Ha salido 18:20",NaN,NaN,U34
2013,NaN,01/Dic/2025,easyJet Europe,EC3737,Milan (MXP),17:35,"En hora, Ha salido",NaN,B738,M8
2014,NaN,01/Dic/2025,easyJet Europe,EC7199,Edinburgh (EDI),17:35,"En hora, Ha salido",NaN,NaN,M8
2015,NaN,01/Dic/2025,Transavia,HV5134,Amsterdam (AMS),17:50,"Retrasado, Ha salido 18:41",NaN,NaN,S22

In [14]:
df_01.loc[df_01['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR5270', 'flight_capacity'] = 189

In [15]:
df_01.loc[df_01['Num_flight'] == 'EC3737', 'Gate'] = 'R'
df_01.loc[df_01['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC3737', 'flight_capacity'] = 156

In [16]:
df_01[(df_01['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1902,NaN,01/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,S25
1903,NaN,01/Dic/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",NaN,NaN,S20
1904,NaN,01/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",NaN,NaN,R11
1905,NaN,01/Dic/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",NaN,NaN,W45
1906,NaN,01/Dic/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",NaN,NaN,U33
1907,NaN,01/Dic/2025,Ryanair,FR3078,Lisbon (LIS),06:30,"En hora, Ha salido",NaN,NaN,S23
1908,NaN,01/Dic/2025,easyJet Europe,EC8062,London (LGW),06:45,"Retrasado, Ha salido 07:04",NaN,NaN,M6
1909,NaN,01/Dic/2025,Ryanair,FR3035,Krakow (KRK),06:45,"En hora, Ha salido",NaN,B738,U32
1910,NaN,01/Dic/2025,Ryanair,FR8215,London (STN),06:45,"En hora, Ha salido",NaN,B38M,Y54
1911,NaN,01/Dic/2025,easyJet Europe,EC7141,Strasbourg (SXB),07:20,"En hora, Ha salido",NaN,NaN,R9
1912,NaN,01/Dic/2025,easyJet Europe,EC7151,Milan (MXP),07:20,"En hora, Ha salido",NaN,NaN,R10
1913,NaN,01/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),07:35,"En hora, Ha salido",NaN,NaN,S22
1916,NaN,01/Dic/2025,Norwegian Air Sweden AOC,D85510,Copenhagen (CPH),08:00,"En hora, Ha salido",NaN,NaN,R13
1917,NaN,01/Dic/2025,Ryanair,FR58,Napoli (NAP),08:35,"Retrasado, Ha salido 08:45",NaN,NaN,U31
1918,NaN,01/Dic/2025,Ryanair,FR575,Bologna (BLQ),08:40,"En hora, Ha salido",NaN,NaN,S21
1919,NaN,01/Dic/2025,easyJet Europe,EC1376,Geneva (GVA),08:45,"En hora, Ha salido",NaN,NaN,R11
1920,NaN,01/Dic/2025,Lauda Europe,LW12,Vienna (VIE),09:00,"En hora, Ha salido",NaN,NaN,S24
1921,NaN,01/Dic/2025,Ryanair,FR6078,Ouarzazate (OZZ),09:05,"En hora, Ha salido",NaN,NaN,Y55
1922,NaN,01/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"En hora, Ha salido",NaN,NaN,U33
1923,NaN,01/Dic/2025,Volotea,V72327,Strasbourg (SXB),09:10,"Retrasado, Ha salido 09:23",NaN,A319,R13
1924,NaN,01/Dic/2025,Air Arabia Maroc,3O398,Rabat (RBA),09:20,"En hora, Ha salido",NaN,NaN,Y58
1925,NaN,01/Dic/2025,Eurowings,EW2521,Stuttgart (STR),09:20,"Retrasado, Ha salido 09:59",NaN,NaN,S21
1926,NaN,01/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,U34
1927,NaN,01/Dic/2025,Wizz Air Malta,W45088,Tirana (TIA),09:25,"En hora, Ha salido",NaN,NaN,W46
1928,NaN,01/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"Retrasado, Ha salido 09:38",NaN,NaN,U32
1929,NaN,01/Dic/2025,Volotea,V73573,Asturias (OVD),09:30,"En hora, Ha salido",NaN,NaN,S23
1930,NaN,01/Dic/2025,easyJet Europe,EC1030,"Basel, Switzerland/Mulhouse (BSL)",09:35,"En hora, Ha salido",NaN,NaN,R10
1931,NaN,01/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:40,"En hora, Ha salido",NaN,NaN,U35
1932,NaN,01/Dic/2025,Transavia,HV6062,Rotterdam (RTM),09:40,"En hora, Ha salido",NaN,NaN,S22
1933,NaN,01/Dic/2025,Eurowings,EW9441,Dusseldorf (DUS),09:45,"En hora, Ha salido",NaN,A321,R14

In [17]:
df_01.loc[df_01['Aircraft'] == 'B738', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Aircraft'] == 'B38M', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Aircraft'] == 'A320', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Aircraft'] == 'A21N', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Aircraft'] == 'A20N', 'Aircraft'] = 'Airbus A320neo'
df_01.loc[df_01['Aircraft'] == 'A319', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Aircraft'] == 'A321', 'Aircraft'] = 'Airbus A321'

In [18]:
df_01.loc[df_01['Aircraft'] == 'Boeing 737-800', 'flight_capacity'] = 189
df_01.loc[df_01['Aircraft'] == 'Boeing 737 MAX 8', 'flight_capacity'] = 197
df_01.loc[df_01['Aircraft'] == 'Airbus A320', 'flight_capacity'] = 180
df_01.loc[df_01['Aircraft'] == 'Airbus A321neo', 'flight_capacity'] = 239
df_01.loc[df_01['Aircraft'] == 'Airbus A320neo', 'flight_capacity'] = 186
df_01.loc[df_01['Aircraft'] == 'Airbus A319', 'flight_capacity'] = 156
df_01.loc[df_01['Aircraft'] == 'Airbus A321', 'flight_capacity'] = 230
#df_04.loc[df_04['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] = 174

In [19]:
df_01[(df_01['Gate'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1984,NaN,01/Dic/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"Retrasado, Programado 14:56",NaN,NaN,NaN
1987,NaN,01/Dic/2025,Volotea,V71443,Ancona (AOI),14:45,"En hora, Programado",NaN,NaN,NaN
1989,NaN,01/Dic/2025,easyJet Europe,EC4212,Napoli (NAP),14:55,"Retrasado, Programado 15:23",NaN,NaN,NaN
1990,NaN,01/Dic/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",NaN,NaN,NaN

In [20]:
df_01.loc[df_01['Num_flight'] == 'V71443', 'Gate'] = 'R'
df_01.loc[df_01['Num_flight'] == 'EC4212', 'Gate'] = 'R'
df_01.loc[df_01['Num_flight'] == 'QS1059', 'Gate'] = 'S'
df_01.loc[df_01['Num_flight'] == 'BZ251', 'Gate'] = 'Y'

In [21]:
df_01[(df_01['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
1902,NaN,01/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,S25
1903,NaN,01/Dic/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",NaN,NaN,S20
1904,NaN,01/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",NaN,NaN,R11
1905,NaN,01/Dic/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",NaN,NaN,W45
1906,NaN,01/Dic/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",NaN,NaN,U33
1907,NaN,01/Dic/2025,Ryanair,FR3078,Lisbon (LIS),06:30,"En hora, Ha salido",NaN,NaN,S23
1908,NaN,01/Dic/2025,easyJet Europe,EC8062,London (LGW),06:45,"Retrasado, Ha salido 07:04",NaN,NaN,M6
1911,NaN,01/Dic/2025,easyJet Europe,EC7141,Strasbourg (SXB),07:20,"En hora, Ha salido",NaN,NaN,R9
1912,NaN,01/Dic/2025,easyJet Europe,EC7151,Milan (MXP),07:20,"En hora, Ha salido",NaN,NaN,R10
1913,NaN,01/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),07:35,"En hora, Ha salido",NaN,NaN,S22
1916,NaN,01/Dic/2025,Norwegian Air Sweden AOC,D85510,Copenhagen (CPH),08:00,"En hora, Ha salido",NaN,NaN,R13
1917,NaN,01/Dic/2025,Ryanair,FR58,Napoli (NAP),08:35,"Retrasado, Ha salido 08:45",NaN,NaN,U31
1918,NaN,01/Dic/2025,Ryanair,FR575,Bologna (BLQ),08:40,"En hora, Ha salido",NaN,NaN,S21
1919,NaN,01/Dic/2025,easyJet Europe,EC1376,Geneva (GVA),08:45,"En hora, Ha salido",NaN,NaN,R11
1920,NaN,01/Dic/2025,Lauda Europe,LW12,Vienna (VIE),09:00,"En hora, Ha salido",NaN,NaN,S24
1921,NaN,01/Dic/2025,Ryanair,FR6078,Ouarzazate (OZZ),09:05,"En hora, Ha salido",NaN,NaN,Y55
1922,NaN,01/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"En hora, Ha salido",NaN,NaN,U33
1924,NaN,01/Dic/2025,Air Arabia Maroc,3O398,Rabat (RBA),09:20,"En hora, Ha salido",NaN,NaN,Y58
1925,NaN,01/Dic/2025,Eurowings,EW2521,Stuttgart (STR),09:20,"Retrasado, Ha salido 09:59",NaN,NaN,S21
1926,NaN,01/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,U34
1927,NaN,01/Dic/2025,Wizz Air Malta,W45088,Tirana (TIA),09:25,"En hora, Ha salido",NaN,NaN,W46
1928,NaN,01/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"Retrasado, Ha salido 09:38",NaN,NaN,U32
1929,NaN,01/Dic/2025,Volotea,V73573,Asturias (OVD),09:30,"En hora, Ha salido",NaN,NaN,S23
1930,NaN,01/Dic/2025,easyJet Europe,EC1030,"Basel, Switzerland/Mulhouse (BSL)",09:35,"En hora, Ha salido",NaN,NaN,R10
1931,NaN,01/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:40,"En hora, Ha salido",NaN,NaN,U35
1932,NaN,01/Dic/2025,Transavia,HV6062,Rotterdam (RTM),09:40,"En hora, Ha salido",NaN,NaN,S22
1935,NaN,01/Dic/2025,Ryanair,FR4545,Porto (OPO),09:50,"En hora, Ha salido",NaN,NaN,S25
1936,NaN,01/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"Retrasado, Ha salido 10:11",NaN,NaN,W42
1937,NaN,01/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:00,"En hora, Ha salido",NaN,NaN,R11
1938,NaN,01/Dic/2025,Transavia,HV5132,Amsterdam (AMS),10:05,"Retrasado, Ha salido 10:20",NaN,NaN,S20

In [22]:
df_01.loc[df_01['Name_company'] == 'Air Arabia Maroc', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] = 174

In [23]:
df_01.loc[df_01['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR5710', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'RR8394', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_01.loc[df_01['Num_flight'] == 'TO4759', 'flight_capacity'] =186

df_01.loc[df_01['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W62378', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2098', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3928', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'V72165', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR878', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EI565', 'flight_capacity'] =174

df_01.loc[df_01['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR6275', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6920', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EC1380', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W43178', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'W43406', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR2402', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2402', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'RR4084', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W46020', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'FR3168', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3168', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3800', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR3800', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W45154', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'EC7682', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'EC7682', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'FR8574', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR8574', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W46728', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W64116', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2250', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR1527', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR4587', 'flight_capacity'] =197

In [24]:
df_01.loc[df_01['Num_flight'] == 'V72135', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'V72135', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'TW408', 'Aircraft'] = 'Airbus A330-200'
df_01.loc[df_01['Num_flight'] == 'TW408', 'flight_capacity'] =246

df_01.loc[df_01['Num_flight'] == 'EC1010', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC1010', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W42940', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EC1956', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6597', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6341', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3807', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3080', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3080', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W64666', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'V71415', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'LW7351', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR133', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W61706', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'LW2896', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'LW2896', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EW7521', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3185', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W61478', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3174', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'W43686', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3320', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'EC7205', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7205', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR269', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'HV5134', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'EC7199', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7199', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2922', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR1786', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR1786', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W67920', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'V73700', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7173', 'flight_capacity'] =156

In [25]:
df_01.loc[df_01['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'RR6300', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'U23372', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'U23372', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6874', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6305', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR2507', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'V73735', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'V73735', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'W43564', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'W43564', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR9811', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR867', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'PC1094', 'flight_capacity'] =220

df_01.loc[df_01['Num_flight'] == 'W61412', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W61412', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR1681', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR2330', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2330', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3146', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3146', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'QS1059', 'Aircraft'] = 'Airbus A220-300'
df_01.loc[df_01['Num_flight'] == 'QS1059', 'flight_capacity'] =149

df_01.loc[df_01['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EC4212', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W64406', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'V71443', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'V71443', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'TK608', 'flight_capacity'] =162

df_01.loc[df_01['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7107', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'BZ251', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'D85502', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_01.loc[df_01['Num_flight'] == 'BT684', 'flight_capacity'] =149

df_01.loc[df_01['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3792', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'LS804', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3189', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR4585', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7153', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'
df_01.loc[df_01['Num_flight'] == 'LG3592', 'flight_capacity'] =76

df_01.loc[df_01['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7131', 'flight_capacity'] =156

In [26]:
df_01.loc[df_01['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'PC1528', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EW521', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'D81741', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'D81741', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'H4264', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR8631', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W46330', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR3108', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W67022', 'flight_capacity'] =239

df_01.loc[df_01['Num_flight'] == 'EC7137', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7137', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'D83657', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'PC1092', 'flight_capacity'] =230

df_01.loc[df_01['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR774', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR6973', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR8217', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR777', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'EC7197', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7197', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR1279', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'TO4755', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'TO4755', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR7539', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR7539', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EI563', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'U22002', 'flight_capacity'] =180

df_01.loc[df_01['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3976', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3121', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'U28056', 'flight_capacity'] =156

df_01.loc[df_01['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR7808', 'flight_capacity'] =197

df_01.loc[df_01['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3143', 'flight_capacity'] =189

df_01.loc[df_01['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W61476', 'flight_capacity'] = 230

df_01.loc[df_01['Num_flight'] == 'FR6559', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6559', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'FR9175', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR9175', 'flight_capacity'] = 189

In [27]:
df_01.loc[df_01['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_01.loc[df_01['Num_flight'] == 'HV5132', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'HV5132', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_01.loc[df_01['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'JU581', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'HV6062', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'HV6062', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2834', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'EC1030', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'EC1030', 'flight_capacity'] = 180

df_01.loc[df_01['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'V73573', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_01.loc[df_01['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W45088', 'flight_capacity'] = 230

df_01.loc[df_01['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_01.loc[df_01['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_01.loc[df_01['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EW2521', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_01.loc[df_01['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_01.loc[df_01['Num_flight'] == 'FR6078', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR6078', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_01.loc[df_01['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_01.loc[df_01['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR58', 'flight_capacity'] = 197

df_01.loc[df_01['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'D85510', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'EC7141', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7141', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC8062', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'FR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_01.loc[df_01['Num_flight'] == 'FR8384', 'flight_capacity'] = 197

df_01.loc[df_01['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_01.loc[df_01['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_01.loc[df_01['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_01.loc[df_01['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_01.loc[df_01['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

In [28]:
df_02 = df_por_fecha['02/Dic/2025'].copy()
df_02
# Martes

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2071,NaN,02/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:00,"En hora, Ha salido",NaN,NaN,R10
2072,NaN,02/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S21
2073,NaN,02/Dic/2025,Ryanair,FR3189,Fes (FEZ),06:15,"En hora, Ha salido",NaN,NaN,Y59
2074,NaN,02/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,"En hora, Ha salido",NaN,NaN,S23
2075,NaN,02/Dic/2025,Ryanair,FR4545,Porto (OPO),06:35,"En hora, Ha salido",NaN,NaN,U37
...,...,...,...,...,...,...,...,...,...,...
2138,NaN,02/Dic/2025,Transavia,TO4759,Paris (ORY),20:45,"En hora, Ha salido",NaN,NaN,S25
2139,NaN,02/Dic/2025,easyJet Europe,EC1380,Geneva (GVA),21:15,"Retrasado, Programado 21:52",NaN,NaN,R13
2140,NaN,02/Dic/2025,Ryanair,FR6394,Dublin (DUB),21:15,"En hora, Ha salido",NaN,NaN,Y58
2141,NaN,02/Dic/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"En hora, Ha salido",NaN,NaN,S24
2142,NaN,02/Dic/2025,Ryanair,FR4585,Porto (OPO),22:00,"En hora, Ha salido",NaN,NaN,S21

In [29]:
df_02.isna().sum()

Unnamed: 0         72
fecha_scrapeo       0
Name_company        1
Num_flight          0
Name_Destiny        0
Time_flight         0
flight_state        0
flight_capacity    70
Aircraft           62
Gate                1
dtype: int64

In [30]:
df_02 = df_02.drop([2131])

In [31]:
df_02[(df_02['Gate'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2115,NaN,02/Dic/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"En hora, Programado",NaN,NaN,NaN

In [32]:
df_02.loc[df_02['Num_flight'] == 'BZ251', 'Gate'] = 'Y'

In [33]:
df_02[(df_02['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2071,NaN,02/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:00,"En hora, Ha salido",NaN,NaN,R10
2072,NaN,02/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S21
2073,NaN,02/Dic/2025,Ryanair,FR3189,Fes (FEZ),06:15,"En hora, Ha salido",NaN,NaN,Y59
2074,NaN,02/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,"En hora, Ha salido",NaN,NaN,S23
2075,NaN,02/Dic/2025,Ryanair,FR4545,Porto (OPO),06:35,"En hora, Ha salido",NaN,NaN,U37
2076,NaN,02/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:25,"En hora, Ha salido",NaN,NaN,R13
2077,NaN,02/Dic/2025,easyJet Europe,EC8062,London (LGW),07:30,"En hora, Ha salido",NaN,NaN,M6
2078,NaN,02/Dic/2025,Ryanair,FR3166,Palermo (PMO),07:35,"En hora, Ha salido",NaN,NaN,S20
2079,NaN,02/Dic/2025,Ryanair,FR5718,Bratislava (BTS),07:35,"En hora, Ha salido",NaN,NaN,S22
2080,NaN,02/Dic/2025,Ryanair,FR3193,Riga (RIX),07:55,"En hora, Ha salido",NaN,NaN,R14
2081,NaN,02/Dic/2025,easyJet Europe,EC3737,Milan (MXP),08:00,"En hora, Ha salido",NaN,NaN,R9
2082,NaN,02/Dic/2025,Ryanair,FR6973,Rome (FCO),08:20,"En hora, Ha salido",NaN,NaN,U31
2083,NaN,02/Dic/2025,Ryanair,FR133,Berlin (BER),08:50,"En hora, Ha salido",NaN,NaN,U35
2084,NaN,02/Dic/2025,Wizz Air Malta,W43938,Chisinau (KIV),09:00,"En hora, Ha salido",NaN,NaN,Y58
2085,NaN,02/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido 09:41",NaN,NaN,U36
2086,NaN,02/Dic/2025,Ryanair,FR3035,Krakow (KRK),09:10,"Retrasado, Ha salido 09:48",NaN,B738,S24
2087,NaN,02/Dic/2025,Ryanair,FR3807,Charleroi (CRL),09:10,"En hora, Ha salido",NaN,NaN,U32
2088,NaN,02/Dic/2025,Wizz Air,W61914,Vilnius (VNO),09:20,"En hora, Ha salido",NaN,NaN,U34
2089,NaN,02/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S21
2090,NaN,02/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,U33
2091,NaN,02/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,S25
2092,NaN,02/Dic/2025,Air Arabia Maroc,3O378,Tanger (TNG),09:45,"En hora, Ha salido",NaN,NaN,Y57
2093,NaN,02/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"En hora, Ha salido",NaN,NaN,W44
2094,NaN,02/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:05,"En hora, Ha salido",NaN,NaN,R10
2095,NaN,02/Dic/2025,Lauda Europe,LW12,Vienna (VIE),10:15,"En hora, Ha salido",NaN,NaN,R14
2096,NaN,02/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U35
2097,NaN,02/Dic/2025,Ryanair,FR1279,Copenhagen (CPH),10:25,"En hora, Ha salido",NaN,NaN,U31
2098,NaN,02/Dic/2025,Ryanair,FR5270,Manchester (MAN),10:30,"En hora, Ha salido",NaN,NaN,Y58
2099,NaN,02/Dic/2025,Easyjet,U22324,London (LTN),10:35,"En hora, Ha salido",NaN,NaN,M6
2100,NaN,02/Dic/2025,Azerbaijan Airlines,J246,Baku (GYD),10:45,"Retrasado, Ha salido 11:05",NaN,NaN,W45

In [34]:
df_02.loc[df_02['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR6267', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_02.loc[df_02['Num_flight'] == 'PC1092', 'flight_capacity'] = 220

df_02.loc[df_02['Num_flight'] == 'FR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR8384', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'D83657', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR3108', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FI597', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'EI563', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR3035', 'flight_capacity'] = 189

In [35]:
df_02[(df_02['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2071,NaN,02/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:00,"En hora, Ha salido",NaN,NaN,R10
2072,NaN,02/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S21
2073,NaN,02/Dic/2025,Ryanair,FR3189,Fes (FEZ),06:15,"En hora, Ha salido",NaN,NaN,Y59
2074,NaN,02/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:20,"En hora, Ha salido",NaN,NaN,S23
2075,NaN,02/Dic/2025,Ryanair,FR4545,Porto (OPO),06:35,"En hora, Ha salido",NaN,NaN,U37
2076,NaN,02/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:25,"En hora, Ha salido",NaN,NaN,R13
2077,NaN,02/Dic/2025,easyJet Europe,EC8062,London (LGW),07:30,"En hora, Ha salido",NaN,NaN,M6
2078,NaN,02/Dic/2025,Ryanair,FR3166,Palermo (PMO),07:35,"En hora, Ha salido",NaN,NaN,S20
2079,NaN,02/Dic/2025,Ryanair,FR5718,Bratislava (BTS),07:35,"En hora, Ha salido",NaN,NaN,S22
2080,NaN,02/Dic/2025,Ryanair,FR3193,Riga (RIX),07:55,"En hora, Ha salido",NaN,NaN,R14
2081,NaN,02/Dic/2025,easyJet Europe,EC3737,Milan (MXP),08:00,"En hora, Ha salido",NaN,NaN,R9
2082,NaN,02/Dic/2025,Ryanair,FR6973,Rome (FCO),08:20,"En hora, Ha salido",NaN,NaN,U31
2083,NaN,02/Dic/2025,Ryanair,FR133,Berlin (BER),08:50,"En hora, Ha salido",NaN,NaN,U35
2084,NaN,02/Dic/2025,Wizz Air Malta,W43938,Chisinau (KIV),09:00,"En hora, Ha salido",NaN,NaN,Y58
2085,NaN,02/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido 09:41",NaN,NaN,U36
2087,NaN,02/Dic/2025,Ryanair,FR3807,Charleroi (CRL),09:10,"En hora, Ha salido",NaN,NaN,U32
2088,NaN,02/Dic/2025,Wizz Air,W61914,Vilnius (VNO),09:20,"En hora, Ha salido",NaN,NaN,U34
2089,NaN,02/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S21
2090,NaN,02/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,U33
2091,NaN,02/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,S25
2092,NaN,02/Dic/2025,Air Arabia Maroc,3O378,Tanger (TNG),09:45,"En hora, Ha salido",NaN,NaN,Y57
2093,NaN,02/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"En hora, Ha salido",NaN,NaN,W44
2094,NaN,02/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:05,"En hora, Ha salido",NaN,NaN,R10
2095,NaN,02/Dic/2025,Lauda Europe,LW12,Vienna (VIE),10:15,"En hora, Ha salido",NaN,NaN,R14
2096,NaN,02/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U35
2097,NaN,02/Dic/2025,Ryanair,FR1279,Copenhagen (CPH),10:25,"En hora, Ha salido",NaN,NaN,U31
2098,NaN,02/Dic/2025,Ryanair,FR5270,Manchester (MAN),10:30,"En hora, Ha salido",NaN,NaN,Y58
2099,NaN,02/Dic/2025,Easyjet,U22324,London (LTN),10:35,"En hora, Ha salido",NaN,NaN,M6
2100,NaN,02/Dic/2025,Azerbaijan Airlines,J246,Baku (GYD),10:45,"Retrasado, Ha salido 11:05",NaN,NaN,W45
2102,NaN,02/Dic/2025,Ryanair,FR58,Napoli (NAP),11:40,"Retrasado, Ha salido 11:50",NaN,NaN,S25

In [36]:
df_02.loc[df_02['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W46020', 'flight_capacity'] = 239

In [37]:
df_02.loc[df_02['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_02.loc[df_02['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_02.loc[df_02['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'RR4084', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == '3O642', 'flight_capacity'] = 174

df_02.loc[df_02['Num_flight'] == 'HV6790', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'HV6790', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'U28058', 'flight_capacity'] = 156

df_02.loc[df_02['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR9015', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_02.loc[df_02['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_02.loc[df_02['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W61176', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'RR6300', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_02.loc[df_02['Num_flight'] == 'HV5134', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'HV5134', 'flight_capacity'] = 232

df_02.loc[df_02['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'V72327', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR575', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR8217', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'EC7682', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'EC7682', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-900'
df_02.loc[df_02['Num_flight'] == 'KU136', 'flight_capacity'] = 278

df_02.loc[df_02['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR3076', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == '5F5512', 'Aircraft'] = 'Airbus A321'
df_02.loc[df_02['Num_flight'] == '5F5512', 'flight_capacity'] = 194

df_02.loc[df_02['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_02.loc[df_02['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

In [38]:
df_02.loc[df_02['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320neo'
df_02.loc[df_02['Num_flight'] == 'J246', 'flight_capacity'] = 186

df_02.loc[df_02['Num_flight'] == 'U22324', 'Aircraft'] = 'Airbus A320neo'
df_02.loc[df_02['Num_flight'] == 'U22324', 'flight_capacity'] = 186

df_02.loc[df_02['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR5270', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR1279', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'EC7656', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'JU581', 'flight_capacity'] = 144

df_02.loc[df_02['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == '3O378', 'flight_capacity'] = 174

df_02.loc[df_02['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321'
df_02.loc[df_02['Num_flight'] == 'W62376', 'flight_capacity'] = 230

df_02.loc[df_02['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_02.loc[df_02['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_02.loc[df_02['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W61914', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR3807', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_02.loc[df_02['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_02.loc[df_02['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
df_02.loc[df_02['Num_flight'] == 'W43938', 'flight_capacity'] = 180

df_02.loc[df_02['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR6973', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC3737', 'flight_capacity'] = 156

df_02.loc[df_02['Num_flight'] == 'FR3193', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR3193', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC8062', 'flight_capacity'] = 156

df_02.loc[df_02['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_02.loc[df_02['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_02.loc[df_02['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_02.loc[df_02['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_02.loc[df_02['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_02.loc[df_02['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_02.loc[df_02['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

In [39]:
df_02['Aircraft'].unique()

array(['Airbus A319', 'Boeing 737-800', 'Boeing 737 MAX 8', 'Airbus A320',
       'Airbus A321neo', 'Airbus A321', 'Airbus A320neo',
       'Airbus A330-900'], dtype=object)

In [40]:
df_02['flight_capacity'].unique()

array([156., 189., 197., 180., 239., 230., 174., 144., 186., 220., 194.,
       278., 232.])

In [41]:
df_02['Gate'].unique()

array(['R10', 'S21', 'Y59', 'S23', 'U37', 'R13', 'M6', 'S20', 'S22',
       'R14', 'R9', 'U31', 'U35', 'Y58', 'U36', 'S24', 'U32', 'U34',
       'U33', 'S25', 'Y57', 'W44', 'W45', 'Y54', 'U41', 'W46', 'W42',
       'W43', 'Y', 'U', 'R11', 'M8'], dtype=object)

In [42]:
df_03 = df_por_fecha['03/Dic/2025'].copy()
df_03
# Miercoles

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2143,NaN,03/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S23
2144,NaN,03/Dic/2025,Ryanair,FR3185,Rabat (RBA),06:05,"En hora, Ha salido",NaN,NaN,W46
2145,NaN,03/Dic/2025,Ryanair,FR9406,Fes (FEZ),06:05,"En hora, Ha salido",NaN,NaN,W45
2146,NaN,03/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2147,NaN,03/Dic/2025,Ryanair,FR483,Malaga (AGP),06:15,"En hora, Ha salido",189.0,Boeing 737-800,U41
...,...,...,...,...,...,...,...,...,...,...
2228,NaN,03/Dic/2025,Easyjet,U22326,London (LTN),20:55,"En hora, Ha salido",NaN,NaN,M6
2229,NaN,03/Dic/2025,easyJet Europe,EC1380,Geneva (GVA),21:15,"Retrasado, Programado 22:17",NaN,NaN,R13
2230,NaN,03/Dic/2025,Wizz Air Malta,W43406,Cluj-Napoca (CLJ),21:25,"En hora, Ha salido",NaN,NaN,S21
2231,NaN,03/Dic/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"Retrasado, Ha salido 21:46",NaN,NaN,S22
2232,NaN,03/Dic/2025,Ryanair,FR6394,Dublin (DUB),22:05,"En hora, Programado",NaN,NaN,W44

In [43]:
df_03.isna().sum()

Unnamed: 0         90
fecha_scrapeo       0
Name_company        0
Num_flight          0
Name_Destiny        0
Time_flight         0
flight_state        0
flight_capacity    86
Aircraft           82
Gate                1
dtype: int64

In [44]:
df_03[(df_03['Gate'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2166,NaN,03/Dic/2025,Air Arabia Maroc,3O642,Tanger (TNG),10:05,"En hora, Ha salido",NaN,NaN,NaN

In [45]:
df_03.loc[df_03['Num_flight'] == '3O642', 'Gate'] = 'Y'

In [46]:
df_03[(df_03['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2143,NaN,03/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S23
2144,NaN,03/Dic/2025,Ryanair,FR3185,Rabat (RBA),06:05,"En hora, Ha salido",NaN,NaN,W46
2145,NaN,03/Dic/2025,Ryanair,FR9406,Fes (FEZ),06:05,"En hora, Ha salido",NaN,NaN,W45
2146,NaN,03/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2148,NaN,03/Dic/2025,easyJet Europe,EC7193,Leeds Bradford (LBA),06:30,"En hora, Ha salido",NaN,NaN,M3
2149,NaN,03/Dic/2025,Ryanair,FR2239,Marrakech (RAK),06:35,"En hora, Ha salido",NaN,NaN,Y59
2150,NaN,03/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),06:45,"En hora, Ha salido",NaN,NaN,U37
2151,NaN,03/Dic/2025,Ryanair,FR3108,Luxembourg (LUX),06:50,"En hora, Ha salido",NaN,B38M,S20
2152,NaN,03/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,"En hora, Ha salido",NaN,NaN,R15
2153,NaN,03/Dic/2025,easyJet Europe,EC8062,London (LGW),07:20,"En hora, Ha salido",NaN,NaN,M8
2155,NaN,03/Dic/2025,Ryanair,FR846,Milan (BGY),08:05,"En hora, Ha salido",NaN,NaN,U37
2156,NaN,03/Dic/2025,easyJet Europe,EC3737,Milan (MXP),08:25,"En hora, Ha salido",NaN,NaN,R10
2157,NaN,03/Dic/2025,easyJet Europe,EC7161,Napoli (NAP),09:20,"En hora, Ha salido",NaN,NaN,R11
2158,NaN,03/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S24
2159,NaN,03/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,U36
2160,NaN,03/Dic/2025,BUZZ,RR8384,Budapest (BUD),09:30,"En hora, Ha salido",NaN,NaN,R14
2161,NaN,03/Dic/2025,Air Arabia Maroc,3O376,Al Aaroui (NDR),09:35,"Retrasado, Ha salido 09:52",NaN,NaN,Y58
2162,NaN,03/Dic/2025,Wizz Air Malta,W42940,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,S23
2163,NaN,03/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:45,"En hora, Ha salido",NaN,NaN,S25
2164,NaN,03/Dic/2025,Ryanair,FR4545,Porto (OPO),09:45,"En hora, Ha salido",NaN,NaN,R13
2165,NaN,03/Dic/2025,BUZZ,RR3049,Krakow (KRK),09:55,"Retrasado, Ha salido 10:30",NaN,NaN,U31
2166,NaN,03/Dic/2025,Air Arabia Maroc,3O642,Tanger (TNG),10:05,"En hora, Ha salido",NaN,NaN,Y
2167,NaN,03/Dic/2025,Transavia,HV5132,Amsterdam (AMS),10:05,"Retrasado, Ha salido 10:23",NaN,NaN,U32
2168,NaN,03/Dic/2025,Ryanair,FR3078,Lisbon (LIS),10:15,"En hora, Ha salido",NaN,NaN,S20
2169,NaN,03/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U35
2170,NaN,03/Dic/2025,Ryanair,FR3039,Prague (PRG),10:20,"En hora, Ha salido",NaN,NaN,U33
2171,NaN,03/Dic/2025,Easyjet,U22002,Manchester (MAN),10:30,"En hora, Ha salido",NaN,NaN,M8
2172,NaN,03/Dic/2025,Air Baltic,BT878,Tallinn (TLL),10:35,"Retrasado, Ha salido 10:54",NaN,NaN,U34
2173,NaN,03/Dic/2025,Norwegian Air Sweden AOC,D85544,Rovaniemi (RVN),10:40,"En hora, Ha salido",NaN,B738,S22
2174,NaN,03/Dic/2025,Ryanair,FR6267,Edinburgh (EDI),10:45,"Retrasado, Ha salido 11:05",NaN,NaN,Y55

In [47]:
df_03.loc[df_03['Num_flight'] == 'HV6064', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'HV6064', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR9334', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR9334', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'PC1094', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'U22704', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'D85544', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'D85544', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR3108', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR3108', 'flight_capacity'] = 197

In [48]:
df_03[(df_03['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2143,NaN,03/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:05,"En hora, Ha salido",NaN,NaN,S23
2144,NaN,03/Dic/2025,Ryanair,FR3185,Rabat (RBA),06:05,"En hora, Ha salido",NaN,NaN,W46
2145,NaN,03/Dic/2025,Ryanair,FR9406,Fes (FEZ),06:05,"En hora, Ha salido",NaN,NaN,W45
2146,NaN,03/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2148,NaN,03/Dic/2025,easyJet Europe,EC7193,Leeds Bradford (LBA),06:30,"En hora, Ha salido",NaN,NaN,M3
2149,NaN,03/Dic/2025,Ryanair,FR2239,Marrakech (RAK),06:35,"En hora, Ha salido",NaN,NaN,Y59
2150,NaN,03/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),06:45,"En hora, Ha salido",NaN,NaN,U37
2152,NaN,03/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,"En hora, Ha salido",NaN,NaN,R15
2153,NaN,03/Dic/2025,easyJet Europe,EC8062,London (LGW),07:20,"En hora, Ha salido",NaN,NaN,M8
2155,NaN,03/Dic/2025,Ryanair,FR846,Milan (BGY),08:05,"En hora, Ha salido",NaN,NaN,U37
2156,NaN,03/Dic/2025,easyJet Europe,EC3737,Milan (MXP),08:25,"En hora, Ha salido",NaN,NaN,R10
2157,NaN,03/Dic/2025,easyJet Europe,EC7161,Napoli (NAP),09:20,"En hora, Ha salido",NaN,NaN,R11
2158,NaN,03/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S24
2159,NaN,03/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,U36
2160,NaN,03/Dic/2025,BUZZ,RR8384,Budapest (BUD),09:30,"En hora, Ha salido",NaN,NaN,R14
2161,NaN,03/Dic/2025,Air Arabia Maroc,3O376,Al Aaroui (NDR),09:35,"Retrasado, Ha salido 09:52",NaN,NaN,Y58
2162,NaN,03/Dic/2025,Wizz Air Malta,W42940,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,S23
2163,NaN,03/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:45,"En hora, Ha salido",NaN,NaN,S25
2164,NaN,03/Dic/2025,Ryanair,FR4545,Porto (OPO),09:45,"En hora, Ha salido",NaN,NaN,R13
2165,NaN,03/Dic/2025,BUZZ,RR3049,Krakow (KRK),09:55,"Retrasado, Ha salido 10:30",NaN,NaN,U31
2166,NaN,03/Dic/2025,Air Arabia Maroc,3O642,Tanger (TNG),10:05,"En hora, Ha salido",NaN,NaN,Y
2167,NaN,03/Dic/2025,Transavia,HV5132,Amsterdam (AMS),10:05,"Retrasado, Ha salido 10:23",NaN,NaN,U32
2168,NaN,03/Dic/2025,Ryanair,FR3078,Lisbon (LIS),10:15,"En hora, Ha salido",NaN,NaN,S20
2169,NaN,03/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U35
2170,NaN,03/Dic/2025,Ryanair,FR3039,Prague (PRG),10:20,"En hora, Ha salido",NaN,NaN,U33
2171,NaN,03/Dic/2025,Easyjet,U22002,Manchester (MAN),10:30,"En hora, Ha salido",NaN,NaN,M8
2172,NaN,03/Dic/2025,Air Baltic,BT878,Tallinn (TLL),10:35,"Retrasado, Ha salido 10:54",NaN,NaN,U34
2174,NaN,03/Dic/2025,Ryanair,FR6267,Edinburgh (EDI),10:45,"Retrasado, Ha salido 11:05",NaN,NaN,Y55
2175,NaN,03/Dic/2025,SkyUp MT,U5406,Chisinau (KIV),10:50,"Retrasado, Ha salido 12:24",NaN,NaN,Y58
2177,NaN,03/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),11:00,"En hora, Ha salido",NaN,NaN,U36

In [49]:
df_03.loc[df_03['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR6394', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320neo'
df_03.loc[df_03['Num_flight'] == 'W43406', 'flight_capacity'] = 186

df_03.loc[df_03['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_03.loc[df_03['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_03.loc[df_03['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_03.loc[df_03['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_03.loc[df_03['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'FB585', 'Aircraft'] = 'Embraer ERJ-190'
df_03.loc[df_03['Num_flight'] == 'FB585', 'flight_capacity'] = 108

df_03.loc[df_03['Num_flight'] == 'TW408', 'Aircraft'] = 'BOEING 777-300ER'
df_03.loc[df_03['Num_flight'] == 'TW408', 'flight_capacity'] = 294

df_03.loc[df_03['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == '3O378', 'flight_capacity'] = 174

df_03.loc[df_03['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'RR5246', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'RR5246', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3143', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'U28058', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR133', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'EW9443', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR1342', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'FR1165', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR1165', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

In [50]:
df_03.loc[df_03['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'RR8394', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EC8060', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC8060', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'E9803', 'Aircraft'] = 'Airbus A350-900'
df_03.loc[df_03['Num_flight'] == 'E9803', 'flight_capacity'] = 432

df_03.loc[df_03['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR4585', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321'
df_03.loc[df_03['Num_flight'] == 'W67920', 'flight_capacity'] = 230

df_03.loc[df_03['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_03.loc[df_03['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_03.loc[df_03['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR3035', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'W61412', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W61412', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'EC7682', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'EC7682', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR12', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EW2521', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'D83659', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'V72327', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'TK608', 'flight_capacity'] = 162

df_03.loc[df_03['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'EW521', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'H4264', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR6597', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_03.loc[df_03['Num_flight'] == 'PC1092', 'flight_capacity'] = 230

df_03.loc[df_03['Num_flight'] == 'FR9925', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR9925', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'EI563', 'flight_capacity'] = 174

In [51]:
df_03.loc[df_03['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR2507', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'U5406', 'Aircraft'] = 'Boeing 737-700'
df_03.loc[df_03['Num_flight'] == 'U5406', 'flight_capacity'] = 141

df_03.loc[df_03['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR6267', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'BT878', 'Aircraft'] = 'Airbus A220-300'
df_03.loc[df_03['Num_flight'] == 'BT878', 'flight_capacity'] = 148

df_03.loc[df_03['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == 'U22002', 'flight_capacity'] = 180

df_03.loc[df_03['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3039', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'HV5132', 'flight_capacity'] = 232

df_03.loc[df_03['Num_flight'] == '3O642', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == '3O642', 'flight_capacity'] = 174

df_03.loc[df_03['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'RR3049', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_03.loc[df_03['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_03.loc[df_03['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR2834', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W42940', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == '3O376', 'Aircraft'] = 'Airbus A320'
df_03.loc[df_03['Num_flight'] == '3O376', 'flight_capacity'] = 174

df_03.loc[df_03['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_03.loc[df_03['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_03.loc[df_03['Num_flight'] == 'EC7161', 'Aircraft'] = 'Airbus A320neo'
df_03.loc[df_03['Num_flight'] == 'EC7161', 'flight_capacity'] = 186

df_03.loc[df_03['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC3737', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EC8062', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC8062', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'EC7193', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC7193', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_03.loc[df_03['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_03.loc[df_03['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR9406', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR3185', 'flight_capacity'] = 189

df_03.loc[df_03['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_03.loc[df_03['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

In [52]:
df_04 = df_por_fecha['04/Dic/2025'].copy()
df_04
# Jueves

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2233,NaN,04/Dic/2025,Ryanair,FR8215,London (STN),06:00,"En hora, Ha salido",NaN,B738,W46
2234,NaN,04/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2235,NaN,04/Dic/2025,Ryanair,FR3976,Dublin (DUB),06:15,"En hora, Ha salido",NaN,B38M,W42
2236,NaN,04/Dic/2025,easyJet Europe,EC7191,Glasgow (GLA),06:40,"Retrasado, Ha salido 07:06",NaN,NaN,M6
2237,NaN,04/Dic/2025,Ryanair,FR3049,Krakow (KRK),06:40,"En hora, Ha salido",NaN,NaN,U33
...,...,...,...,...,...,...,...,...,...,...
2350,NaN,04/Dic/2025,BUZZ,RR3035,Krakow (KRK),21:30,"Retrasado, Programado 22:20",NaN,NaN,U34
2351,NaN,04/Dic/2025,BUZZ,RR4084,Warsaw (WMI),21:30,"En hora, Ha salido",NaN,NaN,U32
2352,NaN,04/Dic/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"Retrasado, Ha salido 21:50",NaN,A21N,S23
2353,NaN,04/Dic/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",NaN,NaN,Y53
2354,NaN,04/Dic/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,W44

In [53]:
df_04.isna().sum()

Unnamed: 0         122
fecha_scrapeo        0
Name_company         1
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    117
Aircraft            96
Gate                 1
dtype: int64

In [54]:
df_04 = df_04.drop([2324])

In [55]:
df_04[(df_04['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2233,NaN,04/Dic/2025,Ryanair,FR8215,London (STN),06:00,"En hora, Ha salido",NaN,B738,W46
2234,NaN,04/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2235,NaN,04/Dic/2025,Ryanair,FR3976,Dublin (DUB),06:15,"En hora, Ha salido",NaN,B38M,W42
2236,NaN,04/Dic/2025,easyJet Europe,EC7191,Glasgow (GLA),06:40,"Retrasado, Ha salido 07:06",NaN,NaN,M6
2237,NaN,04/Dic/2025,Ryanair,FR3049,Krakow (KRK),06:40,"En hora, Ha salido",NaN,NaN,U33
2238,NaN,04/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),06:45,"En hora, Ha salido",NaN,NaN,U31
2240,NaN,04/Dic/2025,Ryanair,FR133,Berlin (BER),07:25,"En hora, Ha salido",NaN,B738,S23
2241,NaN,04/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:30,"En hora, Ha salido",NaN,NaN,R15
2242,NaN,04/Dic/2025,easyJet Europe,EC7151,Milan (MXP),07:30,"En hora, Ha salido",NaN,NaN,R12
2243,NaN,04/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),07:45,"En hora, Ha salido",NaN,NaN,S24
2244,NaN,04/Dic/2025,Norwegian Air Sweden AOC,D85510,Copenhagen (CPH),07:55,"En hora, Ha salido",NaN,NaN,S25
2245,NaN,04/Dic/2025,Ryanair,FR575,Bologna (BLQ),08:05,"En hora, Ha salido",NaN,NaN,U37
2246,NaN,04/Dic/2025,Ryanair,FR774,Torino (TRN),08:05,"En hora, Ha salido",NaN,NaN,U36
2247,NaN,04/Dic/2025,Ryanair,FR6973,Rome (FCO),08:40,"En hora, Ha salido",NaN,NaN,S21
2248,NaN,04/Dic/2025,Wizz Air Malta,W43938,Chisinau (KIV),09:00,"En hora, Ha salido",NaN,A320,W45
2249,NaN,04/Dic/2025,Ryanair,FR5710,Napoli (NAP),09:05,"En hora, Ha salido",NaN,NaN,S22
2250,NaN,04/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido 09:22",NaN,NaN,U32
2251,NaN,04/Dic/2025,Lauda Europe,LW12,Vienna (VIE),09:10,"Retrasado, Ha salido 09:30",NaN,NaN,R13
2252,NaN,04/Dic/2025,Wizz Air,W61914,Vilnius (VNO),09:20,"Retrasado, Ha salido 09:34",NaN,NaN,U34
2253,NaN,04/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,U33
2254,NaN,04/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"Retrasado, Ha salido 09:48",NaN,NaN,U35
2255,NaN,04/Dic/2025,Ryanair,FR3320,Milan (BGY),09:30,"En hora, Ha salido",NaN,NaN,S25
2256,NaN,04/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,S20
2257,NaN,04/Dic/2025,Transavia,TO4751,Paris (ORY),09:40,"Retrasado, Ha salido 09:52",NaN,NaN,U31
2258,NaN,04/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"En hora, Ha salido",NaN,NaN,Y58
2259,NaN,04/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:00,"En hora, Ha salido",NaN,NaN,R10
2260,NaN,04/Dic/2025,Ryanair,FR1279,Copenhagen (CPH),10:00,"En hora, Ha salido",NaN,NaN,S24
2261,NaN,04/Dic/2025,Transavia,HV5132,Amsterdam (AMS),10:05,"En hora, Ha salido",NaN,A21N,R14
2262,NaN,04/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U36
2264,NaN,04/Dic/2025,Ryanair,FR3121,Beauvais (BVA),10:25,"En hora, Ha salido",NaN,NaN,S22

In [56]:
df_04.loc[df_04['Aircraft'] == 'B738', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Aircraft'] == 'B38M', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Aircraft'] == 'A320', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Aircraft'] == 'A21N', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Aircraft'] == 'A20N', 'Aircraft'] = 'Airbus A320neo'

In [57]:
df_04.loc[df_04['Aircraft'] == 'Boeing 737-800', 'flight_capacity'] = 189
df_04.loc[df_04['Aircraft'] == 'Boeing 737 MAX 8', 'flight_capacity'] = 197
df_04.loc[df_04['Aircraft'] == 'Airbus A320', 'flight_capacity'] = 180
df_04.loc[df_04['Aircraft'] == 'Airbus A321neo', 'flight_capacity'] = 239
df_04.loc[df_04['Aircraft'] == 'Airbus A320neo', 'flight_capacity'] = 186
df_04.loc[df_04['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] = 174

In [58]:
df_04[(df_04['Gate'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2300,NaN,04/Dic/2025,SmartWings,QS1059,Prague (PRG),14:55,"Retrasado, Programado 15:06",NaN,NaN,NaN

In [59]:
df_04.loc[df_04['Num_flight'] == 'QS1059', 'Gate'] = 'U'

In [60]:
df_04[(df_04['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2234,NaN,04/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2236,NaN,04/Dic/2025,easyJet Europe,EC7191,Glasgow (GLA),06:40,"Retrasado, Ha salido 07:06",NaN,NaN,M6
2237,NaN,04/Dic/2025,Ryanair,FR3049,Krakow (KRK),06:40,"En hora, Ha salido",NaN,NaN,U33
2238,NaN,04/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),06:45,"En hora, Ha salido",NaN,NaN,U31
2241,NaN,04/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:30,"En hora, Ha salido",NaN,NaN,R15
2242,NaN,04/Dic/2025,easyJet Europe,EC7151,Milan (MXP),07:30,"En hora, Ha salido",NaN,NaN,R12
2243,NaN,04/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),07:45,"En hora, Ha salido",NaN,NaN,S24
2244,NaN,04/Dic/2025,Norwegian Air Sweden AOC,D85510,Copenhagen (CPH),07:55,"En hora, Ha salido",NaN,NaN,S25
2245,NaN,04/Dic/2025,Ryanair,FR575,Bologna (BLQ),08:05,"En hora, Ha salido",NaN,NaN,U37
2246,NaN,04/Dic/2025,Ryanair,FR774,Torino (TRN),08:05,"En hora, Ha salido",NaN,NaN,U36
2247,NaN,04/Dic/2025,Ryanair,FR6973,Rome (FCO),08:40,"En hora, Ha salido",NaN,NaN,S21
2249,NaN,04/Dic/2025,Ryanair,FR5710,Napoli (NAP),09:05,"En hora, Ha salido",NaN,NaN,S22
2250,NaN,04/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido 09:22",NaN,NaN,U32
2251,NaN,04/Dic/2025,Lauda Europe,LW12,Vienna (VIE),09:10,"Retrasado, Ha salido 09:30",NaN,NaN,R13
2252,NaN,04/Dic/2025,Wizz Air,W61914,Vilnius (VNO),09:20,"Retrasado, Ha salido 09:34",NaN,NaN,U34
2253,NaN,04/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,U33
2254,NaN,04/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"Retrasado, Ha salido 09:48",NaN,NaN,U35
2255,NaN,04/Dic/2025,Ryanair,FR3320,Milan (BGY),09:30,"En hora, Ha salido",NaN,NaN,S25
2256,NaN,04/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,S20
2257,NaN,04/Dic/2025,Transavia,TO4751,Paris (ORY),09:40,"Retrasado, Ha salido 09:52",NaN,NaN,U31
2258,NaN,04/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"En hora, Ha salido",NaN,NaN,Y58
2259,NaN,04/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:00,"En hora, Ha salido",NaN,NaN,R10
2260,NaN,04/Dic/2025,Ryanair,FR1279,Copenhagen (CPH),10:00,"En hora, Ha salido",NaN,NaN,S24
2262,NaN,04/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U36
2264,NaN,04/Dic/2025,Ryanair,FR3121,Beauvais (BVA),10:25,"En hora, Ha salido",NaN,NaN,S22
2265,NaN,04/Dic/2025,BUZZ,RR8384,Budapest (BUD),10:25,"En hora, Ha salido",NaN,NaN,S21
2266,NaN,04/Dic/2025,Easyjet,U22326,London (LTN),10:35,"En hora, Ha salido",NaN,NaN,M1
2267,NaN,04/Dic/2025,Easyjet,U28056,London (LGW),10:35,"En hora, Ha salido",NaN,NaN,M6
2268,NaN,04/Dic/2025,Easyjet,U25716,Southend (SEN),10:40,"En hora, Ha salido",NaN,NaN,M3
2269,NaN,04/Dic/2025,Azerbaijan Airlines,J246,Baku (GYD),10:45,"Retrasado, Ha salido 10:55",NaN,NaN,W46

In [61]:
df_04.loc[df_04['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W45154', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W64116', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'RR4084', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'RR4084', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'RR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'RR3035', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321'
df_04.loc[df_04['Num_flight'] == 'W46728', 'flight_capacity'] = 230

df_04.loc[df_04['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_04.loc[df_04['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_04.loc[df_04['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W64406', 'flight_capacity'] = 239

In [62]:
df_04.loc[df_04['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'RR333', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'W64738', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W64738', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3143', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A320neo'
df_04.loc[df_04['Num_flight'] == 'U28058', 'flight_capacity'] = 186

df_04.loc[df_04['Num_flight'] == 'FR8598', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR8598', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == '3O378', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == '3O378', 'flight_capacity'] = 174

df_04.loc[df_04['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR8217', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR1342', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR1342', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'RR3193', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'RR3193', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W61176', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_04.loc[df_04['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_04.loc[df_04['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_04.loc[df_04['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_04.loc[df_04['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC7139', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7139', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'RR6300', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'RR6300', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'V72327', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'RR8394', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'EC1378', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'EC1378', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'FR9913', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR9913', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'V73573', 'flight_capacity'] = 156

In [63]:
df_04.loc[df_04['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR2922', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'QS1059', 'Aircraft'] = 'Airbus A220-300'
df_04.loc[df_04['Num_flight'] == 'QS1059', 'flight_capacity'] = 149

df_04.loc[df_04['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR9015', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-800'
df_04.loc[df_04['Num_flight'] == 'KU136', 'flight_capacity'] = 235

df_04.loc[df_04['Num_flight'] == 'XQ895', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'XQ895', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_04.loc[df_04['Num_flight'] == 'BT684', 'flight_capacity'] = 149

df_04.loc[df_04['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR846', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR6267', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'LG3592', 'Aircraft'] = 'de Havilland Dash 8-400'
df_04.loc[df_04['Num_flight'] == 'LG3592', 'flight_capacity'] = 76

df_04.loc[df_04['Num_flight'] == 'FR3039', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR3039', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'V71445', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'V71445', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321'
df_04.loc[df_04['Num_flight'] == 'PC1092', 'flight_capacity'] = 220

df_04.loc[df_04['Num_flight'] == 'FR3160', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3160', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'EC7131', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320neo'
df_04.loc[df_04['Num_flight'] == 'U22704', 'flight_capacity'] = 186

df_04.loc[df_04['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR4545', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

In [64]:
df_04.loc[df_04['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'J246', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
df_04.loc[df_04['Num_flight'] == 'U25716', 'flight_capacity'] = 186

df_04.loc[df_04['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A320neo'
df_04.loc[df_04['Num_flight'] == 'U28056', 'flight_capacity'] = 186

df_04.loc[df_04['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_04.loc[df_04['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_04.loc[df_04['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR1279', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'EC7656', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'JU581', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'TO4751', 'Aircraft'] = 'Airbus A320neo'
df_04.loc[df_04['Num_flight'] == 'TO4751', 'flight_capacity'] = 186

df_04.loc[df_04['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W61914', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_04.loc[df_04['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_04.loc[df_04['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_04.loc[df_04['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_04.loc[df_04['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR5710', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR6973', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'D85510', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR2507', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_04.loc[df_04['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_04.loc[df_04['Num_flight'] == 'FR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_04.loc[df_04['Num_flight'] == 'FR3049', 'flight_capacity'] = 197

df_04.loc[df_04['Num_flight'] == 'EC7191', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7191', 'flight_capacity'] = 156

df_04.loc[df_04['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_04.loc[df_04['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

In [65]:
df_05 = df_por_fecha['05/Dic/2025'].copy()
df_05
# Viernes

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2355,NaN,05/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2356,NaN,05/Dic/2025,Ryanair,FR8183,Bologna (BLQ),06:10,"En hora, Ha salido",NaN,NaN,S24
2357,NaN,05/Dic/2025,Ryanair,FR8231,London (STN),06:10,"En hora, Ha salido",NaN,NaN,Y59
2358,NaN,05/Dic/2025,Ryanair,FR777,Venice (VCE),06:20,"En hora, Ha salido",NaN,NaN,U36
2359,NaN,05/Dic/2025,Ryanair,FR846,Milan (BGY),06:25,"En hora, Ha salido",NaN,NaN,U35
...,...,...,...,...,...,...,...,...,...,...
2527,NaN,05/Dic/2025,Easyjet,U28060,London (LGW),22:15,"Retrasado, Programado 22:32",NaN,NaN,M6
2528,NaN,05/Dic/2025,Ryanair,FR3080,Malaga (AGP),22:30,"Retrasado, Programado 23:25",197.0,Boeing 737 MAX 8,U
2529,NaN,05/Dic/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,Y58
2530,NaN,05/Dic/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"Retrasado, Programado 23:24",NaN,NaN,U
2531,NaN,05/Dic/2025,Ryanair,FR9814,London (STN),23:10,"En hora, Programado",NaN,NaN,W

In [66]:
df_05.isna().sum()

Unnamed: 0         177
fecha_scrapeo        0
Name_company         1
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    166
Aircraft           157
Gate                 2
dtype: int64

In [67]:
df_05 = df_05.drop([2448])

In [68]:
df_05[(df_05['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2355,NaN,05/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2356,NaN,05/Dic/2025,Ryanair,FR8183,Bologna (BLQ),06:10,"En hora, Ha salido",NaN,NaN,S24
2357,NaN,05/Dic/2025,Ryanair,FR8231,London (STN),06:10,"En hora, Ha salido",NaN,NaN,Y59
2358,NaN,05/Dic/2025,Ryanair,FR777,Venice (VCE),06:20,"En hora, Ha salido",NaN,NaN,U36
2359,NaN,05/Dic/2025,Ryanair,FR846,Milan (BGY),06:25,"En hora, Ha salido",NaN,NaN,U35
2360,NaN,05/Dic/2025,Ryanair,FR133,Berlin (BER),06:35,"En hora, Ha salido",NaN,NaN,U33
2361,NaN,05/Dic/2025,Ryanair,FR4545,Porto (OPO),06:45,"En hora, Ha salido",NaN,B38M,R12
2362,NaN,05/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,"En hora, Ha salido",NaN,NaN,R15
2363,NaN,05/Dic/2025,easyJet Europe,EC7199,Edinburgh (EDI),07:20,"En hora, Ha salido",NaN,NaN,M6
2365,NaN,05/Dic/2025,Norwegian Air Sweden AOC,D85502,Stockholm (ARN),08:00,"Retrasado, Ha salido 08:12",NaN,NaN,S21
2366,NaN,05/Dic/2025,Ryanair,FR3976,Dublin (DUB),08:00,"En hora, Ha salido",NaN,NaN,W45
2367,NaN,05/Dic/2025,Ryanair,FR3185,Rabat (RBA),08:10,"En hora, Ha salido",NaN,NaN,Y59
2368,NaN,05/Dic/2025,Ryanair,FR6973,Rome (FCO),08:15,"En hora, Ha salido",NaN,NaN,R14
2369,NaN,05/Dic/2025,easyJet Europe,EC1376,Geneva (GVA),08:40,"En hora, Ha salido",NaN,NaN,R11
2370,NaN,05/Dic/2025,Ryanair,FR5752,Valletta (MLA),08:40,"En hora, Ha salido",NaN,NaN,S24
2371,NaN,05/Dic/2025,Transavia,TO4751,Paris (ORY),08:45,"En hora, Ha salido",NaN,NaN,U31
2373,NaN,05/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"En hora, Ha salido",NaN,A21N,S23
2374,NaN,05/Dic/2025,easyJet Europe,EC3737,Milan (MXP),09:10,"En hora, Ha salido",NaN,NaN,R12
2375,NaN,05/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:15,"En hora, Ha salido",NaN,B38M,U36
2376,NaN,05/Dic/2025,Air Arabia Maroc,3O374,Casablanca (CMN),09:25,"En hora, Ha salido",NaN,NaN,Y55
2377,NaN,05/Dic/2025,Lauda Europe,LW12,Vienna (VIE),09:25,"En hora, Ha salido",NaN,NaN,R13
2378,NaN,05/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S22
2379,NaN,05/Dic/2025,Wizz Air Malta,W45088,Tirana (TIA),09:25,"En hora, Ha salido",NaN,NaN,W44
2380,NaN,05/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,U33
2381,NaN,05/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),09:40,"En hora, Ha salido",NaN,NaN,U37
2382,NaN,05/Dic/2025,Ryanair,FR3320,Milan (BGY),09:45,"En hora, Ha salido",NaN,NaN,U35
2383,NaN,05/Dic/2025,Transavia,HV6788,Eindhoven (EIN),09:45,"En hora, Ha salido",NaN,NaN,U32
2384,NaN,05/Dic/2025,Easyjet,U26654,Birmingham (BHX),09:45,"Retrasado, Ha salido 10:21",NaN,NaN,M3
2385,NaN,05/Dic/2025,Air Arabia Maroc,3O378,Tanger (TNG),09:50,"En hora, Ha salido",NaN,NaN,Y53
2386,NaN,05/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),09:55,"Retrasado, Ha salido 10:05",NaN,NaN,R10

In [69]:
df_05.loc[df_05['Aircraft'] == 'B738', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Aircraft'] == 'B38M', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Aircraft'] == 'A320', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Aircraft'] == 'A21N', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Aircraft'] == 'A20N', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Aircraft'] == 'A319', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Aircraft'] == 'A321', 'Aircraft'] = 'Airbus A321'

In [70]:
df_05.loc[df_05['Aircraft'] == 'Boeing 737-800', 'flight_capacity'] = 189
df_05.loc[df_05['Aircraft'] == 'Boeing 737 MAX 8', 'flight_capacity'] = 197
df_05.loc[df_05['Aircraft'] == 'Airbus A320', 'flight_capacity'] = 180
df_05.loc[df_05['Aircraft'] == 'Airbus A321neo', 'flight_capacity'] = 239
df_05.loc[df_05['Aircraft'] == 'Airbus A320neo', 'flight_capacity'] = 186
df_05.loc[(df_05['Name_company'] == 'Aer Lingus') &
(df_05['Aircraft'] == 'Airbus A320'), 'flight_capacity'] = 174

In [71]:
df_05[(df_05['Gate'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2426,NaN,05/Dic/2025,FlyOne,5F5512,Chisinau (KIV),13:30,"Retrasado, Programado 15:00",NaN,NaN,NaN
2435,NaN,05/Dic/2025,easyJet Europe,EC7153,Milan (MXP),14:20,"Retrasado, Programado 14:31",NaN,NaN,NaN

In [72]:
df_05.loc[df_05['Num_flight'] == '5F5512', 'Gate'] = 'W'
df_05.loc[df_05['Num_flight'] == 'EC7153', 'Gate'] = 'R'

In [73]:
df_05[(df_05['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2355,NaN,05/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R10
2356,NaN,05/Dic/2025,Ryanair,FR8183,Bologna (BLQ),06:10,"En hora, Ha salido",NaN,NaN,S24
2357,NaN,05/Dic/2025,Ryanair,FR8231,London (STN),06:10,"En hora, Ha salido",NaN,NaN,Y59
2358,NaN,05/Dic/2025,Ryanair,FR777,Venice (VCE),06:20,"En hora, Ha salido",NaN,NaN,U36
2359,NaN,05/Dic/2025,Ryanair,FR846,Milan (BGY),06:25,"En hora, Ha salido",NaN,NaN,U35
2360,NaN,05/Dic/2025,Ryanair,FR133,Berlin (BER),06:35,"En hora, Ha salido",NaN,NaN,U33
2362,NaN,05/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",07:20,"En hora, Ha salido",NaN,NaN,R15
2363,NaN,05/Dic/2025,easyJet Europe,EC7199,Edinburgh (EDI),07:20,"En hora, Ha salido",NaN,NaN,M6
2365,NaN,05/Dic/2025,Norwegian Air Sweden AOC,D85502,Stockholm (ARN),08:00,"Retrasado, Ha salido 08:12",NaN,NaN,S21
2366,NaN,05/Dic/2025,Ryanair,FR3976,Dublin (DUB),08:00,"En hora, Ha salido",NaN,NaN,W45
2367,NaN,05/Dic/2025,Ryanair,FR3185,Rabat (RBA),08:10,"En hora, Ha salido",NaN,NaN,Y59
2368,NaN,05/Dic/2025,Ryanair,FR6973,Rome (FCO),08:15,"En hora, Ha salido",NaN,NaN,R14
2369,NaN,05/Dic/2025,easyJet Europe,EC1376,Geneva (GVA),08:40,"En hora, Ha salido",NaN,NaN,R11
2370,NaN,05/Dic/2025,Ryanair,FR5752,Valletta (MLA),08:40,"En hora, Ha salido",NaN,NaN,S24
2371,NaN,05/Dic/2025,Transavia,TO4751,Paris (ORY),08:45,"En hora, Ha salido",NaN,NaN,U31
2374,NaN,05/Dic/2025,easyJet Europe,EC3737,Milan (MXP),09:10,"En hora, Ha salido",NaN,NaN,R12
2376,NaN,05/Dic/2025,Air Arabia Maroc,3O374,Casablanca (CMN),09:25,"En hora, Ha salido",NaN,NaN,Y55
2377,NaN,05/Dic/2025,Lauda Europe,LW12,Vienna (VIE),09:25,"En hora, Ha salido",NaN,NaN,R13
2378,NaN,05/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S22
2379,NaN,05/Dic/2025,Wizz Air Malta,W45088,Tirana (TIA),09:25,"En hora, Ha salido",NaN,NaN,W44
2380,NaN,05/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,U33
2381,NaN,05/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),09:40,"En hora, Ha salido",NaN,NaN,U37
2382,NaN,05/Dic/2025,Ryanair,FR3320,Milan (BGY),09:45,"En hora, Ha salido",NaN,NaN,U35
2383,NaN,05/Dic/2025,Transavia,HV6788,Eindhoven (EIN),09:45,"En hora, Ha salido",NaN,NaN,U32
2384,NaN,05/Dic/2025,Easyjet,U26654,Birmingham (BHX),09:45,"Retrasado, Ha salido 10:21",NaN,NaN,M3
2385,NaN,05/Dic/2025,Air Arabia Maroc,3O378,Tanger (TNG),09:50,"En hora, Ha salido",NaN,NaN,Y53
2386,NaN,05/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),09:55,"Retrasado, Ha salido 10:05",NaN,NaN,R10
2387,NaN,05/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"Retrasado, Ha salido 10:51",NaN,NaN,Y57
2388,NaN,05/Dic/2025,Ryanair,FR9015,London (STN),10:00,"Retrasado, Ha salido 10:10",NaN,NaN,W42
2389,NaN,05/Dic/2025,Wizz Air Malta,W46018,Rome (FCO),10:00,"En hora, Ha salido",NaN,NaN,S21

In [74]:
df_05.loc[df_05['Name_company'] == 'Air Arabia Maroc', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] = 174

In [75]:
df_05.loc[df_05['Num_flight'] == 'FR9814', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR9814', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W61706', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W45154', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'U28060', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'U28060', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W46728', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W64116', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2250', 'flight_capacity'] = 189

In [76]:
df_05.loc[df_05['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR6597', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EC7682', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == 'EC7682', 'flight_capacity'] = 230

df_05.loc[df_05['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR9811', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR8669', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR7808', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR7808', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'RR6944', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_05.loc[df_05['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'FR3174', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3174', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'U23374', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'U23374', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'EI565', 'flight_capacity'] = 174

df_05.loc[df_05['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'RR8394', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'U22326', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR5710', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'LG3592', 'Aircraft'] = 'Boeing 737-700'
df_05.loc[df_05['Num_flight'] == 'LG3592', 'flight_capacity'] = 141

df_05.loc[df_05['Num_flight'] == 'RR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'RR1786', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'JU585', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR8631', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR7539', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR7539', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'V72135', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'V72135', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'TW408', 'Aircraft'] = 'Airbus A330-200'
df_05.loc[df_05['Num_flight'] == 'TW408', 'flight_capacity'] = 246

df_05.loc[df_05['Num_flight'] == 'W42940', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W42940', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'EC1956', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'EC1956', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W62096', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR6305', 'flight_capacity'] = 197

In [77]:
df_05.loc[df_05['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR6275', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR1527', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W64666', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == 'W64666', 'flight_capacity'] = 230

df_05.loc[df_05['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'EW2521', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR6374', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR6374', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'U28058', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'LW7362', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'LW7362', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'FR2330', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2330', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EW9443', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'EW9443', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'V72165', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR9111', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR9111', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'RR6330', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'RR6330', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR149', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'EC7155', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7155', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR3189', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3189', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR2098', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2098', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'EC7205', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7205', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR6353', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR6353', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'HV5134', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'V73573', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR3076', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR3076', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'W67920', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W67920', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR4587', 'flight_capacity'] = 197

In [78]:
df_05.loc[df_05['Num_flight'] == 'FR878', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'FR878', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W43564', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'W43564', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR6985', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR2925', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2925', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'D85510', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'D85510', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'PC1094', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'PC1094', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'W61412', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W61412', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'EC7694', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'EC7694', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'QS1059', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'QS1059', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR867', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'V71443', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'V71443', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR8215', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR8215', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'TK608', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'S4507', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'S4507', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_05.loc[df_05['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_05.loc[df_05['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR6078', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR6078', 'flight_capacity'] = 189

In [79]:
df_05.loc[df_05['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2922', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'PC1528', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == '5F5512', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == '5F5512', 'flight_capacity'] = 194

df_05.loc[df_05['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'H4264', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'H4264', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR6874', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'PC1092', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'D83657', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'D83657', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FI597', 'flight_capacity'] = 160

df_05.loc[df_05['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'U28056', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'EC7141', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7141', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == '3F232', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == '3F232', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'HV6064', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'HV6064', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'U22324', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'U22324', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'U22002', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'HV5132', 'flight_capacity'] = 232

df_05.loc[df_05['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR6920', 'flight_capacity'] = 197

In [80]:
df_05.loc[df_05['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR9015', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'JU581', 'flight_capacity'] = 174

df_05.loc[df_05['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_05.loc[df_05['Num_flight'] == 'U26654', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'U26654', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_05.loc[df_05['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_05.loc[df_05['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == 'W45088', 'flight_capacity'] = 230

df_05.loc[df_05['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_05.loc[df_05['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_05.loc[df_05['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'EC3737', 'Aircraft'] = 'Airbus A320'
df_05.loc[df_05['Num_flight'] == 'EC3737', 'flight_capacity'] = 180

df_05.loc[df_05['Num_flight'] == 'TO4751', 'Aircraft'] = 'Airbus A320neo'
df_05.loc[df_05['Num_flight'] == 'TO4751', 'flight_capacity'] = 186

df_05.loc[df_05['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_05.loc[df_05['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_05.loc[df_05['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR6973', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR3185', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3185', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR3976', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EC7199', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7199', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_05.loc[df_05['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR846', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'FR8183', 'Aircraft'] = 'Boeing 737-800'
df_05.loc[df_05['Num_flight'] == 'FR8183', 'flight_capacity'] = 189

df_05.loc[df_05['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_05.loc[df_05['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

In [81]:
df_06 = df_por_fecha['06/Dic/2025'].copy()
df_06
# Sabado

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2532,NaN,06/Dic/2025,Ryanair,FR846,Milan (BGY),06:00,"En hora, Ha salido",NaN,NaN,S22
2533,NaN,06/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R12
2534,NaN,06/Dic/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S24
2535,NaN,06/Dic/2025,Ryanair,FR4545,Porto (OPO),06:15,"Retrasado, Ha salido 06:30",NaN,B38M,U31
2536,NaN,06/Dic/2025,Ryanair,FR1342,Palma de Mallorca (PMI),06:20,"Retrasado, Ha salido 06:32",189.0,Boeing 737-800,R11
...,...,...,...,...,...,...,...,...,...,...
2656,NaN,06/Dic/2025,Wizz Air Malta,W46020,Rome (FCO),21:35,"Retrasado, Ha salido 21:45",NaN,NaN,S20
2657,NaN,06/Dic/2025,Ryanair,FR3800,Birmingham (BHX),21:55,"En hora, Ha salido",NaN,NaN,Y58
2658,NaN,06/Dic/2025,Ryanair,FR8574,Rome (FCO),22:10,"En hora, Programado",NaN,NaN,U32
2659,NaN,06/Dic/2025,Wizz Air,W64116,Belgrade (BEG),22:10,"En hora, Ha salido",NaN,NaN,W43
2660,NaN,06/Dic/2025,Air Arabia Maroc,3O642,Tanger (TNG),22:15,"En hora, Ha salido",NaN,NaN,Y55

In [82]:
df_06.isna().sum()

Unnamed: 0         129
fecha_scrapeo        0
Name_company         0
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    120
Aircraft           102
Gate                 0
dtype: int64

In [83]:
df_06.loc[df_06['Name_company'] == 'Air Arabia Maroc', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] = 174

In [84]:
df_06[(df_06['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2532,NaN,06/Dic/2025,Ryanair,FR846,Milan (BGY),06:00,"En hora, Ha salido",NaN,NaN,S22
2533,NaN,06/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R12
2534,NaN,06/Dic/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S24
2535,NaN,06/Dic/2025,Ryanair,FR4545,Porto (OPO),06:15,"Retrasado, Ha salido 06:30",NaN,B38M,U31
2537,NaN,06/Dic/2025,Ryanair,FR777,Venice (VCE),06:30,"En hora, Ha salido",NaN,NaN,U32
2538,NaN,06/Dic/2025,Ryanair,FR8217,London (STN),06:55,"En hora, Ha salido",NaN,NaN,W42
2539,NaN,06/Dic/2025,easyJet Europe,EC7151,Milan (MXP),07:30,"En hora, Ha salido",NaN,NaN,R10
2540,NaN,06/Dic/2025,Ryanair,FR2918,Brussels (BRU),08:05,"En hora, Ha salido",NaN,B738,U34
2541,NaN,06/Dic/2025,Ryanair,FR3180,Rome (FCO),08:15,"En hora, Ha salido",NaN,NaN,U33
2544,NaN,06/Dic/2025,Ryanair,FR575,Bologna (BLQ),08:50,"En hora, Ha salido",NaN,NaN,S24
2545,NaN,06/Dic/2025,Ryanair,FR3166,Palermo (PMO),09:00,"En hora, Ha salido",NaN,NaN,U35
2546,NaN,06/Dic/2025,Wizz Air Malta,W43938,Chisinau (KIV),09:00,"En hora, Ha salido",NaN,NaN,W43
2547,NaN,06/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido 10:01",NaN,NaN,S20
2548,NaN,06/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:15,"En hora, Ha salido",NaN,NaN,R14
2549,NaN,06/Dic/2025,Ryanair,FR133,Berlin (BER),09:20,"En hora, Ha salido",NaN,NaN,U34
2550,NaN,06/Dic/2025,Ryanair,FR2239,Marrakech (RAK),09:20,"En hora, Ha salido",NaN,B738,Y58
2551,NaN,06/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),09:20,"En hora, Ha salido",NaN,NaN,R11
2552,NaN,06/Dic/2025,Wizz Air,W61914,Vilnius (VNO),09:20,"En hora, Ha salido",NaN,NaN,S21
2554,NaN,06/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S23
2555,NaN,06/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,S22
2556,NaN,06/Dic/2025,BUZZ,RR3049,Krakow (KRK),09:30,"Retrasado, Ha salido 10:10",NaN,NaN,U32
2557,NaN,06/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"Retrasado, Ha salido 11:15",NaN,NaN,U31
2558,NaN,06/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"En hora, Ha salido",NaN,NaN,W45
2559,NaN,06/Dic/2025,Ryanair,FR3143,Milan (BGY),10:00,"En hora, Ha salido",NaN,NaN,R13
2560,NaN,06/Dic/2025,Ryanair,FR6559,Liverpool (LPL),10:00,"En hora, Ha salido",NaN,NaN,W42
2561,NaN,06/Dic/2025,Wizz Air Malta,W46018,Rome (FCO),10:00,"En hora, Ha salido",NaN,NaN,U33
2562,NaN,06/Dic/2025,Transavia,HV5132,Amsterdam (AMS),10:05,"En hora, Ha salido",NaN,NaN,R12
2563,NaN,06/Dic/2025,Wizz Air,W61812,Wrocław (WRO),10:10,"En hora, Ha salido",NaN,NaN,S25
2564,NaN,06/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U35
2565,NaN,06/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:20,"En hora, Ha salido",NaN,NaN,R10

In [85]:
df_06.loc[df_06['Aircraft'] == 'B738', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Aircraft'] == 'B38M', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Aircraft'] == 'A320', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Aircraft'] == 'A21N', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Aircraft'] == 'A20N', 'Aircraft'] = 'Airbus A320neo'
df_06.loc[df_06['Aircraft'] == 'A319', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Aircraft'] == 'A321', 'Aircraft'] = 'Airbus A321'

In [86]:
df_06.loc[df_06['Aircraft'] == 'Boeing 737-800', 'flight_capacity'] = 189
df_06.loc[df_06['Aircraft'] == 'Boeing 737 MAX 8', 'flight_capacity'] = 197
df_06.loc[df_06['Aircraft'] == 'Airbus A320', 'flight_capacity'] = 180
df_06.loc[df_06['Aircraft'] == 'Airbus A321neo', 'flight_capacity'] = 239
df_06.loc[df_06['Aircraft'] == 'Airbus A320neo', 'flight_capacity'] = 186
#df_05.loc[(df_05['Name_company'] == 'Aer Lingus') &
#(df_05['Aircraft'] == 'Airbus A320'), 'flight_capacity'] = 174

In [87]:
df_06[(df_06['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2532,NaN,06/Dic/2025,Ryanair,FR846,Milan (BGY),06:00,"En hora, Ha salido",NaN,NaN,S22
2533,NaN,06/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:10,"En hora, Ha salido",NaN,NaN,R12
2534,NaN,06/Dic/2025,Ryanair,FR5718,Bratislava (BTS),06:10,"En hora, Ha salido",NaN,NaN,S24
2537,NaN,06/Dic/2025,Ryanair,FR777,Venice (VCE),06:30,"En hora, Ha salido",NaN,NaN,U32
2538,NaN,06/Dic/2025,Ryanair,FR8217,London (STN),06:55,"En hora, Ha salido",NaN,NaN,W42
2539,NaN,06/Dic/2025,easyJet Europe,EC7151,Milan (MXP),07:30,"En hora, Ha salido",NaN,NaN,R10
2541,NaN,06/Dic/2025,Ryanair,FR3180,Rome (FCO),08:15,"En hora, Ha salido",NaN,NaN,U33
2544,NaN,06/Dic/2025,Ryanair,FR575,Bologna (BLQ),08:50,"En hora, Ha salido",NaN,NaN,S24
2545,NaN,06/Dic/2025,Ryanair,FR3166,Palermo (PMO),09:00,"En hora, Ha salido",NaN,NaN,U35
2546,NaN,06/Dic/2025,Wizz Air Malta,W43938,Chisinau (KIV),09:00,"En hora, Ha salido",NaN,NaN,W43
2547,NaN,06/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"Retrasado, Ha salido 10:01",NaN,NaN,S20
2548,NaN,06/Dic/2025,Ryanair,FR2834,Charleroi (CRL),09:15,"En hora, Ha salido",NaN,NaN,R14
2549,NaN,06/Dic/2025,Ryanair,FR133,Berlin (BER),09:20,"En hora, Ha salido",NaN,NaN,U34
2551,NaN,06/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),09:20,"En hora, Ha salido",NaN,NaN,R11
2552,NaN,06/Dic/2025,Wizz Air,W61914,Vilnius (VNO),09:20,"En hora, Ha salido",NaN,NaN,S21
2554,NaN,06/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,S23
2555,NaN,06/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,S22
2556,NaN,06/Dic/2025,BUZZ,RR3049,Krakow (KRK),09:30,"Retrasado, Ha salido 10:10",NaN,NaN,U32
2557,NaN,06/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"Retrasado, Ha salido 11:15",NaN,NaN,U31
2558,NaN,06/Dic/2025,Air Serbia,JU581,Belgrade (BEG),09:55,"En hora, Ha salido",NaN,NaN,W45
2559,NaN,06/Dic/2025,Ryanair,FR3143,Milan (BGY),10:00,"En hora, Ha salido",NaN,NaN,R13
2560,NaN,06/Dic/2025,Ryanair,FR6559,Liverpool (LPL),10:00,"En hora, Ha salido",NaN,NaN,W42
2561,NaN,06/Dic/2025,Wizz Air Malta,W46018,Rome (FCO),10:00,"En hora, Ha salido",NaN,NaN,U33
2562,NaN,06/Dic/2025,Transavia,HV5132,Amsterdam (AMS),10:05,"En hora, Ha salido",NaN,NaN,R12
2563,NaN,06/Dic/2025,Wizz Air,W61812,Wrocław (WRO),10:10,"En hora, Ha salido",NaN,NaN,S25
2564,NaN,06/Dic/2025,Wizz Air,W61476,Warsaw (WAW),10:15,"En hora, Ha salido",NaN,NaN,U35
2565,NaN,06/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),10:20,"En hora, Ha salido",NaN,NaN,R10
2566,NaN,06/Dic/2025,Ryanair,FR9171,Stockholm (ARN),10:20,"Retrasado, Ha salido 10:30",NaN,NaN,S22
2567,NaN,06/Dic/2025,Easyjet,U22326,London (LTN),10:20,"En hora, Ha salido",NaN,NaN,M6
2569,NaN,06/Dic/2025,Ryanair,FR9307,Cork (ORK),10:30,"En hora, Ha salido",NaN,NaN,W43

In [88]:
df_06.loc[df_06['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321'
df_06.loc[df_06['Num_flight'] == 'W64116', 'flight_capacity'] = 230

df_06.loc[df_06['Num_flight'] == 'FR8574', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR8574', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR3800', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3800', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'RR3039', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'RR3039', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR5220', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_06.loc[df_06['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_06.loc[df_06['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'TO4759', 'Aircraft'] = 'Airbus A320neo'
df_06.loc[df_06['Num_flight'] == 'TO4759', 'flight_capacity'] = 186

In [89]:
df_06.loc[df_06['Num_flight'] == 'FR3928', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3928', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR3182', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3182', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'TW408', 'Aircraft'] = 'BOEING 777-300ER'
df_06.loc[df_06['Num_flight'] == 'TW408', 'flight_capacity'] = 294

df_06.loc[df_06['Num_flight'] == 'FR9581', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR9581', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR867', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR867', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'FR3078', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3078', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'BT878', 'Aircraft'] = 'Airbus A220-300'
df_06.loc[df_06['Num_flight'] == 'BT878', 'flight_capacity'] = 148

df_06.loc[df_06['Num_flight'] == 'FR149', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR149', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'V72327', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'FR5270', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR5270', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR9045', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR9045', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'W61478', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W61478', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W61176', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR3792', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'FR3035', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR3035', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'HV5134', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR878', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR878', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'EC8066', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC8066', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'FR2925', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR2925', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'W43180', 'Aircraft'] = 'Airbus A321'
df_06.loc[df_06['Num_flight'] == 'W43180', 'flight_capacity'] = 230

df_06.loc[df_06['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR6874', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR9015', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'FR2406', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR2406', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR269', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

In [90]:
df_06.loc[df_06['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321'
df_06.loc[df_06['Num_flight'] == 'W46728', 'flight_capacity'] = 230

df_06.loc[df_06['Num_flight'] == 'FR3146', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3146', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR7543', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR7543', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'RR8384', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR3807', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR3807', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'TK608', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'TK608', 'flight_capacity'] = 151

df_06.loc[df_06['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'KU136', 'Aircraft'] = 'Airbus A330-800'
df_06.loc[df_06['Num_flight'] == 'KU136', 'flight_capacity'] = 235

df_06.loc[df_06['Num_flight'] == 'FR58', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR58', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_06.loc[df_06['Num_flight'] == 'BT684', 'flight_capacity'] = 148

df_06.loc[df_06['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'OB775', 'Aircraft'] = 'Airbus A330-200'
df_06.loc[df_06['Num_flight'] == 'OB775', 'flight_capacity'] = 246

df_06.loc[df_06['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR3320', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'FR2507', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'FR2507', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'EI563', 'flight_capacity'] = 174

df_06.loc[df_06['Num_flight'] == 'EC7193', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC7193', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'FR6394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR6394', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'U22704', 'Aircraft'] = 'Airbus A320neo'
df_06.loc[df_06['Num_flight'] == 'U22704', 'flight_capacity'] = 186

df_06.loc[df_06['Num_flight'] == 'U5406', 'Aircraft'] = 'Boeing 737-700'
df_06.loc[df_06['Num_flight'] == 'U5406', 'flight_capacity'] = 141

df_06.loc[df_06['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A320neo'
df_06.loc[df_06['Num_flight'] == 'J246', 'flight_capacity'] = 186

df_06.loc[df_06['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'U28056', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'LW12', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'LW12', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'FR9307', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR9307', 'flight_capacity'] = 197

In [91]:
df_06.loc[df_06['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_06.loc[df_06['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_06.loc[df_06['Num_flight'] == 'FR9171', 'Aircraft'] = 'Boeing 737 MAX 8'
df_06.loc[df_06['Num_flight'] == 'FR9171', 'flight_capacity'] = 197

df_06.loc[df_06['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_06.loc[df_06['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_06.loc[df_06['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'W61812', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W61812', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'HV5132', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'HV5132', 'flight_capacity'] = 232

df_06.loc[df_06['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'FR6559', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR6559', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3143', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'JU581', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'JU581', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321'
df_06.loc[df_06['Num_flight'] == 'W42938', 'flight_capacity'] = 230

df_06.loc[df_06['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'RR3049', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W43176', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'W61914', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W61914', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3028', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR2834', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_06.loc[df_06['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_06.loc[df_06['Num_flight'] == 'W43938', 'Aircraft'] = 'Airbus A320'
df_06.loc[df_06['Num_flight'] == 'W43938', 'flight_capacity'] = 180

df_06.loc[df_06['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'EC7151', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC7151', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR8217', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR777', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_06.loc[df_06['Num_flight'] == 'EC7105', 'Aircraft'] = 'Airbus A319'
df_06.loc[df_06['Num_flight'] == 'EC7105', 'flight_capacity'] = 156

df_06.loc[df_06['Num_flight'] == 'FR846', 'Aircraft'] = 'Boeing 737-800'
df_06.loc[df_06['Num_flight'] == 'FR846', 'flight_capacity'] = 189

In [92]:
df_07 = df_por_fecha['07/Dic/2025'].copy()
df_07

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2661,NaN,07/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,U36
2662,NaN,07/Dic/2025,Ryanair,FR2834,Charleroi (CRL),06:10,"En hora, Ha salido",NaN,NaN,S22
2663,NaN,07/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:25,"Retrasado, Ha salido 08:00",NaN,NaN,U37
2664,NaN,07/Dic/2025,Ryanair,FR4084,Warsaw (WMI),06:25,"En hora, Ha salido",NaN,B738,U34
2665,NaN,07/Dic/2025,Ryanair,FR2239,Marrakech (RAK),06:30,"En hora, Ha salido",NaN,NaN,Y54
...,...,...,...,...,...,...,...,...,...,...
2825,NaN,07/Dic/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",NaN,NaN,W43
2826,NaN,07/Dic/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",NaN,NaN,W44
2827,NaN,07/Dic/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",NaN,NaN,U31
2828,NaN,07/Dic/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",NaN,NaN,S22
2829,NaN,07/Dic/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",NaN,NaN,Y54

In [93]:
df_07.isna().sum()

Unnamed: 0         169
fecha_scrapeo        0
Name_company         1
Num_flight           0
Name_Destiny         0
Time_flight          0
flight_state         0
flight_capacity    160
Aircraft           150
Gate                 3
dtype: int64

In [94]:
df_07[(df_07['flight_capacity'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2661,NaN,07/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,U36
2662,NaN,07/Dic/2025,Ryanair,FR2834,Charleroi (CRL),06:10,"En hora, Ha salido",NaN,NaN,S22
2663,NaN,07/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:25,"Retrasado, Ha salido 08:00",NaN,NaN,U37
2664,NaN,07/Dic/2025,Ryanair,FR4084,Warsaw (WMI),06:25,"En hora, Ha salido",NaN,B738,U34
2665,NaN,07/Dic/2025,Ryanair,FR2239,Marrakech (RAK),06:30,"En hora, Ha salido",NaN,NaN,Y54
2666,NaN,07/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:40,"En hora, Ha salido",NaN,NaN,S23
2667,NaN,07/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",06:50,"En hora, Ha salido",NaN,NaN,R9
2668,NaN,07/Dic/2025,easyJet Europe,EC7191,Glasgow (GLA),07:20,"En hora, Ha salido",NaN,NaN,M6
2669,NaN,07/Dic/2025,easyJet Europe,EC8064,London (LGW),07:20,"En hora, Ha salido",NaN,NaN,M3
2670,NaN,07/Dic/2025,Ryanair,FR6597,Manchester (MAN),07:30,"En hora, Ha salido",NaN,NaN,W43
2671,NaN,07/Dic/2025,Ryanair,FR3108,Luxembourg (LUX),07:35,"En hora, Ha salido",NaN,B738,U41
2673,NaN,07/Dic/2025,Norwegian Air Sweden AOC,D85510,Copenhagen (CPH),07:55,"En hora, Ha salido",NaN,B738,R11
2674,NaN,07/Dic/2025,easyJet Europe,EC7131,Nice/Cote D'Azur (NCE),08:00,"En hora, Ha salido",NaN,NaN,R12
2675,NaN,07/Dic/2025,easyJet Europe,EC3754,Milan (MXP),08:25,"En hora, Ha salido",NaN,NaN,R9
2676,NaN,07/Dic/2025,Ryanair,FR878,Venice (VCE),08:30,"Retrasado, Ha salido 09:40",NaN,B738,U35
2677,NaN,07/Dic/2025,easyJet Europe,EC1376,Geneva (GVA),08:35,"En hora, Ha salido",NaN,NaN,R13
2679,NaN,07/Dic/2025,BUZZ,RR1786,Vilnius (VNO),09:00,"En hora, Ha salido",NaN,NaN,S25
2680,NaN,07/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),09:05,"En hora, Ha salido",NaN,NaN,S24
2681,NaN,07/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"En hora, Ha salido",NaN,NaN,U31
2682,NaN,07/Dic/2025,BUZZ,RR3193,Riga (RIX),09:10,"En hora, Ha salido",NaN,NaN,S20
2683,NaN,07/Dic/2025,Eurowings,EW7521,Hamburg (HAM),09:25,"En hora, Ha salido",NaN,NaN,U32
2684,NaN,07/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,U33
2685,NaN,07/Dic/2025,Wizz Air Malta,W45088,Tirana (TIA),09:25,"En hora, Ha salido",NaN,NaN,W45
2686,NaN,07/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,S22
2687,NaN,07/Dic/2025,Ryanair,FR4545,Porto (OPO),09:35,"En hora, Ha salido",NaN,NaN,S23
2688,NaN,07/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,U36
2689,NaN,07/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),09:45,"En hora, Ha salido",NaN,NaN,R10
2690,NaN,07/Dic/2025,BUZZ,RR333,Gdansk (GDN),09:45,"En hora, Ha salido",NaN,NaN,U34
2691,NaN,07/Dic/2025,BUZZ,RR8384,Budapest (BUD),09:45,"En hora, Ha salido",NaN,NaN,R12
2693,NaN,07/Dic/2025,Ryanair,FR9593,Tanger (TNG),09:50,"Retrasado, Ha salido 10:08",NaN,NaN,Y57

In [95]:
df_07.loc[df_07['Aircraft'] == 'B738', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Aircraft'] == 'B38M', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Aircraft'] == 'A320', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Aircraft'] == 'A21N', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Aircraft'] == 'A20N', 'Aircraft'] = 'Airbus A320neo'
df_07.loc[df_07['Aircraft'] == 'A319', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Aircraft'] == 'A321', 'Aircraft'] = 'Airbus A321'

In [96]:
df_07.loc[df_07['Aircraft'] == 'Boeing 737-800', 'flight_capacity'] = 189
df_07.loc[df_07['Aircraft'] == 'Boeing 737 MAX 8', 'flight_capacity'] = 197
df_07.loc[df_07['Aircraft'] == 'Airbus A320', 'flight_capacity'] = 180
df_07.loc[df_07['Aircraft'] == 'Airbus A319', 'flight_capacity'] = 156
df_07.loc[df_07['Aircraft'] == 'Airbus A321neo', 'flight_capacity'] = 239
df_07.loc[df_07['Aircraft'] == 'Airbus A321', 'flight_capacity'] = 230
df_07.loc[df_07['Aircraft'] == 'Airbus A320neo', 'flight_capacity'] = 186

In [97]:
df_07.loc[df_07['Aircraft'] == 'BBoeing 737-800', 'Aircraft'] = 'Boeing 737-800'

In [98]:
df_07 = df_07.drop([2786])

In [99]:
df_07.loc[df_07['Name_company'] == 'Air Arabia Maroc', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Name_company'] == 'Air Arabia Maroc', 'flight_capacity'] = 174

In [100]:
df_07[(df_07['Gate'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2744,NaN,07/Dic/2025,Norwegian Air Sweden AOC,D85502,Stockholm (ARN),14:40,"En hora, Programado",NaN,NaN,NaN
2745,NaN,07/Dic/2025,Bluebird Airways,BZ251,Tel Aviv (TLV),14:45,"En hora, Programado",NaN,NaN,NaN
2746,NaN,07/Dic/2025,SmartWings,QS1059,Prague (PRG),14:55,"En hora, Programado",NaN,NaN,NaN

In [101]:
df_07.loc[df_07['Num_flight'] == 'D85502', 'Gate'] = 'U'
df_07.loc[df_07['Num_flight'] == 'BZ251', 'Gate'] = 'Y'
df_07.loc[df_07['Num_flight'] == 'QS1059', 'Gate'] = 'U'

In [102]:
df_07[(df_07['Aircraft'].isna())].head(30)

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
2661,NaN,07/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",NaN,NaN,U36
2662,NaN,07/Dic/2025,Ryanair,FR2834,Charleroi (CRL),06:10,"En hora, Ha salido",NaN,NaN,S22
2663,NaN,07/Dic/2025,Ryanair,FR2918,Brussels (BRU),06:25,"Retrasado, Ha salido 08:00",NaN,NaN,U37
2665,NaN,07/Dic/2025,Ryanair,FR2239,Marrakech (RAK),06:30,"En hora, Ha salido",NaN,NaN,Y54
2666,NaN,07/Dic/2025,Ryanair,FR2507,Cologne-Bonn (CGN),06:40,"En hora, Ha salido",NaN,NaN,S23
2667,NaN,07/Dic/2025,easyJet Europe,EC7101,"Basel, Switzerland/Mulhouse (BSL)",06:50,"En hora, Ha salido",NaN,NaN,R9
2668,NaN,07/Dic/2025,easyJet Europe,EC7191,Glasgow (GLA),07:20,"En hora, Ha salido",NaN,NaN,M6
2669,NaN,07/Dic/2025,easyJet Europe,EC8064,London (LGW),07:20,"En hora, Ha salido",NaN,NaN,M3
2670,NaN,07/Dic/2025,Ryanair,FR6597,Manchester (MAN),07:30,"En hora, Ha salido",NaN,NaN,W43
2674,NaN,07/Dic/2025,easyJet Europe,EC7131,Nice/Cote D'Azur (NCE),08:00,"En hora, Ha salido",NaN,NaN,R12
2675,NaN,07/Dic/2025,easyJet Europe,EC3754,Milan (MXP),08:25,"En hora, Ha salido",NaN,NaN,R9
2677,NaN,07/Dic/2025,easyJet Europe,EC1376,Geneva (GVA),08:35,"En hora, Ha salido",NaN,NaN,R13
2679,NaN,07/Dic/2025,BUZZ,RR1786,Vilnius (VNO),09:00,"En hora, Ha salido",NaN,NaN,S25
2680,NaN,07/Dic/2025,Ryanair,FR3028,Ibiza (IBZ),09:05,"En hora, Ha salido",NaN,NaN,S24
2681,NaN,07/Dic/2025,Wizz Air,W62048,Krakow (KRK),09:05,"En hora, Ha salido",NaN,NaN,U31
2682,NaN,07/Dic/2025,BUZZ,RR3193,Riga (RIX),09:10,"En hora, Ha salido",NaN,NaN,S20
2683,NaN,07/Dic/2025,Eurowings,EW7521,Hamburg (HAM),09:25,"En hora, Ha salido",NaN,NaN,U32
2684,NaN,07/Dic/2025,Wizz Air Malta,W43176,Bucharest (OTP),09:25,"En hora, Ha salido",NaN,NaN,U33
2685,NaN,07/Dic/2025,Wizz Air Malta,W45088,Tirana (TIA),09:25,"En hora, Ha salido",NaN,NaN,W45
2686,NaN,07/Dic/2025,Wizz Air,W62376,Budapest (BUD),09:25,"En hora, Ha salido",NaN,NaN,S22
2687,NaN,07/Dic/2025,Ryanair,FR4545,Porto (OPO),09:35,"En hora, Ha salido",NaN,NaN,S23
2688,NaN,07/Dic/2025,Wizz Air Malta,W42938,Vienna (VIE),09:35,"En hora, Ha salido",NaN,NaN,U36
2689,NaN,07/Dic/2025,easyJet Europe,EC7656,Lisbon (LIS),09:45,"En hora, Ha salido",NaN,NaN,R10
2690,NaN,07/Dic/2025,BUZZ,RR333,Gdansk (GDN),09:45,"En hora, Ha salido",NaN,NaN,U34
2691,NaN,07/Dic/2025,BUZZ,RR8384,Budapest (BUD),09:45,"En hora, Ha salido",NaN,NaN,R12
2693,NaN,07/Dic/2025,Ryanair,FR9593,Tanger (TNG),09:50,"Retrasado, Ha salido 10:08",NaN,NaN,Y57
2694,NaN,07/Dic/2025,Ryanair,FR6341,Rome (FCO),09:55,"En hora, Ha salido",NaN,NaN,U37
2695,NaN,07/Dic/2025,BUZZ,RR3049,Krakow (KRK),09:55,"Retrasado, Ha salido 10:30",NaN,NaN,R11
2696,NaN,07/Dic/2025,Ryanair,FR8231,London (STN),10:00,"En hora, Ha salido",NaN,NaN,W43
2697,NaN,07/Dic/2025,Wizz Air Malta,W46018,Rome (FCO),10:00,"En hora, Ha salido",NaN,NaN,R13

In [103]:
df_07.loc[df_07['Num_flight'] == 'FR9406', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR9406', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W61706', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W61706', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'FR5220', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR5220', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W45154', 'Aircraft'] = 'Airbus A321'
df_07.loc[df_07['Num_flight'] == 'W45154', 'flight_capacity'] = 230

df_07.loc[df_07['Num_flight'] == 'W64116', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W64116', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'V71415', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'V71415', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'U22706', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'U22706', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'W46728', 'Aircraft'] = 'Airbus A321'
df_07.loc[df_07['Num_flight'] == 'W46728', 'flight_capacity'] = 230

df_07.loc[df_07['Num_flight'] == 'FR5752', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR5752', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'W46020', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W46020', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'U28060', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'U28060', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'W43406', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'W43406', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'EI565', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EI565', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'W43178', 'Aircraft'] = 'Airbus A321'
df_07.loc[df_07['Num_flight'] == 'W43178', 'flight_capacity'] = 230

df_07.loc[df_07['Num_flight'] == 'FR3792', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR3792', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'HV5134', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'HV5134', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR2896', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2896', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'RR8615', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'RR8615', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W64738', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W64738', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'U22326', 'Aircraft'] = 'Airbus A320neo'
df_07.loc[df_07['Num_flight'] == 'U22326', 'flight_capacity'] = 186

df_07.loc[df_07['Num_flight'] == 'RR6944', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'RR6944', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR6275', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6275', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W62378', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W62378', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'TO4759', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'TO4759', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'LG3596', 'Aircraft'] = 'Boeing 737-700'
df_07.loc[df_07['Num_flight'] == 'LG3596', 'flight_capacity'] = 141

df_07.loc[df_07['Num_flight'] == 'FR4587', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR4587', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EW2521', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'EW2521', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'D83659', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'D83659', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'JU585', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'JU585', 'flight_capacity'] = 174

In [104]:
df_07.loc[df_07['Num_flight'] == 'EW521', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EW521', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR6985', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR6985', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'W67022', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W67022', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'HV6788', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'HV6788', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC4212', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EC4212', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'W62096', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W62096', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'FR8136', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR8136', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'U28058', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'U28058', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR9015', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR9015', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR5710', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR5710', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC3750', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EC3750', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR2233', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2233', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W64406', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W64406', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'V72165', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'V72165', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'EC7159', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7159', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'W61176', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'W61176', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'U25716', 'Aircraft'] = 'Airbus A320neo'
df_07.loc[df_07['Num_flight'] == 'U25716', 'flight_capacity'] = 186

df_07.loc[df_07['Num_flight'] == 'HV6066', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'HV6066', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR8631', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR8631', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC7103', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7103', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'LS804', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'LS804', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W43686', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'W43686', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR2406', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2406', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'V73700', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'V73700', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'EC7109', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7109', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR6305', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6305', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR777', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR777', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR1681', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR1681', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'RR5252', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'RR5252', 'flight_capacity'] = 189

In [105]:
df_07.loc[df_07['Num_flight'] == 'V73573', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'V73573', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR12', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR12', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR5718', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR5718', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'RR8394', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'RR8394', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR2250', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2250', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR8669', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR8669', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC7173', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7173', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR2922', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2922', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR133', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR133', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR269', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR269', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'W61412', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W61412', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'EC7694', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EC7694', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'TO4755', 'Aircraft'] = 'Airbus A320neo'
df_07.loc[df_07['Num_flight'] == 'TO4755', 'flight_capacity'] = 186

df_07.loc[df_07['Num_flight'] == 'RR3072', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'RR3072', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR774', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR774', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR3320', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR3320', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'QS1059', 'Aircraft'] = 'Airbus A220-300'
df_07.loc[df_07['Num_flight'] == 'QS1059', 'flight_capacity'] = 149

df_07.loc[df_07['Num_flight'] == 'BZ251', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'BZ251', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'D85502', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'D85502', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR6973', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6973', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC7107', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7107', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'HV5132', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'HV5132', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'XQ895', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'XQ895', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR4585', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR4585', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR6920', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR6920', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'EC7153', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7153', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'BT684', 'Aircraft'] = 'Airbus A220-300'
df_07.loc[df_07['Num_flight'] == 'BT684', 'flight_capacity'] = 149

df_07.loc[df_07['Num_flight'] == 'FR9811', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR9811', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'PC1528', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'PC1528', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'EC1380', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EC1380', 'flight_capacity'] = 180

In [106]:
df_07.loc[df_07['Num_flight'] == 'U28056', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'U28056', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR3121', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR3121', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W46330', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W46330', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'V71445', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'V71445', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR8598', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR8598', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR2511', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2511', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'PC1092', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'PC1092', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'FR6300', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6300', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'V72167', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'V72167', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR1527', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR1527', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR3976', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR3976', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR3129', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR3129', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR8217', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR8217', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'V72327', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'V72327', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FI597', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FI597', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'EC7139', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7139', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'EI563', 'Aircraft'] = 'Airbus A320neo'
df_07.loc[df_07['Num_flight'] == 'EI563', 'flight_capacity'] = 186

df_07.loc[df_07['Num_flight'] == 'DY1741', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'DY1741', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'U22002', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'U22002', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR3166', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR3166', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'J246', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'J246', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR3143', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR3143', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR1279', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR1279', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR7543', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR7543', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR6267', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6267', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR575', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR575', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W61476', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W61476', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'W61812', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W61812', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'LW7351', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'LW7351', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'FR6874', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR6874', 'flight_capacity'] = 197

In [107]:
df_07.loc[df_07['Num_flight'] == 'W46018', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W46018', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'FR8231', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR8231', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'RR3049', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'RR3049', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR6341', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6341', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR9593', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR9593', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'RR8384', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'RR8384', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'RR333', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'RR333', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC7656', 'Aircraft'] = 'Airbus A321'
df_07.loc[df_07['Num_flight'] == 'EC7656', 'flight_capacity'] = 230

df_07.loc[df_07['Num_flight'] == 'W42938', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W42938', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'FR4545', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR4545', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W62376', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W62376', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'W45088', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W45088', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'W43176', 'Aircraft'] = 'Airbus A321'
df_07.loc[df_07['Num_flight'] == 'W43176', 'flight_capacity'] = 230

df_07.loc[df_07['Num_flight'] == 'EW7521', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EW7521', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'RR3193', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'RR3193', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'W62048', 'Aircraft'] = 'Airbus A321neo'
df_07.loc[df_07['Num_flight'] == 'W62048', 'flight_capacity'] = 239

df_07.loc[df_07['Num_flight'] == 'FR3028', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR3028', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'RR1786', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'RR1786', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'EC1376', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC1376', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'EC3754', 'Aircraft'] = 'Airbus A320'
df_07.loc[df_07['Num_flight'] == 'EC3754', 'flight_capacity'] = 180

df_07.loc[df_07['Num_flight'] == 'EC7131', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7131', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR6597', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR6597', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC8064', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC8064', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'EC7101', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7101', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR2507', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2507', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR2239', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2239', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'FR2918', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR2918', 'flight_capacity'] = 189

df_07.loc[df_07['Num_flight'] == 'EC7191', 'Aircraft'] = 'Airbus A319'
df_07.loc[df_07['Num_flight'] == 'EC7191', 'flight_capacity'] = 156

df_07.loc[df_07['Num_flight'] == 'FR2834', 'Aircraft'] = 'Boeing 737 MAX 8'
df_07.loc[df_07['Num_flight'] == 'FR2834', 'flight_capacity'] = 197

df_07.loc[df_07['Num_flight'] == 'FR3180', 'Aircraft'] = 'Boeing 737-800'
df_07.loc[df_07['Num_flight'] == 'FR3180', 'flight_capacity'] = 189

In [108]:
df_dic = pd.concat([ df_01, df_02, df_03, df_04, df_05, df_06, df_07 ], ignore_index=True)

In [109]:
df_dic

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,NaN,01/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",189.0,Boeing 737-800,S25
1,NaN,01/Dic/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",189.0,Boeing 737-800,S20
2,NaN,01/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",156.0,Airbus A319,R11
3,NaN,01/Dic/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",189.0,Boeing 737-800,W45
4,NaN,01/Dic/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U33
...,...,...,...,...,...,...,...,...,...,...
919,NaN,07/Dic/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",239.0,Airbus A321neo,W43
920,NaN,07/Dic/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",230.0,Airbus A321,W44
921,NaN,07/Dic/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",189.0,Boeing 737-800,U31
922,NaN,07/Dic/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",239.0,Airbus A321neo,S22
923,NaN,07/Dic/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",189.0,Boeing 737-800,Y54

In [110]:
df_dic = df_dic.drop(columns=['Unnamed: 0'])

In [111]:
#df_enero = pd.concat([df_01, df_04, df_05, df_06, df_07], ignore_index=True)

In [112]:
df_dic.reset_index(drop=True, inplace=True)

In [113]:
df_dic

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,01/Dic/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",189.0,Boeing 737-800,S25
1,01/Dic/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",189.0,Boeing 737-800,S20
2,01/Dic/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",156.0,Airbus A319,R11
3,01/Dic/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",189.0,Boeing 737-800,W45
4,01/Dic/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U33
...,...,...,...,...,...,...,...,...,...
919,07/Dic/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",239.0,Airbus A321neo,W43
920,07/Dic/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",230.0,Airbus A321,W44
921,07/Dic/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",189.0,Boeing 737-800,U31
922,07/Dic/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",239.0,Airbus A321neo,S22
923,07/Dic/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",189.0,Boeing 737-800,Y54

In [130]:
#df_dic.to_csv("vuelos_Enero_rellenados.csv")

In [115]:
df_dic.isna().sum()

fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    0
Aircraft           0
Gate               0
dtype: int64

In [116]:
df_dic[df_dic['flight_capacity'].isna()]

Empty DataFrame
Columns: [fecha_scrapeo, Name_company, Num_flight, Name_Destiny, Time_flight, flight_state, flight_capacity, Aircraft, Gate]
Index: []

In [117]:
df_dic['Aircraft'].unique()

array(['Boeing 737-800', 'Airbus A319', 'Boeing 737 MAX 8', 'Airbus A320',
       'Airbus A321neo', 'Airbus A321', 'Airbus A320neo',
       'de Havilland Dash 8-400', 'Airbus A220-300', 'Airbus A330-200',
       'Airbus A330-900', 'Boeing 737-700', 'Airbus A350-900',
       'BOEING 777-300ER', 'Embraer ERJ-190', 'Airbus A330-800'],
      dtype=object)

In [118]:
df_dic['flight_capacity'].unique()

array([189., 156., 197., 180., 239., 174., 230., 186.,  76., 149., 162.,
       220., 246., 144., 194., 278., 232., 148., 141., 432., 294., 108.,
       235., 160., 151.])

In [119]:
import pandas as pd

# Diccionario de traducción de meses en español a números
meses_es = {
    'Ene': '01', 'Feb': '02', 'Mar': '03', 'Abr': '04', 'May': '05', 'Jun': '06',
    'Jul': '07', 'Ago': '08', 'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dic': '12'
}

# Reemplazamos los nombres meses por números usando regex

for mes_nom, mes_num in meses_es.items():
    df_dic['fecha_scrapeo'] = df_dic['fecha_scrapeo'].str.replace(mes_nom, mes_num, regex=False)

In [120]:
df_dic

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,01/12/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",189.0,Boeing 737-800,S25
1,01/12/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",189.0,Boeing 737-800,S20
2,01/12/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",156.0,Airbus A319,R11
3,01/12/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",189.0,Boeing 737-800,W45
4,01/12/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U33
...,...,...,...,...,...,...,...,...,...
919,07/12/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",239.0,Airbus A321neo,W43
920,07/12/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",230.0,Airbus A321,W44
921,07/12/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",189.0,Boeing 737-800,U31
922,07/12/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",239.0,Airbus A321neo,S22
923,07/12/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",189.0,Boeing 737-800,Y54

In [121]:
df_nov = pd.read_csv('vuelos_TODO_LIMPIO.csv')
df_nov

,Unnamed: 0,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate,Type_f,week_day,day_time
0,0,2025-11-17,Grupo Ryanair,FR3180,Rome (FCO),06:00:00,En hora,189,Boeing 737-800,U,EU,Lunes,Mañana
1,1,2025-11-17,Grupo Ryanair,FR846,Milan (BGY),06:10:00,Retrasado,189,Boeing 737-800,S,EU,Lunes,Mañana
2,2,2025-11-17,Grupo easy,EC7105,Geneva (GVA),06:15:00,En hora,156,Airbus A319,R,EU,Lunes,Mañana
3,3,2025-11-17,Grupo Ryanair,FR2233,Al Aaroui (NDR),06:20:00,Retrasado,189,Boeing 737-800,W,INT,Lunes,Mañana
4,4,2025-11-17,Grupo Ryanair,FR8384,Budapest (BUD),06:25:00,En hora,189,Boeing 737-800,R,EU,Lunes,Mañana
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1774,1774,2025-11-30,Grupo wizz,W64116,Belgrade (BEG),21:55:00,En hora,239,Airbus A321neo,W,INT,Domingo,Noche
1775,1775,2025-11-30,Grupo wizz,W45154,Tirana (TIA),22:45:00,Retrasado,230,Airbus A321,W,INT,Domingo,Noche
1776,1776,2025-11-30,Grupo Ryanair,FR5220,Bologna (BLQ),22:50:00,En hora,197,Boeing 737 MAX 8,S,EU,Domingo,Noche
1777,1777,2025-11-30,Grupo wizz,W61706,Gdansk (GDN),22:50:00,En hora,230,Airbus A321,U,EU,Domingo,Noche
1778,1778,2025-11-30,Grupo Ryanair,FR9406,Fes (FEZ),23:15:00,En hora,189,Boeing 737-800,Y,INT,Domingo,Noche

In [122]:
df_nov = df_nov.drop(columns=['Unnamed: 0'])

In [123]:
df_nov.isna().sum()

fecha_scrapeo      0
Name_company       0
Num_flight         0
Name_Destiny       0
Time_flight        0
flight_state       0
flight_capacity    0
Aircraft           0
Gate               0
Type_f             0
week_day           0
day_time           0
dtype: int64

In [124]:
df_nov

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate,Type_f,week_day,day_time
0,2025-11-17,Grupo Ryanair,FR3180,Rome (FCO),06:00:00,En hora,189,Boeing 737-800,U,EU,Lunes,Mañana
1,2025-11-17,Grupo Ryanair,FR846,Milan (BGY),06:10:00,Retrasado,189,Boeing 737-800,S,EU,Lunes,Mañana
2,2025-11-17,Grupo easy,EC7105,Geneva (GVA),06:15:00,En hora,156,Airbus A319,R,EU,Lunes,Mañana
3,2025-11-17,Grupo Ryanair,FR2233,Al Aaroui (NDR),06:20:00,Retrasado,189,Boeing 737-800,W,INT,Lunes,Mañana
4,2025-11-17,Grupo Ryanair,FR8384,Budapest (BUD),06:25:00,En hora,189,Boeing 737-800,R,EU,Lunes,Mañana
...,...,...,...,...,...,...,...,...,...,...,...,...
1774,2025-11-30,Grupo wizz,W64116,Belgrade (BEG),21:55:00,En hora,239,Airbus A321neo,W,INT,Domingo,Noche
1775,2025-11-30,Grupo wizz,W45154,Tirana (TIA),22:45:00,Retrasado,230,Airbus A321,W,INT,Domingo,Noche
1776,2025-11-30,Grupo Ryanair,FR5220,Bologna (BLQ),22:50:00,En hora,197,Boeing 737 MAX 8,S,EU,Domingo,Noche
1777,2025-11-30,Grupo wizz,W61706,Gdansk (GDN),22:50:00,En hora,230,Airbus A321,U,EU,Domingo,Noche
1778,2025-11-30,Grupo Ryanair,FR9406,Fes (FEZ),23:15:00,En hora,189,Boeing 737-800,Y,INT,Domingo,Noche

In [125]:
df_todo = pd.concat([df_nov, df_dic], ignore_index=True)
df_todo

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate,Type_f,week_day,day_time
0,2025-11-17,Grupo Ryanair,FR3180,Rome (FCO),06:00:00,En hora,189.0,Boeing 737-800,U,EU,Lunes,Mañana
1,2025-11-17,Grupo Ryanair,FR846,Milan (BGY),06:10:00,Retrasado,189.0,Boeing 737-800,S,EU,Lunes,Mañana
2,2025-11-17,Grupo easy,EC7105,Geneva (GVA),06:15:00,En hora,156.0,Airbus A319,R,EU,Lunes,Mañana
3,2025-11-17,Grupo Ryanair,FR2233,Al Aaroui (NDR),06:20:00,Retrasado,189.0,Boeing 737-800,W,INT,Lunes,Mañana
4,2025-11-17,Grupo Ryanair,FR8384,Budapest (BUD),06:25:00,En hora,189.0,Boeing 737-800,R,EU,Lunes,Mañana
...,...,...,...,...,...,...,...,...,...,...,...,...
2698,07/12/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",239.0,Airbus A321neo,W43,NaN,NaN,NaN
2699,07/12/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",230.0,Airbus A321,W44,NaN,NaN,NaN
2700,07/12/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",189.0,Boeing 737-800,U31,NaN,NaN,NaN
2701,07/12/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",239.0,Airbus A321neo,S22,NaN,NaN,NaN
2702,07/12/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",189.0,Boeing 737-800,Y54,NaN,NaN,NaN

In [126]:
df_dic

,fecha_scrapeo,Name_company,Num_flight,Name_Destiny,Time_flight,flight_state,flight_capacity,Aircraft,Gate
0,01/12/2025,Ryanair,FR3180,Rome (FCO),06:00,"En hora, Ha salido",189.0,Boeing 737-800,S25
1,01/12/2025,Ryanair,FR846,Milan (BGY),06:10,"En hora, Ha salido",189.0,Boeing 737-800,S20
2,01/12/2025,easyJet Europe,EC7105,Geneva (GVA),06:15,"En hora, Ha salido",156.0,Airbus A319,R11
3,01/12/2025,Ryanair,FR2233,Al Aaroui (NDR),06:20,"En hora, Ha salido",189.0,Boeing 737-800,W45
4,01/12/2025,Ryanair,FR8384,Budapest (BUD),06:25,"En hora, Ha salido",197.0,Boeing 737 MAX 8,U33
...,...,...,...,...,...,...,...,...,...
919,07/12/2025,Wizz Air,W64116,Belgrade (BEG),21:55,"En hora, Ha salido",239.0,Airbus A321neo,W43
920,07/12/2025,Wizz Air Malta,W45154,Tirana (TIA),22:45,"En hora, Programado",230.0,Airbus A321,W44
921,07/12/2025,Ryanair,FR5220,Bologna (BLQ),22:50,"En hora, Programado",189.0,Boeing 737-800,U31
922,07/12/2025,Wizz Air,W61706,Gdansk (GDN),22:50,"En hora, Programado",239.0,Airbus A321neo,S22
923,07/12/2025,Ryanair,FR9406,Fes (FEZ),23:15,"En hora, Programado",189.0,Boeing 737-800,Y54

In [127]:
#df_dic.to_csv("vuelos_Enero_rellenados.csv")

In [128]:
#df_enero.to_csv("vuelos_enero.csv")